### ISSUE TITLE
make planet_osm_roads table optional and/or configurable

### ISSUE THREAD

**Issue by ajashton** [openstreetmap/osm2pgsql#10]
The logic for what goes in the `planet_osm_roads` table is highly tied to the default OSM Mapnik stylesheet. For rendering other styles it might make sense for this table to be different or not present at all.

[Completely removing the creation of this table](https://github.com/ajashton/osm2pgsql/commit/98dcc75b018bec421b896d2231a705d4caaf8809) (since I don't need it) cuts 10-20% off my import times.

**Comment by pnorman** [comment]
ping @ajashton

**Comment by ajashton** [comment]
Yes I think the roads flag in the lua transforms are a good solution here.
