### ISSUE TITLE
[suggestion] Optionnal support for relation of relation aka "super-relation"

### ISSUE THREAD

**Issue by sletuffe** [openstreetmap/osm2pgsql#101]
For some needs it could be usefull if an optionnal switch param could enable support for "super-relation" (those relation whose members are relations whose members (...) are ways) in order to have geometries for them.

Such existing relation are quite rare atm but could include :
type=route for long route made of other routes
http://www.openstreetmap.org/browse/relation/20772
Country boundaries :
http://www.openstreetmap.org/browse/relation/1111111
http://www.openstreetmap.org/browse/relation/11980

**Comment by pnorman** [comment]
There doesn't seem to be interest in this and it's not obvious that we should be doing it anyways, given the duplication that would then be present.
