### ISSUE TITLE
OSX builds on travis fail

### ISSUE THREAD

**Issue by joto** [openstreetmap/osm2pgsql#1035]
The OSX builds on travis have been failing for a few days. This seems to be related to travis switching to OS X Mojave (10.14) which doesn't include the system header files in `/usr/include` any more. I have tried following some advice found "on the internet" to fix this (in [this branch](https://github.com/joto/osm2pgsql/tree/travis-test-osx)), but could not fix it.

Anybody with a Mac who can fix this?

**Comment by Firefishy** [comment]
Homebrew forumla may help: https://github.com/Homebrew/homebrew-core/blob/master/Formula/osm2pgsql.rb the build there for Mojave works.

**Comment by mmd-osm** [comment]
Confirmed. https://formulae.brew.sh/formula/osm2pgsql  has a list of all dependencies which are used to build osm2pgsql. When installing all of them via brew install, you can also build osm2pgsql. 

brew install cmake
brew install boost
brew install ...


Lib |version | comment
-- | -- | --
boost | 1.71.0 | Collection of portable C++ source libraries
geos | 3.8.0 | Geometry Engine
lua | 5.3.5 | Powerful, lightweight programming language
luajit | 2.0.5 | Just-In-Time Compiler (JIT) for the Lua programming language
postgresql | 12.1 | Object-relational database system
proj | 6.2.1 | Cartographic Projections Library
cmake | 3.16.1 | Cross-platform make

**Comment by joto** [comment]
@Firefishy @mmd-osm This is totally beside the point. This issue is about the travis build which doesn't work, not about the homebrew build.

And btw: You don't need geos to build osm2pgsql these days any more.

**Comment by mmd-osm** [comment]
Well, I’ve tested this on a real Mojave and it works there. Wasn’t that your point when asking for someone with a Mac? If Travis uses some entirely incompatible image, you need someone familiar with Travis instead.

**Comment by mmd-osm** [comment]
Regarding /usr/include, did you check out https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035623 ?

**Comment by mmd-osm** [comment]
Can you check if this pull request would help (changes to CMake): https://github.com/micmacIGN/micmac/pull/119

**Comment by joto** [comment]
@mmd-osm You seem to have some ideas. Can you try them out on a PR? Sarah has tried everything she could think of in the `test-travis` branch and I have tried everything in `joto/travis-test-osx` branch. And we couldn't get anywhere. We are at the point now where we will drop OSX tests on travis alltogether if nobody finds a solution for this.

**Comment by mmd-osm** [comment]
I tried a number of options now, none of them seem to work. 

This only major difference I could see is: on virtualbox, c++ points to `/Library/Developer/CommandLineTools/usr/bin/c++`, while travis uses `/Applications/Xcode-11.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++`

Also, travis' sysroot points to:  `-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` while on virtualbox that's `-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk`.

You could contact Travis support by email to enable remote debugging for this repo. This might be easier for troubleshooting. Disabling osx altogether for the time being seems to be a reasonable option, too.
