### ISSUE TITLE
osm2pgsql fails on 100MB+ .pbf files when using Aurora Postgres Serverless DB

### ISSUE THREAD

**Issue by chris** [openstreetmap/osm2pgsql#1056]
Cross posting [this `imposm` issue](https://github.com/omniscale/imposm3/issues/212), since it also affects `osm2pgsql`. In short, `osm2pgsql` does not work when using the AWS Aurora Postgres Serverless database (works fine on non-serverless), whenever you try to import a `.pbf` file that is roughly 100MB or larger, such as Oregon or California extracts from Geofabrik. Smaller extracts, such as Delaware work fine. Here's the error I see:

```
Processing: Node(18314k 188.8k/s) Way(1396k 107.38k/s) Relation(0 0.00/s)COPY_END for COPY planet_osm_ways FROM STDIN;
 failed: ERROR:  unexpected message type 0x2A during COPY from stdin
CONTEXT:  COPY planet_osm_ways, line 1
``` 

I have a support request open with AWS and they are investigating, but so far, from what we can tell, this is some issue that comes up only via use of osm2pgsl or imposm. 

As a workaround, you can do the import using either Aurora Postgres (non-serverless), or regular RDS Postgres, create a snapshot, and then restore that snapshot to an Aurora Postgres Serverless instance in order to use serverless. Aurora Postgres Serverless is Postgres 10.7, PostGIS 2.4. Note though that using the workaround, I use the same Postgres/PostGIS versions, and it works fine, so it seems specific to the serverless version.

**Comment by lonvia** [comment]
What version of osm2pgsql are you using? We have reports for older versions, that postgresql closes connections unexpectedly after some time of inactivity but I haven't heard of any recent occurences.

**Comment by chris** [comment]
Ah, good point. I'm using 0.94, which is what seems to be the apt-get/Ubuntu repository for Ubuntu 18.04 (which is the EC2 AMI image I'm using). I've been using 0.96 on my Mac, via Homebrew. I see that 1.2.1 is the latest. I will see if I can either build it, or find an AMI with that version in the packages. I'll report back once I've been able to try something newer.

**Comment by chris** [comment]
@lonvia thank you! Turns out that mostly solves it! I built it (version 1.2.0), and was able to import. The one caveat is that I did need to ensure the DB didn't go to sleep (by disabling that option in Aurora Postgres Serverless), otherwise I got SSL disconnect errors (might need to allow for a longer connection timeout? It does seem to take about 30 seconds for the DB to come back after being asleep). I will report this back to AWS as well.

**Comment by chris** [comment]
Oops, spoke too soon. I tried with a larger dataset and it failed with that `SSL connection has been closed unexpectedly` error, or `error on COPY: server closed the connection unexpectedly`. I reduced the cache size and re-ran the california one and it succeeded, but I haven't gotten the Germany one (fair bit larger .pbf) to import yet.

**Comment by chris** [comment]
I have tried this further. In the comments of the other issue (for `imposm`) that I referenced in my original post, someone commented that they had to set the autoscaling to basically not (i.e. set the min and max ACU's to be the same). I just tried this, and after 24+ hours of `osm2pgsql` running to import the north-america-latest file, it failed, again with the following:

```
Reading in file: north-america-latest.osm.pbf
Using PBF parser.
Processing: Node(1157250k 142.5k/s) Way(64162k 0.82k/s) Relation(0 0.00/s)Prepared statement failed with: SSL connection has been closed unexpectedly
 (7)
Query: get_node_list
with arguments:
  0: {4833315345,4833315346,4833315347,4833315348,4833315345}
, result COPY END for planet_osm_polygon failed: SSL connection has been closed unexpectedly
```

So, at this point I'll be using the workaround to use a regular Aurora Postgres instance, take a snapshot, and then restore that to a serverless instance.

**Comment by lonvia** [comment]
I don't really see what osm2pgsql can do here. This looks like an Aurora issue.

**Comment by chris** [comment]
@lonvia I'm ok closing it, as it probably is. I'll comment back here if AWS finds anything.

**Comment by KKUMARI01** [comment]
Hello @chris , I have been facing similar issue when trying to connect to Aurora database. It throws error "SSL connection has been closed unexpectedly". Did you get any solution?

**Comment by kritika121** [comment]
Hello @chris, I am doing similar stuff where I am using osm2pgsql to import OSM data to Aurora database. I am using osm2pgsql v0.92.0(I also tried with v1.8.1) but after some time it thrwos error "SSL connection has been closed unexpectedly". 
Did you get any Aurora specific solution later?

**Comment by chris** [comment]
@kritika121 so the main problem is that Aurora Serverless has a 24 hour query limit. Once you hit that, they close the connection on you. What I've found is that setting up really large size data GIS databases is better to do with a provisioned Aurora Postgres instance, and then once you're done, convert that to a Serverless instance. This is quite easy to do. How you do this depends on if you're using Aurora Servleress v1 or v2. For v1, you have to snapshot the DB and then restore it to a serverless instance. But, for v2, you can simply modify the instance to be Serverless, and it'll do it all in place for you.  If you haven't chosen at this point, I'd recommend going with v2, mainly because you can get newer Postgres version (v14.5). Also I personally ran into issues with the PostGIS version that AWS is now using with Postgres v10/Aurora Serverless v1.
Finally, the other advantage of data import this way is that you have a more stable (scale/memory/etc. wise) instance during all your import.

If you are importing into an existing DB, and you are using Aurora Serverless v2, you can do the reverse too - where you convert your serverless instance to provisioned, do your import, then convert back again. For v1, it's a bigger challenge to deal with an existing DB, and more likely if you are exceeding that 24-hour query limit, you will have to break up your data into multiple imports that can be achieved in much less time.
