### ISSUE TITLE
Retire multi output

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#1062]
I'd like to propose to deprecate and eventually remove the multi output.

The multi output was an interesting experiment but I don't think that it was ever really used in production by anybody. The only style I'm aware of is @pnorman experimental style. The code for the multi output is rather complicated and hard to maintain. There are also some performance issues we've never tackled. The new 'flex' output can do the same as the multi output but hopefully in a more flexible and performant way. 

For the moment, I'd just add a deprecation warning when the output is used. Once the 'flex' output is production-ready, we could add a Lua script that processes a multi output configuration and then remove the output completely.

If you are a user of the multi output, please comment here.

**Comment by pnorman** [comment]
I'm okay with this.

**Comment by pnorman** [comment]
cc @kevinkreiser @zerebubuth

**Comment by zerebubuth** [comment]
Thanks for letting me know! I agree with @lonvia; multi output was pretty experimental :smile:

While it did get used in production for a while, I think that system was dropped many years ago. I'm not aware of anyone using it in production at the moment.

**Comment by mboeringa** [comment]
@joto 

Just curious, what is the status of this? 

Has multi output already been cleared from the code base? Your new osm2pgsql manual pages no longer seems to reference it, not even as deprecated, so I guess this issue can be closed, or is there still work to do?

**Comment by joto** [comment]
No, this is still in the code and it is still documented, albeit not in detail. It will be removed after the next release.

**Comment by mmd-osm** [comment]
Here's a proposal to remove multi backend now that 1.4.0 was released in December 2020: https://github.com/mmd-osm/osm2pgsql/tree/patch/multi_removal

It leaves almost no traces of the previous multi backend, except for an error message when using --output. Tests are still passing. Man page re-generation didn't work for some reason.

**Comment by joto** [comment]
Removed now in master.
