### ISSUE TITLE
Minor issue with source path for the LUA tag transform script in latest version?

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1063]
I tried to update to the latest 1.2.1 version of osm2pgsql with libosmium version 2.15.4. I followed the instructions and was able to successfully compile it. So far no problem.

However, when I attempt to run osm2pgsql using the exact same command line I used many times before, osm2pgsql fails with an error about a non-existing path, and I see 'src/openstreetmap-carto' duplicated in the error message, which is indeed an incorrect path.

Simply removing the 'src/openstreetmap-carto' part of the **--tag-transform-script** parameter and re-running the command, allowed osm2pgsql to successfully start up.

This is an absolutely minor issue, but am I correct this is a small undocumented change where the LUA script's path should no longer be included and only the script's name specified?

![afbeelding](https://user-images.githubusercontent.com/7635726/72748551-d8c40380-3bb7-11ea-8b74-29a3a8ed6e89.png)

**Comment by lonvia** [comment]
This is a side-effect of #992 which was intended for the multi output but also had an effect on the pgsql output. The lua path must now be relative to the style file, which is slightly odd given that both file names are given on the command line. We might want to switch back to the old behaviour.

I'm curious though, this change should not be in any released version. Are you on a release or latest master from github?

**Comment by mboeringa** [comment]
> I'm curious though, this change should not be in any released version. Are you on a release or latest master from github?

Thanks @lonvia ,

I used 'git pull origin master', so I guess I am on latest master now, so this is as expected then. 

Not a big issue, and the error output fortunately pointed out the problem quickly. Whether or not to switch back to the old behavior, I leave up to you and Jochen Topf, it might just be wise to have a bit of documentation on the main page of the osm2pgsql github repository if this is going to be the new behavior in a future official release.

**Comment by lonvia** [comment]
Oh, I intentionally left this open. You are totally right that this is odd behaviour and we need to either fix it or document it.

**Comment by pnorman** [comment]
> The lua path must now be relative to the style file, which is slightly odd given that both file names are given on the command line. We might want to switch back to the old behaviour.

That makes the most sense to me. The multi (and probably flex) backends need to be relative to the other file, while command-line args need to be relative to the current working directory.
