### ISSUE TITLE
Make proj dependency optional

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#1065]
Most users of osm2pgsql use it with WGS84 or Mercator. Neither projection requires the proj library. The recent breaking changes in proj are really problematic(see #922). The most easy workaround for the majority of users is to make the dependency on proj optional. When not compiled in, we would only offer the two standard projections.

**Comment by sebastic** [comment]
Does that imply making `reprojection.cpp` optional?

That's the only code that includes `osmium/geom/projection.hpp`.

**Comment by lonvia** [comment]
I meant to just make `generic_reprojection_t` optional. But that entails that the use of `osmium/geom/projection.hpp` becomes optional, too.
