### ISSUE TITLE
Unable to insert OSM data to PostgreSQL due to ERROR: must be owner of relation planet_osm_nodes

### ISSUE THREAD

**Issue by vaunakiller** [openstreetmap/osm2pgsql#1068]
Hello everyone.
I'm following a tutorial 'Manually Building a Tilemap Server - ubuntu 16.04 ' from switch2osm
I've got to a point where I have to import OSM data, but stuck with an error

Input
`root@dev:~# osm2pgsql -d gis --create --slim  -G --hstore --tag-transform-script ~/src/openstreetmap-carto/openstreetmap-carto.lua -C 500 --number-processes 1 -S ~/src/openstreetmap-carto/openstreetmap-carto.style ~/data/azerbaijan-latest.osm.pbf -U renderaccount -W`

Output
`osm2pgsql version 1.2.0 (1.2.0-242-g76a3e78) (64 bit id space)
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=500MB, maxblocks=8000*65536, allocation method=11
Mid: pgsql, cache=500
Setting up table: planet_osm_nodes`

`SQL command failed: ERROR:  must be owner of relation planet_osm_nodes`

`Full query: DROP TABLE IF EXISTS planet_osm_nodes CASCADE
node cache: stored: 0(0.00%), storage efficiency: 0.00% (dense blocks: 0, sparse nodes: 0), hit rate: 0.00%
Osm2pgsql failed due to ERROR: Executing SQL`

As the ERROR text states, user **renderaccount** must be an owner of the relation **planet_osm_node** but:

1. That relation does not exist just yet.
2. The whole db gis were created with **renderaccount** user at the earlier step of the tutorial with `createdb -E UTF8 -O renderaccount gis`, shouldn't that grant **renderaccount** user an ownership of aforementioned relation by default?
3. As a solution I've tried to run `GRANT postgres TO renderaccount` but to no avail

Any help on resolving the issue is appreciated, thank you

**Comment by SomeoneElseOSM** [comment]
Just a quick note - you appear to be running osm2pgsql as root, which wasn't what the switch2osm instructions intended.  I doubt it's an actual osm2pgsql bug as such - if it's a problem with the switch2osm guide it's probably best raising it at https://github.com/switch2osm/switch2osm.github.io (actually https://github.com/switch2osm/switch2osm.github.io/issues/59 is similar).  You'll also find similar questions asked at https://help.openstreetmap.org/ et al.

**Comment by lonvia** [comment]
This is indeed not a bug in osm2pgsql. I refer to help.osm.org for installation questions. This is not the right place for those.
