### ISSUE TITLE
Allow output-relevant switches to be provided in a config file

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/osm2pgsql#107]
I can split the command-line parameters into two groups - those that a given style needs to have set, and those not relevant to the style itself.

For example, 
- `--extra-attributes`, `--multi-geometry`, `--keep-coastlines`, `--hstore` might be required by a style
- `--num-processes`, `--unlogged`, `--input-reader`, `--cache` have no influence on the output.

Styles currently need to have a readme entry stating which particular flags need to be set, otherwise the user will find a non-working system after hours of importing data. Users also need to know enough about how osm2pgsql works in order to successfully merge those options with other ones that they've read elsewhere, usually regarding optimisations.

So a better solution would be to allow the style to control the switches, ideally by extending the standard foo.style osm2pgsql config file.

**Comment by lonvia** [comment]
The new 'flex' output has started to move the style-relevant into the lua style file. So if you want that 'flex' is the way to go.

**Comment by gravitystorm** [comment]
OK, that seems reasonable to me.
