### ISSUE TITLE
Supporting --append in non-slim mode

### ISSUE THREAD

**Issue by systemed** [openstreetmap/osm2pgsql#1076]
I use osm2pgsql 0.85.0 on a fairly resource-constrained system for cycle.travel's rendering.

The rendering is reloaded once every month or so and covers certain areas only: North America, Europe, Aus/NZ. Currently I load a series of Geofabrik extracts using --append in non-slim mode. (If I use slim mode I run out of SSD; if I use non-slim mode and merge the extracts beforehand, I run out of RAM.)

Append in non-slim mode was dropped with the C++ rewrite. This was discussed in #213 and clarified in #372. The cited issue is that `middle_ram_t::relations_using_way` is not supported.

I'd like to use newer osm2pgsql, particularly for the flex backend. I'm happy to have a go at attempting a PR to fix this, but would appreciate any pointers from those with knowledge of osm2pgsql's internals. My C++fu is fairly weak so I can't promise that it'll necessarily come to anything, but I'm willing to give it a go.

**Comment by lonvia** [comment]
It should be fairly easy to get the C behaviour back:

* remove the sanity check in options.cpp that forbids append an non-slim
* return an empty list in relations_using_way()
* change osmdata.cpp to not call `slim->*_delete()` and `slim->*_changed()` when `!slim` in the  `*_modify()` functions
* make sure all your data tables have indexes on `osm_id` before appending a file

I haven't really tested this, so no guarantees that I've found all the places.

I'm undecided if I would accept such a patch in the master version for two reasons. 1) there is a good chance that people try to apply change files in non-slim mode which will go horribly wrong. 2) While I'm reasonably convinced that the changes above do the right thing for classic osm2pgsql (well, provided
the extracts happen to have the data in just the right way), I'm not sure about the second stage of the flex output. It does draw on the ability to get data out of middle and there might be crucial data missing when adding an additional extract.

That said, the patch with the changes above should be so small that you can easily maintain a patched version that follows master and works around the pesky maintainers.


I would also suggest that you look into alternatives to your current import mode that might completely avoid appending extracts. Two suggestions in particular:

* *merge extracts and import with slim + --drop (+ --disable-parallel-indexing)*  There have been quite a few changes to osm2pgsql that reduce the disk footprint in drop mode. You might find that it works for you with the most recent versions. A side effect is that you end up with geometrically sorted tables, improving rendering speed.
* *import each extract into separate tables* Then combine tables either by copying  or using Postgresql partitioning. This might do odd things to relations that  go over extract boundaries (although I'm not even sure they work correctly  with the append method either).

**Comment by joto** [comment]
The current master contains a non-slim mode implementation that need much less RAM than before. Maybe this solves your problem @systemed .
