### ISSUE TITLE
Update failure with flex backend

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/osm2pgsql#1080]
I've just tested updates for the first time, and it failed with the error:

```
Prepared statement failed with: insufficient data in "T" message
 (7)
Query: get_wkb
with arguments:
  0: 753776584
```
osm2pgsql then appears to hang.

This was for 2 minutes worth of diffs, namely 

```
#Sun Dec 08 23:30:03 UTC 2019
sequenceNumber=3794211
txnMaxQueried=2470191311
txnActiveList=
txnReadyList=
txnMax=2470191311
timestamp=2019-12-08T23\:30\:02Z
```
and a maxInterval = 120 in the osmosis configuration. 

Command: 

`osmosis --read-replication-interval workingDirectory=osmosis-diff --simplify-change \
  --write-xml-change file="-" | osm2pgsql --append -r xml --output flex --slim -C 8000 --flat-nodes /home/data/postgres-fast/node-cache/node.cache --multi-geometry --hstore --number-process 6 --style thunderforest-flex.lua -d gis -e 14-14 -o expiry.txt -`

Full output:

```
osm2pgsql version 1.2.0 (1.2.0-252-g28e5d37) (64 bit id space)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=8000MB, maxblocks=128000*65536, allocation method=11
Mid: loading persistent node cache from /home/data/postgres-fast/node-cache/node.cache
Mid: pgsql, cache=8000
osm2pgsql version: 1.2.0
osm2pgsql mode: append
Using projection SRS 3857 (Spherical Mercator)

Reading in file: -
Using XML parser.
Feb 20, 2020 10:07:54 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.39
Feb 20, 2020 10:07:54 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Feb 20, 2020 10:07:54 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Feb 20, 2020 10:07:54 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Feb 20, 2020 10:07:55 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline complete.
Feb 20, 2020 10:07:55 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Total execution time: 1601 milliseconds.
  parse time: 4s
Node stats: total(1258), max(7042636290) in 1s
Way stats: total(279), max(753776584) in 1s
Relation stats: total(2), max(9733660) in 0s

Going over pending ways...
        258 ways are pending

Using 6 helper-processes
Left to process: 252...Prepared statement failed with: insufficient data in "T" message
 (7)
Query: get_wkb
with arguments:
  0: 753776584
Left to process: 0...
```

**Comment by mmd-osm** [comment]
I don't seem to find any command line arguments in your issue that you've used to call osm2pgsql.

**Comment by gravitystorm** [comment]
> I don't seem to find any command line arguments in your issue that you've used to call osm2pgsql.

Good point! Added.

**Comment by mmd-osm** [comment]
Hmm. somehow your update got lost. I still see the original text.

**Comment by gravitystorm** [comment]
Ah, maybe I was only in preview and forgot to press save. Thanks!

**Comment by mmd-osm** [comment]
My guess would be that something in your thunderforest-flex.lua table definition triggers this issue. Can you provide a minimal version which still triggers the bug? 

--multi-geometry is not used any longer according to https://github.com/openstreetmap/osm2pgsql/blob/master/docs/flex.md#command-line-options: _Instead, set the type of the geometry column to the type you want, ie polygon vs. multipolygon._

**Comment by joto** [comment]
This seems to be some nasty threading issue. Setting `--number-processes=1` seems to work as a workaround until I can fix this.

**Comment by mmd-osm** [comment]
Seems like you're right, `-fsanitze=thread` reports data races. Will post details shortly.

**Comment by lonvia** [comment]
Thanks @mmd but we've already identified the buggy code.

**Comment by mmd-osm** [comment]
Ok, thanks. This should involve multiple flex_table_t::get_geom_by_id and flex_table_t::connect, which call into libpq

**Comment by mmd-osm** [comment]
Is this related to a shared connection object? https://stackoverflow.com/questions/28936544/thread-safe-pqconn-object

**Comment by gravitystorm** [comment]
> Setting `--number-processes=1` seems to work as a workaround until I can fix this.

Great, thanks for the workaround!
