### ISSUE TITLE
Import history files?

### ISSUE THREAD

**Issue by linuxluigi** [openstreetmap/osm2pgsql#1087]
How would it be possible to import osh (History fiels) and keep every version in the database?
I'm trying to import the osm [planet file](https://planet.openstreetmap.org/planet/full-history/) with the complete history in an [osm2pgsql schema](https://wiki.openstreetmap.org/wiki/Osm2pgsql/schema) and render it with mapnik. 

I've tried already to download the history file of Berlin via Geofrabrik and when I used to import:
```
osm2pgsql -G --hstore --slim --drop --multi-geometry  \
    --extra-attributes \
    --keep-coastlines \
    --style openstreetmap-carto.style \
    --tag-transform-script openstreetmap-carto.lua \
    berlin-internal.osh.pbf
```

The style & lua file is from [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto)

```
Reading in file: /home/fubu/berlin-internal.osh.pbf
Using PBF parser.
COPY_END for COPY planet_osm_nodes FROM STDIN;
 failed: ERROR:  duplicate key value violates unique constraint "planet_osm_nodes_pkey"
DETAIL:  Key (id)=(172539) already exists.
CONTEXT:  COPY planet_osm_nodes, line 2
```

**Comment by joto** [comment]
No, this doesn't work. Rendering from a history file is much more difficult than rendering from a snapshot and osm2pgsql is totally unsuited for this. Somebody tried this years ago at https://github.com/MaZderMind/osm-history-renderer , but this software is unmaintained.

**Comment by linuxluigi** [comment]
Tanks for your answer.
