### ISSUE TITLE
Use multiple style files

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/osm2pgsql#109]
There is often a requirement to use the same database for multiple styles - for example, a standard rendering and a tiger debug style.

In these cases, people have to manually combine foo.style files from multiple style repositories, and merge their contents by hand. It would be useful if osm2pgsql could read multiple styles, e.g.

`osm2pgsql --style foo.style --style bar.style`

... and use the union of the two files. Conflicting requirements (e.g. key is "polygon" in one style and "delete" in the other) would cause an error.

**Comment by joto** [comment]
With the new flex backend you have the full flexibility of Lua. This allows you to, for instance, include other Lua files. This would allow you to load several component styles from a master file and wiring everything up in a way that they are run one after the other. Of course, if the styles use the same global variables or the same tables names, this would not work. But at least the latter is always going to be a problem, no matter what we do.

I could even imagine that we define some guidelines how to write style files that makes them easy to include into a larger style.

**Comment by lonvia** [comment]
Given that we don't have a simple style definition anymore, it probably doesn't make sense to have such a function in osm2pgsql directly anymore. If Lua functions are mergable or not highly depends on their content. I'm closing this issue for now. If a more specific use  case comes up, we can discuss that.
