### ISSUE TITLE
Homebrew install has Seg Fault 11 crash when using --tag-transform-script option

### ISSUE THREAD

**Issue by and-viceversa** [openstreetmap/osm2pgsql#1092]
I'm working on macOS Mojave 10.14.6 with the `brew` install of osm2pgsql.

I went through the [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md) install tutorial and got Segmentation Fault 11 on the following command:
`osm2pgsql -G --hstore --style openstreetmap-carto.style --tag-transform-script openstreetmap-carto.lua -d gis ~/path/to/data.osm.pbf`

This command succeeds without the --tag-transform-script option (however this is required for osm-carto stylesheets).

I played with `ulimit` and `osm2pgsql -C` options, no joy.

This did not work either:
```
brew install --build-from-source luajit
brew install --build-from-source osm2pgsql
```

The solution was to clone the repo and build my own, which passed all test and works properly with the --tag-transform-script Lua option.

All of this to say, I think there is a problem with the way osm2pgsql is built for Homebrew. This Seg Fault problem has been popping up more and more in recent versions of macOS with varying solutions, and is most likely not a problem with osm2pgsql itself. Please see [here](https://discourse.brew.sh/t/snort-and-macos-mojave-10-14-2-segmentation-fault-11/3977) for a the same bug in an unrelated `brew` install.

**Comment by pnorman** [comment]
Does building 1.2.1 specifically from source work?

**Comment by and-viceversa** [comment]
`osm2pgsql --version` returns
```
osm2pgsql version 1.2.0 (1.2.0-273-g8cfe1d0)

Compiled using the following library versions:
Libosmium 2.15.4
Lua 5.3.5
```

I believe I built from master, because I followed the osm2pgsql install page.

Again, I don't think this specifically an osm2pgsql problem. It's something with the way it's built and distributed in Homebrew.

**Comment by pnorman** [comment]
Can you open up a ticket at https://github.com/Homebrew/homebrew-core/issues covering this? There's nothing we can do about it on our side.
