### ISSUE TITLE
add data is not working on big files

### ISSUE THREAD

**Issue by naaaas** [openstreetmap/osm2pgsql#1101]
Hi.
After creating europe map to a posgis DB i'm trying to add Morocco pbf file. Process is stucked at "Using PBF parser" command line. I wait 1 entire day for complete and it seems to be completely stucked. osm2pgsql version: 0.94.0

Commands for create map (works): 

osm2pgsql -c -d map -C 14000 --slim  --cache-strategy sparse -U postgres -W -H localhost -P 5432 /home/Downloads/europe-latest.osm.pbf

Commands for adding map (not working): 

osm2pgsql -a -d map -C 14000 --slim  --cache-strategy sparse -U postgres -W -H localhost -P 5432 /home/Downloads/morocco-latest.osm.pbf

Thank you

**Comment by joto** [comment]
First, 0.94.0 is a very old version of osm2pgsql. We can't help you with that here. Install a current version and try that.

Second, the append mode (`-a`) is for appending change files, not for appending normal OSM data files. What you are trying to do will be slow and might or might not work in the end. If the two extracts don't have overlapping data it might work, if they do, chances are there will be problems. In any case, the way you are using osm2pgsql is not a supported use case.

Instead merge all extracts you want to import first (recommendation: use `osmium [docs](merge`https://docs.osmcode.org/osmium/v1.11.1/osmium-merge.html) ) and then import that into osm2pgsql.

**Comment by naaaas** [comment]
HI.
Thank you. I'm newbie on liux systems. I tried to update osm2pgsql version...but no way. 0.94 is the supposed latest version. I have ubuntu 18.04 . On previous versions 0.81 on older ubuntu version i can append entire map (not diff). Can you please help me?

**Comment by lonvia** [comment]
This is not the right place to ask installation questions. Try https://switch2osm.org/ for installation instructions and https://help.openstreetmap.org for questions.

**Comment by naaaas** [comment]
Hi.
I still having problems. Current osm2pgsql is 0.96 wich is the latest version on ubuntu 19. When "executing  osm2pgsql -a -d map -C 14000 --slim --cache-strategy sparse -U postgres -W -H localhost -P 5432 /home/Downloads/morocco-latest.osm.pbf" proccess is stucked at "using pbf parser". "--append" option works with maps as for my previous experience on older versions. I have other server with older ubuntu and older osm2pgsql and it works perfectly. So i assume that on this new version should work aswell.
