### ISSUE TITLE
osm2pgsql stops while importing planet

### ISSUE THREAD

**Issue by zimirrr** [openstreetmap/osm2pgsql#1115]
I try to import full planet into postgresql with this command:
```
set tmpfile=flat-nodes
set osm_file=planet-200330.osm.pbf

osm2pgsql-latest\osm2pgsql.exe --create ^
 --number-processes 6 ^
 --cache 30000 ^
 --flat-nodes %tmpfile% ^
 --slim ^
 --drop ^
 --style osm2pgsql.style ^
 --hstore-all ^
 --latlong ^
 --multi-geometry ^
 --database %PGDATABASE% ^
 %osm_file%
```
I use windows 10 with latest updates, it has 128GB RAM.

DB is on another machine in same network.

osm2pgsql stops without any messages.
```
...
Reading in file: planet-200330.osm.pbf
Using PBF parser.
Processing: Node(5880134k 8317.0k/s) Way(182705k 48.75k/s) Relation(0 0.00/s)
```

In Event Viewer i see this msg:
```
Windows successfully diagnosed a low virtual memory condition. The following programs consumed the most virtual memory: osm2pgsql.exe (30400) consumed 175843065856 bytes,  javaw.exe (27024) consumed 3312525312 bytes
...
```

osm2pgsql
```
d:\temp\osm\osm2pgsql-latest>osm2pgsql.exe --version
osm2pgsql version 0.96.0 (64 bit id space)

Compiled using the following library versions:
Libosmium 2.15.1
Lua 5.3.4
```

I tried with different cache parameters, it always uses more memory than i set.

**Comment by joto** [comment]
Your osm2pgsql version is very old and has a known memory problem (actually it is in the included libosmium version) with very complex multipolygons. Please upgrade to the latest released version.

**Comment by zimirrr** [comment]
It worked well, thx.

But I've got strange results when testing small pbf.
I've started couple of times with same command osm2pgsl and it showed different results on relations:
```
Processing: Node(1619k 269.9k/s) Way(115k 38.40k/s) Relation(1590 530.00/s)  parse time: 12s
Processing: Node(1619k 269.9k/s) Way(115k 38.40k/s) Relation(950 475.00/s)  parse time: 11s
Processing: Node(1619k 404.8k/s) Way(115k 38.40k/s) Relation(820 410.00/s)  parse time: 9s
Processing: Node(1619k 404.8k/s) Way(115k 38.40k/s) Relation(2010 670.00/s)  parse time: 11s
Processing: Node(1619k 323.9k/s) Way(115k 57.61k/s) Relation(1930 643.33/s)  parse time: 10s
```
__Number of relations always different.__

command was:
```
set osm_file=azores-latest.osm.pbf

..\osm2pgsql-latest\osm2pgsql.exe --create ^
 --cache 2000 ^
 --slim ^
 --number-processes 4 ^
 --style osm2pgsql.style ^
 --hstore-all ^
 --hstore-add-index ^
 --latlong ^
 --multi-geometry ^
 --database %PGDATABASE% ^
 %osm_file%
```

my
```
osm2pgsql version 1.2.1 (64 bit id space)
Compiled using the following library versions:
Libosmium 2.15.4
Lua 5.3.4
```

**Comment by mboeringa** [comment]
Have you actually checked the number of records in the 'planet_osm_polygon' table, to see if that shows any differences as well?

Relation processing is complex, and it may just be that the progress result is not accurate, but only an estimation, but that the end result in the table is OK.

**Comment by zimirrr** [comment]
Yes, count in polygons and rels tables are the same. 
I just didn't think about it. Thank You for pointing that out.
