### ISSUE TITLE
Make it easier to reproduce --hstore behavior with flex backend

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#1123]
I'm finding it difficult to reproduce the behavior of osm2pgsql with --hstore with the flex backend. This is somewhat of a question, but flex-specific questions aren't a great fit anywhere.

Suppose you want to reproduce `osm2pgsql --output pgsql --hstore --style foo.style` where `foo.style` is
```
node,way foo text linear
```

If you have an OSM object with foo=bar, baz=qux this ends up with an object written with foo=bar, tags=hstore(baz=qux).

With the pgsql backend this can be achieved for nodes with
```lua
function filter_tags_node (keyvalues, numberofkeys)
    if next(keyvalues) == nil then
        return 1, {}
    end
    -- other manipulation like deleting some tags goes here
    return 0, keyvalues
end
```

The equivalent flex table declaration would be

```lua
tables.point = osm2pgsql.define_table{
    name = 'planet_osm_point',
    ids = { type = 'node', id_column = 'osm_id' },
    columns = {
        { column = 'geom', type = 'point' },
        { column = 'foo', type = 'text' },
        { column = 'tags', type = 'hstore' }
    }
}
```

My problems come when I try to write `osm2pgsql.process_node`. If I do
```lua
function osm2pgsql.process_node(object)
    if next(object.tags) == nil then
        return
    end
    tables.point:add_row(object.tags)
end
```
I end up with an unpopulated hstore column.

The only option I see here is something like
```lua
point_columns = {
        { column = 'geom', type = 'point' },
        { column = 'foo', type = 'text' },
        { column = 'tags', type = 'hstore' }
}

tables.point = osm2pgsql.define_table{
    name = 'planet_osm_point',
    ids = { type = 'node', id_column = 'osm_id' },
    columns = point_columns
}

function osm2pgsql.process_node(object)
    if next(object.tags) == nil then
        return
    output_cols = {}
    for col in point_columns do
        output_cols[cols.column] = object.tags[cols.column]
        object.tags[cols.column] = nil
    done
    output_cols.tags = object.tags
    tables.point:add_row(output_cols.tags)
end
```

Is there a better way? If this is the only way, we should add it to `compatible.lua`.
Was there too much "magic" in the old way where you would return all the tags and osm2pgsql would sort out what goes into its own column and what goes into tags?

**Comment by joto** [comment]
There is one useful function `grab_tag` which pulls one tag out of the tags table which simplifies the content of your for-loop. See the `data-types.lua` example on how to use this.

Apart from that this looks pretty okay to me. I'd probably start with a list of text column names only, build the columns config for the define_table from that and then iterate over that using `grab_tag` to pull out the tags. Something like this (untested):

```
text_columns = {'foo', ...}

point_columns = {
    { column = 'geom', type = 'point' },
    { column = 'tags', type = 'hstore' }
}

for i,c in ipairs(text_columns) do
    table.insert(point_columns, { column = c, type = 'text' }
end

tables.point = osm2pgsql.define_table{
    name = 'planet_osm_point',
    ids = { type = 'node', id_column = 'osm_id' },
    columns = point_columns
}

function osm2pgsql.process_node(object)
    if next(object.tags) == nil then
        return
    end
    output_cols = { tags = object.tags }
    for c in text_columns do
        output_cols[c] = object:grab_tag(c)
    done
    tables.point:add_row(output_cols)
end
```

The `compatible.lua` was written to be compatible with the C transform, which doesn't have hstore in it if I remember correctly. But I think it would be great to have a `compatible-c.lua` and `compatible-lua.lua` example/test configuration to mimic the C transform as well as the default lua transform.

**Comment by pnorman** [comment]
> The `compatible.lua` was written to be compatible with the C transform, which doesn't have hstore in it if I remember correctly.

The C transform supports --hstore, --hstore-all, and --hstore-column

> There is one useful function `grab_tag` which pulls one tag out of the tags table which simplifies the content of your for-loop. See the `data-types.lua` example on how to use this.

How can this be worked into the unit tests for a flex config? Without it I'd call `osm2pgsql.process_node({tags = {"foo" = "bar"}})`, but that generates an object that doesn't define `grab_tag(self, k)`

**Comment by pnorman** [comment]
I've been doing some testing, and the best I've come up with is

```lua
local point_columns = {
    'access', ... }

local point_columns_map = {}
for _, key in ipairs(point_columns) do
    point_columns_map[key] = true
end

function osm2pgsql.process_node(object)
    if clean_tags(object.tags) then
        return
    end
    cols['layer'] = layer(object.tags['layer'])
    object.tags['layer'] = nil
    for key, value in pairs(object.tags) do
        if point_columns_map[key] then
            cols[key] = value
            object.tags[key] = nil
        end
    end
    ...
end
```
Iterating over point_columns  is not an option because it is too long and this slows way processing down by about 25%.
