### ISSUE TITLE
osm2pgsql takes 64GB memory for a 1 minute data file

### ISSUE THREAD

**Issue by stoecker** [openstreetmap/osm2pgsql#1129]
Version 1.2.1 seems to have a very major memory leak:

Call

/usr/bin/osm2pgsql --append --database osm --username postgres --number-processes 1 --slim --flat-nodes /var/lib/pgsql/nodes.osmdb --multi-geometry --style /home/map/openstreetmap-carto-de/hstore-only.style --hstore --tag-transform-script /home/map/openstreetmap-carto-de/openstreetmap-carto.lua --prefix planet_osm_hstore --verbose osm-load-next.4301.osc

I already reduced cache and number of processes to the bare minimum and reduced the file size to the minimum of 1 minute and it still takes all memory in a few seconds.

**Comment by stoecker** [comment]
[osm-load-next.4301.osc.txt](https://github.com/openstreetmap/osm2pgsql/files/4496630/osm-load-next.4301.osc.txt)

**Comment by joto** [comment]
Can you check which version of libosmium you are using (`osm2pgsql --version` should tell you). There was a bug in older libosmium versions, but the one that comes with osm2pgsql 1.2.1 should be okay.

**Comment by SomeoneElseOSM** [comment]
Is there a link anywhere saying which libosmium had the problem (is it "everything before X" or "from X to Y")?

**Comment by joto** [comment]
@SomeoneElseOSM You can look at the libosmium change log. The issue I suspect here is fixed in 2.15.4.

Osm2pgsql comes with its own version of libosmium and you should always use that version when compiling.

**Comment by stoecker** [comment]
Seems fixed by an update to libosmium from 2.15.3 to 2.15.4.
