### ISSUE TITLE
cmake should prefer luajit over lua5.1

### ISSUE THREAD

**Issue by gen2** [openstreetmap/osm2pgsql#1154]
If both luajit and lua5.1 are installed, the configuration process should prefer luajit over lua5.1. See #1151.

**Comment by mmd-osm** [comment]
Did you run `cmake -D WITH_LUAJIT=ON ..` as mentioned on the README file? https://github.com/openstreetmap/osm2pgsql#luajit-support

LuaJIT isn't enabled by default, you need to explicitly enable it in cmake.

**Comment by gen2** [comment]
> Did you run `cmake -D WITH_LUAJIT=ON ..` as mentioned on the README file? https://github.com/openstreetmap/osm2pgsql#luajit-support
> 
> LuaJIT isn't enabled by default, you need to explicitly enable it in cmake.

Oops, i wasn't aware this is a separateswitch - sorry for the noise!
