### ISSUE TITLE
Default config for flex output?

### ISSUE THREAD

**Issue by joto** [openstreetmap/osm2pgsql#1165]
Currently the flex output doesn't have a default config, so you always have to specify a config on the command line. On the one hand this is good, because it forces the user to understand that there are several options here and to decide which config they want, on the other hand having some default would make first time use a little bit easier.

If we want to have a default config, we have to decide which one that is. Should it be something similar to what the old default config did? Or something more modern using hstore by default etc.?

I tend towards the latter. This is our chance to introduce a "modern" flexible config that incorporates all we have learned in the last decade about this subject. Something that also doubles as a good baseline from which the use can make small changes. I am thinking about three tables, for points, linestrings, and polygons, each with an hstore or JSON column for the tags. We should take the time to get this right.

I think we also should have two config files that mimic the old C transform and the default Lua transform, to help users who are migrating. There is already the `flex-config/compatible.lua` I wrote, but we have to re-check this.

There is one side-issue here: If we decide we want to have a default config, where should it go? Is this compiled in or is there a specific path where it must be, something like `/etc/osm2pgsql/config.lua` or so? Having a file outside the binary makes osm2pgsql a little harder to use, because you have to properly install it with the extra files. (Also we need to handle systems other than Linux where paths are different.)

**Comment by mboeringa** [comment]
I have given my opinion about hstore before, so I don't have to explain I support your suggestions. To me, it would seem more logical to have the default config located on disk and thus accessible for review, instead of compiled in.

**Comment by lonvia** [comment]
We have decided to always require an explicit configuration. See #1255.
