### ISSUE TITLE
Unclear error message output_flex_t::table_add_row

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osm2pgsql#1171]
The error message in output_flex_t::table_add_row is a bit unclear to a Lua user: 
 _Error in 'add_row': Need two parameters: The osm2pgsql.table and the row data_

The osm2pgsql.table parameter is an internal artifact and pretty much invisible to a user. The expected way to fix the error is to provide a single  "row data" parameter only. The error message should reflect this somehow.

    tables.point:add_row()

**Comment by joto** [comment]
Lua is a bit strange in how it calls "member functions", but anybody writing Lua code has to understand the differences of calling a function with `.` or with `:`. Yes, this is confusing, but I don't see how I can improve this here.

**Comment by mmd-osm** [comment]
Is there some way to find out from C++ side, if the Lua code uses `tables.point:add_row() ` or `tables.point.add_row(tables.point)`? The error message would be perfectly find for the `.` notation, but a bit unexpected for the `:` notation due to the syntactic sugar involved.

If they're both the same, I'd agree that it's hard to improve the error message.

**Comment by joto** [comment]
I am not aware of any way to distinguish these.

**Comment by mmd-osm** [comment]
Ok, thanks for double checking, I'll close the issue due to lack of a better alternative.
