### ISSUE TITLE
Document "get_bbox" return structure

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osm2pgsql#1178]
Flex documentation mentions method `get_bbox` as one of the functions provided by the object parameter table:

` get_bbox(): Get the bounding box of the current node or way.`

Unfortunately, there's no indication about the return type / signature of this function. Also, there's no example in flex-config/ * to demo its usage.

Based on the C++ source code below, I concluded that I need to use something along the lines of  `local lon,lat,dummy,dummy = object.get_bbox()` to get a node's lat/lon values.

https://github.com/openstreetmap/osm2pgsql/blob/487bac707f2444f83e237272ea69ffe76fbcd3f1/src/output-flex.cpp#L527-L543,

**Comment by joto** [comment]
Now that you have figured out what it does, why don't you write a PR adding this to the docs?

**Comment by mmd-osm** [comment]
Maybe I'll do. I'm still trying to make sense of what happened in #1174.
