### ISSUE TITLE
Flex backend question: does flex backend also ignore tablespace for SLIM data?

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1182]
According to the flex backend documentation (https://github.com/openstreetmap/osm2pgsql/blob/master/docs/flex.md), flex backend ignores the table space command line options for osm2pgsql. However, there are two types of tablespaces that can be defined: SLIM (--tablepace-slim-data/index) and the output data (--tablespace-main-data/index).

Does the new flex backend also ignore the **--tablepace-slim-data/index** command line options, and if so, am I right SLIM data will end up in PostgreSQL default tablespace always with flex backend?

**Comment by joto** [comment]
The flex backend doesn't care about the slim tables. I'll clarify this in the docs.

**Comment by mboeringa** [comment]
> The flex backend doesn't care about the slim tables.

@joto . Could you also elaborate a bit what you mean with _"flex backend doesn't care about the slim tables?"_

As I understand it, the SLIM option is what triggers the creation of the **_nodes**, **_ways** and **_rels** tables during import. On the one hand, the https://www.volkerschatz.com/net/osm/osm2pgsql-usage.html webpage metions it as being necessary for: 

> Without this mode, all temporary data is stored in RAM and if you do not have enough the import will not work successfully. With slim mode, you should be able to import the data even on a system with limited RAM, although if you do not have enough RAM to cache at least all of the nodes...

Suggesting not using SLIM tables could lead to failure to import on low RAM systems. On the other hand it is mentioned as needed for the minutely updates (which I have never used) and --append:

> This switch is also required for later updates with --append. 

Which is logical, as you need access to the nodes and ways for any updates.
 
**But about the first option regarding RAM:**
If the _"flex backend doesn't care about the slim tables"_, what is the implication regarding RAM usage of osm2pgsql? Or do you simply mean that flex backend uses the existing infrastructure for this, and is not involved or touch any of this part of the code base of osm2pgsql, so **--slim** is still a valid option with flex backend (as it seems, as I see the tables still being generated with flex option), it is just that the changes for the flex backend have nothing to do with this part of osm2pgsql processing?
