### ISSUE TITLE
Flex backend: getting an "attempt to index global 'osm2pgsql'" error

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1183]
Hi,

I did my first attempt to use the new osm2pgsql flex backend. In order to do this:
- I did a git pull for the lastest master branch of osm2pgsql, and compiled it using "make". No errors were displayed during compiling
- I did a git pull for the flex/master branch of openstreetmap-carto.
- I made one set of targeted changes to the openstreetmap-carto LUA file: adding **data_tablespace** and **index_tablespace** to the table definitions in the LUA file like:
**data_tablespace = '<NAME_TABLESPACE>'**
- Run osm2pgsql with -o flex and dropping some command line options that I normally use, but that are ignored

This ended up with the error below. Any ideas of what may be wrong?

![afbeelding](https://user-images.githubusercontent.com/7635726/82576335-07fc7880-9b8a-11ea-9063-979cbd0d36ad.png)

**Comment by mboeringa** [comment]
Line 139 in the openstreetmap-carto LUA file is this one by the way:

**tables.point = osm2pgsql.define_table{**

**Comment by mmd-osm** [comment]
I just tried the following change, and it works like charm (assuming the respective tablespace was created upfront).

```
tables.point = osm2pgsql.define_table{
    name = 'planet_osm_point',
    ids = { type = 'node', id_column = 'osm_id' },
    data_tablespace = 'bla',
    index_tablespace = 'bla',
    columns = col_definitions.point
}
```

Maybe you can post the relevant parts of your file (as text, rather than screenshots).

**Comment by mboeringa** [comment]
@mmd-osm , is that based on the latest commits? Did you do a git pull as well? I see there were some recent changes, that may be totally irrelevant, but it would be good to know if we are truly using the same commit.

Yes, the table space is available. I've used it a thousand times before with previous imports.

**Comment by mmd-osm** [comment]
I did my tests on d34b7a27d73d1a69278b292ff6af1c7c7033bae3

**Comment by mboeringa** [comment]
Thanks @mmd-osm , that makes it likely we are on the same commit. I will attempt it the default or original LUA file if I can find it. As I wrote, I now used the openstreetmap-carto one that is in development.

**Comment by mmd-osm** [comment]
By the _original Lua file_, I meant the one in the flex/master branch (commit edbfe328462254f12deadfe3f5d8c255e8288c07)- which should be the one you used to apply your changes on, as you wrote.

**Comment by mboeringa** [comment]
@mmd-osm , I have now attempted to run osm2pgsql using the 'compatible.lua' tag transform script as available in the 'osm2pgsql/flex-config' directory as part of the osm2pgsql install by substituting the file name in the command line statement.

This results in exactly the same error, and also failing at the **tables.point = osm2pgsql.define_table{** statement.

'compatible.lua' is essentially the same thing as the current flex version of the 'openstreetmap-carto.lua' tag transform script, just without the 'routes' table definition, and the columns statement as part of the table definitions instead of in a separate variable.

**Comment by mboeringa** [comment]
By the way, just for the record, I am on Ubuntu 20.04 Focal and PostgreSQL 12.3 / PostGIS 3.0.1 right now.

**Comment by mmd-osm** [comment]
I cannot reproduce your issue on Ubuntu 20.04, Postgres 12.2 and Postgis 3.0.0 r17983.

Can you post the output of `./osm2pgsql -V` and the exact command line parameters you're using?

**Comment by mboeringa** [comment]
> Can you post the output of `./osm2pgsql -V` and the exact command line parameters you're using?

@mmd-osm 

```
osm2pgsql version 1.2.0 (0.96.0-652-gd34b7a2)

Compiled using the following library versions:
Libosmium 2.15.5
Lua 5.1.4 (LuaJIT 2.1.0-beta3)
```

I now see the commit number is included in the osm2pgsql version, and that is the same as you mentioned (d34b7a2), so we are definitely on the same version.

`osm2pgsql -o flex -d <DATABASE_NAME> -U <USER_NAME> --tablespace-slim-data '<TABLESPACE_NAME>' --tablespace-slim-index '<TABLESPACE_NAME>' --create -W -l --slim --drop --flat-nodes '<NODE_FILE_PATH>' --style 'src/openstreetmap-carto/openstreetmap-carto.style' --tag-transform-script 'src/openstreetmap-carto/openstreetmap-carto.lua' 'data/new-york-latest.osm.pbf' -C 0`

**Comment by mmd-osm** [comment]
Hmm, this is a bit unexpected. It seems you're still running the Lua script in the "old" world and not using the new flex backend at all!

According to https://github.com/openstreetmap/osm2pgsql/blob/master/docs/flex.md#command-line-options, you would need to:

* Change `-o flex` to `-O flex`
* Replace `--style 'src/openstreetmap-carto/openstreetmap-carto.style' --tag-transform-script 'src/openstreetmap-carto/openstreetmap-carto.lua'` by `-S src/openstreetmap-carto/openstreetmap-carto.lua`. There's no need to provide a .style file, all the information is inside the lua script.

I haven't tested --tablespace-slim-data and --tablespace-slim-index in detail.

**Comment by mboeringa** [comment]
>     * Change `-o flex` to `-O flex`   with an uppercase letter "O" instead of a lowercase one.

Ah, stupid, missed that mistake! Thanks @mmd-osm!

>     * Replace `--style 'src/openstreetmap-carto/openstreetmap-carto.style' --tag-transform-script 'src/openstreetmap-carto/openstreetmap-carto.lua'` by `-S src/openstreetmap-carto/openstreetmap-carto.lua`. There's no need to provide a .style file, all the information is inside the lua script.

Yes, I was still figuring out how to specify the command line correctly and use flex backend. Thanks for the guidance. Will try it out and let you know if it works.

**Comment by mboeringa** [comment]
Great @mmd-osm , osm2pgsql started processing with the corrected command line!

**Comment by mboeringa** [comment]
@mmd-osm : the import went fine! A quick review in DBeaver showed the data tables to be OK, including the new flex backend specific 'planet_osm_route' table @pnorman designed for the flex version of openstreetmap-carto.

Thanks again for the help.
