### ISSUE TITLE
--flat-nodes fails using 64 bit Windows builds

### ISSUE THREAD

**Issue by anothergisblogsamples** [openstreetmap/osm2pgsql#119]
Hello,
When I run the following command from DOS:
C:\osm2pgsql\mingw>c:\osm2pgsql\mingw\osm2pgsql.exe -c -l -U gis -P 5432 -H localhost -d carto_osm --slim --flat-nodes c:\osm2pgsql\flat\flatn.nodes  -S c:\osm2pgsql\default_new.style C:\temp\newyork.osm.pbf

I end up getting an error "Mid: loading persistent node cache from c:\osm2pgsql\flat\flatn.nodes Failed to open node cache file: Invalid argument Error occurred, cleaning up"

Does anyone know what is causing this issue?  What argument is causing this error?

Below is the full output:

osm2pgsql SVN version 0.85.0 (64bit id space)

Using projection SRS 4326 (Latlong)
Setting up table: planet_osm_point
NOTICE:  table "planet_osm_point_tmp" does not exist, skipping
Setting up table: planet_osm_line
NOTICE:  table "planet_osm_line_tmp" does not exist, skipping
Setting up table: planet_osm_polygon
NOTICE:  table "planet_osm_polygon_tmp" does not exist, skipping
Setting up table: planet_osm_roads
NOTICE:  table "planet_osm_roads_tmp" does not exist, skipping
Using built-in tag processing pipeline
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Node-cache: cache=800MB, maxblocks=102400*8192, allocation method=10
Mid: loading persistent node cache from c:\osm2pgsql\flat\flatn.nodes
Maximum node in persistent node cache: 0
Mid: pgsql, scale=10000000 cache=800
Setting up table: planet_osm_nodes
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "planet_osm_nodes
_pkey" for table "planet_osm_nodes"
Setting up table: planet_osm_ways
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "planet_osm_ways_
pkey" for table "planet_osm_ways"
Setting up table: planet_osm_rels
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "planet_osm_rels_
pkey" for table "planet_osm_rels"

Reading in file: C:\temp\newyork.osm.pbf
Processing: Node(4207k 5.0k/s) Way(748k 7.97k/s) Relation(3360 101.82/s)  parse
time: 971s

Node stats: total(4207622), max(2631804192) in 836s
Way stats: total(748964), max(257702182) in 94s
Relation stats: total(3361), max(3457617) in 33s
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads

Going over pending ways...
Maximum node in persistent node cache: 2631925759
        643484 ways are pending

Using 1 helper-processes
Mid: loading persistent node cache from c:\osm2pgsql\flat\flatn.nodes
Failed to open node cache file: Invalid argument
Error occurred, cleaning up

**Comment by andyfenna** [comment]
This problem still occurs I'm getting this error:-

G:\planet-OSM\osm2pgsql-bin>osm2pgsql -c -s -P 5433 -d OSM -W -U postgres -H loc
alhost --flat-nodes "I:\OSM\Full\flat_nodes.bin" -C 10000 --number-processes 24
-k -S openstreetmap-carto.style -G "I:\OSM\Full\planet-latest.osm.pbf" -v
osm2pgsql SVN version 0.89.0-dev (64 bit id space)

Password:
Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for sparse node cache
Node-cache: cache=10000MB, maxblocks=160000*65536, allocation method=9
Mid: loading persistent node cache from I:\OSM\Full\flat_nodes.bin
Maximum node in persistent node cache: 0
Mid: pgsql, scale=100 cache=10000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: I:\OSM\Full\planet-latest.osm.pbf
Using PBF parser.
Processing: Node(3077310k 1173.2k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Failed to
 read from node cache: Invalid argument

**Comment by alex85k** [comment]
Will the error be the same if you specify  ``--flat-nodes "I:/OSM/Full/flat_nodes.bin"`` or just ``--flat-nodes flat_nodes.bin`` ?

**Comment by andyfenna** [comment]
Similar error, any suggestions?

I:\OSM>G:\planet-OSM\osm2pgsql-bin\osm2pgsql.exe --append --slim -P 5433 -d OSM -U postgres -H localhost -C 4000 --number-processes 16 --cache-strategy dense --hstore --hstore-add-index -K -G -W --extra-attributes -v changes.osc.gz --flat-nodes flat_nodes.bin -S "G:\planet-OSM\osm2pgsql-bin\openstreetmap-carto.style"
osm2pgsql SVN version 0.89.0-dev (64 bit id space)

Password:
Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Node-cache: cache=4000MB, maxblocks=64000*65536, allocation method=10
Mid: loading persistent node cache from flat_nodes.bin
Failed to open node cache file: No such file or directory
Error occurred, cleaning up

**Comment by lonvia** [comment]
That's a different error. When you use `--append`, the flatnode file must exist.

**Comment by andyfenna** [comment]
That makes sense, so I started a new import last night, unfortunately it failed with this error:-

I:\OSM>G:\planet-OSM\osm2pgsql-bin\osm2pgsql.exe --create --slim -P 5433 -d OSM -U postgres -H localhost -C 10000 --number-processes 24 --cache-strategy dense --hstore --hstore-add-index -K -G -W --extra-attributes -v I:\OSM\Full\planet-latest.osm.pb
f --flat-nodes planet-full.bin -S "G:\planet-OSM\osm2pgsql-bin\default.style"
osm2pgsql SVN version 0.89.0-dev (64 bit id space)

Password:
Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Node-cache: cache=10000MB, maxblocks=160000*65536, allocation method=10
Mid: loading persistent node cache from planet-full.bin
Maximum node in persistent node cache: 0
Mid: pgsql, scale=100 cache=10000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: I:\OSM\Full\planet-latest.osm.pbf
Using PBF parser.
Processing: Node(3125040k 93.3k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Failed to read from node cache: Invalid argument

I:\OSM>PAUSE
Press any key to continue . . .

I've checked the directories and I attached are the files that I have configured, you can see that the planet-full.bin --flat-nodes file has been created.

Any help is much appreciated, let me know if you need anything from me.

Thanks

Andrew

![image](https://cloud.githubusercontent.com/assets/1129795/11711793/e885ec94-9f20-11e5-9f60-04e5ec0ae946.png)

![image](https://cloud.githubusercontent.com/assets/1129795/11711810/ffb03492-9f20-11e5-8660-544dd167c531.png)

**Comment by andyfenna** [comment]
Does anyone know where this will get picked up?

**Comment by andyfenna** [comment]
creating the data seems to work when i do not setup the flat-nodes file

**Comment by ImreSamu** [comment]
>  --flat-nodes planet-full.bin
> ...
>I've checked the directories and I attached are the files that I have configured, you can see that the >planet-full.bin --flat-nodes file has been created.

Maybe some  Policy settings or Anti-Virus ( Anti-Malware ) Software  is blocking  the  "xxxx.bin"  files overwrite.  Can you check the system logs ?

**Comment by andyfenna** [comment]
OK so I have cleared the system logs and taken the file extension off the planet-full.bin file and i have re run the planet import, this starts creating the file then bombs out when it tried to pump it into the db. 

It usually take a few hours before it bombs out, So i'll keep you posted. Once I have the logs I will post them up.

This is the new command line:-

G:\planet-OSM\osm2pgsql-bin\osm2pgsql.exe --create --slim -P 5433 -d OSM -U postgres -H localhost -C 10000 --number-processes 24 --cache-strategy dense --hstore --hstore-add-index -K -G -W --extra-attributes -v I:\OSM\Full\planet-latest.osm.pbf --flat-nodes planet-full -S "G:\planet-OSM\osm2pgsql-bin\default.style"

PAUSE

Thanks

Andrew

**Comment by ImreSamu** [comment]
Sometimes need to add this files and folders to the "exclusions list"  ( "exclude files or folders from scanning" )

for example:  http://support.eset.com/kb2769/?locale=en_US
```
"How do I exclude files or folders from scanning 
in ESET Smart Security or ESET NOD32 Antivirus?"

Problem :
- File-level scanning of some email servers, backup software, 
gaming applications, etc. is causing abnormal system behavior
- Exclude specific applications or folders from Real-time file system protection 
and all scan activity (Startup scan, On-access scanning 
and Computer (On-demand) scanning)
...
```

**Comment by andyfenna** [comment]
... having spoken to our service team we do not have any virus scanners on our db servers....

**Comment by andyfenna** [comment]
Having left it running all weekend I have not managed to import the planet file.. This is the output of the  console...

I:\OSM>G:\planet-OSM\osm2pgsql-bin\osm2pgsql.exe --create --slim -P 5433 -d OSM -U postgres -H localhost -C 10000 --number-processes 24 --cache-strategy dense --hstore --hstore-add-index -K -G -W --extra-attributes -v I:\OSM\Full\planet-latest.osm.pb
f --flat-nodes planet-full -S "G:\planet-OSM\osm2pgsql-bin\default.style"
osm2pgsql SVN version 0.89.0-dev (64 bit id space)

Password:
Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Node-cache: cache=10000MB, maxblocks=160000*65536, allocation method=10
Mid: loading persistent node cache from planet-full
Maximum node in persistent node cache: 0
Mid: pgsql, scale=100 cache=10000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: I:\OSM\Full\planet-latest.osm.pbf
Using PBF parser.
Processing: Node(3125040k 84.1k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Failed to read from node cache: Invalid argument

Nothing was dumped to the event log... please advise.

Thanks

**Comment by lygstate** [comment]
Still have the problem
```
E:\work>osm2pgsql\osm2pgsql.exe --create -s -C 8000 --flat-nodes ./flat_nodes.bin --number-processes 8 -S vector-datasource/osm2pgsql.style -j planet-161031.osm.pbf -d osm -H localhost -U postgres
osm2pgsql version 0.90.1-dev (64 bit id space)

Using built-in tag processing pipeline
Using projection SRS 3857 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for sparse node cache
Node-cache: cache=8000MB, maxblocks=128000*65536, allocation method=9
Mid: loading persistent node cache from ./flat_nodes.bin
Maximum node in persistent node cache: 0
Mid: pgsql, scale=100 cache=8000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: planet-161031.osm.pbf
Using PBF parser.
Processing: Node(3585280k 1700.8k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Failed to read from node cache: Invalid argument

```

**Comment by pnorman** [comment]
Because windows uses `\` instead of `/`, I wonder what it's trying to do with `./flat_nodes.bin`

**Comment by lygstate** [comment]
nothing wrong with ./ Windows also support for that

**Comment by lonvia** [comment]
This ticket is quite old and we've recently changed the flatnode implementation which might resolve the issue. Closing now. If you experience still problems with the flatnode option using the most recent master, please open a new ticket.

**Comment by jkeane** [comment]
This issue is still happening with v0.92.0.  There is a correlation between the cache size setting and this failure.  4 core,16GB, Windows 2012 R2 box.  
     If I try to import north-america w/ 
                -C 6000 --slim --flat-nodes T:\OSM\north-america-flat-nodes.bin, it fails when trying to parse ways
    
If I try to import texas w/
                -C 6000 --slim --flat-nodes T:\OSM\texas-flat-nodes.bin, it succeeds.

In both cases, the flat nodes file is created (and quite large) after the Node parse step.

**Comment by pnorman** [comment]
> This issue is still happening with v0.92.0.

Does it happen with 0.94.0 or master?

> There is a correlation between the cache size setting and this failure

I don't see that below, both have a cache of 6000MB
