### ISSUE TITLE
Windows: update libpq version

### ISSUE THREAD

**Issue by janhec** [openstreetmap/osm2pgsql#1199]
The action and response is/are:
`F:\osm>"C:\Program Files\PostgreSQL\11\bin\\osm2pgsql-bin\osm2pgsql" -S "C:\Program Files\PostgreSQL\11\bin\default.style" -l --hstore -d SST_hulp -U postgres -W geminitwins -C 4096 nlwater.osm
osm2pgsql version 1.2.0

Password:
Allocating memory for sparse node cache
Node-cache: cache=4096MB, maxblocks=65536*65536, allocation method=1
Connection to database failed: SCRAM authentication requires libpq version 10 or above

DB copy thread failed: Connecting to database.`

Working in windows 10, got osm2pgsql.exe from appveyor.
When executing 'where libpq.dll' I get 2 results, both version 11.6. So my installation is ok.
Then it looks as if osm2pgsql uses libpq (old version) in a static library.
If so, PLEASE make it link dynamically, or update the libpq version?
Thanks, Jan

**Comment by janhec** [comment]
Sorry, I overlooked the libpq.dll in the osm2pgsql-bin folder. After removing that, it worked.
So please close this issue.

**Comment by lonvia** [comment]
Reopening this, if you don't mind. We really should update the supplied library to at least 10, probably even 11 or 12.

It is an interesting question, if we should we even ship the dll. I would assume that libpq is always there when you have a PostgreSQL installed. What I don't know is if the DLL versions are binary-compatible.

**Comment by janhec** [comment]
https://github.com/heroku/stack-images/issues/147
Which says libpq is mostly, but not absolutely (backwards compatible)

**Comment by janhec** [comment]
Recalling, the problem with libpq in the postgresql installation is non-essential, it is that usually it will not be in the path and therefore, programming with e.g. pqxx.lib (C++) you will have to know where to find it. When you have no control over the (client) environment, or there is no postgresql on a (client) machine, it can be best to provide it. Very usual sort of conundrum with dll's. So I suggest that upgrading to 11.6 should not break anything still supported. Support lasts 5 years and https://www.postgresql.org/support/versioning/ appears to show that 9.5 is the oldest supported version.

**Comment by mmd-osm** [comment]
Could we extend the build matrix to run job on Postgres 9.6 as today, and another job for Postgres 11, maybe?

**Comment by lonvia** [comment]
We can get libpq 11 or 12 from Conda. Postgis only supplies 64bit versions for Windows starting from Postgresql 10. I'm tempted to simply drop support for 32bit on appveyor and add 64bit as a hard requirement to the README. It's not like anybody has actively tested this lately, not even on Linux. @pnorman?

**Comment by pnorman** [comment]
+1 to dropping 32bit on appveyor
