### ISSUE TITLE
--hstore-add-index help text is ambiguous

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#120]
The osm2pgsql help text states 

> ```
> Hstore options:
>    -k|--hstore      Add tags without column to an additional hstore
>                     (key/value) column
>       --hstore-match-only   Only keep objects that have a value in one of
>                     the columns (default with --hstore is to keep all objects)
>    -j|--hstore-all  Add all tags to an additional hstore (key/value) column
>    -z|--hstore-column   Add an additional hstore (key/value) column containing
>                     all tags that start with the specified string, eg
>                     --hstore-column "name:" will produce an extra hstore
>                     column that contains all name:xx tags
> ```

This allows multiple hstore columns (e.g. by passing `-k -z "name:"`) but the `--hstore-add-index` text is "Add index to hstore column", which is singular, and contradicts the earlier documentation.

I'm not sure what the real interaction between `-k`, `-j`, `-z`, and `--hstore-add-index` is, but it doesn't reflect the documentation.

**Comment by joto** [comment]
I believe I have cleared up those issues in the documentation at https://osm2pgsql.org/doc/manual.html#use-of-hstore
