### ISSUE TITLE
Adding code coverage job in travis

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osm2pgsql#1207]
I ran a code coverage analysis last night and uploaded results here: https://mmd-osm.github.io/osm2pgsql/coverage/src/index.html

Some methods in the new flex backend don't seem to have much test coverage yet, which was somewhat surprising. I do realize that flex is still in development, so this may be just some intermediate status.

Are there any plans to set up coverage analysis as part of travis, i.e. via coveralls? I think this might be helpful to identify missing test cases, and saves some hassle to run those checks locally from time to time.

Some examples:
https://mmd-osm.github.io/osm2pgsql/coverage/src/output-flex.cpp.gcov.html
https://mmd-osm.github.io/osm2pgsql/coverage/src/node-ram-cache.cpp.gcov.html

**Comment by joto** [comment]
As the one doing most development at the moment I can only say that I don't see the necessity. In my experience with other projects the convenience of not running this locally is outweighed by the inconvenience to set this up and keep it running, fighting strange authorization problems, broken reports and random outages of the services used. This might be different if we had lots of developers or stricter rules about test coverage. But in the end this is for the maintainers to decide of course.

**Comment by mmd-osm** [comment]
Ok, works for me.
