### ISSUE TITLE
Broken geometries with -E 4326 projection.

### ISSUE THREAD

**Issue by AnderPijoan** [openstreetmap/osm2pgsql#121]
Hi, I am using osm2pgsql but I want to import data in EPSG:4326 projection. Therefore, I use the -E 4326 flag. However I get all geometries broken and converted to a big square.

osm2pgsql -c -s -d app -U user -W -H localhost -P 5432 -E 4326 file.osm

I think this is due to having planet_osm_nodes lat / lon columns as integer, which truncates lat / lon decimals and so geometries get wrong coordinates.

Am I doing something wrong? Thanks in advance.

**Comment by jgrocha** [comment]
Hi, to covert to EPSG:4326 using the option -l|--latlong works great. Using -E 4362 does not work well. Both are not equivalent. Tested with osm2pgsql SVN version 0.85.0 (64bit id space).

**Comment by pnorman** [comment]
The options parser does `options.scale = (options.projection->get_proj_id() == PROJ_LATLONG) ? 10000000 : 100;`

This means that specifying `-l` will switch the scale multiplier to one appropriate for degrees, but `-E` will not. This also holds true if using NAD83 or similar, where you'd have the same problems as WGS84
