### ISSUE TITLE
[Flex] Provide conninfo to Lua script

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osm2pgsql#1212]
This relates a bit to #1211. Assuming we want to create additional indices, or use database lookups, etc., it would be useful to have access to the same database connection information that the C++ code uses, and leverage a library like `luasql.postgres` :

```
luasql = require "luasql.postgres"
envv = assert (luasql.postgres())
con = assert (envv:connect(osm2pgsql.conninfo))

--- example only
res = assert (con:execute[[
        CREATE INDEX title_idx_nulls_low ON films (title NULLS FIRST)
]])
```

Maybe this one liner would be sufficient? There's one caveat: conninfo might contain a password. Not sure, if we can assume Lua scripts to be trustworthy enough here.

```
diff --git a/src/output-flex.cpp b/src/output-flex.cpp
index 4c7afd3e..ad43d349 100644
--- a/src/output-flex.cpp
+++ b/src/output-flex.cpp
@@ -1273,6 +1273,7 @@ void output_flex_t::init_lua(std::string const &filename)
     luaX_add_table_func(lua_state(), "define_table",
                         lua_trampoline_app_define_table);
     luaX_add_table_func(lua_state(), "mark", lua_trampoline_app_mark);
+    luaX_add_table_str(lua_state(), "conninfo",  m_options.database_options.conninfo().c_str());
 
     lua_setglobal(lua_state(), "osm2pgsql");

```

**Comment by joto** [comment]
Do you have an actual, current use case for this?

We should not just add features that seem nice or useful, because we have to support them until the end of times...

**Comment by mmd-osm** [comment]
I added a number of use cases to https://github.com/openstreetmap/osm2pgsql/issues/1211#issuecomment-645287526, which all depend on database access, and are equally relevant to this issue.

My assumption is that osm2pgsql will not provide a generic interface to execute database queries (both SELECTs, UPDATES, INSERT, etc.), hence the need for an external Lua library to access the database.

To avoid hard-coding database names, or doing any strange tricks to extracts the relevant parameters from the osm2pgsql command line, having the connection parameters readily available in Lua seemed like the least intrusive option.

**Comment by lonvia** [comment]
Closing as per same reason as #1211.
