### ISSUE TITLE
Create primary keys

### ISSUE THREAD

**Issue by G-Guillard** [openstreetmap/osm2pgsql#1216]
In order to support response paging as specified by WFS 2.0, GeoServer needs a primary key, or it will throw `java.io.IOException: Cannot do natural order without a primary key, please add it or specify a manual sort over existing attributes`.  The server will then hang and end the communication with the client (or anyway things won’t go smoothly).  If the client is QGIS, it will (or may ?) get stalled.

Although one can argue the issue lies in GeoServer or QGIS, it is likely that other similar WFS software are affected by the lack of primary key for this particular feature.  Disabling it in the client (i.e. [unchecking the "activate paging" box in QGIS’ WFS connection settings](http://osgeo-org.1560.x6.nabble.com/Anybody-to-confirm-this-WFS-problem-tp5381615p5393605.html)) or server side is not a satisfactory solution.

Furthermore, another situation where uniqueness was necessary [has already been mentioned](https://github.com/openstreetmap/osm2pgsql/issues/446#issuecomment-137660748) a while ago.

In order to [add primary keys manually](https://gis.stackexchange.com/a/171631/159691), **the user needs write access** on this database, which is not always granted.  In addition, this requires resources like large additional disk space and CPU time, which may be a prejudicial issue in many cases.

On the other hand, computing primary keys at the creation of the database is pretty efficient, implementing it is straightforward, and the small if not negligible additional disk space used by such indexes sounds like quite a reasonable trade-off with regards to the current and future benefits of having a primary key.

Is there a rationale for not creating primary keys by default ?  Note that there could exist an option to prevent their creation anyway (or vice versa, although I believe the decision to drop a useful feature should be left to the advanced user).

NB : I understand that it would be an additional field and not `osm_id`, which by design may not be unique.

**Comment by joto** [comment]
This is pretty easy to achieve using the new flex backend. You can define your own table columns there: 

```
...
{ column = 'id', type = 'serial', create_only = true },
...
```

The type `serial` is simply the postgresql type which creates an autoincrement int column, the `create_only` flag tells osm2pgsql to not try to put any data in there. Then, after the first import, call `CREATE UNIQUE INDEX` to build yourself an index.

**Comment by pnorman** [comment]
A primary key is also not null. Can that constraint be done in the flex backend, or does it need to be done after import?

**Comment by lonvia** [comment]
You get the not-null constraint automatically with the serial type.

**Comment by G-Guillard** [comment]
Great !  So this even more straightforward than I imagined.

Can this be made the default ?  Once the user starts wondering about that, it usually means it’s "too late"…

**Comment by joto** [comment]
@pnorman As @lonvia mentioned a serial column is always NOT NULL, but you can also set the `not_null` column option to `true` if you want to force this for any column.

@G-Guillard There is no such thing as "the default" for the flex backend. The user has to say which columnes they want. But this is certainly something we could document better and put into example config files or so. I have put this on my todo list.

There is another consideration here: Traditionally the `osm_id`s are not necessarily unique in osm2pgsql tables. But with the flex backend this is different. It is possible to configure it in a way that the `osm_id` column (or whatever you name it) is unique. In which case you probably want to use that as your primary key column to save the overhead of an extra column.

**Comment by mboeringa** [comment]
>  **It is possible to configure it in a way that the `osm_id` column (or whatever you name it) is unique.** In which case you probably want to use that as your primary key column to save the overhead of an extra column.

@joto , do you mean by specifying all geometry columns as "multipolygon" so as to prevent having osm2pgsql break up OSM MultiPolygons into separate "polygon" objects?

**Comment by joto** [comment]
@mboeringa Yes, and more. I have written up some documentation in #1220 that should cover everything.

**Comment by lonvia** [comment]
Given that it really depends on your use-case what the primary key should be, and if you want it at all, it doesn't really make sense to add any defaults here.
