### ISSUE TITLE
Missing entries in planet_osm_line

### ISSUE THREAD

**Issue by doskabouter** [openstreetmap/osm2pgsql#1222]
Still using an outdated osm2pgsql (0.92.1) so it could already be fixed, but not really able to update right now...

If there are links without any tags, which are part of a relation (f.e. https://www.openstreetmap.org/way/807910987, part of https://www.openstreetmap.org/relation/11139717) then those links are not put in the planet_osm_line table.
There are around 604000 of them so I'd not expect this to be a wrongly digitized issue.

Some of them are coastlines (which I can more or less expect as I didn't use the --keep-coastlines option), but others I would expect in the lines table.
Is this a software issue, or is this something I could fix in my style file?

**Comment by pnorman** [comment]
I would not expect a way without tags which is part of a relation to cause a row in the planet_osm_line table. There might be a row for the the relation, which, depending on tags would be in some combination of the line, polygon, and roads tables.

**Comment by doskabouter** [comment]
There is a row for the relation and for the polygon.
The reason I stumbled upon it is that I want to have country boundaries with the maritime tag where applicable. The only idea I had to get this was to go through the relations and get all the lines that make up that relation (there are also quite a number of lines whch only have the maritime tag but not boundary or admin_level).

Is there a way to force these "no-tag" lines to be added? Or some other way to get those boundaries with the maritime tag?
I know I can subtract the existing lines from the relation polygon to have it complete, but that seems to me as an ugly workaround, not to mention a performance killer.

**Comment by joto** [comment]
I am not sure I understand correctly what you are trying to do, but from what I understand you want to add all member ways of certain relations to the database even if they don't have any tags. This is something that can be done with the (experimental) flex backend which is not in any released version yet, but it is in `master` and you can try it out. See `docs/flex.md` for more details.

**Comment by doskabouter** [comment]
Almost.
I did do a full import of the planet into postgres.
Want I'm aming for is an extract which gives me the countryboundaries as lines with its maritime tag present.

**Comment by doskabouter** [comment]
I reconstructed the missing geometry from the ways and nodes table, so at least I have a workaround.
And assuming my issue is by design I'm going to close it
