### ISSUE TITLE
Upgrading from 0.81 to 0.84

### ISSUE THREAD

**Issue by emiltin** [openstreetmap/osm2pgsql#123]
Hi,

I'm having trouble upgrading from 0.81 to 0.84 on Ubuntu 12.04. I have Postgres 9.3 and Postgis 2.1 installed. I'm following the instructions at http://wiki.openstreetmap.org/wiki/Osm2pgsql: 
- Run sudo apt-get install software-properties-common to install the command add-apt-repository if the command can't be found.
- Run sudo add-apt-repository ppa:kakrueger/openstreetmap to add the PPA
- Run sudo apt-get update to update your packaging system.
- Run sudo apt-get install osm2pgsql to install the osm2pgsql package.

But this installls osm2pgsql the old 0.81. I first removed osm2pgsql using apt-get remove. The above also installs postgres 9.1, even though 9.3 is already installed.

Any ideas what I might be doing wrong?

**Comment by georgbachmann** [comment]
May I ask a question here? It seems the current version that I get using apt-get is still 0.92.0... But there would be far newer releases here... Am I doing something wrong?
