### ISSUE TITLE
Add support for CockroachDB

### ISSUE THREAD

**Issue by awoods187** [openstreetmap/osm2pgsql#1260]
CockroachDB is adding support for Geospatial types and indexing in our upcoming release. In seeking out OSM data to test, we realized that we can't use osm2pgsql out of the box due to some missing Postgres/PostGIS compatibility. We've tracked our investigation in this [issue](https://github.com/cockroachdb/cockroach/issues/51818).

We'd love to work with you to add support for CockroachDB into the tool. Is that something you would be open to? We'd be happy to discuss it in more detail!

**Comment by lonvia** [comment]
We don't have any plans now or in the near future to provide official support for any other DB than Postgresql/Postgis. We simply don't have the developer/maintainer capacity for that. So that is a firm No, I'm afraid.

That said, I would be open to take PRs that refactor the code so that it becomes easier to maintain your own fork. I haven't given that much thought so far but essentially it would mean something along the lines of isolating all SQL code in a separate header file. We don't use much SQL, so something home-grown would likely do. No need for a full SQL abstraction library.

**Comment by otan** [comment]
Hey Sarah, thanks for replying!

I've taken a look at adapting the tool, it involves a few if conditions to make it fully work: https://github.com/openstreetmap/osm2pgsql/compare/master...otan-cockroach:crdb_branch

I can make the tool detect automatically if it is talking to CockroachDB, and happy to submit a patch with all the tests to make it work. Would it be okay to fold into this osm2pgsql's master branch, or is it preferable to maintain our own fork?

**Comment by otan** [comment]
To break it down a little bit more, I think the only changes that need to happen (after we patch up our side) is the ability to make adding the TRIGGER optional, as that is something we plan to support in our long term plan. The other things we have to comment out (synchronous_commit, autovacuum_enabled, fillfactor, unlogged table) we can mock to not do anything.

Would adding the TRIGGER step as a flag be OK with you?

**Comment by mmd-osm** [comment]
The trigger is only needed if you run an import using a non-standard projection. The additional validation is needed to make sure that the re-projected lat/lon values are still valid. The trigger not needed for the default projection EPSG:4326.

You could as well mention in your README, that you don't support the `-E|--proj num` command line parameter, and be done.

**Comment by otan** [comment]
thanks! in that case, we're all good here (we have this working with the basic settings).

**Comment by lonvia** [comment]
Alright, that's great to hear. I'll close this ticket then as there is nothing immediately actionable. We'll keep in mind to clean up the SQL parts of the code a bit to make it easier to replace the backend when refactoring the code in the future.
