### ISSUE TITLE
Core dump importing Chile

### ISSUE THREAD

**Issue by Startit** [openstreetmap/osm2pgsql#1269]
Hi, i downloaded from geofabrik Chile osm pbf, but when importing in nominatim it returnet Core dump, error 139.
I tried to select a custom map (always Chile) from bbbike, but still have same error.
There is anyone can help me?
Thank you

**Comment by joto** [comment]
Most likely you don't have enough main memory. But you didn't tell us anything about your machine. And you didn't tell us which version of osm2pgsql you are using. Please also post the exact commands you used and the output you got.

**Comment by Startit** [comment]
Hi,
thank you for you reply.
I don't think for enough main memory, i imported Uruguay and gone well.
This is command and error:

/Nominatim/data$ /home/nominatim/Nominatim/osm2pgsql/osm2pgsql -klas -C 2000 -O gazetteer -d nominatim -P 5432 /home/nominatim/Nominatim/data/osmosischange.osc
osm2pgsql SVN version 0.85.0 (64bit id space)

Using projection SRS 4326 (Latlong)
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=2000MB, maxblocks=256000*8192, allocation method=11
Mid: pgsql, scale=10000000 cache=2000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /home/nominatim/Nominatim/data/osmosischange.osc
Processing: Node(33161k 2.4k/s) Way(1537k 0.38k/s) Relation(3350 16.26/s)
Segmentation fault (core dumped)

**Comment by lonvia** [comment]
This is a very, very old version of osm2pgsql. Please make sure you use the latest version 3.5.1 of Nominatim.

**Comment by lonvia** [comment]
Please refer to the installation instructions: https://nominatim.org/release-docs/latest/admin/Installation/

**Comment by Startit** [comment]
thank you
