### ISSUE TITLE
Deprecating gazetteer output

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#1311]
With the flex output, there is no need to have a separate gazetteer output, as it allows to configure most of what we need. This tickets collects the features that would still be needed on the osm2pgsql side to get the flex output on par with the current gazetteer implementation:

- [x] Geometry caching. Gazetteer occasionally calls `add_row()` twice for the same object.
- [x] Do not create an index on the geometry column.
- [x] Do not cluster table.
- [ ] ~~Disable handling of forward dependencies on a per-table base.~~

The tasks for the Nominatim side are collected at https://github.com/osm-search/Nominatim/issues/2047.

**Comment by joto** [comment]
Having Nominatim use the flex output, would open up the possibility of generating a single database for rendering and geocoding. Something that a lot of people want.

At a minimum this would need some mechanism for handling the difference in processing though: For the rendering db osm2pgsql needs to handle the forward dependencies in append mode, Nominatim doesn't need that.

**Comment by joto** [comment]
With the merge of #1847 another big step towards this has been taken. See also https://nominatim.org/2022/11/28/towards-flex.html .

**Comment by lonvia** [comment]
Handling of forward dependencies has been rendered moot by https://github.com/osm-search/Nominatim/pull/2927
https://github.com/osm-search/Nominatim/pull/2932 fully switches Nominatim to flex.

The one task that remains is to remove the gazetteer output. I don't think we need much of a deprecation period as the output was only ever meant to be used with Nominatim.

**Comment by joto** [comment]
Closing in favour of #1870.
