### ISSUE TITLE
Change z_order of link roads

### ISSUE THREAD

**Issue by math1985** [openstreetmap/osm2pgsql#132]
In the main openstreetmap-carto style and most styles derived from that, link roads are rendered below any other type of road. This is done so that the end of link roads [do not overlap](http://www.openstreetmap.org/#map=17/51.67412/5.32896) with the roads on which they end up.

It would therefore be logical to give link roads a lower z_order

Do you think this is something that can/should be handled by osm2pgsql?

See also the discussion here: https://github.com/gravitystorm/openstreetmap-carto/issues/462

**Comment by pnorman** [comment]
I think at this point there's enough experience with the proposed changes to consider them in osm2pgsql. Editing the original message to reflect what's desired
