### ISSUE TITLE
Deprecate pgsql output code to alter tables in append mode?

### ISSUE THREAD

**Issue by joto** [openstreetmap/osm2pgsql#1329]
The pgsql output [contains some code](https://github.com/openstreetmap/osm2pgsql/blob/master/src/table.cpp#L127-L143) that changes the output tables in append mode if the tables in the database are different from what the config says. This code can only handle a few simple cases. As far as I know this was never documented anywhere.

Maybe it is better to deprecate/remove this?

**Comment by lonvia** [comment]
@pnorman Any idea is openstreetmap-carto has ever used this feature to add additional columns for the style?

**Comment by pnorman** [comment]
It would only ever come up if someone had an old schema DB and wanted to go to a new one. This wouldn't work anyways because the transforms would be different and we've only ever removed columns, not added them.

👍 to removing.
