### ISSUE TITLE
o5c update causes "duplicate key value violates unique constraint" error

### ISSUE THREAD

**Issue by kayrus** [openstreetmap/osm2pgsql#133]
When I try to update osm postgresql database from o5c file, osm2pgsql fails with the following message:

```
Processing: Node(14829k 1.4k/s) Way(669k 0.06k/s) Relation(0 0.00/s)
insert_way failed: ERROR:  duplicate key value violates unique constraint "planet_osm_ways_pkey"
DETAIL:  Key (id)=(273191556) already exists.

```

if it makes sense, o5c was created from osc file by osmconvert utility:

```
osmconvert {576..580}.osc.gz --emulate-osmosis --fake-lonlat --merge-versions --out-o5c >  cumulative.o5c

```

osc update works perfectly:

```
osmconvert {576..580}.osc.gz --emulate-osmosis --fake-lonlat --merge-versions --out-osc >  cumulative.osc
```

**Comment by lonvia** [comment]
This was normal behaviour at the time of the report. Only osc files did put osm2pgsql in update mode which is needed to delete an updated way. Closing as this is severely out of date with current code.
