### ISSUE TITLE
Flex output does not by default generate "hstore" tags column in combination with "compatible.lua"

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1333]
Note: I build osm2pgsql from scratch yesterday (21st november), so should be on the latest master code with this.

Minor issue, but I noticed the **compatible.lua** script, that is part of the "flex-config" folder with example LUA scripts that can be used either "as-is" or as a basis for your own style development, does not set the **local hstore** variable to True. As a consequence, no **hstore** column is generated, even though the **local hstore_match_only** variable is set to True.

Since as I understand it, the compatible.lua scripts is meant as an easy way to generate a schema compatible with current pgsql output for users starting to familiarize themselves with the new flex output, that most likely means for a lot of people generating output based on openstreetmap-carto as input style. As a consequence, I think it would be good if the compatible.lua script by default set the **local hstore** variable to True.

Using the old pgsql output in combination with recent releases of openstreetmap-carto always seems to generate an hstore column, so from that perspective being "compatible" likely means an hstore column by default. I would thus suggest to change this in **compatible.lua**.

Note that I did check that changing the **local hstore** to True, does indeed succesfully generate the "tags" hstore column, so that part is OK.

**Comment by mboeringa** [comment]
Maybe other example styles in the flex-config could default to using hstore as well? I must admit I haven't checked them yet...

**Comment by joto** [comment]
The `compatible.lua` file should be compatible with the "old osm2pgsql", that also means that it has the same defaults as before. So `hstore` is set to `false`, because you used to need the `--hstore` option to set this to `true`.

You found an error, though: The `hstore_match_only` should have been set to `false` and I will change that in the code.

**Comment by mboeringa** [comment]
@joto 

Ok, thanks, clear. I hadn't interpreted the result in terms of old style C transforms and results thereof, mainly because I always ran osm2pgsql using the openstreetmap-carto as input style, so this wasn't immediately obvious to me.

Solution to set it in the style file to desired configuration is easy though.
