### ISSUE TITLE
Flex output does not generate numeric (int4) "layer" column with "compatible.lua".

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1334]
As an extension of #1333 , the flex output with "compatible.lua" as input style, does not generate a numeric int4 layer column, instead it generates a text type column. Old style pgsql output of openstreetmap-carto always did this, converting the text layer values to int4 numeric column.

I think it would be desirable to have "compatible.lua" do this as well.

**Comment by joto** [comment]
I am compatible here with the default C transform, not with `openstreetmap-carto`, and the C transform does create a `TEXT` column.

We could have a `compatible-with-openstreetmap-carto` configuration, but that is a bit of a different and more ambitious goal than what I am doing here. The carto style always lived outside the osm2pgsql repository, so I am not trying to bring that in here. @pnorman worked on a ["translation" of the carto style](https://github.com/gravitystorm/openstreetmap-carto/tree/flex/master).

**Comment by mboeringa** [comment]
> The carto style always lived outside the osm2pgsql repository, so I am not trying to bring that in here. @pnorman worked on a ["translation" of the carto style](https://github.com/gravitystorm/openstreetmap-carto/tree/flex/master).

@joto 

Yes, I was aware of Paul's work on this, and in fact have been running that version of the style for the last couple of months in combination with a recent (but not latest master) "flex" version of osm2pgsql, and it seemed to work quite well. The addition of a new "routes" tables is nice as well, and certainly adds something to that new carto version. Main reason I ran into this was, as written in one of the other issues, the work on a new Ubuntu virtual machine instance, that required reconfiguring a lot.

_In terms of output, the compatible.lua and flex version of the openstreetmap-carto style are really close._ Paul had initially suggested some more drastic changes in table layout, e.g. a dedicated highways table (not only for low zoom like "roads"). 

And of course, the potential configurations are endless with this new "flex" version of osm2pgsql... so both new flex styles are in fact still really conservative in what they do!
