### ISSUE TITLE
Link to OpenStreetMap Dev Server broken

### ISSUE THREAD

**Issue by AnjaGer** [openstreetmap/osm2pgsql#1342]
Hi,

the link to the OpenStreetMap Dev Server - as provided in the README.md file - does not work anymore.
https://lonvia.dev.openstreetmap.org/osm2pgsql-winbuild/releases/
Could you provide a new link?

BR, Anja

**Comment by joto** [comment]
The link is okay, its just that the server is currently down.

**Comment by AnjaGer** [comment]
ok, thanks.
