### ISSUE TITLE
Parallel COPY FROM in future PostgreSQL

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1351]
Maybe you are already aware of this, but I noticed that in the commit fest of PostgreSQL, that there appears to be some recent work going on regarding making COPY FROM parallel:

https://commitfest.postgresql.org/31/2610/

Of course, osm2pgsql is already blazingly fast even with a single thread COPY FROM for stages like loading nodes and ways as I witnessed in pgAdmin, but I think it might be good to to keep an eye on this in relation to future releases of osm2pgsql. 

No idea when this will make it into PostgreSQL though, and if the work is actually relevant for osm2pgsql (I see a mention of WHERE clause as well in the linked emails of the commit fest), so just for informational purposes for now.

**Comment by joto** [comment]
osm2pgsql developers are always monitoring changes in PostgreSQL. This is not really a subject for an issue in the osm2pgsql bug tracker. If you want to, you can discuss these kinds of things on the [dev mailing list](https://lists.openstreetmap.org/listinfo/dev). Closing here.
