### ISSUE TITLE
osm2pgsql refuses to run in append mode if -C / --cache isn't specified

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/osm2pgsql#1362]
Example:
`/usr/local/bin/osm2pgsql 
  -a -d gis --slim --hstore 
  --number-processes 6 --flat-nodes /nvme/osm2pgsql/node.cache  
  -e 15-16  -o /var/local/replication/tile_expiry 
  changes.osc.gz`

will fail with

`2020-12-08 09:33:02  osm2pgsql version 1.4.0 (1.4.0)`
`2020-12-08 09:33:02  ERROR: Usage error. For further information call: osm2pgsql --help`

Adding `-C 500` will allow it to run.

As there is already a default cache value, the requirement to add this argument seems to be wrong.

**Comment by joto** [comment]
I can not reproduce this. Are you sure that's the command line you used? That error message typically means that you either used a non-existing command line option or that there was no input file on the command line.

**Comment by simonpoole** [comment]
It's literally from the script that failed and now is running with -C 500 Obviously there might be a two left thumbs issue, but haven't been able to locate that either.
