### ISSUE TITLE
Manual pages links not working on Android

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1363]
Hi @joto ,

First: congratulations with the new release and thanks for the good work on osm2pgsql and the manual pages!

I just stumbled on a number of minor things:

- For some reason, part of the links on the new osm2pgsql **Manual** pages do not seem to work on my Android 7 phone, while they do work without issues within Firefox on my Windows 10 pc. There is no error displayed, trying to click the visibly underlined links just does nothing. E.g. when on the https://osm2pgsql.org/news/2020/12/07/release-1.4.0.html "News" page, I cannot click the "documentation", "examples", "support" and "contributing" links in the first text line, while I can click the "the manual" link on the bottom, and many other links are working as well, so it is not really consistent which ones work or don't.

- I noticed a few minor typos you may wish to correct:

https://blog.jochentopf.com/2020-12-02-osm2pgsql-work.html

"They are not tutorials, but they show a wide range of problems and that and how osm2pgsql can solve them.": **Drop 'and that'**

https://osm2pgsql.org/news/2020/12/07/release-1.4.0.html

"When printing how low something took": **'low' --> 'long'**

"Not that some of these are breaking changes compared to the behaviour in version 1.3.0": **'Not' --> 'Note'**

**Comment by joto** [comment]
First: Please don't put several unrelated things into the same issue. And website-related issues should be opened on the repository https://github.com/openstreetmap/osm2pgsql-website not here.

* The differences in those links could be that some are local links inside the website, but the links that you mention as not working are going to https://osm2pgsql.org, maybe you have a problem with https links. 
* Thanks for the report, I'll fix the typos.

**Comment by mboeringa** [comment]
> First: Please don't put several unrelated things into the same issue. And website-related issues should be opened on the repository https://github.com/openstreetmap/osm2pgsql-website not here.

Ah, sorry, missed that one. Is there a link to that repository from this one, to re-direct people if they are looking for a way to submit corrections? I haven't looked at it I must admit...

Will open a new case there.
