### ISSUE TITLE
Missing osm_timestamp tag when using --extra-attributes and .pbf files

### ISSUE THREAD

**Issue by dalek2point3** [openstreetmap/osm2pgsql#137]
When importing data from .pbf into the database, with --extra-attributes flag (and relevant settings in the style file) -- the metadata for osm_timestamp seems to be blank. I've checked the XML version of the file, and it seems to contain the timestamp metadata. Using an older version (0.83) returned blank for all metadata, while with v0.85 only the timestamp seems to be blank. 

In order to recreate this issue:
run 

    osm2pgsql -U postgres -d gis -W austin.osm.pbf -s -S default.style --extra-attributes

with the following style file:
    http://pastie.org/9121340

and the following OSM data file:
    https://s3.amazonaws.com/metro-extracts.mapzen.com/austin.osm.pbf

This seems to be related to: 
https://github.com/openstreetmap/osm2pgsql/commit/441bedbb68cc64d609d48c696be91200a12ed0a7

**Comment by lonvia** [comment]
There is a TODO for timestamps in the pdf parser: https://github.com/openstreetmap/osm2pgsql/blob/master/parse-pbf.cpp#L216

**Comment by pnorman** [comment]
todo is now at https://github.com/openstreetmap/osm2pgsql/blob/master/parse-pbf.cpp#L202

**Comment by pnorman** [comment]
Just to note, PBFs store timestamp as int32 in the info message but sint64 delta encoded in a denseinfo message.

**Comment by lonvia** [comment]
This should be fixed with the latest version using libosmium. Someone care to check?

**Comment by nvkelso** [comment]
+1 for getting a PBF fix in. Was able to work around the bug by using the XML file instead.

**Comment by pnorman** [comment]
> This should be fixed with the latest version using libosmium. Someone care to check?

wfm
