### ISSUE TITLE
Unexpected output: no polygon for specific OSM relation.

### ISSUE THREAD

**Issue by alxgrh** [openstreetmap/osm2pgsql#1372]
Hello,

I have an issue with osm2pgsql results after loading PBF file to DB.

>    what you are trying to achieve in the end,

I want to load administrative boundaries of the US counties into DB.

>    what you did,

Ways to reproduce. 
1. Download PBF file for New York state from here http://download.geofabrik.de/north-america/us/new-york.html
2. Filter objests you're interested in by osmium
`osmium tags-filter new-york-latest.osm.pbf n/place=city,town,village,hamlet,county r/admin_level=4,5,6,7,8,9,10 --overwrite --verbose -o filtered-new-york-latest.osm.pbf`
3. Load filtered file to DB
` /usr/local/bin/osm2pgsql -p osm -H 192.168.1.3 -P5432 -d dbname -U dbuser -W -c  --slim -l --verbose -G --keep-coastlines  filtered-new-york-latest.osm.pbf`
4. Check counties' borders by DB query
`SELECT name, way FROM osm_polygon WHERE admin_level = '6' order by name;`

>    what behaviour you expected from osm2pgsql,

I expected osm2pgsql created polygons for all counties from the NY state in osm_polygon table. 

>    and what happened instead.

Not all of counties have related polygon in DB.
![изображение](https://user-images.githubusercontent.com/2371914/102139020-564acf00-3e6e-11eb-821a-7351fdd9cce5.png)
You may see the gaps in territory. This is an example of the absent county https://www.openstreetmap.org/relation/1804311#map=10/43.0333/-77.5607
Its data exists in the PBF file. It's possible to check it by command
`osmium show filtered-new-york-latest.osm.pbf `

Also all relevant objects exist in DB,  but not merged into the boundary polygon. It can be checked by such query
```
with rel_members as ( 
	select unnest(parts) id 
	from osm_rels 
	where id = 1804311
),
way_members as (
	select w.id way_id, unnest(nodes) as node_id
	from rel_members m 
	left join osm_ways w on w.id=m.id
)
select st_collect( coalesce(l.way, p.way, ST_GeographyFromText('Point(' || lon/10000000.0 || ' ' || lat/10000000.0 || ')'))::geometry)
from rel_members m 
left join osm_line l on l.osm_id=m.id
left join osm_point p on p.osm_id=m.id
left join way_members w on  w.way_id=m.id
left join osm_nodes n on n.id=w.node_id;
```
![изображение](https://user-images.githubusercontent.com/2371914/102139432-e2f58d00-3e6e-11eb-9783-63a279c3aaca.png)

So it's seems to be an osm2pgsql issue, but not PBF file incompleteness issue. Is there a way to debug this issue, having not edited the C++ code?

osm2pgsql is built from source from the github release v1.4.0 tar.

**Comment by pnorman** [comment]
The relation was not closed, so a polygon could not be formed from it.

I fixed this by adding https://www.openstreetmap.org/way/884922494

**Comment by alxgrh** [comment]
Hi @pnorman 

thanks for the update and fix. 
How can I debug and fix such issues by myself? There are lots of them. You may see that there are about 4-5 missed counties in the NY state. I guess there are many of them in the US and other countries. 
Another example https://www.openstreetmap.org/relation/1837992#map=10/42.7495/-77.4316
![изображение](https://user-images.githubusercontent.com/2371914/102207943-d0676c00-3edf-11eb-8243-f3ceb9098208.png)

Also apart from unclosed relation issue, osm2ppsql was unable to recognize this line https://www.openstreetmap.org/way/303266774#map=11/42.7624/-77.4948 , despite its nodes exist in DB
```
with w as (
	select unnest(ow.nodes) way_node 
	from osm_ways ow
	where ow.id=303266774
)
select way_node, ST_GeographyFromText('Point(' || lon/10000000.0 || ' ' || lat/10000000.0 || ')')
from w, osm_nodes osn 
where osn.id=way_node;
way_node  |st_geographyfromtext          |
----------|------------------------------|
 263513941|POINT (-77.587997 42.85401)   |
3076177262|POINT (-77.5880389 42.8419625)|
3076177263|POINT (-77.5878147 42.8164676)|
 263508743|POINT (-77.5884498 42.7629665)|
```
It seems to be a separate issue.


Is it possible to implement additional feature in osm2pgsql like special option --enclose-relation-to-polygon, which would try to enclose relation into polygon?

**Comment by joto** [comment]
Fixing OSM data is way off topic for osm2pgsql, you should discuss this elsewhere. For a tool see, for instance, [the OSM inspectorI](https://tools.geofabrik.de/osmi/?view=areas) but there are many more.
