### ISSUE TITLE
Confusing error when postigs extension is missing

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#1400]
When running osm2pgsql without naming a database via `-d` or PGDATABASE, then the version check prints a rather confusing message:

```
me@machine:~$ ./osm2pgsql -S ../default.style ~/osm/data/liechtenstein-latest.osm.pbf 
2021-01-29 17:54:41  osm2pgsql version 1.4.0 (1.4.0-82-gfd9c0c33)
2021-01-29 17:54:41  Database version: 11.9 (Debian 11.9-0+deb10u1)
2021-01-29 17:54:41  ERROR: Database error: ERROR:  function postgis_lib_version() does not exist
LINE 1: SELECT regexp_split_to_table(postgis_lib_version(), '\.')
                                     ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

The same happens when the database is right but the postgis extension is missing. We should print a more helpful message here.

**Comment by pnorman** [comment]
What database is it connecting to?

**Comment by stephankn** [comment]
Do I understand correctly, that the request is to first check whether the `postgis` extension is installed, before calling postgis functions?


Like:

```
postgres=# SELECT count(*) FROM pg_extension WHERE extname='postgis';
 count
-------
     1
(1 row)
```

And if not printing an error message?

**Comment by lonvia** [comment]
> What database is it connecting to?

It was connecting to a database under my username, which happened to exist. Issue title fixed.
