### ISSUE TITLE
Show elapsed time for different loading stages (nodes/ways/relations)

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1405]
Currently, there is no easy way to understand how much time each loading stage (nodes/ways/relations) took in osm2pgsql.
I can sort of deduct it from the final node/way/relation "X k/s" figure, but it might be nice to show an "hour:min:second" time elapsed figure after each stage has finished.

So something like:
**8h10m30s to process nodes**

**Comment by joto** [comment]
That's already in master and will bein the next version. Itl shows something like this:

```
2021-01-30 20:08:09    Processed 18966430 nodes in 42s - 452k/s
2021-01-30 20:08:09    Processed 3016803 ways in 183s (3m 3s) - 16k/s
2021-01-30 20:08:09    Processed 41977 relations in 35s - 1k/s
```
