### ISSUE TITLE
Unnecessary inclusion of libdl

### ISSUE THREAD

**Issue by joto** [openstreetmap/osm2pgsql#141]
The Debian build complains:

dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/osm2pgsql/usr/bin/nodecachefilereader debian/osm2pgsql/usr/bin/osm2pgsql were not linked against libdl.so.2 (they use none of the library's symbols)

This seems to be caused by the lua integration: https://github.com/openstreetmap/osm2pgsql/blob/master/m4/ax_lua.m4#L564

**Comment by pnorman** [comment]
Doesn't seem to be directly linking `-ldl` anymore.
