### ISSUE TITLE
New PostGIS check breaks CockroachDB compatibility

### ISSUE THREAD

**Issue by Pjstaab** [openstreetmap/osm2pgsql#1412]
With the new PostGIS check in 1.4.1 osm2pgsql fails to work with CockroachDB, going back to 1.4.0 it loads data just fine.

**Comment by pnorman** [comment]
https://github.com/openstreetmap/osm2pgsql/commit/e63ee8f736d674dd93389c67d2f0b9c4b0de0dc1 is the relevant commit

Is the issue that the `pg_extension` check doesn't work, or the `current_catalog`?

**Comment by joto** [comment]
osm2pgsql is a PostgreSQL/PostGIS importer. Other databases are not supported or tested officially. I am sure we'd be willing to consider pull requests that add support for other databases if they don't break any functionality in PostgreSQL/PostGIS.

**Comment by Pjstaab** [comment]
I totally understand being a PostreSQL/PostGIS importer, but it looks like that CockroachDB specifically tries to be compatible with OSM. In fact, they have a [whole page](https://www.cockroachlabs.com/docs/stable/migrate-from-openstreetmap.html) on how to get OSM running on it. As for the specif error, before it passed with a version of `3.0.1` for the PostGIS extension version. With the new check it's failing on getting the PostGIS version, the query returns nothing. Looks like cockroach has 3 entries in the `pg_extension` schema: `geography_colums`, `Shows all defined geography columns. Matches PostGIS' geography_columns functionality.` `geometry_columns`, `Shows all defined geometry columns. Matches PostGIS' geometry_columns functionality.` and `spatial_ref_sys`, `Shows all defined Spatial Reference Identifiers (SRIDs). Matches PostGIS' spatial_ref_sys table.` I would guess simply tweaking this check to work with both postres and cockroach is all that's needed to fix this. I'm pretty new to all this but I'll see if I can maybe figure out a query that works for both cockroach and postgres.

**Comment by stephankn** [comment]
osm2pgsql checks for existence of the postgis extension and its version. PostgreSQL stores extensions in a dedicated table. This queries for it:

    SELECT regexp_split_to_table(extversion, '\\.') FROM pg_extension WHERE extname='postgis';

If CockroachDB should be supported it has to publish existence of the plugin and its version.

I had a very short look into the documentation. For me it looks like CockroachDB is not using postgis at all, but re-implemented the functions. There is a meta-issue in Github mentioning over 100 implementations missing: 

https://www.cockroachlabs.com/docs/v20.2/known-limitations#spatial-support-limitations

linking to Github: https://github.com/cockroachdb/cockroach/issues/49203

So as compatibility with CockroachDB then depends not on the version of Postgis, but on the main version of CockroachDB a potential fix would have to distinguish between PostgreSQL and CockroachDB. And for CockroachDB check its version against a version tested to be compatible.

    SELECT version();


With the spatial implementation differing, I would expect subtle differences in behavior.

The query for postgis version is fake:

> https://www.cockroachlabs.com/docs/v20.2/functions-and-operators.html
> 
> postgis_lib_version() → string | Compatibility placeholder function with PostGIS. Returns a fixed string based on PostGIS 3.0.1, with minor edits.
> -- | --
> 

Whoever intents do submit a PR should keep this in mind.

**Comment by lonvia** [comment]
I'm going to close this as this is not really something we are going to address from our side.

You are always welcome to propose PRs when you find that some refactoring or more cleverly formulated query makes working with other database systems easier. We will accommodate them as far as possible.
