### ISSUE TITLE
Missing empty string check in flex write_double

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/osm2pgsql#1416]
There's a missing empty string check in [`write_double`](https://github.com/openstreetmap/osm2pgsql/blob/497476d56f7c1fcbbdb95b363293de6ce0feac00/src/output-flex.cpp#L302-L303) which means that an empty string input is written out as `0.0` instead of `null`.

The equivalent `write_integer` [has the check](https://github.com/openstreetmap/osm2pgsql/blob/497476d56f7c1fcbbdb95b363293de6ce0feac00/src/output-flex.cpp#L279-L282) and works fine.

I think the fix is straightforward, but I'm not sure about the tests, which is why I haven't made a PR. My guess would be to add "AND treal IS NULL" to the first 6 of the [invalid string](https://github.com/openstreetmap/osm2pgsql/blob/497476d56f7c1fcbbdb95b363293de6ce0feac00/tests/test-output-flex-types.cpp#L179-L185) tests, but that leaves the issue of the final test which should be valid input for real output as well as being invalid input for the integer columns. I couldn't find any other tests which ensure that real output works correctly for not-an-integer-but-still-a-number-string input e.g. "-123.45", but I'm not sure if such tests are missing or I've overlooked them somewhere else.

**Comment by joto** [comment]
Checking real numbers is always tricky because you can't just use `==` to compare them, so I cheated and didn't write out all the tests it should have. I have changed the tests in a way similar to what you suggested and fixed the code.
