### ISSUE TITLE
[Question] How to find OSM timestamp for replication?

### ISSUE THREAD

**Issue by hypervtechnics** [openstreetmap/osm2pgsql#1418]
I read the docs. For the first fetching of the osm updates I can use the pbf file I imported. But after importing there are new objects. So osm2pgsql should be able to tell me the latest timestamp it is on. So a second/updated timestamp is required

**Comment by joto** [comment]
The tools described [here](https://osm2pgsql.org/doc/manual.html#updating-an-existing-database) do the updating for you, you don't need anything else.

**Comment by hypervtechnics** [comment]
Thank you for the answer. Just found them shortly after :)
