### ISSUE TITLE
possible optimization, dynamic increase of work_mem

### ISSUE THREAD

**Issue by stephankn** [openstreetmap/osm2pgsql#1419]
I imported a smaller extract using osm2pgsql v1.4.1 resulting in a database size of 22GB. I noticed that PostgreSQL 13 used in total a few gigabytes of temp-files. I did a reset of the statistics and rendered tiles and I am quite certain that the temporary filed did not result from rendering. So I guess it is from the import.
I have configured `work_mem=1G` which seems to be too small in this case.

Could it bring some benefit on import speed if osm2pgsql would increase work_mem during the import session?
Has someone considered this already or would it require some test runs?

I queried the temp size with:

    SELECT temp_files AS "Temporary files", temp_bytes AS "Size of temporary files" FROM   pg_stat_database db;

**Comment by joto** [comment]
Documentation on how to tune your PostgreSQL server is in the docs: https://osm2pgsql.org/doc/manual.html#tuning-the-postgresql-server .

osm2pgsql does not do these things for you because every use case is different.

**Comment by stephankn** [comment]
This is not about tuning the database server for operation. My work_mem setting is fine for this, as my tests proved.
It is about speeding up the import process run of osm2pgsql.

Probably I could do this manually: Increasing the setting before the import and reducing it later. But couldn't osm2pgsql do this for me as well? If not going for a fixed parameter, maybe offering a configurable cmdline, like the -C option?

**Comment by lonvia** [comment]
You can use `PGOPTIONS` to use a custom setting for osm2pgsql only. This should be sufficient for specialised needs. Tuning Postgresql is really tricky and unfortunately not something that osm2pgsql can easily do automatically.
