### ISSUE TITLE
Error when --drop specified without --slim being specified

### ISSUE THREAD

**Issue by mzeedijk** [openstreetmap/osm2pgsql#1421]
When --drop is specified and --slim is not specified the following error appears:

ERROR: --drop only makes sense with --slim.

This not true according to the manual:
"Drop the slim mode tables from the database and the flat node file once the import is complete."

In the past this makes sense, but now also the flat-nodes file will be deleted when --drop is specified.
It would be nice if the error only occurred when neither of the 2 options (--slim and --flat-nodes) are specified.
When any of the 2 options are specified the delete actions should be done for any of the specified options.

**Comment by pnorman** [comment]
``--flat-nodes`` requires ``--slim``

**Comment by mzeedijk** [comment]
I am able to run `osm2pgsql` with `--flat-nodes`, but without `--slim`. It doesn't give a warning. But now that you mention it, I noticed that it doesn't create the file specified with --flat-nodes when not using --slim. A warning about this file not being created, either in non-verbose or verbose mode, might be useful.
