### ISSUE TITLE
No module named 'osmium' for osm2pgsql-replication script

### ISSUE THREAD

**Issue by di-rect** [openstreetmap/osm2pgsql#1424]
I run into the following problem with the (new) osm2pgsql-replication script

`./osm2pgsql-replication 
Traceback (most recent call last):
  File "./osm2pgsql-replication", line 36, in <module>
    from osmium.replication.server import ReplicationServer
ModuleNotFoundError: No module named 'osmium'`

I have compiled osmium-tool and installed it and the command osmium is there. 

To be honest, I have no clue why the module would not be there as other "modules" were no issue anymore after installing them.

**Comment by joto** [comment]
You need [PyOsmium](https://github.com/osmcode/pyosmium) installed.

**Comment by di-rect** [comment]
> You need [PyOsmium](https://github.com/osmcode/pyosmium) installed.

Aha, ofcourse! 

Only PyOsmium ?

**Comment by lonvia** [comment]
Also psycopg2 (and python3).

On a Debian-base distribution: `apt install python3-pyosmium python3-psycopg2`

Otherwise get the dependencies with pip: `pip3 install osmium psycopg2`

**Comment by di-rect** [comment]
> Also psycopg2 (and python3).
> 
> On a Debian-base distribution: `apt install python3-pyosmium python3-psycopg2`
> 
> Otherwise get the dependencies with pip: `pip3 install osmium psycopg2`

Yes those two are needed as well but you say osium(-tool) as well ?

**Comment by joto** [comment]
No, you don't need osmium-tool.
