### ISSUE TITLE
osm2pgsql generate nodes table without tags column

### ISSUE THREAD

**Issue by gmuc** [openstreetmap/osm2pgsql#1435]
I have generate my OSM database with the 1.4.1. 

I miss now in the planet_nodes table the "tags" column.

My osm2pgsql call was:

osm2pgsql --password --host localhost --database mygis --username gerd --prefix planet --slim --cache 2048 -m --style /usr/share/osm2pgsql/default.style --hstore-all /BACKUP/allmap.osm

I got so a planet_nodes table:

CREATE TABLE public.planet_nodes
(
    id bigint NOT NULL,
    lat integer NOT NULL,
    lon integer NOT NULL,
    CONSTRAINT planet_nodes_pkey PRIMARY KEY (id)
        USING INDEX TABLESPACE tbl_space1
)

If I use the call on osm2pgsql with same arguments in a earlier version I got an other tablestructure:

CREATE TABLE "public"."planet_nodes" (
	"id" int8 NOT NULL,
	"lat" int4 NOT NULL,
	"lon" int4 NOT NULL,
	"tags" text[] COLLATE "default",
	CONSTRAINT "planet_nodes_pkey" PRIMARY KEY ("id") NOT DEFERRABLE INITIALLY IMMEDIATE
)
WITH (OIDS=FALSE);
ALTER TABLE "public"."planet_nodes" OWNER TO "verkehr";
CREATE INDEX  "planet_nodes_pkey" ON "public"."planet_nodes" USING btree("id" "pg_catalog"."int8_ops" ASC NULLS LAST);

In my application is SQL code that access at the "tags" column, i.e.

select pn.id, pn.tags, pn.lat, pn.lon from planet_nodes pn 
where pn.tags is not null and array_to_string(pn.tags,',') like '%LocationCode%';

This don't work now and my application is broken :(

How can I generate with the current version of osm2pgsql the planet_nodes table with the "tags" column?

**Comment by lonvia** [comment]
The planet_nodes table is the internal backing table, whose format is subject to change. The tags column has been removed [4 years ago](https://github.com/openstreetmap/osm2pgsql/commit/7a081d44237a94a06691714a3a42e9460ef2db23) because it is not needed internally. You should read tags from the output tables in your application, `planet_osm_point` for nodes.

**Comment by gmuc** [comment]
Thank's! 
Can I join plant_nodes.id and planet_osm_point.osm_id? There is no lat + lon in planet_osm_point? Where is documented witch table internal and witch output table?
