### ISSUE TITLE
Compiling from source not working ... ?

### ISSUE THREAD

**Issue by kinkersnick** [openstreetmap/osm2pgsql#144]
I'm trying to build from source on OSX 10.9.2 (Mavericks).

I've used the following commands:

```
git clone https://github.com/openstreetmap/osm2pgsql.git
./autogen.sh
./configure
make

No executable has been created, however.

Here is the end of the output from the make command, which seems to list some errors, though I don't know what they mean:

clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
ld: warning: directory not found for option '-L/usr/lib/x86_64-linux-gnu'
Undefined symbols for architecture x86_64:
  "geos::io::WKTReader::read(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      _parse_wkt in build_geometry.o
  "geos::geom::GeometryFactory::createPolygon(geos::geom::LinearRing*, std::__1::vector<geos::geom::Geometry*, std::__1::allocator<geos::geom::Geometry*> >*) const", referenced from:
      _get_wkt_simple in build_geometry.o
      _get_wkt_split in build_geometry.o
      _build_geometry in build_geometry.o
  "geos::geom::GeometryFactory::createMultiPolygon(std::__1::vector<geos::geom::Geometry*, std::__1::allocator<geos::geom::Geometry*> >*) const", referenced from:
      _build_geometry in build_geometry.o
  "geos::geom::GeometryFactory::createMultiLineString(std::__1::vector<geos::geom::Geometry*, std::__1::allocator<geos::geom::Geometry*> >*) const", referenced from:
      _build_geometry in build_geometry.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [osm2pgsql] Error 1
make: *** [all] Error 2
```

Any thoughts?

**Comment by pnorman** [comment]
The issue seems abandoned, and the issues reported are probably with the reporters environment.

**Comment by systemed** [comment]
This is the same issue for me and prevents osm2pgsql from compiling. (OS X Yosemite, 10.10.3.)

I use Postgres.app, which includes PostGIS and therefore geos. Their geos is linked against libstdc++.

In theory I could compile osm2pgsql like this:

`./configure --with-zlib=/usr/local/opt/zlib --with-bzip2=/usr/local/opt/bzip2 --with-geos=/usr/local/Cellar/geos/3.4.2/bin/geos-config --with-postgresql=/Applications/Postgres.app/Contents/MacOS/bin/pg_config`

However, this results in a GCC command line like this:

`-I/Applications/Postgres.app/Contents/MacOS/include [...] -I/usr/local/Cellar/geos/3.4.2/include`

so it still finds the Postgres.app geos before the Homebrew one.

I have a "last good" version of osm2pgsql (0.83.0) which works fine for me, but I've pretty much given up on getting newer versions to work, I'm afraid.

**Comment by pnorman** [comment]
Not sure what to suggest, or if this is resolvable on the osm2pgsql end.

@springmeyer any thoughts?

**Comment by springmeyer** [comment]
reading this again: I'm still thinking it is mixed up c++ libraries. It sounds like it may be geos using libc++ (and c++11) and osm2pgsql using libstdc++ (and not being built in c++11) mode. If that is the case then solution is do `export CXXFLAGS="-std=c++11 -stdlib=libc++" && export LDFLAGS="-std=c++11 -stdlib=libc++` before building.

However, overall in my experience this issue is best solved on OS X by providing binaries and removing the need for 99% of the developers from needing to do a source compile.

**Comment by pnorman** [comment]
> However, overall in my experience this issue is best solved on OS X by providing binaries and removing the need for 99% of the developers from needing to do a source compile.

Who would be the equivalent of a distro package maintainer who would do this? Would it be done from within homebrew, or something else?

**Comment by dionysiusmarquis** [comment]
I was able to compile under osx 10.10.4 by installing dependencies over MacPorts and:

``./configure  --includedir=/opt/local/include/ --bindir=/opt/local/bin/ --libdir=/opt/local/lib --with-proj=/opt/local/lib/proj47/ CC="clang" CXX="clang++" CXXFLAGS="-std=c++11 -stdlib=libc++" --disable-shared``

I had to use port ``proj47`` and be sure to force recompile with ``make -B``

**Comment by pnorman** [comment]
The solution is to install **both** Postgres.app and PostgreSQL/PostGIS/GEOS from brew. You don't need to run the postgres from brew, just have it installed to link against.

After homebrew/homebrew#42663, the easiest option for most users will be to install osm2pgsql with homebrew.

**Comment by pnorman** [comment]
> PostgreSQL/PostGIS/GEOS

More specifically, you need geos and libpq from the same source.
