### ISSUE TITLE
Would like to have some kind of lock during update

### ISSUE THREAD

**Issue by andreynovikov** [openstreetmap/osm2pgsql#1446]
I have a background process that is permanently generating custom maps from osm database. As I understand update process is not safe in terms of data consistency (I didn't find the use of transactions in source code). So when database is updated I will get incomplete data. I'm using daily change sets and it may cause significant issues. That's why it would be nice to have some means of checking if update is in place. I could search through process list but a file lock or a special flag in database would be better.

**Comment by stephankn** [comment]
Depends on your rendering process.
In case of tirex, just alter your update cron-job to start with `tirex-rendering-control --stop ALL` and after the update resume with `tirex-rendering-control --continue ALL`. This will retain your rendering queue but stop all rendering activities in between.

**Comment by andreynovikov** [comment]
No, it's custom. But you propose to add locking to cron job. It's a nice clue, thank you.

**Comment by joto** [comment]
I have just added a chapter to the manual: https://osm2pgsql.org/doc/manual.html#using-database-while-updating
