### ISSUE TITLE
Stuck on PREPARE get_wkb(int8) AS SELECT way FROM "planet_osm_roads" WHERE osm_id = $1

### ISSUE THREAD

**Issue by oscar-corredor** [openstreetmap/osm2pgsql#1515]
Hi, I'm trying to process a country file downloaded from geofabrik, however the process gets stuck in the _Setting up table 'planet_osm_roads'_ step. More specifically, the SQL log shows that it's on the following query: 

`SQL: PREPARE get_wkb(int8) AS SELECT way FROM "planet_osm_roads" WHERE osm_id = $1
`
My versions are the following:
osm2pgsql - 1.4.2
postgres: 12.7
Postgis: 3.0

The command I am using to execute osm2pgsql is the following
`osm2pgsql -r pbf -s -d osm -l -v -C 15000 --slim --drop --number-processes=8 -U odco -W - localhost -P 5432 --log-level='debug' --log-sql --log-sql-data colombia-latest.osm.pbf`

How can I fix this issue? Any help will be appreciated, thanks in advance.

**Comment by pnorman** [comment]
What does `select now()-query_start, state, query from pg_stat_activity;` report?

**Comment by lonvia** [comment]
There is a typo in your command-line here:
```
osm2pgsql -r pbf -s -d osm -l -v -C 15000 --slim --drop --number-processes=8 -U odco -W - localhost -P 5432 --log-level='debug' --log-sql --log-sql-data colombia-latest.osm.pbf
                                                                                       ^^^ 
```

You probably meant to write `-H localhost`. Because of the typo osm2pgsql interprets `-` as an input file. `-` means to read data from stdin. So after initialisation osm2pgsql just sits there and waits for data.

**Comment by oscar-corredor** [comment]
> There is a typo in your command-line here:
> 
> ```
> osm2pgsql -r pbf -s -d osm -l -v -C 15000 --slim --drop --number-processes=8 -U odco -W - localhost -P 5432 --log-level='debug' --log-sql --log-sql-data colombia-latest.osm.pbf
>                                                                                        ^^^ 
> ```
> 
> You probably meant to write `-H localhost`. Because of the typo osm2pgsql interprets `-` as an input file. `-` means to read data from stdin. So after initialisation osm2pgsql just sits there and waits for data.

Thanks! this has done it!
