### ISSUE TITLE
Changing a style file after import and then applying diffs

### ISSUE THREAD

**Issue by MarkCupitt** [openstreetmap/osm2pgsql#152]
If I add elements to a style file after the initial planet import, will osm2pgsql add the extra columns in postgres or will they be ignored, or even worse, cause a failure.

I want to know how to approach updating the database after the initial import and new tags not previously used have been added to osm

Thanks

**Comment by pnorman** [comment]
With lua tag transforms, the flex backend and other more advanced transforms that we didn't have in 2014, I don't think this is something we should document and support.
