### ISSUE TITLE
Duplicated serial values when appending data to flex backend

### ISSUE THREAD

**Issue by nextstopsun** [openstreetmap/osm2pgsql#1522]
Defining a column as `sql_type=serial primary key` in flex works fine during initial import, but breaks when running osm2pgsql in append mode.
Postgres throws `Duplicate key violates unique constraint`.
If `primary key` is removed and only `sql_type=serial` is left in a column definition, then append completes successfully, but column receives duplicate values.

Seems like newly created sequence is used only for a temporary table and then is somehow reset when attached to a resulting table.

Here's code to reproduce:
```lua
local tables = {}

tables.test =
    osm2pgsql.define_table(
    {
        schema = "osm",
        name = "test",
        ids = { type = "node", id_column = "node_id" },
        columns = {
            { column = "gid", sql_type = "serial primary key", create_only = true },
            { column = "tags", type = "jsonb" },
            { column = "geom", type = "point" }
        }
    }
)


function osm2pgsql.process_node(object)
    tables.test:add_row({
        tags = object.tags,
        geom = { create = "point" }
    })
end
```

**Comment by lonvia** [comment]
To quote the [manual](https://osm2pgsql.org/doc/manual.html#defining-columns):

> The content of the sql_type field is not checked by osm2pgsql, it is passed on to PostgreSQL as is. Do not set this to anything else but a valid PostgreSQL type.

Adding constraints to `sql_type` is not supported.

**Comment by nextstopsun** [comment]
Constraint is used just to demonstrate an issue.
[Manual](https://osm2pgsql.org/doc/manual.html#using-an-additional-id-column) does allow to use `serial` type.
You can add a constraint after initial import as manual suggests.

The problem rises when you run `append` to this data. Sequence does not continue to increment for newly added rows, but instead runs from start. This leads to duplicating values for this serial column.
