### ISSUE TITLE
Improve performance of processing diff files

### ISSUE THREAD

**Issue by doskabouter** [openstreetmap/osm2pgsql#1528]
When processing diff files, the performance of processing nodes is dramatically (0.2k/s for append vs 800k/s for create) slow.

Based on my investigations the bottleneck is the 
`PREPARE mark_rels_by_node(int8) AS  SELECT id FROM "southamerica"."planet_osm_rels"    WHERE parts && ARRAY[$1]      AND parts[1:way_off] && ARRAY[$1];
PREPARE mark_rels_by_way(int8) AS  SELECT id FROM "southamerica"."planet_osm_rels"    WHERE parts && ARRAY[$1]      AND parts[way_off+1:rel_off] && ARRAY[$1];
`
query. because it maxes out 1 core of my databaseserver. 
Adding --number-processes 5 didn't help here, is this part easily rewritten as multithreaded so at least this part of the process uses multiple threads for getting relation ids for the changed nodes/ways?

Also checked the query plan and it's correctly using the index for that

**Comment by joto** [comment]
The `PREPARE` SQL statements are definitely not the bottle neck, they basically don't take any time at all. When checking active queries in PostgreSQL the last queries are reported even if the connection is now idle. That's probably what you are seeing. There is some flag that shows whether the question is actually running, don't know off the top of my hat what that was called.

Anyway: We are fully aware that the processing in osm2pgsql is not always using as many threads as it theoretically could and there are ways to make things faster, but it is not so easy to do that and changes in that area will need quite a lot of effort.

**Comment by doskabouter** [comment]
That is what postgres gave me when querying running queries. and the pid of that query had one core fully in use, so it's probably a reporting thing from postgres.
That being said, too bad that this one isn't simple to do multithreaded...
