### ISSUE TITLE
Add style flag to add column, but not add objects based on that flag

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#153]
For analysis of some subset of objects I often use a .style file like

```
node,way    name                    text    linear
node,way    amenity                 text    area
node,way    office                  text    area
node,way    shop                    text    area
```

I want the name tags, but I don't want having a name tag alone to cause an object to be added to the database.

The closest I can get to this is having name in a hstore, either with `--hstore-match-only` or `--hstore-column`

**Comment by lonvia** [comment]
This can be achieved with a lua-based style.
