### ISSUE TITLE
Possible performance improvement

### ISSUE THREAD

**Issue by doskabouter** [openstreetmap/osm2pgsql#1532]
While importing a full planet into postgres I noticed that at the stage where it's creating the indices (after "Reading input files done") osm2pgsql is still using almost 64GB of memory (with a large part of it still in memory i.e. not in swap) presumably it's the nodes and probably other caches.
As these are not needed anymore after processing input files, perhaps that memory could be free'd so postgres itself has more memory to use as a file-cache

**Comment by joto** [comment]
How did you determine that osm2pgsql is not freeing the memory?

**Comment by doskabouter** [comment]
Well that's what windows's taskmanage said...

**Comment by joto** [comment]
Memory that the application has freed is not automatically returned to the operating system, that's totally normal. It depends on the program, the kernel and the C++ runtime how this is handled in detail. So just looking from the outside of the process doesn't tell you how much memory the application has actually still allocated. It might well be that osm2pgsql is not perfect in that regard, but you just can't tell this way.

On the other hand, it doesn't mean that other programs can't use this memory. I don't know enough about Windows, but on Linux the kernel is able to tell that this memory isn't actually in use and it can let other processes use it.

**Comment by stephankn** [comment]
Windows taskmanager is much improved in Windows 10, but certainly not perfect. Process Explorer from Sysinternals gives some additional hints.

In which "column" of Task manager did you see the memory still allocated? What was it named? Is it called private active working set?
In this case I would also suspect that osm2pgsql still has it's fingers on it.

As Jochen mentioned osm2pgsql is supposed to return the memory. I have not checked the code, but assuming it is doing new/delete on the heap. So it would be the task of the heap memory management of the runtime to return this to the operating system.

read here on how Windows handles this: https://docs.microsoft.com/en-us/windows/win32/memory/working-set

So if you really see a persistent high working set, even in a situation where osm2pgsql already deleted the memory, then it would be worth investigating further. I would then suppose this being an issue with the specific runtime used here in the windows version.

**Comment by doskabouter** [comment]
It was something like 64GB Commit size, Working set around 45GB and some 20GB Shareable
On windows server 2008.
Unfortunately the process has finished now so not able to check with procexp to see what's going on exactly.

Only thing that I was thinking about is a possible late free/delete after all the work is done instead of after the cache isn't needed anymore.
But if you think it's already freed in the code at the correct moment, then it's probably the runtime/memory manager holding on to it because it might be needed again. If that is true then I'd suspect it's too much effort forcing the memory back to the os

**Comment by stephankn** [comment]
"Working set" indicates that these are actually pages mapped to physical. So this is RAM in use by the process and not available to others unless paged out to disk (or compressed, Windows does similar to ZRAM).
As Jochen pointed out, this does not necessarily mean that the application code is not releasing the memory, it could also be the behavior of the allocator in use.

See this for a nice explanation on how for example the glibc allocator works and where I had analyzed such issues before: https://sourceware.org/glibc/wiki/MallocInternals

Potentially you are facing such an issue. Further investigation here would certainly require some additional time and effort. It would specifically get more complicated in case the effect is limited to Windows, as to my knowledge the main contributors work with Linux.

To move here forward I recommend that you create a reproduction case. Potentially pausing osm2pgsql execution at the right point  (after "Reading input files done"). If this again confirms that the allocator does not return memory to the OS, despite huge amounts of memory are released by application code then further steps can be considered. Allocators can be tuned or replaced by other allocators like for example tcmalloc. Would also require some investigation what allocator implementation is actually used in your windows build.
