### ISSUE TITLE
'pgsql output' ignoring '--tablespace-index=TABLESPC' option

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1543]
According to the osm2pgsql manual pages here:

https://osm2pgsql.org/doc/manual.html#schemas-and-tablespaces

it should be possible to set the tablespace for the pgsql output as well as for the middle using the pgsql "--tablespace-index=TABLESPC" command line option. However, when I use this option, the 'planet_osm_point/line/polygon/roads' tables created after invoking the command, show 'pg_default' as the tablespace.

If I use the other mentioned options of "--tablespace-main-data=TABLESPC" and "--tablespace-main-index=TABLESPC", the tables do use the proper tablespace as set on the command line.

**Comment by joto** [comment]
As always: Please tell us *exactly* what you did, what you expected to happen and what happened instead. That makes it easier to understand the issue.

In this case: `--tablespace-index=TABLESPC` sets the tablespace for the indexes not for the tables. Your wording

> However, when I use this option, the 'planet_osm_point/line/polygon/roads' tables created after invoking the command, show 'pg_default' as the tablespace.

suggests you checked the tables, not the indexes.

**Comment by mboeringa** [comment]
@joto:
See: https://github.com/openstreetmap/osm2pgsql-website/issues/13
