### ISSUE TITLE
osm2pgsql failed due to ERROR :PBF error :invalid Blobheader size (> max_blob_header_size)

### ISSUE THREAD

**Issue by ICE-FA** [openstreetmap/osm2pgsql#1551]
Hello,
Can you please help me understand this issue?
I can't find any result in Google with this error message.

I have downloaded geofabrik.osm.pbf fole, and want to import it to the database according dovumentation, in screenshot you can see the command i have executed.

My machine parameters is 6 core, 4GB of ram, 1TB of disc.
Postgis version is 3
Postgresql version is 12
![16282373422965681033469763717898](https://user-images.githubusercontent.com/88532371/128478571-a7f0c1f1-0eca-4440-95fb-3a29f23ae34b.jpg)

**Comment by joto** [comment]
This error comes from libosmium. It means your input file is invalid. Maybe it was corrupted during download. Please check the md5sum of your file against the md5sum you can see on https://download.geofabrik.de/ . If you downloaded this file today, it should have md5sum `1f9dd3f810ef28bfcd18c377665a58a5`. I just checked that file on my machine and it is valid here.

**Comment by ICE-FA** [comment]
how do i clear all the data in the server terminal .. I feel like i made a
lot of errors and i would like to start the process afresh. how do i do
that?

HELP

Regards
ICE-FA

**Comment by ICE-FA** [comment]
![16282802752056881204962690525042](https://user-images.githubusercontent.com/88532371/128565580-da970890-1c53-4bc4-bb91-d7cd8bb38a45.jpg)

**Comment by ICE-FA** [comment]
i started a fresh and now its showing  error... no such file or directory

**Comment by mmd-osm** [comment]
https://help.openstreetmap.org/ would probably be a better place to discuss your questions.

This Github repository is mainly used to report software issues, bugs or enhancement requests.

**Comment by joto** [comment]
Then you don't have that file. Sorry, but this is a bug tracker for osm2pgsql, not a help line for introductory computer issues.
