### ISSUE TITLE
not using quoted table name in DROP TABLE

### ISSUE THREAD

**Issue by pesekon2** [openstreetmap/osm2pgsql#1552]
## What version of osm2pgsql are you using?

master

## What operating system and PostgreSQL/PostGIS version are you using?

Debian 10

## What is the problem?

Throughout the code (see below), the command `DROP TABLE` is used with the table name unquoted (`DROP TABLE {}` instead of `DROP TABLE \"{}\"`). This could cause a problem when a function is called from within a code and the table name contains a character that should be "escaped" (such as `-`).

```
src/table.cpp
95:            "DROP TABLE IF EXISTS {} CASCADE"_format(qual_name));
99:    m_sql_conn->exec("DROP TABLE IF EXISTS {}"_format(qual_tmp_name));
227:        m_sql_conn->exec("DROP TABLE {}"_format(qual_name));

src/middle-pgsql.cpp
89:    db_connection.exec("DROP TABLE IF EXISTS {}"_format(qual_name));
620:                "DROP TABLE IF EXISTS {} CASCADE"_format(qual_name));

src/flex-table.cpp
170:            "DROP TABLE IF EXISTS {} CASCADE"_format(table().full_name()));
175:        "DROP TABLE IF EXISTS {}"_format(table().full_tmp_name()));
249:        m_db_connection->exec("DROP TABLE {}"_format(table().full_name()));
```

## How to fix it?

An obvious fix is to put `\"{}\"` instead of `{}`. I can prepare such PR, it's easy. But I am not sure it's so easy - couldn't it cause some troubles when the function is called from another place with the table name already in double quotes? Because then the command would be for example `DROP TABLE \"\"my-table\"\"`, right?

**Comment by joto** [comment]
The table names put into those formats (like `qual_tmp_name`, `qual_name`, etc.) should all already contain the quotes. The reason this is done this way are the (optional) schemas. A schema-qualified table name must be quoted as `"schema"."table"`, not `"schema.table"` but we want to use `"table"` if the default schema is used, so the quoting is done in special functions before they are put into the format.

**Comment by pesekon2** [comment]
Okay, I have missed that. Can see it now. Thanks!
