### ISSUE TITLE
Not all field references double quoted in SQL generated by osm2pgsql

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1564]
## What version of osm2pgsql are you using?

osm2pgsql v1.5.1

## What operating system and PostgreSQL/PostGIS version are you using?

Ubuntu 20.04.1 LTS, PostgreSQL 13.4 / PostGIS 3.1.3

## What did you do exactly?

Import Planet using osm2pgsql and monitor the actual processing in pgAdmin

## What did you expect to happen?

As a quite recent change, osm2pgsql started quoting all schema, table and field name references in SQL. I'd expect this to extend to all field references.

## What did happen instead?

Minor issue, but the "way" field reference in the **ORDER BY** clause is not quoted, see attached screenshot from pgAdmin:

![afbeelding](https://user-images.githubusercontent.com/7635726/131688130-7246fffd-da3e-470a-883b-7c35aea9a4c5.png)

**Comment by joto** [comment]
This isn't really a problem, because the name `way` is valid in any context in the database (not a reserved word) and it is hardcoded in osm2pgsql, the user can't change it. So quoting this or not quoting this doesn't matter.
