### ISSUE TITLE
Postgres database update error by osm2pgsql

### ISSUE THREAD

**Issue by fpintoa** [openstreetmap/osm2pgsql#1571]
We have an error situation in the update process.
At certain times, the update process crashes and does not proceed. The error message in the file /var/log/tiles/osm2pgsql.log is shown below:

> Reading in file: /var/lib/mod_tile/changes.osc.gz
> Using XML parser.
> Processing: Node(10k 0.0k/s) Way(3k 3.66k/s) Relation(40 20.00/s)  parse time: 407s
> Node stats: total(10020), max(9090048720) in 404s
> Way stats: total(3661), max(983093395) in 1s
> Relation stats: total(81), max(13209476) in 2s
> DB writer thread failed due to ERROR: result COPY_END for planet_osm_polygon failed: ERROR:  invalid input > syntax for type integer: "2.75"
> CONTEXT:  COPY planet_osm_polygon, line 26, column layer: "2.75"

The message seems to indicate that a double value (2.75) is being written to the layer field of the planet_osm_polygon table, which is set to integer.

To work around this, we decreased the value of the maxInterval parameter in the configuration file /var/lib/mod_tile/.osmosis/configuration.txt
And we manually increment the sequenceNumber value of the /var/lib/mod_tile/.osmosis/state.txt file, so that it advances in the update. We believe there may be some information recorded wrong in the update files, which are available at https://planet.openstreetmap.org/replication/minute

However, this is impacting our environment as it requires a lot of technical intervention.

Our environment is Ubuntu 20.04 LTS. The osm2pgsql version is shown below:

osm2pgsql version 1.2.1 (64 bit id space)
Compiled using the following library versions:
Libosmium 2.15.4
Lua 5.2.4

We would appreciate if you can guide us on how to solve the problem.

Yours sincerely,

**Comment by fpintoa** [comment]
Attached is the graph with the occurrences of the problem in the last 7 days
![crash-osm2pgsql-2021-09](https://user-images.githubusercontent.com/57007191/133789109-79f86753-54fb-4ec9-bbda-5723379a722d.jpg)

**Comment by mmd-osm** [comment]
It seems that the style you’re using is not fault tolerant enough to correctly deal with a tag „layer=2.75“

You need to this fix bit first before continuing. By the way, that issue would probably be out of scope for this repository.

**Comment by fpintoa** [comment]
What do you mean by non-fault tolerant style? If the field in the planet_osm_polygon table is an integer type, I understand that someone is doing something wrong along the way. Can you point a way for me to solve the problem? Where do you think the problem might be?

Sorry, if the problem is outside the scope of the repository. Where do you suggest I can get help?

Yours sincerely,

**Comment by mmd-osm** [comment]
Please try help.openstreetmap.org instead.

**Comment by fpintoa** [comment]
Thank you.

**Comment by mmd-osm** [comment]
Follow up link: https://help.openstreetmap.org/questions/81796/tile-server-update-error
