### ISSUE TITLE
Polygons not properly created when a node is at 0.0,0.0

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#158]
This XML
```xml
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="hand">
<node id="1" version="1" timestamp="2010-01-01T00:00:00Z" uid="1" user="user1" changeset="1" lat="0.0" lon="0.0"/>
<node id="2" version="1" timestamp="2010-01-01T00:00:00Z" uid="1" user="user1" changeset="1" lat="0.01" lon="0.0"/>
<node id="3" version="1" timestamp="2010-01-01T00:00:00Z" uid="1" user="user1" changeset="1" lat="0.01" lon="0.01"/>
<way id="1" version="1" timestamp="2010-01-01T00:00:00Z" uid="1" user="user1" changeset="1">
<nd ref="1"/>
<nd ref="2"/>
<nd ref="3"/>
<nd ref="1"/>
<tag k="building" v="yes"/>
</way>
<relation id="1" version="1" timestamp="2010-01-01T00:00:00Z" uid="1" user="user1" changeset="1">
<member type="way" ref="1" role="outer"/>
<tag k="type" v="multipolygon"/>
</relation>
</osm>
```
with the stylesheet ``node,way building text polygon`` does not result in any rows in planet_osm_polygon when imported with ``./osm2pgsql  -S buildings.style test.osm``

If node 1 is changed to ``<node id="1" version="1" timestamp="2010-01-01T00:00:00Z" uid="1" user="user1" changeset="1" lat="0.001" lon="0.001"/>`` (note lat/lon) it then creates a polygon.

The polygon in the former case is ``LINESTRING(0 1113.19,1113.19 1113.19)`` and in the latter case is ``POLYGON((0 1113.19,1113.19 1113.19,111.32 111.32,0 1113.19))``

**Comment by lonvia** [comment]
Fixed in 27a75c7. Ram cache no longer uses 0,0 as invalid marker.
