### ISSUE TITLE
Feature request: Opposite lua helper function of make_clean_tags_func

### ISSUE THREAD

**Issue by Franky1** [openstreetmap/osm2pgsql#1586]
There is a Lua helper function `make_clean_tags_func`.
Unfortunately, the osm data are quite unclean, so you have to filter out a lot of useless tags.
Therefore, a function `make_filter_tags_func` to filter only the desired tags would be useful?

**Comment by joto** [comment]
Do you have a concrete use case for such a function? Usually you either have a hstore/jsonb column with all data minus stuff you really don't need or you have columns for all the stuff that you do need, if you have a limited list.

**Comment by mboeringa** [comment]
> Therefore, a function `make_filter_tags_func` to filter only the desired tags would be useful?

While I understand the basic desire, I agree with Jochen that this may be less useful than you think. Unless you are developing a really basic style and are **_absolutely_** sure you will never need new keys, there is high chance you will be forced to re-import your entire database to add new keys with a "make_filter_tags_func" that excludes any key from hstore/jsonb not on your "whitelist" of desired keys.

This may disrupt a potential continuous update process you have running, and may require to take your service offline if you haven't got spare hardware.

In practice, with any kind of "complicated", quasi "Topographic", type of style, you will quickly discover during style development that you in fact need quite a bit more keys than initially anticipated, and that you may be adding new keys for years with the ever changing landscape of tagging and enrichment of the OSM database.

With all remaining keys in hstore/jsonb however, you can quickly and dynamically adapt your style by pulling the new required OSM keys from the tag storage using SQL ("tags -> <YOUR_KEY>" for hstore, "tags ->> <YOUR_KEY>" for json).
