### ISSUE TITLE
Bind placeholders [...] in the global namespace is deprecated

### ISSUE THREAD

**Issue by boldt** [openstreetmap/osm2pgsql#1602]
## What version of osm2pgsql are you using?

Github sources, tag 1.5.1: https://github.com/openstreetmap/osm2pgsql/tree/1.5.1

## What operating system and PostgreSQL/PostGIS version are you using?

* Ubuntu 20.04
* No postgis/postgres

## What did you do exactly?

Build osm2pgsql from sources.

## What did happen instead?

In the `make` step, I see the following note:

```
[ 11%] Building CXX object src/CMakeFiles/osm2pgsql_lib.dir/gazetteer-style.cpp.o
In file included from /usr/include/boost/bind.hpp:30,
                 from /usr/include/boost/property_tree/json_parser/detail/parser.hpp:7,
                 from /usr/include/boost/property_tree/json_parser/detail/read.hpp:13,
                 from /usr/include/boost/property_tree/json_parser.hpp:16,
                 from /osm2pgsql/src/gazetteer-style.cpp:14:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
```

**Comment by joto** [comment]
That's not something we can do anything about, because it is triggered deep inside the boost library. Lets hope they fix this at some point. Feel free to open an issue with boost on this.

**Comment by mmd-osm** [comment]
Probably there's no need to open a new upstream issue: https://github.com/boostorg/property_tree/issues/51

**Comment by boldt** [comment]
The upstream issue is closed, I hope they still see the comments.

**Comment by mmd-osm** [comment]
Boost 1.76 in the first version with the fix: https://www.boost.org/doc/libs/1_76_0/boost/property_tree/json_parser/detail/parser.hpp

`#include <boost/bind/bind.hpp>`

If you can't upgrade, you probably need to follow the description in https://github.com/boostorg/property_tree/pull/50#issuecomment-767317099 and apply same logic that to https://github.com/openstreetmap/osm2pgsql/blob/master/src/gazetteer-style.cpp#L14

**Comment by joto** [comment]
There is really no need to "fix" anything here. This is a warning only and, as far as I can tell, it doesn't break anything in osm2pgsql. Apparently this is already fixed upstream, so nothing to do for us here. Please open a new issue if you see any actual brakage.
