### ISSUE TITLE
osm2pgsql fails with large relations

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#1607]
Someone has recently created a relation with more than 200k members: https://www.openstreetmap.org/relation/13671879 (now deleted) This causes osm2pgsql to fail with the following message:

```
ERROR: DB copy thread failed: Ending COPY mode for 'planet_osm_rels' failed: ERROR:  value "218678" is out of range for type smallint
CONTEXT:  COPY planet_osm_rels, line 121, column way_off: "218678"
```

osm2pgsql should reject all relations that have more than 10k (50k? 100k?) members and not try to process them.

If you run into this bug: make sure to download a diff range large enough that it includes the deletion of the relation that followed about 40min later.

**Comment by joto** [comment]
This is a regression, see #713 and the fix in 8763ce951bddee2af553fab6ce4e1f4e79eeaaa0. During refactoring the check was moved to the wrong place and only protected the output, not the middle tables. Fix coming up...
