### ISSUE TITLE
install on REDHAT 8.4 

### ISSUE THREAD

**Issue by A0x01** [openstreetmap/osm2pgsql#1646]
Hi osm2pgsql team , 
 thank you for the great you have done on this tool 
but  i hope you can provide some support for redhat /centos system  
and add osm2pgsql to the yum or dnf package managers 
because the install from source is difficult 
thank you

**Comment by joto** [comment]
Fedora has packages available, I would expect them to be usable on other Redhat-based distributions. We can not provide support for every system out there, that's a lot of work. If you are willing to pay for the support, contact the developers directly.
