### ISSUE TITLE
ERROR: planet_osm_nodes - error on COPY: SSL SYSCALL error: EOF detected

### ISSUE THREAD

**Issue by ihar-kouhanau-epam** [openstreetmap/osm2pgsql#1688]
## What version of osm2pgsql are you using?
osm2pgsql version 1.6.0

## What operating system and PostgreSQL/PostGIS version are you using?
Database version: 12.10
PostGIS version: 3.1

## Tell us something about your system
Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1022-aws x86_64)

RAM 32 GB
CPU 8

## What did you do exactly?

I run command in docker container (remote database)
sudo -u renderer osm2pgsql -r pbf -d 'dbname=gis host=host port=5432 user=postgres password=password' --create --slim -G --hstore --tag-transform-script /home/renderer/src/openstreetmap-carto/openstreetmap-carto.lua --number-processes 4 -S /home/renderer/src/openstreetmap-carto/openstreetmap-carto.style /home/renderer/data/regions.pbf -C 16000

## What did you expect to happen?
Importing data

## What did happen instead?
It works some period of time but eventually I get error: planet_osm_nodes - error on COPY: SSL SYSCALL error: EOF detected
![osm2](https://user-images.githubusercontent.com/23447665/176182625-8d07630c-9cae-4261-9df8-1560e1cab2a2.png)
It works good for small files but when I import a big file to remote database it fails

**Comment by joto** [comment]
That sounds like a problem with the connection between osm2pgsql and the database. Somehow the connection gets closed and then SSL errors out, or something like that. Look in your database log whether you can find something there. Maybe your system is too slow and something times out. Or docker does something wierd with that connection. Anyway, this doesn't look like something we have any influence over in osm2pgsql but a more general sysadmin-type problem.

**Comment by Garett-MacGowan** [comment]
@ihar-kouhanau-epam did you manage to fix your issue? Running into the same problem with osm2pgsql and postures logs being unhelpful.
