### ISSUE TITLE
Osm2pgsql failed due to ERROR: get_node_list failed: ERROR:  relation "planet_osm_nodes" does not exist at character 59

### ISSUE THREAD

**Issue by raphael10-collab** [openstreetmap/osm2pgsql#1690]
## What version of osm2pgsql are you using?

    raphy@pc:~$ osm2pgsql --version
    osm2pgsql version 1.2.1 (64 bit id space)
    
    Compiled using the following library versions:
    Libosmium 2.15.4
    Lua 5.2.4

## What operating system and PostgreSQL/PostGIS version are you using?

Ubuntu 20.04 Desktop

## Tell us something about your system

    32 Gb RAM
    8 CPUs

## What did you do exactly?

    raphy@pc:~$ osm2pgsql -d gis --create --slim  -G --hstore --tag-transform-script ./OSM/openstreetmap-carto/openstreetmap-carto.lua \
    > -C 5000 --number-processes 6 \
    > -S ./OSM/openstreetmap-carto/openstreetmap-carto.style ./OSM/data/europe-latest.osm.pbf 
    > -S ./OSM/openstreetmap-carto/openstreetmap-carto.style ./OSM/data/europe-latest.osm.pbf 
    osm2pgsql version 1.2.1 (64 bit id space)
    
    Allocating memory for dense node cache
    Allocating dense node cache in one big chunk
    Allocating memory for sparse node cache
    Sharing dense sparse
    Node-cache: cache=5000MB, maxblocks=80000*65536, allocation method=11
    Mid: pgsql, cache=5000
    Setting up table: planet_osm_nodes
    Setting up table: planet_osm_ways
    Setting up table: planet_osm_rels
    Using lua based tag processing pipeline with script ./OSM/openstreetmap-carto/openstreetmap-carto.lua
    Using projection SRS 3857 (Spherical Mercator)
    Setting up table: planet_osm_point
    Setting up table: planet_osm_line
    Setting up table: planet_osm_polygon
    Setting up table: planet_osm_roads
    
    Reading in file: ./OSM/data/europe-latest.osm.pbf
    Using PBF parser.
    Processing: Node(2990243k 364.2k/s) Way(3702k 1.79k/s) Relation(0 0.00/s)node cache: stored: 462265405(15.46%), storage efficiency: 70.54% (dense blocks: 41824, sparse nodes: 156372353), hit rate: 36.70%
    Osm2pgsql failed due to ERROR: get_node_list failed: ERROR:  relation "planet_osm_nodes" does not exist at character 59
    (7)
    Arguments were: {1734096827,1734096831}, 

## What did you do to try analyzing the problem?

    raphy@pc:/var/log/postgresql$ tail postgresql-12-main.log 
    2022-07-07 17:20:26.725 CEST [970] HINT:  Consider increasing the configuration parameter "max_wal_size".
    2022-07-07 17:20:55.580 CEST [970] LOG:  checkpoints are occurring too frequently (29 seconds apart)
    2022-07-07 17:20:55.580 CEST [970] HINT:  Consider increasing the configuration parameter "max_wal_size".
    2022-07-07 17:21:22.338 CEST [970] LOG:  checkpoints are occurring too frequently (27 seconds apart)
    2022-07-07 17:21:22.338 CEST [970] HINT:  Consider increasing the configuration parameter "max_wal_size".
    2022-07-07 17:21:49.906 CEST [970] LOG:  checkpoints are occurring too frequently (27 seconds apart)
    2022-07-07 17:21:49.906 CEST [970] HINT:  Consider increasing the configuration parameter "max_wal_size".
    2022-07-07 17:56:37.165 CEST [76850] raphy@gis ERROR:  relation "planet_osm_nodes" does not exist at character 59
    2022-07-07 17:56:37.165 CEST [76850] raphy@gis STATEMENT:  PREPARE get_node_list(int8[]) AS SELECT id, lat, lon FROM planet_osm_nodes WHERE id = ANY($1::int8[]);

**Comment by joto** [comment]
Version 1.2.1 is more than two years old and many bugs have been fixed since. Please upgrade to a current version.

**Comment by raphael10-collab** [comment]
I installed it via `Ubuntu repository` : 
    
    raphy@pc:~$ sudo apt install osm2pgsql
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    osm2pgsql is already the newest version (1.2.1+ds-1build1).
    The following packages were automatically installed and are no longer required:
      python3-cliapp python3-markdown python3-packaging python3-pygments
      python3-pyparsing python3-ttystatus
    Use 'sudo apt autoremove' to remove them.
    0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.


I'm going to download and compile from `github`: https://github.com/openstreetmap/osm2pgsql
