### ISSUE TITLE
PREPARE SQL statements have inconsistent formatting for spaces

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1693]
## What version of osm2pgsql are you using?

1.6.0 (1.3.0-734-g1f045f9d)

## What operating system and PostgreSQL/PostGIS version are you using?

Ubuntu 20.04.4 LTS, PostgreSQL 14.4, PostGIS 3.2

## What did you expect to happen?

SQL statements generated by osm2pgsql use proper formatting with no excess spaces between keywords

## What did happen instead?

PREPARE SQL statement have inconsistent number of spaces, where only one space is needed in all of these cases, see output as seen in pgAdmin while import was running:

```
PREPARE get_way(int8) AS  SELECT nodes, tags    FROM "planet_osm_ways" WHERE id = $1;
PREPARE get_way_list(int8[]) AS  SELECT id, nodes, tags    FROM "planet_osm_ways"      WHERE id = ANY($1::int8[]);
```

**Comment by joto** [comment]
Can you tell us why this is a problem?

**Comment by mboeringa** [comment]
> Can you tell us why this is a problem?

Can you tell me why osm2pgsql needs to output badly formatted SQL?

**Comment by joto** [comment]
It doesn't need to do that, but it does. Probably because it looks better that way in the source code. It sre as hell doesn't do that just for the heck of it.

Closing as "wont fix".
