### ISSUE TITLE
Providing Windows binaries/packages

### ISSUE THREAD

**Issue by springmeyer** [openstreetmap/osm2pgsql#17]
In addition to OS X (#15) the osm2pgsql community of developers should provide binaries for Windows.

Let's coordinate how to get this done via this ticket.

Tasks:

 - [ ] - code changes needed to support compiling under mingw, msvc, and/or cygwin
 - [ ] - volunteer(s) to create binaries on windows and to test them
 - [ ] - writing an easy installer using nsis that should produce a working executable without any additional installs or development toolkits and should work on 32/64 bit systems ranging from windows XP -> Win8.

Background discussions: hotosm/hotosm#1

**Comment by pnorman** [comment]
Given the age of this issue, I'm going to go ahead and close it. If there are new specific issues in 0.88.0 or 0.89.0-dev, they should be raised as new issues.
