### ISSUE TITLE
Provide tmp .osc.gz file to post processing script

### ISSUE THREAD

**Issue by stalker314314** [openstreetmap/osm2pgsql#1719]
Post-processing scripts are limited with current arguments (only seq and timestamp). It would be good if script can access location of temp file (full absolute path to .osc.gz file) and read this file. I would send PR for this change (sending issue first to see what do you think). It should not break backward-compatibility (if `timestamp` is `None`, we still will have 3rd argument as full path and filename). Only question is whether we should treat this temp file as hidden from post processing script for any reason? Or maybe we should unpack it before providing it to post-processing script?

## What version of osm2pgsql are you using?

osm2pgsql --version
2022-07-29 22:18:11  osm2pgsql version 1.6.0
Build: None
Compiled using the following library versions:
Libosmium 2.18.0
Proj [API 6] 9.0.1
Lua 5.3.6

**Comment by joto** [comment]
What post-processing scripts and timestamps and arguments are you talking about?

The questions in the issue template are there for a reason. Can you please describe exactly what you are trying to achieve and why this doesn't work?

**Comment by stalker314314** [comment]
Sorry if I was not being more details, it looked like an easy addition, but you are right.

Scenario:
I would like to keep my local postgis minutely up-to-date and also stream all .osc changes further down the pipeline. My scenario is monitoring and processing changes, think about real-time [monitoring tools ](https://wiki.openstreetmap.org/wiki/Quality_assurance#Monitoring_Tools), for example how would you recreate today [osm-watch](https://wiki.openstreetmap.org/wiki/Osm-watch) tool, or how would this [restaurant notifier](https://try-something-new.web.app/) be implemented in OSM. So, I basically would like to use all the easiness of osm2pgsql use, and enrich .osc data with postgis data and process it further.

P.S. I already implemented it for my needs, but I though this might be interesting to everyone

P.P.S. Slightly related to this (but I would open new issue if you are OK with it) is concept of "pre-processing". Idea is to enable scenarios where one can hook trim_osc.py to in-place edit .osc files *before* they are sent to osm2pgsql and to be able to compare old (in postgis) and new (in .osc) data for contextual differences. This "pre-processing" would also have path to temp .osc file as parameter.

**Comment by lonvia** [comment]
You have left out the small but essential detail that you are likely talking about the osm2pgsql-replication script. The rest of the answer assumes that this is the case.

If you need to access the diff file in your post-processing script, simply use the `--osm-diff` parameter and give the diff file an explicit name and location.

**Comment by stalker314314** [comment]
Ahaha, good catch, @lonvia , completely forgot to mention that this is about `osm2pgsql-replication`! Sorry for making confusion.

While I can use `--diff-file` in `osm2pgsql-replication`, I still cannot get its name in post-processing script, can I? Unless I use some orchestration (parent process) which would call both `osm2pgsql-replication` and my post-process script. But then I lose all benefits of `osm2pgsql-replication` (ability to contact minutely server, batch and simplify changes, send them to `osm2pgsql`). Am I missing something?

**Comment by stalker314314** [comment]
Oh, I see, you think I am providing some well-known location for a diff file and my script can assume its location and use it? I guess that can do it. Feel free to close issue.

Is there any similar workaround for pre-processing script that I mentioned? To stop after getting data from minutely repl server and before sending it to `osm2pgsql`?

**Comment by stalker314314** [comment]
Closed this, continued with pre-processing question on separate issue, #1729
