### ISSUE TITLE
Osm2pgsql failed due to ERROR: Generic projections not available.

### ISSUE THREAD

**Issue by TommasoDb** [openstreetmap/osm2pgsql#1730]
## What version of osm2pgsql are you using?

osm2pgsql version 1.3.0

Compiled using the following library versions:
Libosmium 2.17.2
Lua 5.2.4

## What operating system and PostgreSQL/PostGIS version are you using?

Ubuntu 20.04
Linux ThinkPad-P51 5.15.0-41-generic #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

 PostgreSQL 12.2 (Ubuntu 12.2-4) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-8ubuntu1) 9.3.0, 64-bit

 3.0 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

## What did you do exactly?
I'm tring to import OSM data in Postgres using this command

`osm2pgsql --keep-coastlines -s -j -r xml -E 32631 -H localhost -P 5432 -U liqui -d xxxxxxx_geo data.xml`

## What did you expect to happen?

The data are imported in the database

## What did happen instead?

The tool fails because of the option -E 32631. The error message is:
`Osm2pgsql failed due to ERROR: Generic projections not available.`

Without the -E option the import runs fine

**Comment by joto** [comment]
You compiled osm2pgsql without the proj library. You should have gotten some message about proj not being available when running `cmake`. Or you disabled it when running cmake.

Also: The version 1.3.0 is rather old. I recommend switching to the current version.
