### ISSUE TITLE
gazetteer output missing stylesheet

### ISSUE THREAD

**Issue by geoHeil** [openstreetmap/osm2pgsql#1733]
How can I get the `gazetteer` output to work without forcing me to specify a stylesheet? Or at least if I select one of the example stylesheets that work fine for the `flex` output- osmp2gsql currently fails with Lua parsing errors.

I am using a current 1.6.0 version of osm2pgsql.

**Comment by pnorman** [comment]
What is the full command you are using?

**Comment by joto** [comment]
You can not use the flex stylesheets with gazetteer backend, that doesn't make any sense.

**Comment by lonvia** [comment]
The gazetteer output is meant to be used only by [Nominatim](https://nominatim.org), it doesn't make any sense otherwise. Styles for the output are also distributed only with Nominatim.

**Comment by geoHeil** [comment]
Well, I do NOT want to use flex with gazetter - but when I do not specify anything I am prompted and forced to specify a style file. This is why I am asking:

```
osm2pgsql --create --cache 1100 --output nominatim ... user/db/port/host/password ... path
```

was telling me that a style file (like flex) is missing.

**Comment by lonvia** [comment]
To clarify:

> How can I get the gazetteer output to work without forcing me to specify a stylesheet?

You can't.

Also, if you have the need to manually run `--output gazetteer` you are almost certainly doing something wrong.

**Comment by geoHeil** [comment]
So I should not *manually* call osm2pgsql with gazetteer output but somewhere have nominatim do this behind the scenes automatically?
