### ISSUE TITLE
some area data lose with gazetteer output

### ISSUE THREAD

**Issue by xlofhappy** [openstreetmap/osm2pgsql#1759]
## What version of osm2pgsql are you using?

Build: Release
Compiled using the following library versions:
Libosmium 2.17.3
Proj [API 6] 9.0.0
Lua 5.1.4 (LuaJIT 2.1.0-beta3)

## What operating system and PostgreSQL/PostGIS version are you using?
Database version: 14.3
PostGIS version: 3.2

## Tell us something about your system
RAM: 64GB
CPU: intel-10500 6 core

## What did you do exactly?
osm2pgsql -v -Uxiaole -dnominatim -P5432 -H127.0.0.1 --hstore --latlon --slim --with-forward-dependencies=false --log-progress=true --number-processes=1 --cache=4096 --output=gazetteer --style=/import-admin.style --create /planet-220829.osm.pbf

## What did you expect to happen?
new import database with all data

## What did happen instead?

some area lost, I import two PBF file: 
planet-211220.osm.pbf 
planet-220829.osm.pbf
(download from planet.openstreetmap.org)

but I found that the Relation 3507759 was lost when I load file planet-220829.osm.pbf, it didn't store in table place.
file planet-211220.osm.pbf seem to be right.

## What did you do to try analyzing the problem?
1. I tried to build different versions of osm2pgsql, got the same result. so I think it may be the problem of pbf files.
2. I tried to find the code than the data was not passed. it's 
<img width="521" alt="image" src="https://user-images.githubusercontent.com/31211644/189250796-6cfd82b3-264b-482f-a01e-58e405f93cfa.png">
I am not good at C language, so give me a hand.

**Comment by joto** [comment]
The gazetteer output is only for the use of the Nominatim geocoder. It will be called in the context of Nominatim and only makes sense in that context. Don't use it for anything else.

If you tell us what you are trying to achieve in the end, we might be able to help you find a solution.

**Comment by lonvia** [comment]
Issues with osm2pgsql inside Nominatim should be reported with [Nominatim](https://github.com/openstreetmap/Nominatim/issues/).

That said, the relation has a broken geometry as can be seen in the [OSM Inspector](https://tools.geofabrik.de/osmi/?view=areas&lon=121.20810&lat=24.51229&zoom=15&baselayer=Geofabrik%20Standard&overlays=duplicate_node%2Csingle_node_in_way%2Cduplicate_segment%2Cway_in_multiple_rings%2Cintersection%2Cintersecting_segments%2Cring_not_closed%2Ctouching_rings%2Crole_should_be_inner%2Crole_should_be_outer%2Cinner_with_same_tags%2Cways%2Cduplicate_node%2Csingle_node_in_way%2Cduplicate_segment%2Cway_in_multiple_rings%2Cintersection%2Cintersecting_segments%2Cring_not_closed%2Ctouching_rings%2Crole_should_be_inner%2Crole_should_be_outer%2Cinner_with_same_tags%2Cways). Fix the geometry and all will be fine.

Closing as data issue.
