### ISSUE TITLE
Check if way-node index exists before enabling forward dependencies

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#1814]
If a database is imported with `--with-forward-dependencies=false` and then updated without the option, updates will be slow to the point of being unusable because the way-node index is missing.

osm2pgsql should check that the index exists before allowing forward dependencies.

Related to #1311.

**Comment by joto** [comment]
We don't have the name of the index, but this should probably work:
```
SELECT count(*) FROM pg_indexes WHERE tablename='{prefix}ways' AND indexdef LIKE '%nodes%';
```
If the result is >0, the index is there.

**Comment by joto** [comment]
Do we need this check now that `--with-forward-dependencies` is going away anyway?

See #1866 .

**Comment by lonvia** [comment]
Nope.
