### ISSUE TITLE
`osm2pgsql-replication`: compute database date fails if data is not in `public` schema

### ISSUE THREAD

**Issue by JakobMiksch** [openstreetmap/osm2pgsql#1818]
## What version of osm2pgsql are you using?

`master` at https://github.com/openstreetmap/osm2pgsql/commit/41f2e56d8c18b8a694ceb5307926d652ae1faec0

## What did you do exactly?

I imported OSM data in the schema `foobar` and tried to initilise the replication **without** providing the OSM file.

```shell
export PGHOST=localhost
export PGPORT=5432
export PGUSER=postgres
export PGPASSWORD=postgres
export PGDATABASE=osm

DB_SCHEMA=foobar
psql -c "CREATE SCHEMA IF NOT EXISTS ${DB_SCHEMA}";

osm2pgsql \
  --create \
  --slim \
  --verbose \
  --middle-schema=${DB_SCHEMA} \
  path/to/osm-file.pbf

osm2pgsql-replication init
```

## What did you expect to happen?

The date from the OSM should have been read and a table with the replication should have been created.

## What did happen instead?

`osm2pgsql-replication` could not find the table with OSM date, because it is not aware that it is stored in a schema. Error message:

```
Traceback (most recent call last):
  File "/home/jakob/Repos/osm2pgsql/scripts/osm2pgsql-replication", line 551, in <module>
    sys.exit(main())
  File "/home/jakob/Repos/osm2pgsql/scripts/osm2pgsql-replication", line 545, in main
    return args.handler(conn, args)
  File "/home/jakob/Repos/osm2pgsql/scripts/osm2pgsql-replication", line 290, in init
    date = compute_database_date(conn, args.prefix)
  File "/home/jakob/Repos/osm2pgsql/scripts/osm2pgsql-replication", line 103, in compute_database_date
    cur.execute(sql.SQL("SELECT max(id) FROM {}").format(table))
psycopg2.errors.UndefinedTable: relation "planet_osm_ways" does not exist
LINE 1: SELECT max(id) FROM "planet_osm_ways"
```

## What did you do to try analyzing the problem?

I assume the script `osm2pgsql-replication` has to be adapted to handle OSM data stored in different schemas. The error occurs [here](https://github.com/openstreetmap/osm2pgsql/blob/41f2e56d8c18b8a694ceb5307926d652ae1faec0/scripts/osm2pgsql-replication#L102)

**Comment by lonvia** [comment]
Fixed with #1817.

**Comment by gislars** [comment]
I'm using version 1.7.2 and I'm getting the same error. 

`osm2pgsql  --create  --slim --cache 2000 --output=flex --style=/config/tables.lua --middle-schema=foo  "/data/osm-file.pbf"`

the tables get created in schema `foo` `planet_osm_nodes, planet_osm_rels, planet_osm_ways` and containing data.
the osm data is imported in schema `import` (specified in the lua file).

Running `osm2pgsql-replication init --middle-schema foo --server https://planet.osm.org/replication/minute/` gives me the error:

```
Traceback (most recent call last):
  File "/usr/bin/osm2pgsql-replication", line 556, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/osm2pgsql-replication", line 550, in main
    return args.handler(conn, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/osm2pgsql-replication", line 293, in init
    date = compute_database_date(conn, args.prefix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/osm2pgsql-replication", line 106, in compute_database_date
    cur.execute(sql.SQL("SELECT max(id) FROM {}").format(table))
psycopg2.errors.UndefinedTable: relation "planet_osm_ways" does not exist
LINE 1: SELECT max(id) FROM "planet_osm_ways"
```
```
osm2pgsql version 1.7.2
Build: None
Compiled using the following library versions:
Libosmium 2.18.0
Proj [API 6] 9.1.1
Lua 5.3.6
```
`POSTGIS="3.3.2 4975da8" [EXTENSION] PGSQL="150" GEOS="3.9.0-CAPI-1.16.2" PROJ="7.2.1" LIBXML="2.9.10" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)" TOPOLOGY`

OS: debian sid

Am I making something wrong here? Should I open a new issue about it?

**Comment by lonvia** [comment]
So #1817 has fixed everything around schemas except what was reported here. :(

**Comment by gislars** [comment]
I think this line https://github.com/openstreetmap/osm2pgsql/blob/1359e2eaba52fdfdfd9f453409ad65b2589483e0/scripts/osm2pgsql-replication#L106 needs to be fixed by adding the schema.

I just hard coded this line to 
`        cur.execute(sql.SQL("SELECT max(id) FROM foo.planet_osm_ways"))`
and osm2pgsql-replication init worked.
