### ISSUE TITLE
Osm2pgsql not generating data in polygon table for Multigeometry

### ISSUE THREAD

**Issue by RakeshGupta-tomtom** [openstreetmap/osm2pgsql#1848]
osm2pgsql version 1.6.0

I have geometry which in multi polygon / multi geometry form , when I do osm2pgsql its not populating data to polygon table ,
but *rels (relation ) table populated correctly

**Comment by pnorman** [comment]
Please check the multipolygon for validity in JOSM first, then if it's valid, provide enough information to reproduce including the OSM data you're trying to import and the transforms you're using.

**Comment by joto** [comment]
Not enough information. Closing.
