### ISSUE TITLE
Importing with Dutch "Rijksdriehoekstelsel" projection (SRID 28992) fails (extremely slow)

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1876]
osm2pgsql version: 1.7.1 (1.7.0-75-g6a5d2500)

## What operating system and PostgreSQL/PostGIS version are you using?

Ubuntu 22.04.1 LTS, PostgreSQL 15.1, PostGIS 3.3.2

## Tell us something about your system

Bare metal 2x Xeon E5-2680 v4, 256GB RAM

## What did you do exactly?

Tried to import the Geofabrik "Netherlands" extract using osm2pgsql and a LUA flex output style, setting the projection to SRID 28992 for the Dutch "Rijksdriehoekstelsel" (RD New) projection. 

Note that I have used exactly(!) the same style and Geofabrik extract before to import in Web Mercator (3857) and WGS 1984 (4326) without issues. With these projections set, the import finishes in less than 15 minutes.

## What did you expect to happen?

 The import finishes in less than 15 minutes.

## What did happen instead?

Contrary to what I see happening with 3857 or 4326 projection import, the 28992 projection import seems to import normally to up to about the progress showing 730k ways loaded, then progressively and continuously slows down to now 0.06k/s ways loaded, where it normally achieves about 55k/s way loading (tested with the entire planet as well). After more than 8 hours, the import is still not finished with the way loading stage.

I have never seen this behavior before, but this is the first time I tried using any other projection than Web Mercator or WGS 1984.

Note that the Dutch "Rijksdriehoekstelsel" 28992 projection, a stereographic projection, even though a very nice compromise projection for small regions and countries like the Netherlands, is actually quite unusual in an international context. If I recall well, there is maybe just one other country in the world using a similar projection. As a consequence, proper support for this projection in software has historically often been lacking.

## What did you do to try analyzing the problem?

I looked in pgAdmin, and see the following processes / queries listed as "active" when this issue occurs:
`COPY "planet_osm_ways" FROM STDIN`
`COPY "osm"."planet_osm_polygon" ("osm_id","way","tags","layer") FROM STDIN`
I was slightly expecting only to see the first statement? But I guess this is normal?

Double checked that 3857 and 4326 imports are fine by re-importing. As expected, they finish in less than 15 minutes.

**Comment by joto** [comment]
Can you show us the exact command line used and the flex Lua config?

**Comment by joto** [comment]
I have seen problems like this when switching from lat/lon to Mercator coordinates or the other way round when splitting long lines or large polygons or so, because a line split at 1° is okay, but splitting every 1m in Mercator multiplies the number of features enormously. So maybe it is something to do with coordinate values/ranges.

**Comment by mboeringa** [comment]
> I have seen problems like this when switching from lat/lon to Mercator coordinates or the other way round when splitting long lines or large polygons or so, because a line split at 1° is okay, but splitting every 1m in Mercator multiplies the number of features enormously. So maybe it is something to do with coordinate values/ranges.

I actually have code for this in my LUA flex style to deal with this. If the projection is 4326, lines are split at 1 degree, all other projections detected at 100k meters.

I also have a second configuration option, where I can disable line splitting by setting a boolean variable to false. And the current style is configured with false, so no line splitting is taking place.

**Comment by mboeringa** [comment]
The style:
[openstreetmap-carto_crs_28992_rd_debug.zip](https://github.com/openstreetmap/osm2pgsql/files/10358792/openstreetmap-carto_crs_28992_rd_debug.zip)

Note that you can set and thus test the different projections for all tables in the top "Configuration" section by setting the 
`local srid=x`
variable.

If you want to change the schema as well, set the 
`local schema=x`
variable.

Command line used for import:
osm2pgsql -O flex -d test -U <YOUR_USERNAME> --tablespace-slim-data <YOUR_TABLESPACE> --tablespace-slim-index <YOUR_TABLESPACE> --create -W --slim --drop -C 40000 -P 5433 -S 'osm2pgsql/flex-config/openstreetmap-carto_crs_28992_rd_debug.lua' 'data/netherlands-latest.osm.pbf'

**Comment by joto** [comment]
I can't see anything in your command line/config that should pose a problem with a different projection. I would expect a different projection to be somewhat slower, because projections just need some time (the Mercator projection is handled internally in some highly optimized way, so it doesn't suffer from that as much). But the times you report are way slower than what I would expect.

Here are some things you can try:
1. Comment out parts of your code to see whether its only some layers that are the problem.
2. The only thing I can think of that's different between projections (except the transformation itself), is the validity check performed in the database. Maybe that's horrible slow for some reason in that projection. You can find the code in osm2pgsql where that trigger is configured and remove it temporarily to check that.

But all of those above don't explain why the import seems to be fast at first and then gets slower. If that's actually what's happening then it could be related to table filling up and making queries on that table slow because of a missing index. But that should a) not be happening anyway and b) is not related to projections!?

**Comment by mboeringa** [comment]
> I can't see anything in your command line/config that should pose a problem with a different projection. I would expect a different projection to be somewhat slower, because projections just need some time (the Mercator projection is handled internally in some highly optimized way, so it doesn't suffer from that as much).

I am surprised to hear that Web Mercator is handled differently than other projections in osm2pgsql. I initially assumed it would be the same as any other projection, also because of code maintenance. However, this does at least explain why Web Mercator importing isn't affected by the same issue.

@joto, could you try out this style and command line yourself and see what happens? You just need to download Geofabrik's Netherlands extract, nothing else. You should have everything now to test and confirm the issue.

**Comment by joto** [comment]
@mboeringa Except time, yes. Sorry, can't do more at the moment there.

**Comment by mboeringa** [comment]
@joto , I have now switched the style to use EPSG 327631, which represents UTM zone 31N based on WGS1984 GCS. This zone covers the Netherlands.

I see similar behavior of processing significantly slowing down after about 700k ways imported. The slowing down seems less than EPSG 28992 though, and flat out at around 1k/s with UTM zone 31N. That is still **50x** as slow as compared to the other projections though, and seriously hampers its application.

So the issue doesn't seem specific to the Dutch EPSG 28992 stereographic projection, but more general for any other projection than 3857 and 4326.

**Comment by lonvia** [comment]
Any unusual increase in memory usage by osm2pgsql? Also, please check which proj version you have.

**Comment by mboeringa** [comment]
> Any unusual increase in memory usage by osm2pgsql? Also, please check which proj version you have.

@lonvia 

Memory consumption of osm2pgsql seems stable at 1.1GB according to System Monitor in Ubuntu. CPU usage by osm2pgsql is just 2%, and overall usage equally low in Ubuntu at this stage.

PostGIS version: POSTGIS="3.3.2 4975da8" [EXTENSION] PGSQL="150" GEOS="3.10.2-CAPI-1.16.0" PROJ="8.2.1" LIBXML="2.9.13" LIBJSON="0.15" LIBPROTOBUF="1.3.3" WAGYU="0.5.0 (Internal)"

**Comment by mboeringa** [comment]
@lonvia. Another question: As a test, I tried disabling RAM cache by setting '-C 0'. I remember you stating that cache wasn't particularly useful anymore in the latest versions of osm2pgsql, especially with Planet imports. However, if I set it to 0, I get a warning message: 

"RAM cache is disabled. This will likely slow down processing a lot."

Is this warning still valid?

EDIT: yes, it still seems valid. I now see the EPGS 28992 import having the same poor way processing performance from the very start, so already with less than 10k ways loaded.

This does raise the question though if somehow the cache is involved in this issue?

**Comment by joto** [comment]
I just realized that I have a PR open (#1873) that might have something to do with your problem. @lonvia didn't have a chance yet to look at it, but you can try it and see whether it makes a difference.

**Comment by mboeringa** [comment]
> I just realized that I have a PR open (#1873) that might have something to do with your problem. @lonvia didn't have a chance yet to look at it, but you can try it and see whether it makes a difference.

I have little doubt you nailed it. This was the same issue affecting PostGIS once it switched from using PROJ4 to 5? or 6?, where initializing the projection object was no longer trivial, but _much_ more expensive. It caused a similar 50 to 100x slow down of some of my code calling ST_Transform, and was fixed in a subsequent release of PostGIS by also caching the projection object.

So this patch seems right.

Maybe it is good to document on the osm2pgsql website though, unless you intend to backport this fix to all versions from the moment osm2pgsql flex started technically supporting arbitrary projections, that unfortunately this functionality cannot yet be practically used with flex output due to this issue in these earlier releases of osm2pgsql with flex output support, and only 3857 and 4326 can be reasonably used. Once the new release is out, the proper support for it can be documented again.

I am actually a bit surprised I am the first to report this issue, would have expected someone else to have tried it as well.

**Comment by mboeringa** [comment]
Final note: the code did finish. Importing the Netherlands extract using EPSG 32631 for UTM zone 31N took > 15 hours though, instead of 15 minutes.

**Comment by mboeringa** [comment]
@joto. 

This issue is indeed fixed in #1873. 

I rebuild osm2pgsl from latest master, and I have now successfully imported with the Dutch Rijksdriehoekstelsel projection (EPSG 28992) in a total time of just 18 minutes!

I am pleasantly surprised how little the total processing time is influenced by the extra projection step. Way loading showed 36k/s, which is about 35% slower than importing with 3857, which showed about 55k/s. However, total import time is even less influenced by the extra work, considering there are other longish steps like indexing.

All in all good news!
