### ISSUE TITLE
osm2pgsql not able to convert geometry in pbf to db , but if I import to qgis ,jsom its opening correctly

### ISSUE THREAD

**Issue by RakeshGupta-tomtom** [openstreetmap/osm2pgsql#1878]
osm2pgsql version 1.6.0
osm2pgsql not able to convert pbf containing multi geometry to db
same pbf if uploaded to qgis / josm its valid geometry 
importing pbf to db get all the information on planet_osm_rels table but planet_osm_polygon table does not have data

**Comment by RakeshGupta-tomtom** [comment]
let me know if you need more information

**Comment by joto** [comment]
Chances are your multipolygon is invalid for some reason. Different tools have different ideas on what constitutes a valid multipolygon in OSM. You can use the `oat_create_areas` tool from https://github.com/osmcode/osm-area-tools to check your data for validity. It can produce all sorts of debug output.

**Comment by RakeshGupta-tomtom** [comment]
i tried using qgis check validity its not finding any error

**Comment by RakeshGupta-tomtom** [comment]
I am not sure how to use oat_create_areas
can you provide command to run

**Comment by RakeshGupta-tomtom** [comment]
we have same id in another pbf but thats working correctly

**Comment by RakeshGupta-tomtom** [comment]
can we see error while using osm2pgsql command , i tried debug option but that not giving any error

**Comment by pnorman** [comment]
Can you reduce this to a testcase with with *just* the offending relation and dependent objects? The PBF has lots of nodes unrelated to the relation which makes it difficult to see what's going on.

Like I asked above, if you have more normal IDs with this data, do you get a polygon? You can test this with `osmium renumber`.

**Comment by RakeshGupta-tomtom** [comment]
sharing again t
[test-working.pbf.zip](https://github.com/openstreetmap/osm2pgsql/files/10371991/test-working.pbf.zip)
est file which has same id range and able to convert to polygon

**Comment by RakeshGupta-tomtom** [comment]
if you want can share the renumbered pbf

**Comment by RakeshGupta-tomtom** [comment]
@pnorman  @joto any update on this , have you guys found out the issue

**Comment by pnorman** [comment]
Please don't ping maintainers on your issue asking for an update. If you need faster support, you could pay someone to provide it.

Please build `oat_create_areas` and run it on your PBF. The command provides its own documentation.
