### ISSUE TITLE
Update lua autoconf macro

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#188]
The ax_lua.m4 macro has been updated since the version we took, improving  BSD support and other improvements: http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=history;f=m4/ax_lua.m4

We should probably update

**Comment by pnorman** [comment]
Upstream ax_lua.m4 doesn't actually work

**Comment by pnorman** [comment]
I never could figure out how to report the issue to upstream, so I'm not sure if they're aware that ax_lua.m4 doesn't work on Ubuntu, Debian, or pretty much any system.

**Comment by lonvia** [comment]
There have been some recent commits upstream for ax_lua.m4.
