### ISSUE TITLE
Garbled data in the tags field ('name' tags with accents).

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1893]
## What version of osm2pgsql are you using?
1.7.2 (1.7.0-236-g8b9eedc9)

## What operating system and PostgreSQL/PostGIS version are you using?

Ubuntu 22.01.4 LTS with latest updates. PostgreSQL 15.1

## What did you do exactly?

Import Italy extract of Geofabrik

## What did you expect to happen?

Data is properly imported

## What did happen instead?

Data in the 'tags' field is garbled. Special characters do not come over properly, e.g. https://www.openstreetmap.org/node/3225272477#map=19/46.05451/9.43078
is an example node, in this area of the Italian Alps there are many more.

## What did you do to try analyzing the problem?
Looked in the 'planet_osm_point' table:

![afbeelding](https://user-images.githubusercontent.com/7635726/213316303-a1b66b68-c016-451d-afc3-7c7b851c98f5.png)

**Comment by joto** [comment]
The question was "What did you do exactly?". The answer "Import Italy extract of Geofabrik" doesn't answer that. What command line did you use?

Also: Is your database set to UTF8? (see https://osm2pgsql.org/doc/manual.html#creating-a-database )

**Comment by mboeringa** [comment]
Same as always:
`osm2pgsql -O flex -d <YOUR_DATABASE> -U <YOUR_USERNAME> --tablespace-slim-data <YOUR_TABLESPACE> --tablespace-slim-index <YOUR_TABLESPACE> --create -W --slim --drop -C 40000 -P 5433 -S 'osm2pgsql/flex-config/openstreetmap-carto.lua' 'data/italy-latest.osm.pbf'`

And yes, pgAdmin defaults to UTF8 for creating any new database, and this one is UTF8.

I now compiled from the latest master, and it still shows the same issue.

**Comment by mboeringa** [comment]
'tags' column is defined as JSONB by the way, using the new flex output options for that.

**Comment by mboeringa** [comment]
Maybe this OpenStreetMap Diary entry with posts by prominent OpenStreetMap members like Andy Allen, Simon Poole and mmd also provides some food for thought:

[OpenStreetMap Isn't Unicode](https://www.openstreetmap.org/user/bdon/diary/397922)

The case of "surrogate pairs" Andy mentions was certainly interesting to me having little background in this specific matter...

**Comment by lonvia** [comment]
Fixed with #1896.
