### ISSUE TITLE
Clarify documentation around hstore and --extra-attributes

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#190]
--extra-attributes essentially gives each node/way/relation a few extra tags. This tends to confuse people if they then add hstore options which cause all tagged objects to be added to the database, as it then results in a lot of extra objects.

See also #189

**Comment by joto** [comment]
I have added a note to the manual: https://osm2pgsql.org/doc/manual.html#use-of-hstore
