### ISSUE TITLE
Use a logging library

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#202]
Currently everything prints out with fprintf. This makes it hard to change the verbosity.

Any thoughts?

@zerebubuth, do you think [MapQuest/logging](https://github.com/MapQuest/logging) would be suited here?

**Comment by pnorman** [comment]
boost::log was only introduced in 1.54. This is a big minus.

@zerebubuth, I can't remember the options we came up with at the hack weekend.

**Comment by zerebubuth** [comment]
There's google's logging library too. I've never used it, though, so I
can't say whether it's any good.

The MQ logging library is probably no good for now, as it currently depends
on mapnik and that's too big of a dep to pull in (imho).

**Comment by pnorman** [comment]
I forgot our library depends on Mapnik. I agree, that rules it out.

[log4cxx](http://logging.apache.org/log4cxx/) is another library mentioned, patterned after log4j. log4cxx is packaged on Ubuntu 12.04, 14.04 and FreeBSD

[google-glog](https://code.google.com/p/google-glog/) is Google's. It is packaged on Ubuntu 14.04 and FreeBSD, but not Ubuntu 12.04.

**Comment by alex85k** [comment]
Maybe use something lighweight and header-only like https://github.com/gabime/spdlog , if you are going to use cppformat anyway https://github.com/openstreetmap/osm2pgsql/issues/398
It would be great to replace boost completely, to my opinion. It is the biggest dependency, after all and used only in few places.

**Comment by alex85k** [comment]
Another way is to use boost whenever possible, like https://github.com/alacarte-maps/alacarte and https://github.com/Project-OSRM/osrm-backend (including logging, formatting, testing etc.)

**Comment by pnorman** [comment]
osmium::util::VerboseOutput might be of use here

**Comment by pnorman** [comment]
Per previous discussion, we need support for three levels of output - details (off by default), standard, and errors.

We might also have additional debugging output with some compile-time flags (e.g. all COPY lines to postgres)
