### ISSUE TITLE
geos::util:topologyexception loading Africa into Database

### ISSUE THREAD

**Issue by achapkowski** [openstreetmap/osm2pgsql#206]
I'm loading in Africa from http://download.geofabrik.de/africa.html and I get the following error:

![image](https://cloud.githubusercontent.com/assets/5131271/4796908/33675c54-5e07-11e4-9f22-fe66b16be6e1.png)

I can take sections of the database, but not the whole shabang.  Any suggestions on how to work around this?

Thanks

A

**Comment by pnorman** [comment]
Geos version information was never provided.
