### ISSUE TITLE
1.9.2 failed to build on several architectures (error: static assertion failed)

### ISSUE THREAD

**Issue by sebastic** [openstreetmap/osm2pgsql#2065]
The Debian package build for 1.9.2 failed on several architectures:
```
/<<PKGBUILDDIR>>/src/gen/tracer.cpp:51:36: error: static assertion failed
   51 | static_assert(sizeof(potrace_word) == 8);
      |               ~~~~~~~~~~~~~~~~~~~~~^~~~
```
Full buildlogs: [i386](https://buildd.debian.org/status/fetch.php?pkg=osm2pgsql&arch=i386&ver=1.9.2%2Bds-1&stamp=1693835886&raw=0), [armel](https://buildd.debian.org/status/fetch.php?pkg=osm2pgsql&arch=armel&ver=1.9.2%2Bds-1&stamp=1693835641&raw=0), [armhf](https://buildd.debian.org/status/fetch.php?pkg=osm2pgsql&arch=armhf&ver=1.9.2%2Bds-1&stamp=1693835745&raw=0), [hppa](https://buildd.debian.org/status/fetch.php?pkg=osm2pgsql&arch=hppa&ver=1.9.2%2Bds-1&stamp=1693838398&raw=0), [powerpc](https://buildd.debian.org/status/fetch.php?pkg=osm2pgsql&arch=powerpc&ver=1.9.2%2Bds-1&stamp=1693836496&raw=0)

`sizeof()` most likely returns 4 on these architectures, see:

 https://wiki.debian.org/ArchitectureSpecificsMemo#Summary

**Comment by joto** [comment]
Officially we are not supporting 32bit architectures and have for a while now. Its not that you can do much with a 32bit system with OSM data. So maybe it is time to take these architectures out?

**Comment by sebastic** [comment]
The buildd notifications for the failed builds are bit a annoying, but maintaining the list of Achitectures is also a pain, so let's just remove the package from the 32bit release architectures:

 [Debian Bug#1051212: RM: osm2pgsql [i386 armel armhf] -- ROM; 32bit architectures not supported](https://bugs.debian.org/1051212)
