### ISSUE TITLE
windows set port to 5433 not working

### ISSUE THREAD

**Issue by blu-elephant** [openstreetmap/osm2pgsql#210]
I have a PostgreSQL server running on localhost:5433, but setting this explicitly in osm2pgsql cmd line using -p 5433 OR -port 5433 doesn't seem to make a difference.

It seems to want everything to be on default 5432.

Is this a known issues on Windows?

**Comment by pnorman** [comment]
What's the exact command line you're using? The port option is `-P|--port`, not `-p` or `-port`

**Comment by blu-elephant** [comment]
This was a few years ago now and I don't have the machine/can't replicate the issue now. I'll choose the issue
