### ISSUE TITLE
middle_ram_t::relations_using_way is unimlpemented

### ISSUE THREAD

**Issue by netalien** [openstreetmap/osm2pgsql#213]
Hello,

We're trying to load north-america's pbf using the following command:
```
osm2pgsql -a -k -E EPSG:4326  -H localhost -U postgres -W -d osm_test1 /tmp/north-america-latest.osm.pbf -C 12000

Upon ways processing, the following message is thrown and the load is aborted:

Using 1 helper-processes
terminate called after throwing an instance of 'std::runtime_error'
  what():  middle_ram_t::relations_using_way is unimlpemented, and should not have been called. This is probably a bug, please report it at https://github.com/openstreetmap/osm2pgsql/issues
Aborted
```

I've looked at middle_ram_t definition and the execption at https://github.com/openstreetmap/osm2pgsql/blob/master/middle-ram.cpp and seems weird to me that it mentions that relations_using_ways is only used in slim mode which in the command above isn't used.

The version of osm2pgsql I'm using is: osm2pgsql SVN version 0.87.0 (64bit id space)

Is this a bug or I'm a missing something?

**Comment by systemed** [comment]
> The -a option is there to append/change data in a database that already contains data. It requires slim mode and a change file, you shouldn't be using it with pbf files at all

I'd quibble with that: I load multiple Geofabrik .pbfs using -c for the first country, dropping the indexes, then -a for all subsequent countries, and recreating the indexes at the end. (I'm still using a version of osm2pgsql from before the big C++ change, and am not using slim mode.)

**Comment by lonvia** [comment]
Jep, I've also come to the conclusion that this is a regression. The C version used to consider the whole file as one big add action. I'm just not sure about marking pending of related ways/relation. Without slim it probably is a null operation anyways.

**Comment by lonvia** [comment]
The C version actually just appended the new data potentially duplicating everything where the extracts overlap. I'm not sure that's actually what one would expect. I would rather expect that the new pbf is handled like a huge change file with adds only. What do others here think?

Getting the old behaviour back is relatively simple and only requires a small change in the libosmium parser.

To implement the change file behaviour, we would need to introduce an index over the osm_ids on the output tables and remove a few sanity checks. Also possibly add a huge warning that append in non-slim mode might cause potential data loss if actually used with a change file.

**Comment by pnorman** [comment]
> To implement the change file behaviour, we would need to introduce an index over the osm_ids on the output tables

This would be a bad idea to do by default, since it would add unneeded bloat to output. Checking if there's an existing btree (osm_id) index would be difficult

**Comment by lonvia** [comment]
I wonder... are people using the non-slim append only because append with pbf files doesn't work in slim mode? Because in that case it might be better to add proper support for that with change file behaviour and just leave the append/non-slim as an illegal combination. Main drawback: proper append will be slower because we need to check for duplicates on each insert.

**Comment by pnorman** [comment]
Most I've seen have imported one extract then want to get in more data, and are't aware of options to merge the file before loading.

@systemed is one of the exceptions, where he is doing multiple loads sensibly - probably with different lua transforms for each extract.

**Comment by systemed** [comment]
Indeed - I have different transforms for the UK and Western Europe.

I've also found performance can sometimes be better by running a series of country appends rather than just importing a single combined file.
