### ISSUE TITLE
Multipolygon error

### ISSUE THREAD

**Issue by floscher** [openstreetmap/osm2pgsql#215]
I've reported an issue over at gravitystorm/openstreetmap-carto#1133, where a label of a multipolygon displays far away from the OSM-ways forming the multipolygon. I was pointed to this repository, because it is reasonably certain neither a osm-carto-issue nor a OSM-data-issue.

Also the solved issue #67 seems to be similar, but not responsible for this particular bug.

For seeing the effects of this bug, visit [this link to osm.org](http://www.openstreetmap.org/relation/1395820?mlat=48.8873&mlon=9.1928#map=9/48.8873/9.1925), where you'll see the relation 1395820, which is responsible for this bug and a marker showing the location of the label for this relation in zoomlevels 10 and 11.

For a detailed description, please see the [original issue](https://github.com/gravitystorm/openstreetmap-carto#1133).

Edit: I'd like to note, that this bug did not occur when I set up osm-carto locally with a Geofabrik-extract. It seems to happen only with incremental updates like on the main OSM-tileserver.

**Comment by pnorman** [comment]
Cannot reproduce - if we get more information we can re-open it, but as it stands it's not actionable.
