### ISSUE TITLE
Add support for site relations

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/osm2pgsql#221]
It would be nice to have some kind of support for site relations so that they can be rendered. The current definition is very generic (allowing for relations consisting only in points or ways for example):
http://wiki.openstreetmap.org/wiki/Relations/Proposed/Site

Maybe the perimeter-object could be used to create a polygon (if present) and if no area is defined in the relation a convex hull could be calculated (or a node) and the relation tags added to it. This would not allow for nice polygon/outline rendering in most cases, but to label the area it would be sufficient.

**Comment by pnorman** [comment]
Not interested in supporting it in the C tag transforms. Lua should be able to do something with them - if there are specific osm2pgsql features missing in order for a Lua transform to make something sensible out of a site relation, they should have specific issues opened for them.
