### ISSUE TITLE
Memory leaks of C++ version (Windows-only?)

### ISSUE THREAD

**Issue by alex85k** [openstreetmap/osm2pgsql#228]
Some out-of-memory problems of C++-switched Windows build were exposed https://github.com/openstreetmap/osm2pgsql/issues/17#issuecomment-62354744

After adding opensource Visual Leaks Detector (no Valgrind available) to the project (``#include <vld.h>``),  I was able to catch multiple leaks. Will post the messages from log here and try to provide possible fixes in separate PRs.

**Comment by pnorman** [comment]
We were just down to non-critical leaks, and since then we're using std::string in the middle. Any new leaks can get their own issues.
