### ISSUE TITLE
Crash when updating with more than one thread

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/osm2pgsql#229]
Version current as of opening this issue.

Command line (updating a database imported with a very recent version of osm2pgsql)

/usr/local/bin/osm2pgsql -a --slim --number-process 4 -e15:15 --flat-nodes /fast1/osm2pgsql/node.cache --hstore -o /var/lib/mod_tile/dirty_tiles.24387 /var/lib/mod_tile/changes.osc.gz

Fails either with 

     dupplicate!

or with

    dupplicate!
    pure virtual method called
    terminate called without an active exception
    Aborted (core dumped)
 
Reducing --number-process to 1 allows the update to complete without errors.

**Comment by lonvia** [comment]
Just to be clear, #232 has not fixed that issue and I have no intention on tackling this one. Better if @kevinkreiser or @zerebubuth look into it, as they know more more about the new threading code.
