### ISSUE TITLE
64 bit ids do not work

### ISSUE THREAD

**Issue by 4x4falcon** [openstreetmap/osm2pgsql#23]
I'm trying to create a nominatim server and attempting to load osm file using osm2pgsql gives segfault as soon as it gets to a 64bit id.

You can get a copy of the small (~15k) datafile from http://www.4x4falcon.com/osm_data/node_0002.osm which shows the problem.

The version of osm2pgsql I'm using is the latest (1 May 2013) from git.

The problem appears to be in the function ram_cache_nodes_set_dense in file node-ram-cache.c

Command to load using nominatim is

./utils/setup.php --osm-file node_0002.osm --all

which then uses osm2pgsql with the following command

./osm2pgsql -lsc -O gazetteer --hstore -C 4250 -d nominatim node_0002.osm

Even if i enter the osm2pgsql command directly osm2pgsql still segfaults.

Running on ubuntu 12.04 lts

Cheers
Ross

**Comment by rakeshsukla53** [comment]
@lonvia  @4x4falcon @lonvia  I am sorry for tagging you all but I am running into the exact same error and not able to resolve it. I initially tried this by reducing the cache size to 512MB and then 256MB but it is the returning the same error. 

Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping
NOTICE:  type "keyvalue" does not exist, skipping
NOTICE:  type "wordscore" does not exist, skipping
NOTICE:  type "stringlanguagetype" does not exist, skipping
NOTICE:  type "keyvaluetype" does not exist, skipping
NOTICE:  function get_connected_ways(pg_catalog.int4[]) does not exist, skipping
Allocating memory for dense node cache
Out of memory for node cache dense index, try using "--cache-strategy sparse" instead
Error occurred, cleaning up
ERROR: Error executing external command: /home/nominatim/Nominatim/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore -C 2048 -P 5432 -d nominatim /home/nominatim/data/latest.osm.pbf 

and then I tried to use --cache-strategy sparse as you can see below but it is not working 

    ~/Nominatim/utils/setup.php   --osm-file data/latest.osm.pbf   --all --osm2pgsql --cache-strategy sparse 

I think I don't know how to use cache strategy sparse and I will really appreciate any help you can provide. I have also attached the error screenshot
![capture8](https://cloud.githubusercontent.com/assets/9192661/9230140/ad39286c-40ee-11e5-81e7-d7ff732976b7.JPG)

**Comment by pnorman** [comment]
> @lonvia @4x4falcon @lonvia I am sorry for tagging you all but I am running into the exact same error and not able to resolve it. I initially tried this by reducing the cache size to 512MB and then 256MB but it is the returning the same error.

This issue is about using a custom OSM file with extra-large IDs. If you're using normal unmodified OSM data, you are encountering a different issue, so should open a new ticket.
