### ISSUE TITLE
osm2pgsql 0.87.0 fails to build on some architectures due to incorrect Boost linking

### ISSUE THREAD

**Issue by sebastic** [openstreetmap/osm2pgsql#231]
The C++ rewrite using Boost fails to build on some architectures with the following error:
```
libtool: link: g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-z -Wl,relro -o nodecachefilereader node-persistent-cache-reader.o -pthread  ./.libs/libosm2pgsql.a -L/usr/lib -lz -L/usr/lib/aarch64-linux-gnu -lpq -lxml2 -lbz2 -lgeos-3.4.2 /usr/lib/libproj.so -lprotobuf-c -L/usr/lib/x86_64-linux-gnu -llua5.2 -lm -ldl -lboost_filesystem -lboost_system -lboost_thread -lstdc++ -pthread
./.libs/libosm2pgsql.a(osmdata.o): In function `scoped_lock':
/usr/include/boost/atomic/detail/lockpool.hpp:62: undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
/usr/include/boost/atomic/detail/lockpool.hpp:62: undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
/usr/include/boost/atomic/detail/lockpool.hpp:62: undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
/usr/include/boost/atomic/detail/lockpool.hpp:62: undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
/usr/include/boost/atomic/detail/lockpool.hpp:62: undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
./.libs/libosm2pgsql.a(osmdata.o):/usr/include/boost/atomic/detail/lockpool.hpp:62: more undefined references to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)' follow
collect2: error: ld returned 1 exit status
```
Build logs: [arm64](https://buildd.debian.org/status/fetch.php?pkg=osm2pgsql&arch=arm64&ver=0.87.0-1~exp1&stamp=1418281978), [armel](https://buildd.debian.org/status/fetch.php?pkg=osm2pgsql&arch=armel&ver=0.87.0-1~exp1&stamp=1418310296), [powerpc](https://buildd.debian.org/status/fetch.php?pkg=osm2pgsql&arch=powerpc&ver=0.87.0-1~exp1&stamp=1418281501), [ppc64el](https://buildd.debian.org/status/fetch.php?pkg=osm2pgsql&arch=ppc64el&ver=0.87.0-1~exp1&stamp=1418281775), [s390x](https://buildd.debian.org/status/fetch.php?pkg=osm2pgsql&arch=s390x&ver=0.87.0-1~exp1&stamp=1418281760)

There was an issue in Boost 1.54 with the linking of libboost_atomic which has been fixed in the mean time. This issue was reported in [Debian Bug #721544](https://bugs.debian.org/721544) & [Debian Bug #721577](https://bugs.debian.org/721577), and upstream in [Boost Issue #9041](https://svn.boost.org/trac/boost/ticket/9041), and it was fixed in Boost 1.55 which is used on all architectures where osm2pgsql fails to build.

I'm not sure what the proper fix for osm2pgsql is. Please advise how to best help resolve this issue.

**Comment by pnorman** [comment]
Everything is working now.

@sebastic I suggest you use the new ``--without-lockfree`` option for `./configure` as it eliminates the need for the patch.

**Comment by nullr0ute** [comment]
Seeing the issue in Fedora too, what reduction in functionality occurs with the --without-lockfree option?

**Comment by pnorman** [comment]
No functionality change.

The pending ways list can either be a std::queue or a boost::lockfree::queue. The lockfree queue is faster. #196 is tracking fixing what --without-lockfree works around - if you have thoughts, I'd welcome them!

**Comment by sebastic** [comment]
> I suggest you use the new --without-lockfree option for ./configure as it eliminates the need for the patch.

I've dropped the patch and switched to use the --without-lockfree configure option in the Debian package for 0.87.2, the builds on the various architectures look good.

**Comment by pnorman** [comment]
I should note that `--without-lockfree` is slower so if possible should be avoided.

**Comment by sebastic** [comment]
I could make the use of `--without-lockfree` conditional, and only use it on the many problematic architectures.

Per architectures differences are not desirable, but if the performance impact is large enough it may make sense to not use it on all architectures. The option is not required for successfull builds on amd64, i386 & x32, which are the architectures most likely to see actual usage of osm2pgsql.

**Comment by lonvia** [comment]
We should be linking against `libboost_atomic`, either unconditionally or conditionally as described in https://svn.boost.org/trac/boost/ticket/9041.

**Comment by lonvia** [comment]
I had some further look into that. This is not a problem of an indirect dependency. boost_atomic is directly used in osmdata.cpp in the lockfree version, so we absolutely must link against it for `--with-lockfree`. It only worked on some architectures because where hardware support is available atomic is effectively a header-only library.

**Comment by pnorman** [comment]
I had a go at this, but can't work my way through the autoconf logic to figure out this.

**Comment by lonvia** [comment]
I had the same problem. The atomic is only needed for the object counter. How about using the C++11 atomic functions instead of boost atomic? We can still make it optional and use the mutex implementation where C++11 is not available.

**Comment by pnorman** [comment]
It tells you something of autoconf when we consider a code change instead of linking to a library whenever the lockfree implementation is used...

But I'd be okay with that. We might have to think about test coverage, but we need to look at this anyways for C++11

**Comment by lonvia** [comment]
Turns out that the lockfree queue is pulling undefined references as well. Boost dependencies are really no fun. I can hack something into autoconf that will work on Debian/Ubuntu. I just can't guarantee that it works on any other system.
