### ISSUE TITLE
Flat nodes test disk space usage

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#238]
Currently the flat nodes tests use >20GB of space to run. This comes from using an extract for testing them, with sparse node IDs while flat-node disk usage is based on max(node id).

This is not desirable for testing as it makes using VMs difficult.

**Comment by pnorman** [comment]
http://svn.openstreetmap.org/applications/utils/filter/osm-renumber/osm-renumber.pl may be useful here

**Comment by lonvia** [comment]
Fixed in ade9d4dc182238824a8289172d83b70b0c3ea54d.
