### ISSUE TITLE
Can't import latest planet.pbf

### ISSUE THREAD

**Issue by cblervacques** [openstreetmap/osm2pgsql#241]
Hi,

I try to import the entire latest planet in PostgreSQL database with osm2pgsql but I do not succeed
I first tried to import without the "-u" for the convertion of the old data in UTF-8.

But there's an error:
> Osm2pgsql failed due to ERROR: result COPY_END for planet_osm_line failed: ERROR:  invalid byte sequence for encoding "UTF8": 0xb0
> CONTEXT:  COPY planet_osm_line, line 83590925

So I tried with the "-u" with no more success ...

__File :__
`planet-141203.osm.pbf `

__osm2pgsql :__ 
`osm2pgsql SVN version 0.87.0 (64bit id space)`

__Cmd :__
`osm2pgsql -c -d $db_name -P $db_port -U $db_user --slim -C 8000 -u -l -k -z -K --number processes 6 --flat-nodes $flat_nodes_path $planet_path`

__Result :__
> osm2pgsql SVN version 0.87.0 (64bit id space)
> 
> Using built-in tag processing pipeline
> Using projection SRS 4326 (Latlong)
> Setting up table: planet_osm_point
> Setting up table: planet_osm_line
> Setting up table: planet_osm_polygon
> Setting up table: planet_osm_roads
> Allocating memory for dense node cache
> Allocating dense node cache in one big chunk
> Allocating memory for sparse node cache
> Sharing dense sparse
> Node-cache: cache=8000MB, maxblocks=1024000*8192, allocation method=11
> Mid: loading persistent node cache from /flat_nodes
> Allocated space for persistent node cache file
> Maximum node in persistent node cache: 0
> Mid: pgsql, scale=10000000 cache=8000
> Setting up table: planet_osm_nodes
> Setting up table: planet_osm_ways
> Setting up table: planet_osm_rels
> 
> Reading in file: /planet-141203.osm.pbf
> Processing: Node(2631697k 730.4k/s) Way(262849k 1.28k/s) Relation(0 0.00/s)Maximum node in persistent node cache: 3217031167
> node cache: stored: 992702445(37.72%), storage efficiency: 94.67% (dense blocks: 925605, sparse nodes: 50378307), hit rate: 29.35%
> Osm2pgsql failed due to ERROR: result COPY_END for planet_osm_line failed: ERROR:  invalid byte sequence for encoding "UTF8": 0xb0
> CONTEXT:  COPY planet_osm_line, line 83590925

Do you know why this error occurs ?
Can you help me to import the planet, please ?

Thanks in advance :-)
Charly Blervacques.

**Comment by cblervacques** [comment]
Hi, (and happy new year ! :-D)

osm2pgsql process is now terminated but i can't determinate if is successfull or not !
I thinks it's OK i can see world map in qGIS.

You can see the result : 

> osm2pgsql SVN version 0.87.1 (64bit id space)
> 
> Using built-in tag processing pipeline
> Using projection SRS 4326 (Latlong)
> Setting up table: planet_osm_point
> Setting up table: planet_osm_line
> Setting up table: planet_osm_polygon
> Setting up table: planet_osm_roads
> Allocating memory for dense node cache
> Allocating dense node cache in one big chunk
> Allocating memory for sparse node cache
> Sharing dense sparse
> Node-cache: cache=8000MB, maxblocks=1024000*8192, allocation method=11
> Mid: loading persistent node cache from /corto/corto/osm/flat_nodes
> Allocated space for persistent node cache file
> Maximum node in persistent node cache: 0
> Mid: pgsql, scale=10000000 cache=8000
> Setting up table: planet_osm_nodes
> Setting up table: planet_osm_ways
> Setting up table: planet_osm_rels
> 
> Reading in file: /corto/corto/osm/planet-141203.osm.pbf
> Processing: Node(2631697k 735.5k/s) Way(262849k 1.31k/s) Relation(2964140 10.74/s)  parse time: 480549s
> Node stats: total(2631697063), max(3216785266) in 3578s
> Way stats: total(262849583), max(315552715) in 200890s
> Relation stats: total(2964140), max(4245760) in 276081s
> Committing transaction for planet_osm_point
> Committing transaction for planet_osm_line
> Committing transaction for planet_osm_polygon
> Committing transaction for planet_osm_roads
> Setting up table: planet_osm_nodes
> Setting up table: planet_osm_ways
> Setting up table: planet_osm_rels
> Using built-in tag processing pipeline
> Setting up table: planet_osm_nodes
> Setting up table: planet_osm_ways
> Setting up table: planet_osm_rels
> Using built-in tag processing pipeline
> Setting up table: planet_osm_nodes
> Setting up table: planet_osm_ways
> Setting up table: planet_osm_rels
> Using built-in tag processing pipeline
> Setting up table: planet_osm_nodes
> Setting up table: planet_osm_ways
> Setting up table: planet_osm_rels
> Using built-in tag processing pipeline
> Setting up table: planet_osm_nodes
> Setting up table: planet_osm_ways
> Setting up table: planet_osm_rels
> Using built-in tag processing pipeline
> Setting up table: planet_osm_nodes
> Setting up table: planet_osm_ways
> Setting up table: planet_osm_rels
> Using built-in tag processing pipeline
> Mid: loading persistent node cache from /corto/corto/osm/flat_nodes
> Maximum node in persistent node cache: 3217031167
> 
> Going over pending ways...
>   170332901 ways are pending
> 
> Using 6 helper-processes
> bufferOriginalPrecision failed (TopologyException: assigned depths do not match at 10.8024 55.3099), trying with reduced precision
> recomputing with precision scale factor = 1e+11
> Scaler: offsetX,Y: 0,0 scaleFactor: 1e+11
> ReScaler: offsetX,Y: 0,0 scaleFactor: 1e+11
> bufferOriginalPrecision failed (TopologyException: depth mismatch at  at -0.667899 52.2555), trying with reduced precision
> recomputing with precision scale factor = 1e+10
> Scaler: offsetX,Y: 0,0 scaleFactor: 1e+10
> ReScaler: offsetX,Y: 0,0 scaleFactor: 1e+10
> bufferOriginalPrecision failed (TopologyException: assigned depths do not match at 18.9119 50.1692), trying with reduced precision
> recomputing with precision scale factor = 1e+14
> Scaler: offsetX,Y: 0,0 scaleFactor: 1e+14
> ReScaler: offsetX,Y: 0,0 scaleFactor: 1e+14


At the end, is this a normal result with success ? (Very all nodes ,ways and relation are imported into pgsql ?)

**Comment by pnorman** [comment]
What geos version?

**Comment by lonvia** [comment]
libgeos is a library used by osm2pgsql to compute the geometries. There are some versions around that have a bug, which causes the TopologyExceptions you see. (Although I'm starting to wonder if we are running into a problem here with libgeos also not being thread safe or something.)  Is that the last line of output you get? Then osm2pgsql failed half way through, although with a different error this time. On what system are you running this?

**Comment by pnorman** [comment]
On most linux systems, `geos-config --version` will tell you the geos version.

**Comment by pnorman** [comment]
> Although I'm starting to wonder if we are running into a problem here with libgeos also not being thread safe or something

I doubt that - I've not run into geos errors on my extensive benchmarking with -j8 on a machine with a recent geos version, and other people have it repeatably.

**Comment by cblervacques** [comment]
I'm running osm2pgsql on Ubuntu 12.04.4 LTS (GNU/Linux 3.2.0-67-generic x86_64) with geos version 3.2.2.
And yes this is the full result I get until the last line..

You think it's because of the version of libgeos ?

**Comment by pnorman** [comment]
Closing. There are multiple issues mixed up here, it's not clear that there are any remaining issues, there's not enough information to debug, and geos 3.2.2 is pretty old.
