### ISSUE TITLE
o5m import throws an exception

### ISSUE THREAD

**Issue by TobWen** [openstreetmap/osm2pgsql#244]
When using the o5m reader inside of osm2pgsql SVN version 0.87.1 (64bit id space) on Debian 7 Wheezy, this warning gets shown immediately:

`osm2pgsql Warning: unknown .o5m dataset id: 0xdb`

Seems like the o5m format got updated, but the reader wasn't.

**Comment by pnorman** [comment]
I doubt this issue was ever as described, but the message is gone with #497
