### ISSUE TITLE
middle-pgsql fails to escape special characters

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#247]
The function that escapes tag values, [escape_tag() in pgsql_middle](https://github.com/openstreetmap/osm2pgsql/blob/master/middle-pgsql.cpp#L144), escapes '\n', '\r' and '\t' to 'n', 'r' and 't'. That doesn't look right. It isn't clear from the code if the intention was to write the special character into the database or a slash and a letter.

To reproduce load http://www.openstreetmap.org/api/0.6/node/30029830 into the database. I'll provide a test shortly.

**Comment by pnorman** [comment]
When I was looking at this part of the code I as wondering if we should really be writing our own escaping code or if we could use something from libpq or prepared statements

**Comment by lonvia** [comment]
That escape code certainly isn't pretty, in particular, as it is repeated three times throughout the code. Prepared statements are not really an alternative as much of it is about escaping strings for copy mode. The libpq escaping seems to want to do its own memory allocation. That sounds expensive. Also, we might want to switch to C++ bindings first.

**Comment by pnorman** [comment]
> Prepared statements are not really an alternative as much of it is about escaping strings for copy mode

Oh ya - that excludes prepared, and [`COPY` is far faster](http://www.postgresql.org/docs/9.3/static/populate.html#POPULATE-COPY-FROM).

> switch to C++ bindings first

Do you mean something like like libpqxx?

**Comment by lonvia** [comment]
Yes, I had libpqxx in mind. Documentation states that it just wraps libpq, I wonder if that is true for the escape functions as well.

**Comment by pnorman** [comment]
I used libpqxx with cgimap, I'm not sure it's a great option. Several PostgreSQL people recommended just using libpq. @zerebubuth, any thoughts?

**Comment by zerebubuth** [comment]
I think libpqxx is a really good library. There are some issues around the escaping there as well (IIRC it doesn't natively support hstore, we'd have to add that), and I don't remember whether it allocates while escaping as well...

As for `escape_tag()` - I can't immediately see the problem with it. It seems to add one (or two, if `escape` is set - but I have no idea when that would be set) backslash in front of ", \, \n, \r, \t - which seems to be what the [documentation](http://www.postgresql.org/docs/9.2/static/sql-copy.html#AEN66683) is asking for...

**Comment by lonvia** [comment]
`escape` is set to 1 when `escape_tag()` is used for escaping stuff for copy mode and set to 0 when escaping for an `INSERT` statement. These are all escapes for array lists. Oddly enough, there is code [here](https://github.com/openstreetmap/osm2pgsql/blob/master/middle-pgsql.cpp#L251) that decodes slash + character into the special characters when reading from the database. It is all rather confusing.

**Comment by joto** [comment]
The `escape_tag()` function is long gone. Closing here.
