### ISSUE TITLE
make install overwrites customized default.style

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/osm2pgsql#249]
make install silently overwrites (a potentially customized) default.style config

Either it should only install a default.style.sample or similar, or at least make a backup of the original file if present.

**Comment by pnorman** [comment]
I'm not sure - the default osm2pgsql .style is that file, and is installed the same way the binaries are.

**Comment by simonpoole** [comment]
yes but it is a config file that is potentially modified contrary to the binaries were updating is exactly what you would want

**Comment by zerebubuth** [comment]
It seems like `make install` always does this - I can't find any options to make it either backup existing files or not overwrite those files. I think such policies with packages must be implemented at the package manager level. (Frustratingly, GNU install _does_ support making backups, but for compatibility reasons it's not exposed via autotools' `install-sh`)

So it seems like we have the following options:
1. Don't install any config files, but install a `style.conf.example

**Comment by lonvia** [comment]
It's really difficult to get this right as long as osm2pgsql cannot determine if the copy has been modified. In any case, I would consider it bad style to overwrite data files from an application installation.

@pnorman Any objections to close as 'won't fix'?

**Comment by pnorman** [comment]
> @pnorman Any objections to close as 'won't fix'?

No objections.

It's in `/usr/share` on my system, and unlike `/etc`, it's a place that is not intended for user modification. 

> Any program or package which contains or requires data that doesn't need to be modified should store that data in /usr/share

Overwriting default.style is the same as overwriting /usr/bin/osm2pgsql - an expected consequence of installing.
