### ISSUE TITLE
Missing some roads when importing

### ISSUE THREAD

**Issue by nanolab** [openstreetmap/osm2pgsql#253]
I'm importing this file http://download.geofabrik.de/europe/ukraine-latest.osm.pbf:

    osm2pgsql -l -d gpx -U ra -W -H localhost -C 1024 --hstore --cache-strategy sparse --slim ukraine-latest.osm.pbf

osm2pgsql SVN version 0.87.2-dev (64bit id space)

This query

    SELECT * FROM planet_osm_ways WHERE id = 23697167

returns 1 string:

    23697167;"{262266618,1762256438,256593967}";"{name:ru,"Матросова улица",name:en,"Matrosova Street",name,"Матросова вулиця",highway,residential}"

So it's imported correctly. But

    SELECT * FROM planet_osm_roads WHERE osm_id = 23697167
    SELECT * FROM planet_osm_polygon WHERE osm_id = 23697167

returns nothing.

This way exists in .osm version too:
```
	<way id="23697167" version="13" timestamp="2012-11-01T19:19:46Z" changeset="13714624" uid="495642" user="agb2">
		<nd ref="262266618"/>
		<nd ref="1762256438"/>
		<nd ref="256593967"/>
		<tag k="highway" v="residential"/>
		<tag k="name" v="Матросова вулиця"/>
		<tag k="name:en" v="Matrosova Street"/>
		<tag k="name:ru" v="Матросова улица"/>
	</way>
```

This way (23697167) is a part of relation:
```
	<relation id="2391944" version="6" timestamp="2013-09-20T12:58:58Z" changeset="17939782" uid="356014" user="_sev">
		<member type="way" ref="23697167" role="street"/>
		<member type="way" ref="188659428" role="street"/>
		<member type="way" ref="177154126" role="house"/>
		<member type="way" ref="177155315" role="house"/>
		<member type="way" ref="177156558" role="house"/>
		<member type="way" ref="90261595" role="house"/>
		<member type="way" ref="90261617" role="house"/>
		<member type="way" ref="90261623" role="house"/>
		<member type="way" ref="90261635" role="house"/>
		<member type="way" ref="90261662" role="house"/>
		<member type="way" ref="90261664" role="house"/>
		<member type="way" ref="90261672" role="house"/>
		<member type="way" ref="90261677" role="house"/>
		<member type="way" ref="90261697" role="house"/>
		<member type="way" ref="90261709" role="house"/>
		<member type="way" ref="90261713" role="house"/>
		<member type="way" ref="90261741" role="house"/>
		<member type="way" ref="90261747" role="house"/>
		<member type="way" ref="90261774" role="house"/>
		<member type="way" ref="181731710" role="house"/>
		<member type="way" ref="181731903" role="house"/>
		<member type="way" ref="181731961" role="house"/>
		<member type="way" ref="181731976" role="house"/>
		<member type="way" ref="181782525" role="house"/>
		<member type="way" ref="181782526" role="house"/>
		<member type="way" ref="181782528" role="house"/>
		<tag k="name" v="Матросова вулиця"/>
		<tag k="street:id" v="208"/>
		<tag k="type" v="associatedStreet"/>
	</relation>
```
But this relation does not exists in planet_osm_roads or planet_osm_polygon  tables (but exists in planet_osm_rels).

**Comment by pnorman** [comment]
> So it's imported correctly. But
> 
>     SELECT * FROM planet_osm_roads WHERE osm_id = 23697167
>     SELECT * FROM planet_osm_polygon WHERE osm_id = 23697167
> returns nothing.

This is expected. It's not a polygon, nor does it have tags that would put it in the roads table.

You should find it in planet_osm_line.

> (associatedStreet relation)
> But this relation does not exists in planet_osm_roads or planet_osm_polygon tables (but exists in planet_osm_rels).

Associated street relations are not present in the rendering tables.

**Comment by nanolab** [comment]
> You should find it in planet_osm_line.

Found it. Thank you!
