### ISSUE TITLE
Unable to open data.osm.pbf

### ISSUE THREAD

**Issue by Allen3** [openstreetmap/osm2pgsql#258]
When I try to load the data into `gis` and run 
`osm2pgsql --create --database gis data.osm.pbf`
I got the following prompted information:

----

    osm2pgsql SVN version 0.87.2-dev (64bit id space)

    Using built-in tag processing pipeline
    Using projection SRS 900913 (Spherical Mercator)
    Setting up table: planet_osm_point
    Setting up table: planet_osm_line
    Setting up table: planet_osm_polygon
    Setting up table: planet_osm_roads
    Allocating memory for dense node cache
    Allocating dense node cache in one big chunk
    Allocating memory for sparse node cache
    Sharing dense sparse
    Node-cache: cache=800MB, maxblocks=102400*8192, allocation method=3
    Mid: Ram, scale=100

    Reading in file: data.osm.pbf
    Unable to open data.osm.pbf
    Error occurred, cleaning up

----

So what should I do?

**Comment by Allen3** [comment]
As this error occured, I couldn't get the tables referred above.

**Comment by pnorman** [comment]
Does data.osm.pbf check out with md5sum?

Can you try with tests/liechtenstein-2013-08-03.osm.pbf
If that doesn't work, try with tests/liechtenstein-2013-08-03.osm.bz2. If the bzip2 works but the PBF doesn't, are you sure you built it with pbf support?

**Comment by pnorman** [comment]
User has not replied and this cannot be resolved without more information.

**Comment by narcissic** [comment]
I have the same issue. Can you please help with this one?
The same error for me as the example adobe. I tried what you suggested (if I got it right). And what I got:

trying on tests/liechtenstein-2013-08-03.osm.pbf the result was: 
Reading in file: tests/liechtenstein-2013-08-03.osm.pbf
Unable to open tests/liechtenstein-2013-08-03.osm.pbf
Error occurred, cleaning up

trying on tests/liechtenstein-2013-08-03.osm.bz2 the result was:
Reading in file: tests/liechtenstein-2013-08-03.osm.bz2
error while opening file tests/liechtenstein-2013-08-03.osm.bz2
