### ISSUE TITLE
Similar tables do not function the same with multi-backend

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#267]
cc @kevinkreiser 

if I define

``` json
  {
    "name": "osm_address_number_point",
    "type": "point",
    "tagtransform": "address_number.lua",
    "tagtransform-node-function": "address_nodes",
    "tagtransform-way-function": "drop_all",
    "tagtransform-relation-function": "drop_all",
    "tagtransform-relation-member-function": "drop_all",
    "tags": [
      {"name": "housenumber", "type": "text"}
    ]
  },
  {
    "name": "bar",
    "type": "point",
    "tagtransform": "address_number.lua",
    "tagtransform-node-function": "address_nodes",
    "tagtransform-way-function": "drop_all",
    "tagtransform-relation-function": "drop_all",
    "tagtransform-relation-member-function": "drop_all",
    "tags": [
      {"name": "housenumber", "type": "text"}
    ]
  }
```

where address_nodes is a function that returns `0, {housenumber = something}` for nodes with `addr:housenumber` I get surprising results

```
gis=# select count(*) from osm_address_number_point;
 count
-------
 81639
(1 row)

gis=# select count(*) from bar;
 count
-------
     0
(1 row)
```

If I reverse the two definitions in the JSON, which gets the rows also reverses.

I tried duplicating address_number and renaming the functions but it didn't help.

It looks like I can't add the same point twice into different tables?

**Comment by kevinkreiser** [comment]
Cool I can have a look seems (off the top of my head) that it can't be that hard to fix

**Comment by pnorman** [comment]
So, I hit this from a different route. It looks like it happens whenever there are two polygon tables, even if they're based on completely different tags. If this is so, it would explain why it isn't hit with the pgsql backend and Lua transforms - they can't have two tables of the same type.

I put a debugging statement into the way function of the second transform, and it was being called.

I'll have to reduce this into a testcase.

**Comment by pnorman** [comment]
I tried reproducing with points and was unable to - either my testcase was too simple, or this bug doesn't occur with points.

https://gist.github.com/pnorman/36e98bc3d43350e29acc is the test that does not reproduce this issue

**Comment by lonvia** [comment]
All output processors assume that they are the only users of the keyval struct containing the tags and modify these lists in-place. My guess of what happens here: your second table just sees the modified tag list from the first table which only contains a housenumber tag and no addr:housenumber tag and drops the item.

Yet another strong point for rewriting keyvals as std::vector.

**Comment by pnorman** [comment]
> Yet another strong point for rewriting keyvals as std::vector.

Do you think `std::vector<std::pair<std::string, std::string>>` or `std::map<std::string, std::string>`?

On C++11 I'd suggest std::unordered_map, but we're not there yet

**Comment by lonvia** [comment]
I'm thinking:

~~~
  struct tag {
    std::string key;
    std::string value;
};

std::vector<tag>
~~~

I'm not a fan of `std::pair`s because the first/second accessors make the code hard to read. Also, a simple struct is much more lightwight. It would probably also be a good idea to wrap the tag list in its own type and add a couple of convenience functions (e.g. get by key).

**Comment by pnorman** [comment]
This is fixed.
