### ISSUE TITLE
Delete undesired tags with Lua transform

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#268]
The C tag transform can drop tags like created_by, odbl, note, source, tiger:\* and others specified in the style file. The sample Lua transform, style.lua, should do the same.

The following Lua might be helpful

``` lua
delete_tags = {'INT-*', 'note', 'note:*', 'source', 'source_ref', 'source:*',
               'attribution', 'comment', 'fixme', 'created_by', 'odbl',
               'odbl:note', 'SK53_bulk:load', 'tiger:*', 'NHD:*', 'nhd:*',
               'gnis:*', 'geobase:*', 'accuracy:meters', 'sub_sea:type',
               'waterway:type', 'KSJ2:*', 'yh:*', 'osak:*', 'kms:*', 'ngbe:*',
               'naptan:*', 'CLC:*', '3dshapes:ggmodelk', 'AND_nosr_r',
               'import', 'it:fvg:*'}
function preprocess_tags (kv)
  tags = {}
  for k, v in pairs (kv) do
    match = false
    for _, d in ipairs(delete_tags) do
      match = match or string.find(k, d)
    end
    if not match then
      tags[k] = v
    end
  end
end
```

It takes num tags \* num deletes iterations through the loop, but does short-circuit the string.find call if it's already matched a delete.

**Comment by lonvia** [comment]
Isn't that done  [here](https://github.com/openstreetmap/osm2pgsql/blob/master/style.lua#L55) already?

**Comment by pnorman** [comment]
> Isn't that done [here](https://github.com/openstreetmap/osm2pgsql/blob/master/style.lua#L55) already?

Ah, I had missed that.

Kind of - there are two differences from the C transforms. The first is it uses a different list, which is easily fixed. The second is that the method used (setting specific keys to nil) doesn't work for wildcards.

**Comment by lonvia** [comment]
Indeed, I overlooked those wildcards. I always wonder if we shouldn't compile a huge reqex for such a case. Anyways, as you have only two cases, fullmatch and startswith, I'd probably split that in two steps, first deleting the full matches as done in the current style and then check for a match as the beginning with the double loop (although with an early `break` as soon as a match is found). But that might all be overoptimising, it might not really matter because the lua execution is insignificant compared to everything else that happens.

**Comment by pnorman** [comment]
> it might not really matter because the lua execution is insignificant compared to everything else that happens

yes - provided you don't go the tag delete code for untagged nodes.

My code snippet doesn't quite work - I screwed up the patterns.

**Comment by joto** [comment]
This is outdated, we will not do any larger changes on the pgsql output. The flex output has provisions for dropping tags.
