### ISSUE TITLE
Import quits with "double free or corruption (!prev)"

### ISSUE THREAD

**Issue by thejeed** [openstreetmap/osm2pgsql#269]
I've tried to import the planet.osm of last week and it finally quit with this message:
*** Error in `osm2pgsql': double free or corruption (!prev): 0x00007f1b4c000030 ***
I'm thankful for any advice or a fix.

Environment:
Ubuntu 14.04.1 LTS 64 bit Server
32 GB RAM
2 TB Harddisk
PostgreSQL 9.3

Command line:
nohup osm2pgsql --slim -U mapcreateuser --create --hstore --flat-nodes /opt/flatnodes/flatnodes.bin -d osm -C 15000 --number-processes 4  --style /opt/osm2pgsql/openstreetmap-carto/openstreetmap-carto.style /opt/planet-150119.osm >/tmp/osm.err 2>/tmp/osm.log < /dev/null &

And finally, the output:
```
osm2pgsql SVN version 0.87.2-dev (64bit id space)

Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=15000MB, maxblocks=1920000*8192, allocation method=11
Mid: loading persistent node cache from /opt/flatnodes/flatnodes-24-01-2015.bin
Allocated space for persistent node cache file
Maximum node in persistent node cache: 0
Mid: pgsql, scale=100 cache=15000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /opt/planet-150119.osm

Node stats: total(2693780701), max(3297900166) in 10042s
Way stats: total(269387902), max(322984938) in 64219s
Relation stats: total(3073468), max(4499077) in 159277s
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline
Mid: loading persistent node cache from /opt/flatnodes/flatnodes-24-01-2015.bin
Maximum node in persistent node cache: 3298820095

Going over pending ways...
        174500965 ways are pending

Using 4 helper-processes
*** Error in `osm2pgsql': double free or corruption (!prev): 0x00007f1b4c000030 ***

```

**Comment by pnorman** [comment]
Is `/opt/planet-150119.osm` an uncompressed XML file? It *shouldn't* matter, but I've never tested a large XML file, as PBF is what is used for planet imports.

Once my current benchmarking is done, I can try to reproduce, but this is either random, or something oddly specific to your situation.

What exact version of osm2pgsql do you have (the git commit hash).

**Comment by thejeed** [comment]
Yes, it's an uncompressed XML file. Maybe don't do this effort - I'll try again with the PBF and if then something happens, I can write again.

Anyway, I guess this is the hash: ed86d635cb0e54252881c766ede90a532e63dca0

**Comment by lonvia** [comment]
I doubt that this is the correct hash. Your osm2pgsql has been running for 64 hours according to the log above and this commit is less than 10 hours old. Try with this latest git version, it is supposed to fix the double corruption.

**Comment by molind** [comment]
Saw the same crash. That's was bad surprise after 10h of data importing. Checking now on latest commit. (c23a65b7e)

**Comment by lonvia** [comment]
@molind @thejeed  Did the latest version fix the crash?
