### ISSUE TITLE
Excluding linestrings from polygon tables with multi backend

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#270]
If I write a multi-backend style with `"type": "polygon"` the table may still end up with linestrings in it.

As an example, an open way with `building=yes` (35497220 version 2) with building=house area=yes ended up in the building table from the sample multi-backend style.

The correct behavior is not obvious. With the standard style these objects would go in the line table.

**Comment by pnorman** [comment]
So, after thinking about it and writing some multi-backend transforms, I think unclosed ways that the transform indicates are an area should not make it into the polygon table.

With the pgsql backend, it's important as `waterway` is an area key and otherwise you'd never get rivers to the line table.

With a multi-backend, the idea of the same tagging leading to an object being a line or area based on geometry is not useful, as you can differentiate between `waterway=river` and `waterway=riverbank`

**Comment by lonvia** [comment]
So basically, your conclusion is that from the tagging it is always possible to figure out the expected geometry? That would be really good news for a potential transition to any future area type.

**Comment by pnorman** [comment]
> So basically, your conclusion is that from the tagging it is always possible to figure out the expected geometry?

In typical OSM fashion, this has four answers: no, maybe, yes, and it doesn't matter.

Some objects have contradictory tagging, such as `type=multipolygon` `area=no`. It's not possible to figure out the expected geometry, even if you know if the members are closed or not.

Leaving aside contradictory tagging, reproducing the current osm2pgsql behavior requires knowledge of if the way is closed or not. The multi-backend can't reproduce the pgsql backend, and still won't be able to with this change. But having `landuse=residential`, `power=line` or `power=sub_station`  be a linear feature or an area depending on closed or not is absolutely insane and we don't **want** to rely on that. So maybe.

I have yet to see any tagging in the wild that would be either a line or an area based on if its closed or not. If it's tagging that indicates an area and it's not closed, it's a tagging or geometry error. This matches mappers expectations, who often think of areas and lines of being different.

And lastly, for this specific bug, it doesn't matter, because in the context of a multi-backend, you are putting specific known features into tables, and you know if they're areas or not, and having non-areas in polygon tables violates your expectations.

**Comment by lonvia** [comment]
The 'yes' answer is the interesting one. If there was tagging where being closed is important to determine the kind of feature, I would have suggested to add 'closedness' as an input property to the tag transforms. But if OSM data is well behaved enough, just dropping bad geometries is enough.

**Comment by pnorman** [comment]
> I would have suggested to add 'closedness' as an input property to the tag transforms. But if OSM data is well behaved enough, just dropping bad geometries is enough

I did consider that, but think it's well behaved enough.

It would also change the Lua tagtransform API. Now, there are some reasonable reasons for breaking compatibility for the multi-backend such as the roads flag being meaningless.
