### ISSUE TITLE
osm_changeset not importing

### ISSUE THREAD

**Issue by lxbarth** [openstreetmap/osm2pgsql#271]
I'm trying to import osm_changeset and osm_version information into point, line and polygon tables.

- Expected behavior: populated `osm_changeset` column (just like `osm_version` column)
- Unexpected: `osm_changeset` column empty

## Details

My .style file contains (among others) the rules:

    node,way   osm_changeset       text  linear
    node,way   osm_version         text  linear

This is how I import data:

    curl -o $HOME/nyc.osm "http://www.overpass-api.de/api/xapi?map?bbox=-74.021416,40.697983,-73.932495,40.756263"
    osm2pgsql -c --extra-attributes --style changefeed.style -d osm --slim $HOME/nyc.osm

Here's how my resulting `planet_osm_polygon` table looks like:

    osm=> \d planet_osm_polygon
                 Table "public.planet_osm_polygon"
           Column       |           Type            | Modifiers 
    --------------------+---------------------------+-----------
     osm_id             | bigint                    | 
     addr:housenumber   | text                      | 
     addr:street        | text                      | 
     addr:full          | text                      | 
     addr:interpolation | text                      | 
     nyc:bin            | text                      | 
     building           | text                      | 
     osm_uid            | text                      | 
     osm_changeset      | text                      | 
     osm_version        | text                      | 
     way                | geometry(Geometry,900913) | 
    Indexes:
        "planet_osm_polygon_index" gist (way)
        "planet_osm_polygon_pkey" btree (osm_id)

The result is a populated version column while the changeset column is empty:

    osm=> select count(*)  from planet_osm_polygon where osm_version is not null;
     count 
    -------
     43717

    osm=> select count(*)  from planet_osm_polygon where osm_changeset is not null;
     count 
    -------
         0

**Comment by pnorman** [comment]
What version?

**Comment by lxbarth** [comment]
osm2pgsql --version
    osm2pgsql SVN version 0.82.0 (64bit id space)

**Comment by pnorman** [comment]
Update to a more recent version.

I was able to reproduce the bug on 0.82.0 and 0.84.0 but not 0.86.0, the latest release version, nor master. 0.87.1 the latest dev version doesn't compile on the box I was using, but I imagine it's the same.

Although not related to the bug, I notice that you're using `--slim`. If you're not using the slim tables elsewhere in your toolchain, you don't need `--slim` for an extract this small.

You may also be better off with
```
node,way   osm_changeset       integer  linear
node,way   osm_version         integer  linear
```
