### ISSUE TITLE
Update maps

### ISSUE THREAD

**Issue by rmoravcik1** [openstreetmap/osm2pgsql#276]
Hello All,

Please i need an advise regarding upgrading OSM maps.

Im runing tile/wms server with Installed:
  Centos 6.4
  Mapnik 2
  PostgreSQL 9.1
  Mapproxy 1.4.0

HW:
 Virtual machine - 8xCpu @ 2500MHz , 4GB ram and 6GB swap with 77GB free diskspace.

I need update at least one country, exactly Slovakia, but im not perfectly sure about this process how to achieve that.

I would try to download the latest osm.pbf file of country and load it into database with osm2pgsql this way:

osm2pgsql --slim -a -d dbname -C 1500 --number-processes 3 ./Slovakia-latest.osm.pbf

Will it works this way?

Thank you very much for answers in advance.
Richard

**Comment by pnorman** [comment]
http://switch2osm.org/loading-osm-data/ has a reasonable explanation of loading OSM data, both on a planet-wide scale and an extract.

It does not cover ``-drop``, which it probably should, but the [middle layer options documentation](https://github.com/openstreetmap/osm2pgsql/blob/master/docs/usage.md#middle-layer-options) covers that.

**Comment by rmoravcik1** [comment]
https://github.com/openstreetmap/osm2pgsql/blob/master/docs/usage.md#middle-layer-options

"A <i>--slim --drop</i> import is generally the fastest way to import the planet if updates are not required."

But i really <b>need</b> to do only update of containing database and tables :)

If the option <i>--create --slim --drop</> can recreate tables with fresh data i should be the best way.

Im asking so much because production application is using this map, so i dont want to mess it up totaly...

**Comment by lonvia** [comment]
Geofabrik now provides diffs for its updates which are suitable for updating databases created from extracts.
