### ISSUE TITLE
Splitting long lines is not projection-aware

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/osm2pgsql#277]
The splitting of long lines currently happens at one projected unit for EPSG:4326, and 100.000 projected units for all other projections. This can lead to undesirable results when using other projections than EPSG:4326 and EPSG:3857. See https://github.com/openstreetmap/osm2pgsql/blob/ed86d635cb0e54252881c766ede90a532e63dca0/output-pgsql.cpp#L125-L128

Solving this is probably not trivial since you cannot simply project an 1° long line into the target projection - the target projection might not even be defined everywhere on the planet. It might be best to simply request direct user input of the split length when using non-standard projections.

**Comment by pnorman** [comment]
> Solving this is probably not trivial since you cannot simply project an 1° long line into the target projection - the target projection might not even be defined everywhere on the planet. It might be best to simply request direct user input of the split length when using non-standard projections.

It would also be nice to be able to define the split arbitrarily anyways, and turn off splitting completely for analysis purposes.

**Comment by TobWen** [comment]
I'd really apprechiate a switch to define split arbitrarily or turn it off completely. Right now, I have to run some SQL magic to merge the parts together again :)

**Comment by Komzpa** [comment]
I would expect --multi-geometry to disable this logic: it produces one row for one object in polygons/relations, so I would expect it to do one row per object in lines.

**Comment by lonvia** [comment]
The new 'flex' output allows to set a custom split length and also to disable splitting completely. Please give it a try.
