### ISSUE TITLE
Remove fastupdate hack

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#281]
psql-middle has [here](https://github.com/openstreetmap/osm2pgsql/blob/master/middle-pgsql.cpp#L1246) a special hack to include `fastupdate=off` to array indexes for postgres versions 8.4 and larger. Considering that versions below 8.4 are not supported anyways, this string hack should be removed and `fastupdate=off` hardcoded into the CREATE INDEX command.

**Comment by pnorman** [comment]
related: #37, which is about finding a way to completely remove fastupdate
