### ISSUE TITLE
Set linear vs polygon on a per-tag basis

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/osm2pgsql#284]
Please add support for importing importing one tag as a polygon while other ways with that key but a different tag are still linestrings.

Cross-ref gravitystorm/openstreetmap-carto#1253

**Comment by pnorman** [comment]
So, there's three things you're asking. One is if what you want can be done in a Lua transform. The answer to that is yes. The other is to add the ability set linear vs polygon on a per-tag basis with the C tag transforms. The third is to use that ability and change the default.style. I'm editing your question to reflect the second.

**Comment by pnorman** [comment]
Given the additional complexity this would involve and the well supported state of Lua tag transforms, I don't think this is something we want to be adding to the C tag transforms.

**Comment by sommerluk** [comment]
@pnorman Okay, so Lua is the way that we should go.

If I understood @math1985 correctly in what he said at the end of gravitystorm/openstreetmap-carto#1253 and gravitystorm/openstreetmap-carto#1271 he proposes to start from style.lua and make there some changes.

Do you think this is something that can be done in osm2pgsql? If so, I would open a separate issue for this. Or do you think openstreetmap-carto must come with its own style.lua file?

**Comment by math1985** [comment]
> If I understood @math1985 correctly in what he said at the end of gravitystorm/openstreetmap-carto#1253 and gravitystorm/openstreetmap-carto#1271 he proposes to start from style.lua and make there some changes.

Yes, I proposed that based on @pnorman's suggestions.

I think it would be nice to have an example in the style.lua file on how to do per-key filtering. In fact, I think most of the things we want in openstreetmap-carto, like treating highway=services as area, apply to most users of osm2pgsql, so I think it would make sense to model things like that in the default style.lua.

**Comment by pnorman** [comment]
There is a bit of a tension in style.lua in being the default Lua transform,  a starting point for people to write transforms, and an example of what can be done. I'm not sure what this means for adding special cases like highway=services.

I do want to go and add some of what I've learned from writing the sample multi backend transform and apply it to style.lua.

**Comment by math1985** [comment]
> There is a bit of a tension in style.lua in being the default Lua transform, a starting point for people to write transforms, and an example of what can be done.

Yes, I agree the project should decide on the purpose of style.lua. However, I think in all of the three use cases, adding highway=services (or at least an example of a key based rule) would be useful.
