### ISSUE TITLE
Zlib compression failed (code -3, incorrect data check)

### ISSUE THREAD

**Issue by pirogovsky85** [openstreetmap/osm2pgsql#285]
Hi,
Server Ubuntu 14.04 LTS, 96Gb RAM, 12 cores.
Used install instructions from here: http://switch2osm.org/loading-osm-data/
When I try import planet data I got error Zlib compression failed (code -3, incorrect data check):

```
sudo -u postgres osm2pgsql -r pbf -sc -d gis -C 40000 --number-processes 12 --cache-strategy dense --flat-nodes nodes.flat planet-150202.osm.pbf
osm2pgsql SVN version 0.82.0 (64bit id space)

Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
NOTICE:  table "planet_osm_point" does not exist, skipping
NOTICE:  table "planet_osm_point_tmp" does not exist, skipping
Setting up table: planet_osm_line
NOTICE:  table "planet_osm_line" does not exist, skipping
NOTICE:  table "planet_osm_line_tmp" does not exist, skipping
Setting up table: planet_osm_polygon
NOTICE:  table "planet_osm_polygon" does not exist, skipping
NOTICE:  table "planet_osm_polygon_tmp" does not exist, skipping
Setting up table: planet_osm_roads
NOTICE:  table "planet_osm_roads" does not exist, skipping
NOTICE:  table "planet_osm_roads_tmp" does not exist, skipping
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Node-cache: cache=40000MB, maxblocks=5120001*8192, allocation method=10
Mid: loading persistent node cache from nodes.flat
Allocated space for persistent node cache file
Maximum node in persistent node cache: 0
Mid: pgsql, scale=100 cache=40000
Setting up table: planet_osm_nodes
NOTICE:  table "planet_osm_nodes" does not exist, skipping
Setting up table: planet_osm_ways
NOTICE:  table "planet_osm_ways" does not exist, skipping
Setting up table: planet_osm_rels
NOTICE:  table "planet_osm_rels" does not exist, skipping

Reading in file: planet-150202.osm.pbf
Processing: Node(64830k 1906.8k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Zlib compression failed (code -3, incorrect data check)
Error occurred, cleaning up
```

**Comment by pirogovsky85** [comment]
osm2pgsql SVN version 0.85.0 same problem.
Small files (I tried ukraine-latest.osm.pbf from geofabrik.de) imported fine.

**Comment by pnorman** [comment]
Does the planet-150202.osm.pbf report okay with md5sum?
If you follow http://switch2osm.org/loading-osm-data/ for importing, does it work?

**Comment by pnorman** [comment]
> osm2pgsql SVN version 0.82.0 (64bit id space)

I don't see how you got this version if you followed the instructions on http://switch2osm.org/loading-osm-data/ with the OS you specified.

**Comment by pirogovsky85** [comment]
About version osm2pgsql.
I used the version 0.85.0 as in http://switch2osm.org/loading-osm-data/, but got error. Then I removed package and repository. After installed default version (0.82.0), but error still left.

About md5sum:
md5sum -c planet-150202.osm.pbf.md5
planet-150202.osm.pbf: OK

I tried older PBF file, but got same error.

Yesterday I started importing from *.osm.bz2 file. Still work without error.

So I have problem with uncompressing of big PBF file (small on 200Mb imported fine), but I do not understand what I can fix. I already installed libprotobuf-c0-dev protobuf-c-compiler.

**Comment by pnorman** [comment]
I checked that planet file and it worked fine, but on a different version.

Could you reinstall the sysem and try the instructions at http://switch2osm.org/loading-osm-data/

**Comment by pirogovsky85** [comment]
Hi,
I reinstalled system. Same error.

**Comment by pnorman** [comment]
What command line did you use this time?

**Comment by pirogovsky85** [comment]
Seems I have problem with RAID on 3Tb.
I found that if read file from 3Tb disk using any application (osmconvert, osm2pgsql). After this read md5sum is not math, but before was ok.
Then I tried download planet file (~27Gb) to other disk (other part on 48Gb) and start osm2pgsql.
Data (PostgreSQL database) write to 3Tb disk.
Now I got error:
CREATE INDEX planet_osm_polygon_index ON planet_osm_polygon USING GIST (way);
 failed: ERROR:  compressed data is corrupt

So planet file from 48Gb disk read fine. I have problem with big 3Tb disk (RAID).
Thanks Paul from your help. You can close this issue.

**Comment by lygstate** [comment]
I do also have same problem, I have MD5 checked the pbf file, it's matched
```
Processing: Node(3467864k 1353.0k/s) Way(361033k 6.56k/s) Relation(1359500 50.52/s)Zlib compression failed (code -3, invalid distance too far back)
Error occurred, cleaning up
```
What's going on?
