### ISSUE TITLE
Move to modern geometry types

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#309]
osm2pgsql currently uses [`AddGeometryColumn`](http://postgis.net/docs/manual-2.1/AddGeometryColumn.html), `geometry_columns`, which are fragile and error-prone compared to modern type-based checking.

This would break PostGIS 1.5 compatibility. PostGIS 1.5 is end of life.

See https://github.com/openstreetmap/osm2pgsql/pull/279#issuecomment-77034639

**Comment by lonvia** [comment]
According to [the docs](http://postgis.net/docs/manual-2.1/AddGeometryColumn.html) AddGeometryColumn automatically does the right thing on PostGIS 2.0+ and adds modern geometry types. geometry_columns is just a view there. So I don't see what else we could gain from switching.

**Comment by pnorman** [comment]
We did this for everything but gazetteer, and it did simplify the code.

**Comment by lonvia** [comment]
No objection doing that with gazetteer as well. Nominatim now requires PostGis 2.0+
