### ISSUE TITLE
error while file opening

### ISSUE THREAD

**Issue by mitsol** [openstreetmap/osm2pgsql#313]
i use  version 0.87.3-dev (64bit id space) on ubuntu 14.04. When i start this command
osm2pgsql austria-latest.osm.pbf -c -U postgres -W mypass -H localhost

it starts parsing the file. At the end i get this:

Reading in file: austria-latest.osm.pbf
Processing: Node(39006k 1114.5k/s) Way(3987k 24.02k/s) Relation(74860 550.44/s)  parse time: 337s

Reading in file: mypass
error while opening file mypass

I don't know why it tries to open "mypass"-File here? - Anyway, i don't have any data in the database after this.

**Comment by pnorman** [comment]
`-W|--password` does not take a password, so you have specified two files to load on the command line.

Standard ways to authenticate to a server would be local sockets, [.pgpass](http://www.postgresql.org/docs/9.3/static/libpq-pgpass.html), and [SSL](http://www.postgresql.org/docs/9.3/static/ssl-tcp.html)
