### ISSUE TITLE
route_name tag

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#315]
A user on IRC was confused why names for route relations were not appearing in their osm2pgsql database. So was I, until I found 

[tagtransform.cpp:113](https://github.com/openstreetmap/osm2pgsql/blob/b81f2d992cf96aebe84e24eb57cbf4c483a3df5a/tagtransform.cpp#L113)
```cpp
if (is_route && (p->key == "name"))
  tags.addItem("route_name", p->value, true);
```

https://trac.openstreetmap.org/ticket/1703 is related, but I don't believe it is relevant anymore.

It may have been relevant if relying on catchalls with osm.xml, but isn't relevant to any recent stylesheet.

The lua transforms do not do this.

It is undocumented.

Should we still be doing this?

This does not impact openstreetmap-carto.

cc @Tommyf

**Comment by lonvia** [comment]
The special handling for routes is rather old. The original commit is [here](https://github.com/openstreetmap/osm2pgsql/commit/5645aef1aa5643baa1f40473d5c0fd04e08e3471) and was done for the cycle map, I believe. It was never used by the mapnik style. @gravitystorm should know more details.

I suspect that a lot of maps that handle route relations still rely on this code. If we want to phase this out, it has to be long term thing (with announcements on dev@ etc.) and we should provide a lua style that emulates the old behaviour. Personally, I'm more for just leaving the C transform as is with all it's quirks, concentrate on making the lua tagtransform more efficient and promote that in the future.

**Comment by pnorman** [comment]
ping @gravitystorm 

Would it cause problems if the `name` column was populated in *addition* to the `route_name` column?

The relevant code is
```cpp
for (keyval *p = rel_tags->firstItem(); p; p = rel_tags->nextItem(p)) {
     //copy the name tag as "route_name"
     if (is_route && (p->key == "name"))
         tags.addItem("route_name", p->value, true);
     //copy all other tags except for "type"
     else if (p->key != "type")
         tags.addItem(p->key, p->value, true);
 }
```

I'd do this by changing the `else if` to an `if`

**Comment by gravitystorm** [comment]
I think the original intention was to have the name of the underlying way clearly distinct from the name of the route relation, hence the different tags. Or I think it might have been a way to access routes before `route=` tagging of relations was common, e.g. "select * from planet_osm_ways where route_name is not null" but take that with a pinch of salt.

Of course, getting access to properties of underlying ways when dealing with route relations (e.g. is this part of the relation off-road, on a bridge, etc) is still a dark art and I've no idea of the current output for route relations in osm2pgsql.

So make whatever changes you think are appropriate!

**Comment by pnorman** [comment]
> Of course, getting access to properties of underlying ways when dealing with route relations (e.g. is this part of the relation off-road, on a bridge, etc) is still a dark art

The C transforms don't do this, but there is #230 open about adding the ability to do this in Lua.

> and I've no idea of the current output for route relations in osm2pgsql.
Assuming default.style, they get populated in the line table, but not the roads table. For a road relation, they are like `route=road ref=123`. If you added the columns, they'd also generally have a network value and a route_name value if the relation has a `name=*` tag. Unless there was a tagging error, they would not have a highway=* tag. If there *was* a tagging error and highway=* was on the relation, the road would end up being rendered twice, as with gravitystorm/openstreetmap-carto#302
