### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by lzqlzq** [openstreetmap/osm2pgsql#318]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with osm2pgsql. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable osm2pgsql on @Sourcegraph by going to https://sourcegraph.com/github.com/openstreetmap/osm2pgsql and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by pnorman** [comment]
I looked at this and was reluctant to add it on the basis of the information given. Also, the text submitted in this issue is generic text generated by @sourcegraph.

@lonvia, any thoughts?

**Comment by lonvia** [comment]
I agree that more information is needed. I could not find out if this tool just mirrors github or if signed-in users can add more content. In the latter case, somebody might have to follow what is happening, which would stretch our non-existing resources further.
