### ISSUE TITLE
Where to find the latest builds

### ISSUE THREAD

**Issue by anothergisblogsamples** [openstreetmap/osm2pgsql#319]
Is there a location/page where all builds can be posted?  A lot of users make builds, but they are spread out all around the issues page.  It would be nice to have a central repo where all this information can be posted.

Thank you

**Comment by pnorman** [comment]
The osm2pgsql maintainers don't prepare packages for distributions/OSes. If someone packaging for a distro needs help with osm2pgsql specific issues we can provide it.

**Comment by anothergisblogsamples** [comment]
@pnorman - ok, thank you for that information.  For a noob trying to build the osm2pgsql software for windows, can you please provide a how-to guide on how to get this done?  

I only asked because I found a build called osm2pgsql-november-release.zip, which worked on Windows quite well, but there are a lot of builds floating on the issues pages.  

I find osm2pgsql way easier to use on Windows than osmosis, and it provides better control over the fields.  Anything you can help with would be awesome!

**Comment by pnorman** [comment]
I don't run osm2pgsql on Windows, so I'm not able to help with that.

**Comment by martin-s** [comment]
Check this out: https://github.com/alex85k/osm2pgsql-cmake

**Comment by anothergisblogsamples** [comment]
Awesome, I'll check it out
