### ISSUE TITLE
relative paths for multi-backend lua files

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#321]
Currently if you set a tagtransform of `"tagtransform": "foo.lua"` it looks for foo.lua relative to your current working directory, not relative to the multi-backend style file or relative to osm2pgsql.

This means that it's impossible to have a style that works no matter where you call osm2pgsql from unless you use absolute paths.

I would prefer it to be relative to the style file.

**Comment by lonvia** [comment]
This is the main blocker for making tests completely location-independent.

**Comment by lonvia** [comment]
Fixed in #992.
