### ISSUE TITLE
C++11

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#324]
When rewriting to C++, we wanted to use C++11 but there were too many people with compilers that didn't support it.

At what point is it sensible to allow code using C++11 features?

Ubuntu 14.04 has GCC recent enough to support it. 12.04 requires a PPA. I'm not sure about 10.04.

Some points we want to wait for
* OSMF rendering moving to 14.04
* Ubuntu 10.04 going EOL (April 30, 2015)

**Comment by lonvia** [comment]
There is also Debian stable. I don't think there is a fixed date yet for Jessie to become stable.

Personally I think that it is fair to point anybody with such old distributions to the last C version. It is usable and stable. It will still be some time before the C++ version has significant improvements that make it necessary to change and until then it is likely that these old distros have died out.

Being able to use C++11 features will definitely make developing a lot easier and potentially the code a lot faster (thinking move constructor here).

**Comment by lonvia** [comment]
The next Debian release has been announced for end of April. So by May all major distros should have a recent enough compiler.

As for OSMF servers, aren't they still running a C version anyway?

**Comment by pnorman** [comment]
Closing. We're okay with adding C++11 features, and announced this with release 0.87.3.
