### ISSUE TITLE
Not creating indexes?

### ISSUE THREAD

**Issue by Venex** [openstreetmap/osm2pgsql#326]
I've loaded several osm extracts successfully. It took a while loading the pfb file into the database and took about the same time for step "Sorting data and creating indexes"

This time I have (apparently) an issue with europe.osm.pbf (geofabrik.de) using 

version: osm2pgsql SVN version 0.87.3-dev (64bit id space)
command: osm2pgsql --slim -d gis -C 4000 --number-processes 4 

When loading nodes/ways/relations, it skips immediately to committing transaction and exits application

**Comment by pnorman** [comment]
What is the output from osm2pgsql?

**Comment by Venex** [comment]
Dear pnorman, this is the output of a new execution:

osm2pgsql SVN version 0.87.3-dev (64bit id space)

Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=2000MB, maxblocks=256000*8192, allocation method=11
Mid: pgsql, scale=100 cache=2000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /home/tileuser/Documents/europe-latest.osm.pbf

Processing: Node(10k 10.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Processing: Node(20k 20.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
... etc etc...
Processing: Node(1441488k 182.3k/s) Way(176918k 7.39k/s) Relation(2307960 114.90/s)
Processing: Node(1441488k 182.3k/s) Way(176918k 7.39k/s) Relation(2307970 114.90/s)  parse time: 51945s
Node stats: total(1441488525), max(3416627506) in 7909s
Way stats: total(176918078), max(334598994) in 23950s
Relation stats: total(2307971), max(4726594) in 20086s
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads

Thats it.

Seems to be missing some statements I've seen before:

Sorting data and creating indexes for planet_osm_polygon
Sorting data and creating indexes for planet_osm_roads
Sorting data and creating indexes for planet_osm_line
Sorting data and creating indexes for planet_osm_point
Building index on table: planet_osm_rels
Building index on table: planet_osm_ways

**Comment by pnorman** [comment]
And it exits successfully from there?

What command line you ran, and what is the git has of the version you built?

**Comment by Venex** [comment]
I do not properly understand your first question.
Committing transactions is the last action executed and the application will exit.
See:

<pre>osm2pgsql SVN version 0.87.3-dev (64bit id space)

Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=2000MB, maxblocks=256000*8192, allocation method=11
Mid: pgsql, scale=100 cache=2000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /home/tileuser/Documents/europe-latest.osm.pbf

Processing: Node(10k 10.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Processing: Node(20k 20.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
... etc etc...
Processing: Node(1441488k 182.3k/s) Way(176918k 7.39k/s) Relation(2307960 114.90/s)
Processing: Node(1441488k 182.3k/s) Way(176918k 7.39k/s) Relation(2307970 114.90/s) parse time: 51945s
Node stats: total(1441488525), max(3416627506) in 7909s
Way stats: total(176918078), max(334598994) in 23950s
Relation stats: total(2307971), max(4726594) in 20086s
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads</pre>

Assumingly creation of indexes is missing.
I ran 
<pre>sudo -u postgres osm2pgsql --slim -d gis -C 2000 --number-processes 4 /home/tileuser/Documents/europe-latest.osm.pbf</pre>

I did not check out a version before building, just grabbed latest, which seems to be 0.87.3-dev

**Comment by pnorman** [comment]
I'd suggest increasing the cache to up to about 12000 if you have enough RAM, and not doing this as the postgres user, but neither of those changes should matter for the problem.

Are there any errors in the PostgreSQL log?

What does `SELECT * FROM pg_stat_activity WHERE datname = 'gis'` report?

Just for confirmation, can you try the same command, except instead of Europe, use the `tests/liechtenstein-2013-08-03.osm.pbf` file distributed with osm2pgsql.

**Comment by Venex** [comment]
The computer only has 4GB of ram, so... :-)
I checkedout and build 0.87.2 and load all again, never had this before. I'll keep you posted, when indexes aren't created again, I''ll give you the error dump

**Comment by Venex** [comment]
Dear Paul, thank you for your help. I'd try another import using version 0.87.2 which didn't result in creating indexes either. the pg_stat_activity table remained empty.

This is my output of liechtenstein which executed everything properly, don't know why europe stopped after committing transactions

<pre>osm2pgsql SVN version 0.87.2 (64bit id space)

Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=3000MB, maxblocks=384000*8192, allocation method=11
Mid: pgsql, scale=100 cache=3000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /home/tileuser/src/osm2pgsql/tests/liechtenstein-2013-08-03.osm.pbf

Processing: Node(10k 10.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Processing: Node(20k 20.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Processing: Node(30k 30.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Processing: Node(40k 40.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Processing: Node(50k 50.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Processing: Node(60k 60.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
Processing: Node(65k 65.7k/s) Way(1k 1.00k/s) Relation(0 0.00/s)
Processing: Node(65k 65.7k/s) Way(2k 2.00k/s) Relation(0 0.00/s)
Processing: Node(65k 65.7k/s) Way(3k 3.00k/s) Relation(0 0.00/s)
Processing: Node(65k 65.7k/s) Way(4k 4.00k/s) Relation(0 0.00/s)
Processing: Node(65k 65.7k/s) Way(5k 5.00k/s) Relation(0 0.00/s)
Processing: Node(65k 65.7k/s) Way(6k 6.00k/s) Relation(0 0.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.00k/s) Relation(0 0.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.12k/s) Relation(10 10.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.12k/s) Relation(20 20.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.12k/s) Relation(30 30.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.12k/s) Relation(40 40.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.12k/s) Relation(50 50.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.12k/s) Relation(60 60.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.12k/s) Relation(70 70.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.12k/s) Relation(80 80.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.12k/s) Relation(90 90.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.12k/s) Relation(100 100.00/s)
Processing: Node(65k 65.7k/s) Way(7k 7.12k/s) Relation(110 110.00/s)  parse time: 1s
Node stats: total(65733), max(2403384707) in 0s
Way stats: total(7121), max(232012458) in 0s
Relation stats: total(113), max(3090789) in 1s
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline

Going over pending ways...
	4162 ways are pending

Using 4 helper-processes

Finished processing 4162 ways in 0 sec

Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads

Going over pending relations...
	0 relations are pending

Using 4 helper-processes

Finished processing 0 relations in 0 sec

Committing transaction for planet_osm_point
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_line
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_polygon
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_roads
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_point
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_line
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_polygon
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_roads
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_point
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_line
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_polygon
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_roads
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_point
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_line
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_polygon
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_roads
WARNING:  there is no transaction in progress
Stopping table: planet_osm_nodes
Stopped table: planet_osm_nodes in 0s
Sorting data and creating indexes for planet_osm_point
Stopping table: planet_osm_ways
Building index on table: planet_osm_ways
Sorting data and creating indexes for planet_osm_polygon
Sorting data and creating indexes for planet_osm_line
Stopping table: planet_osm_rels
Building index on table: planet_osm_rels
Sorting data and creating indexes for planet_osm_roads
Stopped table: planet_osm_rels in 0s
Copying planet_osm_roads to cluster by geometry finished
Creating geometry index on  planet_osm_roads
Copying planet_osm_point to cluster by geometry finished
Creating geometry index on  planet_osm_point
Creating osm_id index on  planet_osm_roads
Creating indexes on  planet_osm_roads finished
Creating osm_id index on  planet_osm_point
Creating indexes on  planet_osm_point finished
All indexes on  planet_osm_roads created  in 1s
Completed planet_osm_roads
All indexes on  planet_osm_point created  in 1s
Completed planet_osm_point
Copying planet_osm_line to cluster by geometry finished
Creating geometry index on  planet_osm_line
Copying planet_osm_polygon to cluster by geometry finished
Creating geometry index on  planet_osm_polygon
Creating osm_id index on  planet_osm_line
Creating indexes on  planet_osm_line finished
Creating osm_id index on  planet_osm_polygon
Creating indexes on  planet_osm_polygon finished
Stopped table: planet_osm_ways in 1s
All indexes on  planet_osm_polygon created  in 1s
Completed planet_osm_polygon
All indexes on  planet_osm_line created  in 1s
Completed planet_osm_line
node cache: stored: 65733(100.00%), storage efficiency: 51.16% (dense blocks: 18, sparse nodes: 55028), hit rate: 99.96%

Osm2pgsql took 3s overall
</pre>

**Comment by pnorman** [comment]
What does `\d+ planet_osm_polygon` from within postgresql output?

It shouldn't be related, but it's really bad practice to run osm2pgsql as the postgres user. It's like running everything as root all the time.

**Comment by pnorman** [comment]
No reply to questions raised, so closing.
