### ISSUE TITLE
C transforms future

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#328]
We've had issues come up which would involve changing the behavior of the C transforms. (#132, #315) (which no longer are C, but are C++ instead).

I would prefer to continue development on the transforms, and someone needs a precise transform without any changes I'd rather direct them to using a lua transform that they can keep static.

In the past there hasn't been a reluctance to change the transforms.

**Comment by joto** [comment]
From what I have seen the Lua transforms are fast enough (and now with the flex backend flexible enough) that we can work towards getting rid of the c transforms at some point. We'll need to support them for backwards compatibility for a while, but once the flex backend stabilizes we can write a Lua script that exactly mimics their behaviour if that's needed. There is already a `compatible.lua` script that tries to do that, but it is untested.

Lua itself is stable enough and available on all platforms that we support, that keeping the option of compiling osm2pgsql without Lua support doesn't seem that important to me. There is only going to be a very small minority that will be happy with the inflexible and outdated c transforms anyway.

**Comment by joto** [comment]
There isn't anything actionable in this issue at this point. The [road map](https://osm2pgsql.org/contribute/road-map.html) contains some info on our plans including the possibility of removing the pgsql output in the long run.
