### ISSUE TITLE
Import data to sharding PostgreSQL server by Osm2pgsql

### ISSUE THREAD

**Issue by dhthong92** [openstreetmap/osm2pgsql#347]
I've sharded my PostgreSql database server by this extension
https://github.com/citusdata/pg_shard/
That extension work well, nothing fail. But when I imported data with osm2pgsql tool, it only import to my master server, like a non-sharding server. 
After that, I've tested it again by running simple SQL script: INSERT ... and it worked. The data which I've just inserted has moved to sharded nodes, not in master node.
So may osm2pgsql load data to the database by another way? 
Any ideas?

**Comment by pnorman** [comment]
it appears that pg_shard [does not properly support `COPY`](https://github.com/citusdata/pg_shard/issues/62), the recommended way for bulk data loads. I suggest you peruse the issue with pg_shard.
