### ISSUE TITLE
lost road

### ISSUE THREAD

**Issue by Cactusbone** [openstreetmap/osm2pgsql#359]
using osm2pgsql 0.85.0-1~trusty1

```
select * from planet_osm_ways where id=197265764
```
returns a line but 
```
select * from planet_osm_polygon where osm_id=197265764
select * from planet_osm_line where osm_id=197265764
select * from planet_osm_roads where osm_id=197265764
```
do not .
I'm not sure what happened here, it's part of some multipolygons

http://www.openstreetmap.org/way/197265764#map=19/48.86484/2.39892

It seems it worked in version 0.81.0-1~precise1.

any idea ?

**Comment by SomeoneElseOSM** [comment]
It's not related to issue 304 is it?

**Comment by Cactusbone** [comment]
it does seems similar yes, it looks like the ways forming the multipolygon do not remain.

**Comment by pnorman** [comment]
Could you please provide a somewhat reduced testcase, with specific data?

**Comment by Cactusbone** [comment]
I'll try to do that today :)

**Comment by pnorman** [comment]
ping @Cactusbone

Need at least some more information

**Comment by Cactusbone** [comment]
I wanted to make a test case out of it but did not have the time.
I'll still try to do it asap.

take a look here : 
http://demo.f4map.com/#lat=48.8649841&lon=2.3986905&zoom=19&3d=false&camera.theta=0.9

you'll notice the "place gambetta" road (which look like a roundabout) is missing.

my first guess is it disappeared because it's part of a multipolygon also tagged as a highway, but i can't find it anymore. so i have no clue why it disappeared :(

on an older server (running 0.81.0-1~precise1) it's there.

**Comment by Cactusbone** [comment]
really weird . it looks like on our latest import it's back. i think the relation including it may have disappeared from osm, thus fixing it.

**Comment by pnorman** [comment]
probably #304, and not enough information here to reproduce.

**Comment by Cactusbone** [comment]
ok found the relation
http://www.openstreetmap.org/relation/2796793/history

It's indeed been deleted from osm

from what i see, having a way tagged highway within a multipolygon relation made all the ways inside the relation only appear as a single polygon, and not as their parts

If i manage to understand how your test cases work, i may be able to reproduce it :)

**Comment by Cactusbone** [comment]
unfortunately, this did not bring back the missing roads, i'll need to do a full import i guess
