### ISSUE TITLE
linker errors & more

### ISSUE THREAD

**Issue by sumarlidason** [openstreetmap/osm2pgsql#361]
First, I had to patch this commit https://github.com/hholzgra/osm2pgsql/commit/f710045953b8f02aeba846ba89749961639ee0c5 from issue https://github.com/openstreetmap/osm2pgsql/issues/13 under CentOS 6.6

Second, to get a successful configure I had export BOOST_ROOT **and**  pass it at the command line [1]. One or the other would not work.

Third, BOOST_CPPFLAGS as declared in ax_boost_base.m4 would add '/include' to my custom include search path. I had to remove this.

Lastly, during linking my custom library search path didn't seem to populate correctly:
```
/bin/sh ./libtool --tag=CXX   --mode=link g++  -g -O2   -o nodecachefilereader node-persistent-cache-reader.o libosm2pgsql.la -pthread -L/usr/lib -lz -L/usr/pgsql-9.4/lib -lpq -lxml2 -lz -lm -L/usr/lib -lbz2 -L/usr/lib64 -L/usr/lib64 -lgeos -L/usr/lib -lproj -L/usr/lib -lprotobuf-c -L/usr/lib/x86_64-linux-gnu -llua-5.1  -lm -ldl  -lboost_filesystem -lboost_system -lboost_thread-mt  
libtool: link: g++ -g -O2 -o nodecachefilereader node-persistent-cache-reader.o -pthread  ./.libs/libosm2pgsql.a -L/usr/lib -L/usr/pgsql-9.4/lib -lpq -lxml2 -lz -lbz2 -L/usr/lib64 -lgeos -lproj -lprotobuf-c -L/usr/lib/x86_64-linux-gnu -llua-5.1 -lm -ldl -lboost_filesystem -lboost_system -lboost_thread-mt -pthread
/usr/bin/ld: cannot find -lboost_filesystem
```
Note the -L/usr/lib64 -L/usr/lib64 duplicate parameters; I was able to link those manually by changing the latter to -L/usr/lib64/boost148

Thanks for reading & developing, If I was more familiar with these build tools I'd happily contribute back; alas I hope this helps.

[1] ./configure --with-boost=$BOOST_ROOT --with-boost-libdir=/usr/lib64/boost148/

**Comment by sumarlidason** [comment]
Also, It seems the configure script does not check for **proj-epsg**'s /usr/share/proj/epsg

HTH

**Comment by pnorman** [comment]
Are you using CentOS 6.x? I'm not sure what @lonvia thinks, but if forced to choose between warnings and the buggy version of m4 on CentOS, I'd probably go with the former. I do see that ax_cflags_warn_all [has been updated](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=commitdiff;h=1156e1362b82616ec34ab037fd334f4bf1c7f7c4) but I don't see that the update would fix the centos issues.

$BOOST_ROOT should only be needed with a staged boost library.

Where are your boost header files, and what did you specify for --with-boost?

Like for most people, autotools is very much black magic, so I'm not sure how much help I can be.

**Comment by pnorman** [comment]
There's been no reply to the questions raised, so closing.
