### ISSUE TITLE
Set coding style

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#370]
> Should we also agree on using either 2 or 4 spaces for indention?
Yes. I was going for 4, since that's what most of the file was. We also should set out if the { goes on a newline, etc. Because we're mixing so many styles already, we have complete freedom to set something new, since it won't match a good portion of the code no matter what it is.

(from https://github.com/openstreetmap/osm2pgsql/pull/368#issuecomment-118479495)

I have no real preference here, but it'd be nice to get all new code the same.

**Comment by lonvia** [comment]
I would suggest the following as minimum standard:

- no tabs, standard indentation 4 spaces
- opening brackets on the same line (possible exception for class and function definitions)
- use underscores in names, no camel case
- class/struct names end in _t
- no space between function name and bracket
- space between for/if/while and bracket
- spaces around operators

This seems to reflect the general trend in the code. I'm not particularly insisting on any of those rules (with exception of the "no tabs" rule maybe). I just would like to see more consistency.

**Comment by pnorman** [comment]
K&R (1TBS variant) then? That's what we ended up using in [avecado](https://github.com/MapQuest/avecado/blob/master/README.md#contributing)

**Comment by lonvia** [comment]
Jep, fine with me.
