### ISSUE TITLE
Out of order nodes don't fall back to dense nodes

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#377]
A small API produced OSM file results in the error message "Node cache size is too small to fit all nodes." with the command line `osm2pgsql -C 8000 map.osm`. It is most likely failing to fall back to dense nodes.
#360 is related.

**Comment by joto** [comment]
Input must be ordered in current versions of osm2pgsql and the ram middle has a completely new implementation. Closing as outdated.
