### ISSUE TITLE
problem after exectuing: ./configure && make && make install

### ISSUE THREAD

**Issue by gischy** [openstreetmap/osm2pgsql#378]
checking for boostlib >= 1.48... configure: We could not detect the boost libraries (version 1.48 or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost option.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
configure: error: cannot find Boost libraries, which are are required for building osm2pgsql. Please install libboost-dev.

**Comment by gravitystorm** [comment]
And have you installed libboost-dev?

You need to provide more details, such as the version of boost installed, how you installed it, what platform you are on etc.

**Comment by pnorman** [comment]
No reply to questions raised, so closing.
