### ISSUE TITLE
Invalidation for large relations

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#38]
Invalidation of tiles for large relations could lead to all the tiles in the US being invalidated by a tag change on a US border relation. It would be desirable to be able to not invalidate the interior of large boundary relations.

cc @gravitystorm

**Comment by lonvia** [comment]
cc @Nakaner

**Comment by pnorman** [comment]
A misdirected email from @woodpeck from 2013 said

> Normally, expire_tiles_from_poly will expire tiles for the whole bounding box of the polygon unless the bbox has a width or height higher than EXPIRE_TILES_MAX_BBOX, in which case only those tiles actually touched by the outline of the polygon will be expired.

> This should make sure that the whole of the US is never invalidated.

**Comment by joto** [comment]
Large multipolygon relations are handled through the [--expire-bbox-size](https://osm2pgsql.org/doc/manual.html#expire) mechanism. For future ideas see #1662.
