### ISSUE TITLE
error while opening file mapserver ubuntu 14.04

### ISSUE THREAD

**Issue by baditaflorin** [openstreetmap/osm2pgsql#385]
command that i am using osm2pgsql mexico-150713.osm.pbf -d mexico -U mapuser -W mapserver -S /usr/share/osm2pgsql/default.style

Install via apt-get in ubuntu 14.04 
SVN version 0.84.0 (64bit it space)

Reading in file: mexico-150713.osm.pbf
Processing: Node(9799k 3266.7k/s) Way(1056k 24.56k/s) Relation(6000 352.94/s)  parse time: 63s

Reading in file: mapserver
error while opening file mapserver
![capture](https://cloud.githubusercontent.com/assets/2330999/8668965/2085468a-2a19-11e5-9b47-66a00d8430b7.PNG)

**Comment by pnorman** [comment]
`-W mapserver`

`-W` does not take an argument, so this tells osm2pgsql to prompt for a password, and then to load the file "mapserver"
