### ISSUE TITLE
-O null requests database connection

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/osm2pgsql#387]
Running osm2pgsql with -O null ("no output. useful for testing.") does attempt to connect to a PostGIS database and fails if none is available. 

Expected behaviour: Read through the input file and quit.
Or: Amend description with "(note: database still require for middle stage.)"

**Comment by pnorman** [comment]
was this with `--slim`? If so, this is the expected behavior, but the docs could probably be clearer that `-O null` only changes the output backend, not the middle backend.
