### ISSUE TITLE
error: ‘class OSMPBF::Blob’ has no member named ‘release_raw’ 

### ISSUE THREAD

**Issue by kbalk** [openstreetmap/osm2pgsql#392]
The contrib/libosmium library seems to be out of sync with the osm2pgsql code:

    libtool: compile:  g++ -DHAVE_CONFIG_H -I. -Icontrib/protobuf -Icontrib/libosmium -pthread -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -DOSM2PGSQL_DATADIR=\"/usr/local/share/osm2pgsql\" -Igeos-fallback -pthread -I/usr/include -g -O2 -std=gnu++11 -MT parse-osmium.lo -MD -MP -MF .deps/parse-osmium.Tpo -c parse-osmium.cpp  -fPIC -DPIC -o .libs/parse-osmium.o
    In file included from contrib/libosmium/osmium/io/detail/pbf_input_format.hpp:55:0,
                 from contrib/libosmium/osmium/io/pbf_input.hpp:47,
                 from contrib/libosmium/osmium/io/any_input.hpp:48,
                 from parse-osmium.cpp:27:
    contrib/libosmium/osmium/io/detail/pbf_parser.hpp: In function ‘std::unique_ptr<const std::basic_string<char> > osmium::io::detail::unpack_blob(const string&)’:
    contrib/libosmium/osmium/io/detail/pbf_parser.hpp:336:66: error: ‘class OSMPBF::Blob’ has no member named ‘release_raw’
                     return std::unique_ptr<std::string>(pbf_blob.release_raw());
                                                                  ^

**Comment by lonvia** [comment]
This looks like residue from a previous build. Run `make distclean && ./autogen.sh && ./configure && make` to make sure everything is built properly.

**Comment by kbalk** [comment]
I've done so and the problem remains.  If you look at fileformat.ph.h where class Blob is defined, no release_raw() method is defined.

**Comment by pnorman** [comment]
can you provide the output of `git status` then try `git clean -xfd && ./autogen.sh && ./configure && make`.

**Comment by kbalk** [comment]
[~/osm2pgsql]$ git status
# On branch master
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   configure.ac
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       configure.ac.save
#       contrib/protobuf/osmpbf/fileformat.pb.h
#       contrib/protobuf/osmpbf/osmformat.pb.h
#       fileformat.pb.cc
#       fileformat.pb.h
#       osmformat.pb.cc
#       osmformat.pb.h
no changes added to commit (use "git add" and/or "git commit -a")

**Comment by kbalk** [comment]
Same error, different location:
In file included from contrib/libosmium/osmium/io/detail/pbf_input_format.hpp:55:0,
                 from contrib/libosmium/osmium/io/pbf_input.hpp:47,
                 from contrib/libosmium/osmium/io/any_input.hpp:48,
                 from parse-osmium.cpp:27:
contrib/libosmium/osmium/io/detail/pbf_parser.hpp: In function ‘std::unique_ptr<const std::basic_string<char> > osmium::io::detail::unpack_blob(const string&)’:
contrib/libosmium/osmium/io/detail/pbf_parser.hpp:336:66: error: ‘class OSMPBF::Blob’ has no member named ‘release_raw’
                     return std::unique_ptr<std::string>(pbf_blob.release_raw());
                                                                  ^
make[1]: *** [parse-osmium.lo] Error 1

**Comment by pnorman** [comment]
git is showing `contrib/protobuf/osmpbf/fileformat.pb.h` as untracked, but it's in `.gitignore`, so you must not have 2b51f5a55edbd1ef09a4b99c7e63dbbc5ca1024c.

Can you try again with the latest master (c1b109683d5bf79a9c9ede54ad119f3dd5ccb10d)?

**Comment by kbalk** [comment]
I did a 'git clone' yesterday around 11 AM, so unless the master was updated after that, I'm going to get the same errors.

**Comment by kbalk** [comment]
I did another 'git clone', 'git clean', etc. same problem.  The top of git log shows:

    commit 6117a6652e4f4bca6127c92ca98ebe02f8e9f08c
    Merge: 08aba09 b3f52c9
    Author: Paul Norman <penorman@mac.com>
    Date:   Tue Jul 14 00:38:56 2015 -0700

        Merge pull request #384 from pnorman/libosmium-port-readme

        Libosmium readme changes

    commit 08aba09935a7c02cf7337dbee93fb408e2ae5a1b
    Merge: 58d77f5 35f5ee6
    Author: Sarah Hoffmann <lonvia@denofr.de>
    Date:   Tue Jul 14 09:24:17 2015 +0200

        Merge pull request #379 from lonvia/libosmium-port

        Initial libosmium port

**Comment by pnorman** [comment]
> I did another 'git clone', 'git clean', etc. same problem. The top of git log shows:

For some reason, your clone isn't picking up the latest version.

Looking at the diff from what you ended up with to the latest version, https://github.com/openstreetmap/osm2pgsql/compare/6117a6652e4f4bca6127c92ca98ebe02f8e9f08c...master, I don't see anything which would be related to the problem but you probably should still figure out why your git isn't picking up the latest version.

Can you check `grep '^PROTOC' config.log` to see what protobuf compiler it's finding, then call it with `--version`, e.g. `protoc --version` if `protoc` is what it found.

**Comment by kbalk** [comment]
[~/osm2pgsql]$ grep '^PROTOC' config.log
PROTOC='protoc'
[~/osm2pgsql]$ protoc --version
libprotoc 2.3.0

**Comment by kbalk** [comment]
I went to another directory, did another 'git clone' and got a few new changes, but none that fixed the problem:

    CXX    parse-osmium.lo
    In file included from contrib/libosmium/osmium/io/detail/pbf_input_format.hpp:55:0,
                 from contrib/libosmium/osmium/io/pbf_input.hpp:47,
                 from contrib/libosmium/osmium/io/any_input.hpp:48,
                 from parse-osmium.cpp:27:
    contrib/libosmium/osmium/io/detail/pbf_parser.hpp: In function ‘std::unique_ptr<const std::basic_string<char> > osmium::io::detail::unpack_blob(const string&)’:
    contrib/libosmium/osmium/io/detail/pbf_parser.hpp:336:66: error: ‘class OSMPBF::Blob’ has no member named ‘release_raw’
                     return std::unique_ptr<std::string>(pbf_blob.release_raw());
                                                                  ^
    make[1]: *** [parse-osmium.lo] Error 1

git log output:

    [~/take2/osm2pgsql]$ git log | more
    commit 358fdc013c524d3e98c0551bcf044ec7bfc80e84
    Merge: c1b1096 5e523c0
    Author: Sarah Hoffmann <lonvia@denofr.de>
    Date:   Wed Jul 15 21:59:56 2015 +0200

        Merge pull request #375 from pnorman/table_options

        Update on/off options to bool

**Comment by lonvia** [comment]
Your protoc is really ancient. I'm having 2.6.1 here and even Debian old-stable comes with 2.4.1. Please try with a newer version of the protobuf libraries.

**Comment by kbalk** [comment]
I'm using Centos 6.6 which has old versions of just about everything.  But I think you're missing the point ... release_raw() isn't defined anywhere, so even if protoc was newer, it won't find 'release_raw':

 [~/take2/osm2pgsql]$ find . -name '*' | xargs grep release_raw
./contrib/libosmium/osmium/io/detail/pbf_parser.hpp:                    return std::unique_ptr<std::string>(pbf_blob.release_raw());

**Comment by pnorman** [comment]
2.3.0 is quite old, though libosmium documentation says [it meets the requirements](https://github.com/osmcode/libosmium/wiki/Libosmium-dependencies#google-protocol-buffers).

> But I think you're missing the point ... release_raw() isn't defined anywhere, so even if protoc was newer, it won't find 'release_raw':

It is defined in the code output by protoc. From 2.6.1, 

```
fileformat.pb.h
110:  inline ::std::string* release_raw();
369:inline ::std::string* Blob::release_raw() {
```

**Comment by lonvia** [comment]
The dependency list in libosmium is wrong there. I'm leaning towards ignoring the problem for the moment and simply wait for the next version of libosmium which will no longer have a dependency on google-protobuf.

**Comment by pnorman** [comment]
I've updated the libosmium docs, and done a PR to enforce a minimum version with ./configure

**Comment by kbalk** [comment]
Updated my version of libprotoc:
      [~/take2/osm2pgsql]$ protoc --version
      libprotoc 2.6.1

Did a distclean, autogen, configure, make and I no longer have the previous error, but I now get the error:

    ./.libs/libosm2pgsql.a(osmdata.o): In function `boost::thread::start_thread()':
    /usr/local/include/boost/thread/detail/thread.hpp:179: undefined reference to `boost::thread::start_thread_noexcept()'
    ./.libs/libosm2pgsql.a(osmdata.o): In function `boost::thread_exception::thread_exception(int, char const*)':
       :
    /usr/local/include/google/protobuf/wire_format_lite_inl.h:333: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilLimit() const'    ./.libs/libosm2pgsql.a(osmformat.pb.o):/usr/local/include/google/protobuf/wire_format_lite_inl.h:333: more undefined references to `google::protobuf::io::CodedInputStream::BytesUntilLimit() const' follow
    collect2: error: ld returned 1 exit status
    make[1]: *** [osm2pgsql] Error 1
    make[1]: Leaving directory `/home/kbalk/take2/osm2pgsql'
    make: *** [all] Error 2
