### ISSUE TITLE
protobuf development libraries not found.

### ISSUE THREAD

**Issue by darshand** [openstreetmap/osm2pgsql#396]
Hi, 
Getting above mentioned error while try to run ./configure. 
I am in Ubuntu 14.04. Any idea.?

**Comment by lonvia** [comment]
Have you installed the protobuf libraries and you also need pkg-config:

`sudo apt-get install protobuf-dev protobuf-compiler pkg-config`

A full list of dependencies can be found in the Building section in the README file.

**Comment by darshand** [comment]
I can only see `protobuf-c-compiler  protobuf-compiler`, no `protobuf-dev`

**Comment by lonvia** [comment]
Sorry `libprotobuf-dev`.

Again, please see https://github.com/openstreetmap/osm2pgsql/blob/master/README.md#building for a copy-and-paste-able list of packages to install on Ubuntu.

**Comment by darshand** [comment]
@lonvia thank you.
