### ISSUE TITLE
Try cppformat as a replacement for boost:format

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#398]
The boost::format library is known to have a very bad performance. A recommended replacement is the [cppformat library](https://github.com/cppformat/cppformat). We should try that.

**Comment by pnorman** [comment]
I thought that we weren't using it anywhere that mattered for performance, but found a lot more than I thought with a grep.

It looks like cppformat **just** made it into Debian. Would we be looking at including it like libosmium and compiling it in header-only mode?

**Comment by lonvia** [comment]
Given that it is relatively new and still in development, including it as a contrib library will give as more control. So I would prefer that.

If the performance turns out well, it would be nice to be able to replace the remaining hacky printfs in the code that creates SQL statements.

**Comment by pnorman** [comment]
Including an unrelated third-party library often causes problems with package maintainers, so we should check with them before planning that
