### ISSUE TITLE
#include order

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#401]
Currently `#include` order is completely random, which is probably something we should try to change over time.

The headers can generally be broken down into C++ standard library, C standard library, boost, and osm2pgsql files.

How should we order these, and order them within each group?

**Comment by lonvia** [comment]
The order you mentioned sounds good, alphabetically within each group.

If you clean that up, use [include-what-you-use](http://include-what-you-use.org/) to make sure the includes are sensible.

**Comment by pnorman** [comment]
does include-what-you-use only find missing includes, or both missing and unnecessary includes? I've found a few includes that aren't used, a duplicate include, and some includes that can be replaced by forward declarations.

**Comment by lonvia** [comment]
If finds both missing and unnecessary includes. It even does forward declarations. Output should be taken with a grain of salt as there is the occasional false-positive.

**Comment by DerDakon** [comment]
My preferred style is to always have the own headers first, and the header of the hpp directly matching a cpp as first one under all circumstances. The idea is that you immediately can spot if your hpp does not include or define everything it needs to get compiled.
