### ISSUE TITLE
Move to cmake?

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#417]
Autotools is a difficult build system to work with, despite being fairly common. Moving to cmake might offer some advantages, particularly for Windows builds.

@alex85k has a cmake build script for osm2pgsql at https://github.com/alex85k/osm2pgsql-cmake from about 0.87.1, and is probably best able to comment on what would be involved with moving to cmake.

Since the time he wrote it, a few things have changed in osm2pgsql

* Libosmium is used
* C++11 is used
* PBF support is mandatory
* protobuf-c-compiler is no longer required
* osm2pgsql compiles with `-Werror -Wall -pedantic`
* Numerous minor new files and renames which probably will require minor changes

cmake advantages
* Less layers involved
* Better Windows support
* libosmium uses it
* Less arcane oddities

autotools advantages
* Very common
* What we're currently using

**Comment by martin-s** [comment]
I would appreciate it. But there will be always two parties (linux vs. windows) that are hardly convincible for the one tool. E.g., at OpenLayers they moved to make.

**Comment by pnorman** [comment]
cmake is reasonably supported on Linux, so I don't see an issue there. Automake might support more arcane operating systems, but given the need for protobuf, boost, GEOS, postgres, and a big advantage to 64 bit, I can't see cmake support being an issue on any usable OS.

**Comment by pnorman** [comment]
@alex85k, do you have any thoughts on what effort would be involved here? You've got the most experience with osm2pgsql and cmake.

**Comment by alex85k** [comment]
I like cmake but I am not a professional. If it will be the only build system, then someone should 
check the scripts and test it on different systems (travis will do it automatically for Linux, Appveyor with Windows). Some non-classical variants of file locations for *BSD, RedHat etc. can still fail before more fixes).
We can rely on libosmium cmake scripts for finding libraries (only PostgreSQL and lua are needed too), then CMakeLists.txt will be short and simple.

**Comment by alex85k** [comment]
Tested on Free
Should I prepare a PR with cmake build scripts, appveyor Windows build automation and tarvis+cmake additional variant?

**Comment by pnorman** [comment]
Yes, a PR to move to cmake would be good. I had a go at converting, but didn't very far.

**Comment by alex85k** [comment]
OK, let's do it. When converting I'l try to fix some rough places like long predefined lists of sources and weird directory structure needed for separate build.

**Comment by alex85k** [comment]
Phew, it took 20 tries to make both Travis CI and Appveyor happy :)
Had to downgrade cmake script to cmake 2.8.7 (available on Travis and old Ubuntu).
Here is the PR: https://github.com/openstreetmap/osm2pgsql/pull/460

**Comment by DerDakon** [comment]
This is fixed, no?
