### ISSUE TITLE
Deleting relation when a way should be deleted instead

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#422]
Stepping through #419 found a bug.

In pending relations `DELETE FROM planet_osm_roads WHERE osm_id = -1` (and other tables) is executed, but relation 1 is not touched in the diff, nor is it related to any objects in the diff. **Way** 1 is touched, and is processed correctly in pending ways.

**Comment by joto** [comment]
Is this the same as #1048?

**Comment by pnorman** [comment]
Looks like it.
