### ISSUE TITLE
osm2pgsql granting select on output tables to PUBLIC

### ISSUE THREAD

**Issue by strk** [openstreetmap/osm2pgsql#43]
I don't think it belongs to this utility granting permissions on tables, instead output_pgsql.c is granting SELECT to PUBLIC (any database user) on anything that's imported.

On CartoDB we have a special user representing "the public", and that user is NOT "PUBLIC", so this assumption of osm2pgsql is wrong. What's the rationale for setting permissions from the importer ?

**Comment by pnorman** [comment]
@lonvia we should decide on this. The patch is pretty trivial technically. I agree with @gravitystorm on this, it's not expected behavior.

**Comment by lonvia** [comment]
+1 for removing the grant. It's surprising.
