### ISSUE TITLE
Compile errors on Wheezy

### ISSUE THREAD

**Issue by aimdev** [openstreetmap/osm2pgsql#432]
While following the git/autogen/configure instructions, during make I get this...

```
  CXX    parse-osmium.lo
In file included from contrib/libosmium/osmium/io/bzip2_compression.hpp:57:0,
                 from contrib/libosmium/osmium/io/any_compression.hpp:45,
                 from contrib/libosmium/osmium/io/any_input.hpp:46,
                 from parse-osmium.cpp:27:
contrib/libosmium/osmium/io/compression.hpp:127:13: error: expected unqualified-id before '[' token
In file included from contrib/libosmium/osmium/io/file.hpp:42:0,
                 from contrib/libosmium/osmium/io/detail/input_format.hpp:43,
                 from contrib/libosmium/osmium/io/reader.hpp:55,
                 from contrib/libosmium/osmium/io/pbf_input.hpp:46,
                 from contrib/libosmium/osmium/io/any_input.hpp:48,
                 from parse-osmium.cpp:27:
contrib/libosmium/osmium/io/file_format.hpp:51:28: error: expected '}' before end of line
contrib/libosmium/osmium/io/file_format.hpp:51:28: error: expected unqualified-id before end of line
contrib/libosmium/osmium/io/file_format.hpp:51:28: error: expected '}' before end of line
contrib/libosmium/osmium/io/file_format.hpp:51:28: error: expected '}' before end of line
contrib/libosmium/osmium/io/file_format.hpp:51:28: error: expected declaration before end of line
make[1]: *** [parse-osmium.lo] Error 1
make[1]: Leaving directory `/home/develop/osm2pgsql'
make: *** [all] Error 2
```

Can any one else reproduce this error.

**Comment by pnorman** [comment]
What compiler and version?

The relevant code is coming from [compatibility.hpp](https://github.com/openstreetmap/osm2pgsql/blob/master/contrib/libosmium/osmium/util/compatibility.hpp)

@joto the compression.hpp line is `OSMIUM_NORETURN void error(osmium::io::file_compression compression)`. The [isocpp.org FAQ](https://isocpp.org/wiki/faq/cpp11-language-misc#attributes) shows noreturn as an example `void f [ [ noreturn ] ]`, putting noreturn after the function name, but I see some examples in the wild putting it before.

**Comment by aimdev** [comment]
Hi

gcc --version
gcc (Debian 4.7.2-5) 4.7.2


Aimee

**Comment by pnorman** [comment]
You'll need GCC 4.8 or Clang 3.4. I'm not sure which is easier to get on Wheezy. I'm slightly surprised that GCC 4.7 passed ./configure, so there's an issue there.

**Comment by aimdev** [comment]
Hi

Hum, the only reason I was trying to compile osm2pgsql was I believe this version allows map diffs to be added.

The mainstream one apparently doesn’t, or have I been mis informed?

If I am correct then will this version be migrated to mainstream?

The reason for not going to jessie is there may be some speed issues, so I wanted to do a comparison.

Thanks

Aimee

**Comment by joto** [comment]
@pnorman I think `[[noreturn]]` in front is right. See for example http://en.cppreference.com/w/cpp/utility/program/exit . Anyway, it works on all C++11-capable browsers I have seen.

**Comment by pnorman** [comment]
> Hum, the only reason I was trying to compile osm2pgsql was I believe this version allows map diffs to be added.

All non-ancient versions of osm2pgsql have diff support.

> The mainstream one apparently doesn’t, or have I been mis informed?
> 
> If I am correct then will this version be migrated to mainstream?

The version in git is the main version.
