### ISSUE TITLE
Redhat Install Instructions

### ISSUE THREAD

**Issue by achapkowski** [openstreetmap/osm2pgsql#433]
Hello,

I was wondering if anyone could point me to instructions on how to install osm2pgsql with postgres on a RedHat OS.

Thank you
Andrew

**Comment by pnorman** [comment]
> I was wondering if anyone could point me to instructions on how to install osm2pgsql with postgres on a RedHat OS.

Modern software can be difficult to install on some versions of Redhat/Centos.

For Redhat/Centos 6, see https://github.com/openstreetmap/osm2pgsql/issues/13#issuecomment-128190355 and be prepared to do a lot of work yourself (or hire someone to do it).

Redhat/Centos 7 is more likely to work. If it has recent enough packages, it should just be a matter of installing the appropriate packages and then building. If it doesn't, then look for other RPMs where possible, or build from source if not.

The dependency list in [README.md](https://github.com/openstreetmap/osm2pgsql/blob/master/README.md) should get you started, and the RPM list for Fedora in the same file might be helpful.

Of course, to install it using best practices would also involve packaging osm2pgsql into a RPM, but that's not something we can really help you with

**Comment by pnorman** [comment]
Closing. I could add a Centos/RHEL 7 package list if there's any differences from Fedora, but would need someone to generate the list.
