### ISSUE TITLE
storage efficiency

### ISSUE THREAD

**Issue by cmyk** [openstreetmap/osm2pgsql#436]
I cannot find any documentation on "storage efficiency:".
If I import Switzerland with osm2pgsql 0.86.0 (with psql 9.4.4 and postgis 2.1) I get this line:
```node cache: stored: 25680983(100.00%), storage efficiency: 51.95% (dense blocks: 5753, sparse nodes: 21773462), hit rate: 100.00%```

Could it be closer to 100%?

**Comment by pnorman** [comment]
close to 50% is normal for a small extract.

**Comment by cmyk** [comment]
Europe took up 317GB, that seems a lot.

**Comment by pnorman** [comment]
> Europe took up 317GB, that seems a lot

are you running without --slim?

**Comment by cmyk** [comment]
No, with --slim. Switzerland takes up 6GB. 

Could a postgresql.conf setting be causing this?

**Comment by pnorman** [comment]
How did you get the 317GB value, and what was your osm2pgsql command line?

**Comment by pnorman** [comment]
> Could a postgresql.conf setting be causing this?

No, postgres settings wouldn't cause osm2pgsql to take more memory.

**Comment by cmyk** [comment]
I just did \l+ in psql to see the sizes of the databases.

time osm2pgsql --slim --hstore -d osm --cache 19000 --number-processes 10 -S /home/osm/carto/map/openstreetmap-carto.style /data/files/pbf/europe-latest.osm.pbf

I did compile osm2pgsql from master a couple of days ago. Maybe not such a good idea... Sorry, I'm pretty new to this. I will try again with release 0.88.

**Comment by cmyk** [comment]
I just tested the lastest stable release.
Switzerland is now 5486 mb instead of 6103 mb.
So, I guess that was the problem.

**Comment by pnorman** [comment]
Database size is completely unrelated to storage efficiency, which is about in-memory caching.

317GB sounds about right for all of Europe, when the slim tables (needed for updating) are included.
