### ISSUE TITLE
pgsql_add_relation() is preventing to generate lines/polygons for user-defined tags through lua

### ISSUE THREAD

**Issue by jocelynj** [openstreetmap/osm2pgsql#44]
I want to generate line for type=waterway in addition to already existing types. I have added the corresponding code to style.lua, but was blocked by the following code:
```c
  /* Only a limited subset of type= is supported, ignore other */
  if ( (strcmp(type, "route") != 0) && (strcmp(type, "multipolygon") != 0) && (strcmp(type, "boundary") != 0))
    return 0;
```

This is already handled by style.lua, but it doesn't seem to be present in default tagtransform.

**Comment by pnorman** [comment]
Closing - issue abandoned and not enough information.
