### ISSUE TITLE
insert queries - schema

### ISSUE THREAD

**Issue by bvbever** [openstreetmap/osm2pgsql#445]
Is it possible to give as inputparameter a schema ?

**Comment by pnorman** [comment]
If you are talking about a PostgreSQL SCHEMA, see #279, and setting a default `search_path`.

If you are talking about a different data schema, the `-O` option lets you define the backend to use. The pgsql backend has the tables fixed, but you can customize their contents with the .style file and optionally a Lua tag transform. The multi backend is more configurable and is designed to be able to match an existing schema.
