### ISSUE TITLE
unique ids - force

### ISSUE THREAD

**Issue by bvbever** [openstreetmap/osm2pgsql#446]
Is it possible to force in my postgis db unique osm_id's ?
I do not understand why there are doubles in mn db. Where do thy come from ?
I use my own style.lua

I add delta's (osc) to my db. It seems that I have only dups regarding ferries ?

**Comment by mboeringa** [comment]
See here:
http://gis.stackexchange.com/questions/103572/are-osm-ids-unique-over-all-object-types
http://wiki.openstreetmap.org/wiki/Elements
http://wiki.openstreetmap.org/wiki/Osm2pgsql/schema

**Comment by pnorman** [comment]
The rendering tables do not have a primary key. Two rows with the same ID can occur when

* A long linestring is split
* a MULTIPOLYGON is split into multiple POLYGON rows

The latter can be turned off with `-G`, but even then I wouldn't want to guarantee unique IDs for polygons without checking it.

**Comment by bvbever** [comment]
Thanks for the links Mboeringa. I do known how the datamodel is working.
Pnorman, Is there any possibility that I can alter the code so a long linestring is NOT split ?
Or can you tell me in what file/line it is split ? Then I can alter it myself.

**Comment by rory** [comment]
Just for the record, you can add a unique id to a table in PostgreSQL with this SQL query:

    ALTER TABLE tablename ADD COLUMN gid SERIAL UNIQUE;

This will add a new column (`gid`) and populate it with new, unique, values. Updating the database by applying a diff will still work, and new rows will have new, unique, values.

**Comment by bvbever** [comment]
Rory, Thanks, but thats not my purpose. I want to link some extra information on the osm_id-column of the roads table. Therefore I need unique osm_ids. I want to alter the code, but I do not know where. Do you known ?

**Comment by ImreSamu** [comment]
@bvbever :  maybe you can check/modify  the code here:  
* https://github.com/openstreetmap/osm2pgsql/search?utf8=%E2%9C%93&q=Split+long+ways

And check ["-multi-geometry"  "-G"](https://github.com/openstreetmap/osm2pgsql/blob/master/docs/usage.md#output-data-options) parameter  , as pnorman wrote ...


Alternative  PostGIS solution : 
*  [ST_Union]  ( http://postgis.net/docs/ST_Union.html )

**Comment by ImreSamu** [comment]
@bvbever :  same problem ( #33 )
and the solution - add "split_at = 100000000000;"   :  https://github.com/openstreetmap/osm2pgsql/issues/33#issuecomment-18791842

**Comment by mboeringa** [comment]
> add line: "split_at = 100000000000;" : #33 (comment)

I think there may potentially be very negative consequences of adding that line. Having huge geometries with thousands or even millions of vertices in a single geometry database record, might cause serious performance issues later on when using the data in a GIS or rendering application.

Of course @pnorman is the expert here, but huge geometries can definitely be a pain in any geographic database. I don't think it is without reason the default setup handles these geometries / relations as it does (reducing their impact by splitting them up or distributing individual parts of a multi-polygon over multiple database records).

**Comment by pnorman** [comment]
If you are rendering you do **not** want to disable splitting as performance will suffer severely.

For analysis and complex queries, osm_id is generally close enough to a primary key.

* It is not null
* Any rows with the same osm_id can only differ in `way` and `way_area`
* For real data, the statistical properties are the same, i.e. the number of values is approximately the number of rows

I don't think I've yet encountered a situation where uniqueness is  **necessary**, though it would make some queries easier (e.g. gravitystorm/openstreetmap-carto#596)

If you have additional information about a specific OSM object in another table, you can still JOIN against the osm_id.

ST_Union, ST_Collect, ST_UnaryUnion, and GROUP BY are what you need.

**Comment by rory** [comment]
> I don't think I've yet encountered a situation where uniqueness is necessary

If you want to to set up database replication with [Slony](http://slony.info/), it requires a unique primary key column.

**Comment by pnorman** [comment]
> I used that ALTER TABLE snippet for that.

I'd suggest making it NOT NULL as well.

All cases of using replication I've seen have relied on WAL-based replication.
