### ISSUE TITLE
osc apply not deleting nodes

### ISSUE THREAD

**Issue by jendrusk** [openstreetmap/osm2pgsql#448]
Since some time I found that there are in my database synchronised by osmosis&osm2pgsql points deleted from osm, so I made some test...

1. Found changeset with deleted nodes (http://www.openstreetmap.org/changeset/33591061)
2. Checked if there is a node from this changeset in may database (with select by osm_id) and there is (it shouldn't be because my database should be synchronised)
3. I've downloaded this changeset (http://www.openstreetmap.org/api/0.6/changeset/33591061/download) into file `art.osc` and apply it once again with: /usr/local/bin/osm2pgsql  --number-processes 1 -v -C 2000 -G -K -j -x -s -S ./default.style --append -d osm2pgsql --bbox 13.50,48.50,24.50,55.50  art.osc
4. Checked if there is a node from this changeset in may database (with select by osm_id) and still there is
5. I changed postgres.conf to write all statements and once again run osm2pgsql, [so i get this](https://www.dropbox.com/s/szsr4tv3dsltcdy/postgresql-2015-09-09_134829.log?dl=0)
6. I checked once again with select by osm_id - points are still there...

I can't see any execution of prepared statements at all, so seems like osm2pgsql is not deleting nodes(points) from diff...

Am I doing something wrong with debug? 
Is there any other method of debugging this?
Maybe it is known issue and fixed in latest version?

**Comment by woodpeck** [comment]
Reason is here: https://github.com/openstreetmap/osm2pgsql/blob/8179cdb67e70d7fb5605ab6ddedfd0bd3347db47/parse-osmium.cpp#L64-L66 (or in earlier versions, https://github.com/openstreetmap/osm2pgsql/blob/0.87.4/parse-xml2.cpp#L271-L278). Deleted nodes in .osc files have no coordinates anymore (since mid-2012), hence osm2pgsql cannot decide whether the node falls into your bbox or not.

**Comment by jendrusk** [comment]
@woodpeck Thanx for quick answer, but:

1. I'm quite sure this was working few weeks ( max 2-3 months) ago, maybe it's case of version (I've changed it about 2-3 months ago from first using 64-bit id space), but I'm sure this issue is not lasting from mid-2012 :)

2. I think in most cases using --bbox option is like 'I've got data from this bbox  I'm not interested in other data cause I don't have it in database'...  I don't know any of cases where bbox means I've got data from bbox A and B but you can update only A and you can't touch bbox B... IMO:
- deletes should be processed anyway even if software don't know if it's in bbox or not. All you're risking is trying to delete node that isn't in database so nothing bad will happen, or
- there should be a switch so user can decide what to do with nodes to be deleted by osc.

Without any modification option --bbox is useless, or all software is useless in case if you have only data within some bbox - If I'll use this it will break down my database cause I get all inserts and updates but not deletes, if I'll not use it I'll get all deletes but also inserts where I don't have any other data so I'll get new road in a middle of nothing... After few months I'll get my bbox of map and a lots of garbage around...

First is bad and second not good...

**Comment by pnorman** [comment]
> eleted nodes in .osc files have no coordinates anymore (since mid-2012), hence osm2pgsql cannot decide whether the node falls into your bbox or not.

It's probably safe to just delete then - if it's outside the bbox it won't touch any rows, and if inside, it'll delete it.

Perhaps something like this?

```c++
double lat = node.location().lat();
double lon = node.location().lon();

if (node.deleted()) {
    data->node_delete(node.id());
} else if (bbox.inside(lat, lon)) {
    proj->reproject(&lat, &lon);
    convert_tags(node);
    if (append) {
        data->node_modify(node.id(), lat, lon, tags);
    } else {
        data->node_add(node.id(), lat, lon, tags);
    }
}
```

Of course, I'd want to add a test case so we know the behavior is correct and if there's a regression.

**Comment by jendrusk** [comment]
Hi Paul

I'll be grateful if You'll make needed modifications. I can't help you with this cause I'm not a developer, but I can do some tests and give some feedback :)
