### ISSUE TITLE
Change license to AGPL v3

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/osm2pgsql#450]
Somebody copied code to [parse_o5m.cpp](https://github.com/openstreetmap/osm2pgsql/blob/master/parse-o5m.cpp) from [Osmconvert](http://wiki.openstreetmap.org/wiki/Osmconvert). It's license is [AGPL v3](http://www.gnu.org/licenses/agpl-3.0.en.html). Hence, all osm2pgsql source code should be licensed AGPL v3. None of three conditions of section 5 were met:
* There is no mention of osmconvert, and that the source code was modified.
* There is no mention of AGPL.
* The entire work (osm2pgsql) is licensed not only under AGPL v3, but with an incompatible license.

**Comment by marqqs** [comment]
Hello Zverik, thank you for bringing up this license problem!
I am the author of the file in question and contributed it with the intention that it might become an official part of osm2pgsql source. Therfore it's perfectly allright to apply the same license as for the whole osm2pgsql package: GPL (and not AGPL).
The license description included in https://github.com/openstreetmap/osm2pgsql/blob/master/parse-o5m.cpp is ok with me!
Markus

**Comment by Zverik** [comment]
¯\\\_(ツ)\_/¯
Okay then.

Thanks for your work :) By the way, do you know of any library in any programming language that can write o5m?

**Comment by pnorman** [comment]
Longer-term we're going to be doing all parsing with libosmium, which has an open issue for o5m support, osmcode/libosmium#97. If you need o5m support in your software, that's the place to implement it.

Implementing it in libosmium will also help keep o5m support in osm2pgsql.
