### ISSUE TITLE
Importing Error

### ISSUE THREAD

**Issue by chantalokh** [openstreetmap/osm2pgsql#453]
Hello, 
i am using the 0.87.1 version of osm2pgsql, and when importing the map France i have the following error:

Processing: Node(337173k 44.6k/s) Way(50154k 6.81k/s) Relation(397761 102.67/s)  parse time: 18797s
Node stats: total(337173237), max(3763145667) in 7557s
Way stats: total(50154727), max(372765077) in 7366s
Relation stats: total(397761), max(5543852) in 3874s
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
i tried with the latest map but i get always the same error, have you any idea?
Thanks

**Comment by pnorman** [comment]
Please provide the command line you used, and how much RAM your system has

**Comment by chantalokh** [comment]
hello @pnorman,
the command is : osm2pgsql --slim -d gis -P 5433 -C 3000 --number-processes 4 /users3/osm00/data/france-latest.osm.bz2
and i have 24GO of RAM, but i dont think that it uses all of it, what is the minimum required RAM for the import?

**Comment by lonvia** [comment]
Make sure your system allows to overcommit memory. `cat /proc/sys/vm/overcommit_memory`should return 1 or 0.

To enable overcommit run `echo 0 > /proc/sys/vm/overcommit_memory` as root.

**Comment by chantalokh** [comment]
thank you, i have tried exactelly the same setup on another machine and it worked. i think that's the DirectMap4k parameter that was wrong
