### ISSUE TITLE
ERROR on Importing data into the database [Beginner] 

### ISSUE THREAD

**Issue by wendelllacerda** [openstreetmap/osm2pgsql#456]
I'm following this tutorial to install a OpenstreetMap Tile server (https://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/). I'm using a virtual machine with 2GB RAM and 100GB of memory. But when I run this command appear the following error and I'm not understanding what is happening, someone can help me?

osm2pgsql --slim -d gis -C 16000 --number-processes 3 brazil-latest.osm.pbf 

mapserver@ubuntu:/usr/local/share/maps/brazil$ osm2pgsql --slim -d gis -C 16000 --number-processes 3 brazil-latest.osm.pbf
osm2pgsql SVN version 0.89.0-dev (64bit id space)

Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Out of memory for dense node cache, reduce --cache size
Error occurred, cleaning up

**Comment by SomeoneElseOSM** [comment]
You've got 2Gb memory and have specified a 16Gb cache, so it's 
confused.  It's trying to be helpful by saying "reduce --cache-size" 
(which is the parameter for which -C is the shortcut).

At 271Mb, Brazil in OSM terms is fairly small - it's less than the 
extract that I load into a virtual server with the same memory (2Gb) and 
less disk (20Gb) allocated.  I use " -C 1500" there (as opposed to your 
16000) and it works OK.  I also use "--number-processes 1" as I've only 
one CPU allocated to it.

**Comment by wendelllacerda** [comment]
Ah ok, thank you so much. I was just running this command without fully understanding about...

It works here. :)
