### ISSUE TITLE
Problem during uploading OSM data to POSTGIS 2.1

### ISSUE THREAD

**Issue by Amrizhan** [openstreetmap/osm2pgsql#459]
Hi there

I am building OSM on Windows 8 x64, I installed the PostgresSql v. 9.4.5 And next step was to upload osm data into Postgis using osm2pgsql for Windows x64 and i have next error:

C:\geodata>osm2pgsql -c -d gis -U postgres -H localhost -P 5432 -S C:\geodata\de
fault.style geodata\data\KZ.osm
osm2pgsql SVN version af61cae663 (64bit id space)

release notes: 'Windows version built by Dominik Perpeet (http://www.customdebug
.com/osm2pgsql/index.html)'
Using projection SRS 900913 (Spherical Mercator)
Unknown flag 'nocolumn' line 158, ignored
Unknown flag 'nocolumn' line 159, ignored
Unknown flag 'nocolumn' line 160, ignored
Unknown flag 'nocolumn' line 161, ignored
Unknown flag 'nocolumn' line 162, ignored
Unknown flag 'nocolumn' line 163, ignored
Setting up table: planet_osm_point
NOTICE: table "planet_osm_point" does not exist, skipping
NOTICE: table "planet_osm_point_tmp" does not exist, skipping
SELECT AddGeometryColumn('planet_osm_point', 'way', 900913, 'POINT', 2 );
failed: ERROR: function addgeometrycolumn(unknown, unknown, integer, unknown,
integer) does not exist
LINE 1: SELECT AddGeometryColumn('planet_osm_point', 'way', 900913, ...
^
HINT: No function matches the given name and argument types. You might need to
add explicit type casts.

Error occurred, cleaning up

Thank you for your time and help!!!

**Comment by pnorman** [comment]
> I am building OSM on Windows 8 x64, I installed the PostgresSql v. 9.4.5 And next step was to upload osm data into Postgis using osm2pgsql for Windows x64 and i have next error:

How did you install PostGIS onto the database you are using? With recent versions, it's `CREATE EXTENSION postgis;` See [postgis documentation](http://postgis.net/docs/manual-2.1/postgis_installation.html#create_new_db_extensions) for more info

Additionally, af61cae is a very old version, so if there is an osm2pgsql issue, you'll need to update to a recent version.

**Comment by Amrizhan** [comment]
Where i can download latest osm2pgsql???

**Comment by Amrizhan** [comment]
Thanks, pnorman. i added postgis extension and now i got new error:


C:\geodata>osm2pgsql KZ.osm.pbf -d osm -U postgres -P 5432 -S default.style --hstore
osm2pgsql SVN version 0.69-21289M

Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
NOTICE:  table "planet_osm_point" does not exist, skipping
NOTICE:  table "planet_osm_point_tmp" does not exist, skipping
PREPARE get_way (int4) AS SELECT AsText(way) FROM planet_osm_point WHERE osm_id= $1;
 failed: ERROR:  function astext(geometry) does not exist
LINE 1: PREPARE get_way (int4) AS SELECT AsText(way) FROM planet_osm...
                                         ^
HINT:  No function matches the given name and argument types. You might need to
add explicit type casts.

Error occurred, cleaning up

**Comment by alex85k** [comment]
@Amrizhan 
You can build it yourself by https://github.com/alex85k/winbuilds if you are a developer.

If you need testing exe-s, they are here (automatically generated from Git periodically): 
https://ci.appveyor.com/project/alex85k/osm2pgsql-cmake/build/artifacts

**Comment by pnorman** [comment]
> ```LINE 1: PREPARE get_way (int4) AS SELECT AsText(way) FROM planet_osm...
> ^
> HINT: No function matches the given name and argument types. You might need to
> add explicit type casts.

This is from using an old versio.
