### ISSUE TITLE
proj projection library not found by configure

### ISSUE THREAD

**Issue by shongololo** [openstreetmap/osm2pgsql#463]
UPDATED: 
System: Mac OS X El Capitan

Issue: Proj is available from the terminal on the default paths, but <code>./configure</code> (used without any flags) doesn't find it.

**Comment by shongololo** [comment]
As an update, it works if I add the paths for proj and pg_config manually prior to running autogen and configure.

**Comment by shongololo** [comment]
On further investigation I'm not sure what the issue is. Using a different (but also Mac) system, I was only able to install once downloading and installing proj.4 from github. Thus not sure if the issue is the specific version of proj.4, or if it is that the configure script only looks in the usr/local location.

**Comment by pnorman** [comment]
I believe the script works with the standard location for homebrew installed proj.

What was the full `./configure` line you used, and what is the location of proj_api.h on your system?

**Comment by pnorman** [comment]
You might want to try with #460 and see if the cmake scripts improve it

**Comment by shongololo** [comment]
In my case proj is available from the terminal on the default paths, but the ./configure (used without any flags) doesn't find it. When I use <code>./configure --with-proj=/opt/local</code> then it successfully finds it.

proj_api.h is located in the /opt/local/include/ folder. (MacPorts installation location.)

**Comment by pnorman** [comment]
This is expected behavior for when something is installed in a different location, which MacPorts does. You can use the command line utilities since MacPorts adds wherever it installs binaries to `$PATH`. We could look at adding that location to the proj configure macro, but with #460 in progress, I'd rather fix it there.
