### ISSUE TITLE
Multithreading on Windows

### ISSUE THREAD

**Issue by alex85k** [openstreetmap/osm2pgsql#464]
Currently when running a Windows build tets, I get many warnings
```
1: WARNING: osm2pgsql was compiled without fork, only using one process!
```
But I see that there is no actual fork() in code, only in broken node-persistent-cache-reader.cpp
There are also unused fork-related defines here: 
https://github.com/openstreetmap/osm2pgsql/blob/master/middle-pgsql.cpp#L87

Maybe it is time to remove #ifdef HAVE_FORK from options.hpp and allow Windows users to use multithreading too?
 ( Or maybe it does strictly require Pthread etc.? )

**Comment by lonvia** [comment]
Fixed in #498.
