### ISSUE TITLE
Maybe we can use std::thread only?

### ISSUE THREAD

**Issue by alex85k** [openstreetmap/osm2pgsql#466]
Since osm2pgsql is now fully C++11, maybe it is a time to switch from boost::thread and pthread fragments to std::thread from standard library (like libosmium)? @pnorman  @lonvia 

Its functionality should be enough (I have seen nothing complex). The advantages
  
   - Can get rid of boost::thread dependency (+boost_date_time and boost_chrono on some systems) and related bugs like https://github.com/openstreetmap/osm2pgsql/pull/460#issuecomment-149125399 on clang
   - Make multithreading work on Windows https://github.com/openstreetmap/osm2pgsql/issues/464 :) (pthread should be enough?)
   - There are only 3 files to adapt and 2 of them are just "create n threads -> join":
https://github.com/openstreetmap/osm2pgsql/blob/eece9ac7fd73bf0a922ff98c140953e957de6670/output-pgsql.cpp#L395
https://github.com/openstreetmap/osm2pgsql/blob/eece9ac7fd73bf0a922ff98c140953e957de6670/middle-pgsql.cpp#L1191
https://github.com/openstreetmap/osm2pgsql/blob/eece9ac7fd73bf0a922ff98c140953e957de6670/osmdata.cpp#L244

**Comment by pnorman** [comment]
I'd prelfer to use standard library threads. Particularly instead of pthread.

**Comment by lonvia** [comment]
Jep, moving to std::thread sounds good. I have a partial port somewhere that never made it into master, let me check if it is still usable.
