### ISSUE TITLE
Funny output for empty changeset

### ISSUE THREAD

**Issue by MaxSem** [openstreetmap/osm2pgsql#468]
osm2pgsql SVN version 0.86.0 (64bit id space)

When importing an empty data file (for example, because replication didn't bring in any new data), you get this message:
`node cache: stored: 0(-nan%), storage efficiency: -nan% (dense blocks: 0, sparse nodes: 0), hit rate: -nan%`

**Comment by pnorman** [comment]
I believe the output has changed in recent versions. I think it's still wrong, but now **differently** wrong.

I looked at cache usage in #441 and I'm not sure if this includes the fixed memory cost associated with the dense cache block tracking, which would make the numbers horribly misleading.

**Comment by alex85k** [comment]
By the way, I have the following warning on Windows related to output:
```
osm2pgsql.cpp(48): warning C4477: 'fprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 2 has type 'unsigned __int64'
osm2pgsql.cpp(48): note: consider using '%llu' in the format string
osm2pgsql.cpp(48): note: consider using '%Iu' in the format string
osm2pgsql.cpp(48): note: consider using '%I64u' in the format string

node-ram-cache.cpp(370): warning C4477: 'fprintf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'int64_t'
node-ram-cache.cpp(370): note: consider using '%lld' in the format string
node-ram-cache.cpp(370): note: consider using '%Id' in the format string
node-ram-cache.cpp(370): note: consider using '%I64d' in the format string
node-ram-cache.cpp(378): warning C4477: 'fprintf' : format string '%li' requires an argument of type 'long', but variadic argument 5 has type 'int64_t'
node-ram-cache.cpp(378): note: consider using '%lli' in the format string
node-ram-cache.cpp(378): note: consider using '%Ii' in the format string
node-ram-cache.cpp(378): note: consider using '%I64i' in the format string
```
https://github.com/openstreetmap/osm2pgsql/blob/master/node-ram-cache.cpp#L370
https://github.com/openstreetmap/osm2pgsql/blob/master/osm2pgsql.cpp#L48

Maybe this is related?

**Comment by alex85k** [comment]
By the way, by fixing format we can fix the last warning on MacOS 
https://travis-ci.org/openstreetmap/osm2pgsql/jobs/86858232
and add ``-Werror`` flag for it on Travis.
