### ISSUE TITLE
CMakeLists coding style inconsistent

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#474]
There are two styles in use for spaces and capitalization in CMakeLists.txt

**Comment by pnorman** [comment]
@alex85k and @derdakon are the two writing the most cmake. What style is best to standardize on?

**Comment by DerDakon** [comment]
The upstream style (i.e. what happens in CMake itself) is to lowercase all commands. Where to put spaces (e.g. "set (" vs. "set(") is IIRC inconsistent even there, so I suggest to use the same style as in C++ code.

**Comment by joto** [comment]
Fixed in #979.
