### ISSUE TITLE
Don't rely on dropbox files for appveyor

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#476]
Currently the dependencies for osm2pgsql are brought in from a compressed file on dropbox. This isn't a good practice, particularly if we start distributing the artifacts on appveyor for releases

The file includes
- [ ] ~~Geos~~
- [ ] bzlib
- [ ] expat
- [ ] getopt
- [ ] lua
- [ ] proj.4
- [ ] zlib
- [ ] boost
- [ ] psycopg2 (optional)

The lack of a standard well-adopted packaging system like apt for Windows makes everything harder. Appveyor makes [postgresql available](http://www.appveyor.com/docs/services-databases#postgresql) and allows [installing additional software](http://www.appveyor.com/docs/build-configuration#installing-additional-software) with Chocolatey, Web Platform Installer, or PowerShell.

Of what's in the file, getopt is the only dependency that we could probably do without, if we were moving to a different option parser

**Comment by pnorman** [comment]
geos and proj are available through osgeo4w

Chocolatey seems the most similar to apt, but doesn't have individual libraries. 

* [gtk-runtime](https://chocolatey.org/packages/gtk-runtime) includes expat and zlib, as well as a bunch of stuff we don't need.
* [lua](https://chocolatey.org/packages/Lua) has its own package, but might be dead

Boost has [windows binaries](http://sourceforge.net/projects/boost/files/boost-binaries/)

**Comment by alex85k** [comment]
If Mapbox team agrees, the simplest solution would be to use dependencies pack generated by 
the project https://github.com/mapbox/windows-builds
@springmeyer @BergWerkGIS 

libosmium and OSRM already uses it

**Comment by alex85k** [comment]
Sample uses:
https://github.com/osmcode/libosmium/blob/master/appveyor.yml#L52
https://github.com/Project-OSRM/osrm-backend/blob/develop/appveyor-build.bat

**Comment by pnorman** [comment]
I'd want to make sure that the dependency packs are reproducible - the issue is binary blobs coming in as part of the build process, not just that they're on dropbox.

**Comment by alex85k** [comment]
You can build it yourself or on server by either https://github.com/mapbox/windows-builds or https://github.com/alex85k/winbuilds :)

**Comment by BergWerkGIS** [comment]
No problem, as you like, use package, scripts or roll your own.

Two caveats with https://github.com/mapbox/windows-builds tough:
*  `geos` build is not maintained ATM, but I don't think it will be any trouble to activate it again
* we don't have `psycopg2`

**Comment by lonvia** [comment]
Appveyor dependencies are now on errol. For a discussion on how to rebuild the dependency package see also #742.
