### ISSUE TITLE
Regression tests missing default.style

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#490]
```
test_regression_simple
NOTICE:  database "osm2pgsql-test-25469-1443121178" does not exist, skipping
Couldn't open style file 'default.style': No such file or directory
FAIL
```

Perhaps related to #478

cc @alex85k

**Comment by alex85k** [comment]
Checking...

**Comment by alex85k** [comment]
Seem to pass on Windows from ctest. 

Did you run it manually? Seems it can work only from osm2pgsql folder now (and will not find executable file).

**Comment by alex85k** [comment]
I made it pass manually only by running
```
python tests/regression-test.py -f tests/liechtenstein-2013-08-03.osm.pbf -x G:/winbuilds/osm2pgsql/build/Debug/osm2pgsql.exe
```
from th main osm2pgsql folder.

**Comment by pnorman** [comment]
You're looking at the python test, I was looking at a C++ one.

It failed with ctest and running it from the command line.

**Comment by alex85k** [comment]
Sorry for misunderstanding. I can reproduce only when calling from build folder without ctest:
```
 ./tests/test-output-pgsql-tablespace 
```
ctest explicitly says to use working directory:
```
 add_test(NAME ${test_name} COMMAND ${test_name}
    WORKING_DIRECTORY ${osm2pgsql_SOURCE_DIR})
 ``` 

However, I am not sure if osm2pgsql_SOURCE_DIR is set correctly on old cmake. Which version do you use?

Maybe replacing  ${osm2pgsql_SOURCE_DIR} with  ${PROJECT_SOURCE_DIR} or absolute path can help (then the changes will be needed).

**Comment by pnorman** [comment]
> Sorry for misunderstanding. I can reproduce only when calling from build folder without ctest:
> ```
 ./tests/test-output-pgsql-tablespace 
```

It's important to be able to do this, otherwise it's a huge pain to attach a debugger to the process.

This was also with `tests/test-output-pgsql`, but the problem probably applies to any tests that use default.style

Perhaps as part of the build process we could copy default.style to the build directory?

> However, I am not sure if osm2pgsql_SOURCE_DIR is set correctly on old cmake. Which version do you use?

My testing VM has 2.8.12.2.

Doing a full `git clean -xfd && git reset --hard HEAD` fixed this particular test failing in ctest, but we still need to be able to run a single test in isolation.

**Comment by alex85k** [comment]
Running tests also open many files from tests folder. For now single test can be run from main folder as
```
build/tests/test-output-pgsql-tablespace
```
One solution is to copy all exes into main source folder automatically, another - to copy exes, styles and tests folder into some "testingPack".

**Comment by lonvia** [comment]
Can't you just hand in the source directory into the tests and have them use absolute paths to the required resources?

**Comment by alex85k** [comment]
Yes, maybe that src_dir environment variable we deleted was the best solution. (changed to TESTDATA_DIR, maybe). But this will require patching  all the test.
