### ISSUE TITLE
Error reading file

### ISSUE THREAD

**Issue by luzhskij** [openstreetmap/osm2pgsql#492]
Hi! I'm trying to expand at the planet . I use Linux , Ubuntu.
There is such a mistake -

$ osm2pgsql --create --database allworld --latlong -U postgres -W -H localhost --keep-coastlines --number-processes 4 --cache 24000 --unlogged --flat-nodes /media/node.cache --slim --style /media/openstreetmap.style /media/planet-latest.osm.pbf
osm2pgsql SVN version 0.89.0-dev (64 bit id space)

Using built-in tag processing pipeline
Using projection SRS 4326 (Latlong)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=24000MB, maxblocks=384000*65536, allocation method=11
Mid: loading persistent node cache from /media/node.cache
Allocated space for persistent node cache file
Maximum node in persistent node cache: 0
Mid: pgsql, scale=10000000 cache=24000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /media/planet-latest.osm.pbf
Using PBF parser.
Processing: Node(3068847k 3939.5k/s) Way(241475k 20.40k/s) Relation(0 0.00/s)terminate called after throwing an instance of 'osmium::pbf_error'
  what():  PBF error: truncated data (EOF encountered)

This is due to the file by the planet-latest.osm.pbf, or not?

Sincerely.

**Comment by pnorman** [comment]
Check that the md5 sum of the file you downloaded matches that of the .md5 file of the same name.

**Comment by luzhskij** [comment]
Oh, that's the trouble . It seems that the md5 do not match. I hope that this is the problem .
Thank you.
