### ISSUE TITLE
no polygon generated

### ISSUE THREAD

**Issue by lincoln310** [openstreetmap/osm2pgsql#493]
Hi, i got 6 ways in planet_osm_ways but 0 polygons in planet_osm_polygon. Ways with id in (-230, -211) should be import to polygons.

Following is my osm content.

```xml
  <?xml version='1.0' encoding='UTF-8'?>
<osm version='0.6' upload='true' generator='JOSM'>
  <node id='-229' visible='true' lat='39.11302752166' lon='117.74911767018'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-228' visible='true' lat='39.11302752166' lon='117.74912665333'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-227' visible='true' lat='39.11302055159' lon='117.74911767018'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-226' visible='true' lat='39.11302055159' lon='117.74912665333'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-209' visible='true' lat='39.11301647799' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-207' visible='true' lat='39.11297354243' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-205' visible='true' lat='39.11297214842' lon='117.74912713993'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-203' visible='true' lat='39.11296517835' lon='117.74912713993'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-199' visible='true' lat='39.11302268133' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-197' visible='true' lat='39.11304865175' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-195' visible='true' lat='39.11304865175' lon='117.74913244897'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-193' visible='true' lat='39.11290662981' lon='117.74913244897'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-191' visible='true' lat='39.11290662981' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-189' visible='true' lat='39.11296413284' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-187' visible='true' lat='39.11297214842' lon='117.74911815678'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-185' visible='true' lat='39.11296517835' lon='117.74911815678'>
    <tag k='indoor' v='wall' />
  </node>
  <way id='-230' visible='true'>
    <nd ref='-229' />
    <nd ref='-227' />
    <nd ref='-226' />
    <nd ref='-228' />
    <nd ref='-229' />
    <tag k='indoor' v='wall' />
  </way>
  <way id='-219' visible='true'>
    <nd ref='-199' />
    <nd ref='-197' />
    <nd ref='-195' />
    <nd ref='-193' />
    <nd ref='-191' />
    <nd ref='-189' />
    <tag k='barrier' v='wall' />
  </way>
  <way id='-217' visible='true'>
    <nd ref='-207' />
    <nd ref='-209' />
    <tag k='barrier' v='wall' />
  </way>
  <way id='-215' visible='true'>
    <nd ref='-209' />
    <nd ref='-199' />
    <tag k='room' v='entrance' />
  </way>
  <way id='-213' visible='true'>
    <nd ref='-189' />
    <nd ref='-207' />
    <tag k='room' v='entrance' />
  </way>
  <way id='-211' visible='true'>
    <nd ref='-187' />
    <nd ref='-185' />
    <nd ref='-203' />
    <nd ref='-205' />
    <nd ref='-187' />
    <tag k='indoor' v='wall' />
  </way>
</osm>
```

**Comment by lincoln310** [comment]
<node id='-229' visible='true' lat='39.11302752166' lon='117.74911767018'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-228' visible='true' lat='39.11302752166' lon='117.74912665333'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-227' visible='true' lat='39.11302055159' lon='117.74911767018'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-226' visible='true' lat='39.11302055159' lon='117.74912665333'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-209' visible='true' lat='39.11301647799' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-207' visible='true' lat='39.11297354243' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-205' visible='true' lat='39.11297214842' lon='117.74912713993'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-203' visible='true' lat='39.11296517835' lon='117.74912713993'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-199' visible='true' lat='39.11302268133' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-197' visible='true' lat='39.11304865175' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-195' visible='true' lat='39.11304865175' lon='117.74913244897'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-193' visible='true' lat='39.11290662981' lon='117.74913244897'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-191' visible='true' lat='39.11290662981' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-189' visible='true' lat='39.11296413284' lon='117.74906246123'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-187' visible='true' lat='39.11297214842' lon='117.74911815678'>
    <tag k='indoor' v='wall' />
  </node>
  <node id='-185' visible='true' lat='39.11296517835' lon='117.74911815678'>
    <tag k='indoor' v='wall' />
  </node>
  <way id='-230' visible='true'>
    <nd ref='-229' />
    <nd ref='-227' />
    <nd ref='-226' />
    <nd ref='-228' />
    <nd ref='-229' />
    <tag k='indoor' v='wall' />
  </way>
  <way id='-219' visible='true'>
    <nd ref='-199' />
    <nd ref='-197' />
    <nd ref='-195' />
    <nd ref='-193' />
    <nd ref='-191' />
    <nd ref='-189' />
    <tag k='barrier' v='wall' />
  </way>
  <way id='-217' visible='true'>
    <nd ref='-207' />
    <nd ref='-209' />
    <tag k='barrier' v='wall' />
  </way>
  <way id='-215' visible='true'>
    <nd ref='-209' />
    <nd ref='-199' />
    <tag k='room' v='entrance' />
  </way>
  <way id='-213' visible='true'>
    <nd ref='-189' />
    <nd ref='-207' />
    <tag k='room' v='entrance' />
  </way>
  <way id='-211' visible='true'>
    <nd ref='-187' />
    <nd ref='-185' />
    <nd ref='-203' />
    <nd ref='-205' />
    <nd ref='-187' />
    <tag k='indoor' v='wall' />
  </way>

**Comment by pnorman** [comment]
What style file did you use?

**Comment by lincoln310** [comment]
Hi pnorman, i used default.style.

**Comment by lincoln310** [comment]
Hi pnorman, thank you very much for finger out the reason.

**Comment by pnorman** [comment]
To explain for anyone else finding this, `indoor` is not in default.style, so there's no reason for a way with just an `indoor` tag to be formed into a polygon.
