### ISSUE TITLE
Indexes Failed to Create With Large Data Load (Windows)

### ISSUE THREAD

**Issue by achapkowski** [openstreetmap/osm2pgsql#494]
Hello, 
I am using a windows build of the osm2pgsql.exe and I was loading all of asia from a pbf file from here:
http://download.geofabrik.de/asia.html

I used the following build:
osm2pgsql SVN version 0.89.0-dev (64 bit id space)

All the tables created, but the indexing failed.  I was wondering if someone can provide the sql statements of the sorting and indexing so I can just build it manually.

No errors were printed out, the osm2pgsql.exe just crashes.  

Thank you

**Comment by alex85k** [comment]
The index creating commands are here:
https://github.com/openstreetmap/osm2pgsql/blob/master/table.cpp
(search for CREATE INDEX , name is the database table name)
Not sure if it will help.

Was indexing on smaller extracts successful? Do you have the log of failure to inspect?

**Comment by achapkowski** [comment]
Correct, the indexes built for the geofabrik's extract of Africa (which is smaller). 
Is there a more recent build for windows? Is there a place where users can post their builds?  Maybe I am not using the latest.

I am using PostGRES 9.3 for my DB.  I have roughly 500 GB free HDD space, so I think that is not an issue.  32 GB of RAM, so it's not a memory issue....

Here is the message output from the command window:

C:\data>osm2pgsql.exe --slim --extra-attributes --hstore-all
 -d asia -c -l -S c:\osm2pgsql\default.style -U gis asia-latest.osm.pbf
osm2pgsql SVN version 0.89.0-dev (64bit id space)

WARNING: osm2pgsql was compiled without fork, only using one process!
Using built-in tag processing pipeline
Using projection SRS 4326 (Latlong)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for sparse node cache
Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=9
Mid: pgsql, scale=10000000 cache=800
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: asia-latest.osm.pbf
Using PBF parser.
Processing: Node(455469k 39.1k/s) Way(45955k 1.11k/s) Relation(394930 15.81/s)
parse time: 77920s
Node stats: total(455469977), max(3813186682) in 11658s
Way stats: total(45955671), max(377910487) in 41282s
Relation stats: total(394935), max(5634238) in 24980s
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline

Going over pending ways...
        27011193 ways are pending

Using 1 helper-processes
Finished processing 27011193 ways in 50879 sec

27011193 Pending ways took 50879s at a rate of 530.89/s
Committing transaction for planet_osm_point
Committing transaction for planet_osm_line
Committing transaction for planet_osm_polygon
Committing transaction for planet_osm_roads

Going over pending relations...
        0 relations are pending

Using 1 helper-processes
Finished processing 0 relations in 0 sec

Committing transaction for planet_osm_point
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_line
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_polygon
WARNING:  there is no transaction in progress
Committing transaction for planet_osm_roads
WARNING:  there is no transaction in progress
Stopping table: planet_osm_nodes
Sorting data and creating indexes for planet_osm_point
Stopped table: planet_osm_nodes in 0s
Stopping table: planet_osm_ways
Building index on table: planet_osm_ways
Copying planet_osm_point to cluster by geometry finished
Creating geometry index on planet_osm_point
Creating osm_id index on planet_osm_point
Creating indexes on planet_osm_point finished
All indexes on planet_osm_point created in 1138s
Completed planet_osm_point
Sorting data and creating indexes for planet_osm_line
Copying planet_osm_line to cluster by geometry finished
Creating geometry index on planet_osm_line
Creating osm_id index on planet_osm_line
Creating indexes on planet_osm_line finished
All indexes on planet_osm_line created in 5420s
Completed planet_osm_line
Sorting data and creating indexes for planet_osm_polygon

**Comment by alex85k** [comment]
You can grab automatic build from here:
https://ci.appveyor.com/project/alex85k/osm2pgsql/build/artifacts 
(there will be something like this in main repository too, https://github.com/openstreetmap/osm2pgsql/issues/476 ).

**Comment by alex85k** [comment]
One of the following command seem to fail:
```
        pgsql_exec_simple(sql_conn, PGRES_COMMAND_OK, (fmt("CREATE TABLE %1%_tmp %2% AS SELECT * FROM %1% ORDER BY CASE WHEN ST_IsEmpty(way) THEN NULL ELSE ST_GeoHash(ST_Transform(ST_Envelope(way),4326),10) END") % name % (table_space ? "TABLESPACE " + table_space.get() : "")).str());
        pgsql_exec_simple(sql_conn, PGRES_COMMAND_OK, (fmt("DROP TABLE %1%") % name).str());
        pgsql_exec_simple(sql_conn, PGRES_COMMAND_OK, (fmt("ALTER TABLE %1%_tmp RENAME TO %1%") % name).str());
        // Re-add constraints if on 1.x. 2.0 has typemod, and they automatically come with CREATE TABLE AS
        pgsql_exec_simple(sql_conn, PGRES_TUPLES_OK, (fmt("SELECT CASE WHEN PostGIS_Lib_Version() LIKE '1.%%' THEN Populate_Geometry_Columns('%1%'::regclass) ELSE 1 END;") % name).str());
```

If the base is still in that sate you can try to execute manually
```
CREATE TABLE planet_osm_polygon_tmp AS SELECT * FROM planet_osm_polygon ORDER BY CASE WHEN ST_IsEmpty(way) THEN NULL ELSE ST_GeoHash(ST_Transform(ST_Envelope(way),4326),10) END
DROP TABLE planet_osm_polygon
ALTER TABLE planet_osm_polygon_tmp RENAME TO planet_osm_polygon
SELECT CASE WHEN PostGIS_Lib_Version() LIKE '1.%%' THEN Populate_Geometry_Columns('planet_osm_polygon'::regclass) ELSE 1 END;"
```

**Comment by alex85k** [comment]
I have prepared a testing version with option to disable indexing.
https://ci.appveyor.com/project/alex85k/osm2pgsql/build/1.0.123/artifacts

```
set INDEX_SQL_FILE=makeindex.sql
osm2pgsql .....
=> all indexing sqls will be in makeindex.sql file for future manual exec in future 
```

**Comment by alex85k** [comment]
Updated the testing build: https://ci.appveyor.com/project/alex85k/osm2pgsql/build/artifacts

**Comment by martin-s** [comment]
Is there a current windows build available on appveyor?
I think the latest thread updates are not included in artifacts. Right?

**Comment by lonvia** [comment]
Closing as this refers to a very old version of osm2pgsql. Open a new issue if you encounter something similar. Regular windows builds are available via [Appveyor](https://ci.appveyor.com/project/openstreetmap/osm2pgsql/history) (choose a build and select artifacts).
