### ISSUE TITLE
Some failing tests

### ISSUE THREAD

**Issue by alex85k** [openstreetmap/osm2pgsql#499]
Here is the test log I got on Windows with current master branch.
https://gist.github.com/alex85k/e04ba9f9e60b0f15c868

Few days ago these tests passed. Trying old commits showed that 650ed3fc1be has this errors but 60f5493e162 has not (the tests pass).

Seems that this merged branch https://github.com/pnorman/osm2pgsql/tree/multi_area and the tests are not synced. 
@pnorman or this is windows-only problem?

**Comment by pnorman** [comment]
more info: https://github.com/openstreetmap/osm2pgsql/pull/471#issuecomment-153880316

**Comment by lonvia** [comment]
Got fixed a long time ago.
