### ISSUE TITLE
Impossible to import only linear data

### ISSUE THREAD

**Issue by Komzpa** [openstreetmap/osm2pgsql#510]
For my task, I need only highways from OSM in the database, as lines.

I wrote a style for osm2pgsql that basically is just:
```way    highway       text        linear```

osm2pgsql fails to create such a database,
```Osm2pgsql failed due to ERROR: No columns provided for table geocode_osm_point```

I'll work around it for now, but I think thematic databases is a thing to support :)

**Comment by pnorman** [comment]
duplicate of #272
