### ISSUE TITLE
some multipolygons don't get created when using --proj 4326

### ISSUE THREAD

**Issue by TobWen** [openstreetmap/osm2pgsql#514]
osm2pgsql is not building some multipolygons when using --proj 4326.

Have a look at this relation:
```wget -O nrw.osm http://www.openstreetmap.org/api/0.6/relation/62761/full```
or its simiplied version (only have the size and faster to download):
 ```wget -O nrw.osm https://clbin.com/nbVgx```

I've imported it like this using the default.style with and without --multi-geometry using osm2pgsql c8265f809e3c809638040db750477ba2963cc0ee:
```
osm2pgsql --create --database testcase --proj 4326 nrw.osm
```

The resulting administrive area can't be found in planet_osm_polygon, it can be found splittet in more than 20 pieces in planet_osm_line.

Import works as expected when using native mercator projection:
```
osm2pgsql --create --database testcase nrw.osm
```

**Comment by lonvia** [comment]
I've checked as far back as 0.86 and it doesn't work there either.

Note that it works with `-l` which essentially is the same as `--proj 4326` only faster.
