### ISSUE TITLE
New master build needs specifying default style

### ISSUE THREAD

**Issue by hyperknot** [openstreetmap/osm2pgsql#515]
A month or so ago, before the CMAKE version I was able to run this command.

```
osm2pgsql --create --slim --drop --hstore --flat-nodes flat.bin --cache 26000 --number-processes 8 --database osm planet-latest.osm.pbf
```

Today, with the new CMAKE build, the command fails with:
```
Osm2pgsql failed due to ERROR: Couldn't open style file './default.style': No such file or directory
```

Adding the --style argument as below, fixes it.
```
--style /usr/local/share/osm2pgsql/default.style 
```

OS is FreeBSD 10.2.

**Comment by joshchernoff** [comment]
I was running into this on arch linux. It never gave an error but because no styles had been specified all my columns like attr:housenumber was null. Took me awhile to realize it was not using the default styles though the file was found `/usr/share/osm2pgsql/default.style`

**Comment by joshchernoff** [comment]
Clearly this is old but I found this as a result of googling this very issues so it has relevant to say if you run into unexpected behavior this is likely an issue. For me it was not aware there even was a default styles let alone it was not loading by default and that I had to be specific about it. I assume its own its probably a bug even for newer supported versions which I'm likely running.
