### ISSUE TITLE
osm2pgsql applies building=yes to all members of a multipolygon (for some relations). 

### ISSUE THREAD

**Issue by skorasaurus** [openstreetmap/osm2pgsql#52]
I'm running postgis 2.0.1, psql 9.1.9, master of osm2pgsql, ubuntu 12.04, 64bit. 

Note this problem does not occur for people using 0.81. 

 SELECT landuse, building FROM planet_osm_polygon WHERE osm_id=-2901483;  
 SELECT landuse, building FROM planet_osm_polygon WHERE osm_id=-2915918;  
 SELECT landuse, building FROM planet_osm_polygon WHERE osm_id=-2934273;   

First query returned landuse=residential, 
2nd query, blank on both, 
both were expected behaviors, but in this third query, 
[for this relation](http://www.openstreetmap.org/browse/relation/2934273), I received a landuse=residential and building=yes  
even though this relation was a type=multipolygon relation. 

Building=yes is attributed for all polygons in this relation although these member areas are not all buildings. 

I realize these relations, created for the HOT task manager, are hackish, but they may be other use cases where this happens.

**Comment by lonvia** [comment]
Fixed by dropping all old-style multipoygon handling.
