### ISSUE TITLE
amount of processed relations is wrong

### ISSUE THREAD

**Issue by TobWen** [openstreetmap/osm2pgsql#523]
Verbose output of osm2pgsql outputs "Finished processing 0 relations in 0 sec", that doesn't seem correct.

Though, "Finished processing 7773617 ways in 237 sec" actually is correct.

**Comment by pnorman** [comment]
> Verbose output of osm2pgsql outputs "Finished processing 0 relations in 0 sec", that doesn't seem correct.

What's wrong with it? If this is an import there are no pending relations, so there's nothing to be done in that stage

**Comment by TobWen** [comment]
Why don't you call it "pending relations" then? Right now, it suggest to be the processing time of relations. Sorry, I just want to clean up the unclear output of the tool.
