### ISSUE TITLE
switch to turn off clustering

### ISSUE THREAD

**Issue by TobWen** [openstreetmap/osm2pgsql#525]
Right now, osm2pgsql creates prefix_* on import. Then the data gets copied to a table called prefix_*_tmp by a selection ordered by GeoHash. Afterwards, the old prefix_* gets removed and prefix_*_tmp is renamed to prefix_*. Before the old table gets removed, the import takes twice the amount on the disk (the original import and its sorted copy).

Could you please add a switch to turn off clustering of databases (using GeoHash)? Sure, there's a benefit in sorting data on the drive, but on smaller SSDs, there will be problems importing big datasets. Since there's an index on the geometry and since updates don't get sorted at all, turning off "sort in index" might be a solution for users with small SSDs only.

**Comment by pnorman** [comment]
#27 would cover this
