### ISSUE TITLE
"Targets may link only to libraries."

### ISSUE THREAD

**Issue by shongololo** [openstreetmap/osm2pgsql#531]
When installing to Mac El Capitan 10.11.3:

The default installation finds the system geos framework but when I try to override this by editing `CMakeCache.txt` to my macports version then I get a list of warnings to this effect:

```
Target "osm2pgsql" requests linking to directory "/opt/local/include/geos".  Targets may link only to libraries.  CMake is dropping the item.
```

Then `make` subsequently fails with errors to this effect:

```
Undefined symbols for architecture x86_64:
etc.
```

Any ideas for what is wrong or how to get cmake to accept the macports geos?

**Comment by pnorman** [comment]
You shouldn't edit CMakeCache.txt.

> If some installed dependencies are not found by CMake, more options may need to be set. Typically, setting `CMAKE_PREFIX_PATH` to a list of appropriate paths is sufficient.

**Comment by pnorman** [comment]
After #684 we no longer use geos, so this is a moot point.
