### ISSUE TITLE
Enhance with a datamodel option, using JSONB

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/osm2pgsql#533]
Suggestion to discuss (and plan) a future option to store tags and other attributes  in a unique and flexible [JSONB](http://www.postgresql.org/docs/9.5/static/datatype-json.html) field.

Typical case: the  `tags` field (of _planet_osm_nodes, planet_osm_rels_ and _planet_osm_ways_) can be converted to JSONB with `jsonb_object()`...  But perhaps some changes more in [Osm2pgsql/schema](http://wiki.openstreetmap.org/wiki/Osm2pgsql/schema), simplifying tables &mdash; migrating many attributes to the JSONB attribute.

 ("other attributes"  = information that is not geometry neither primary-key or foreign-key).

**Comment by pnorman** [comment]
What advantages would JSONB have over hstore?

JSONB is actually possible right now, declare a column as it, and use a lua transform which produces a string which casts cleanly to jsonb.

ClearTables does something similar [creating an array](https://github.com/pnorman/ClearTables/blob/3abfd71f0c46dd59408ef1bcbf965bc6230b24b2/common.lua#L117-L127) which is used for [ref tags](https://github.com/pnorman/ClearTables/blob/3abfd71f0c46dd59408ef1bcbf965bc6230b24b2/transportation.lua#L95) to fill a [`text[]` column](https://github.com/pnorman/ClearTables/blob/3abfd71f0c46dd59408ef1bcbf965bc6230b24b2/cleartables.yaml#L141-L142)

**Comment by ppKrauss** [comment]
Hi @pnorman,  thanks for reply!  "What advantages would JSONB have over hstore?", hum... Is not a kind of "optional flavor",

*  today [JSON](http://www.json.org/) is a [*de facto* standard](https://en.wikipedia.org/wiki/De_facto_standard) for all web applications;  and [*de jure*](https://en.wikipedia.org/wiki/De_jure) since [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) in 2013 and [RFC 7159](https://tools.ietf.org/html/rfc7159) in 2014. <br/>Is also the [W3C standard for linked data](http://json-ld.org/), for [tabular metadata](https://www.w3.org/TR/tabular-data-model/), and the a *de facto* standard for many no-SQL databases as Zorba and MongDB... So, JSON also enhances flexibility, user-community, conectivity and [data interchange](https://en.wikipedia.org/wiki/Electronic_data_interchange).

* The [database  support (functions, convertions and operations)](http://www.postgresql.org/docs/9.5/static/functions-json.html)  is so better!!

* The queries will be simple, and stored data so efficient with [JSONB](http://www.postgresql.org/docs/9.5/static/datatype-json.html).

* ... etc. PS: see also [convertions at this answer](http://stackoverflow.com/a/35617429/287948).

And is not  a proposal to convert (duplicating information and CPU time), but to produce directly tables with JSONB, and perhaps review the *database model* to enhance the database flexibility and simplifying data model.

**Comment by pnorman** [comment]
Generally you should **not** be querying the slim tables (nodes, ways, and rels). You cannot depend on them existing, as they depend on import settings and are  internal to osm2pgsql and not structured to be easy for other applications to query.

We'd actually like to drop them all for something similar to flat-nodes.

> * The [database  support (functions, convertions and operations)](http://www.postgresql.org/docs/9.5/static/functions-json.html)  is so better!!

I don't see that JSONB offers any operators that would be useful that hstore doesn't.

**Comment by ImreSamu** [comment]
Hi @ppKrauss,
Interesting topic,  Do you have some  performance benchmarks?  ( jsonb vs hstore )
I only find this thread :  https://www.reddit.com/r/PostgreSQL/comments/36rdlr/improving_select_performance_with_jsonb_vs_hstore/

**Comment by drkludge** [comment]
I found this 2014 video that provides timing performance on XML, HSTORE, JSON, and JSONB.
https://www.youtube.com/watch?v=p04XnSDED_M
These two videos have more information on recent efforts with JSONB mid 2015.
https://www.youtube.com/watch?v=4SaBDf3EliU&list=PLWW0CjV-TafZo4lBWuzw7OYJY7Y4SW76B&index=9

https://www.youtube.com/watch?v=ln2WUAH0-LA&list=PLWW0CjV-TafZo4lBWuzw7OYJY7Y4SW76B&index=10

**Comment by ppKrauss** [comment]
Hello, thanks for all (@drkludge , @ImreSamu , @pnorman), I think there are some commom understand about JSONB datatype in persistent storage (most of osm2pgsql users need *tags*  only to read) advantages (!) and the relevance to offer an option to this *standard format* (JSON(B) is a standard and a build-in format) .

Next step (in a "roadmap" to this issue) will be basic implementation and sub-options:

* **Options `--json` and `--jsonb`** are possible, but I recomend use of JSONB only.
 
* **Simplest implementation**: Simplest but CPU-time consuming and disk consuming. Use [`hstore_to_json()`](http://www.postgresql.org/docs/9.5/static/hstore.html) and [`json_object()`](http://www.postgresql.org/docs/9.5/static/functions-json.html) as [suggested here](http://stackoverflow.com/a/35617429/287948), and `ALTER TABLE` to add new columns and (after convertion) drop old columns.

* **Better implementation** (no add/convert/drop columns): need some review and development. A first and simplest optiomization is to convert extra-tags (today this is the *hstore* option) directly into JSOB, without need for `hstore_to_json`.

* **Other (sub) options**: the main is to simplify table (SQL structures), moving some non-indexed columns  to the JSONB structure... We need first (to discuss) to document structure, as suggested at issue #535 (must reopen).

**Comment by pnorman** [comment]
> Generally you should not be querying the slim tables (nodes, ways, and rels). You cannot depend on them existing, as they depend on import settings and are internal to osm2pgsql and not structured to be easy for other applications to query.

To clarify, are you suggesting changes to the nodes, ways, and relations tables, or changes to the rendering tables?

**Comment by ppKrauss** [comment]
Hi @pnorman let's  start some design and drafts!... Do you have a **UML class diagram** of tables generated by  `osm2pgsql`?  

My suggestion is a option that produce another table structure... General ideia:

**WITHOUT the option**

```sql
CREATE TABLE sometable1 (
  id serial NOT NULL PRIMARY KEY,
  mainfield11 int,
  mainfield12 geometry(LINESTRING,4326),
  otherfield11 int,
  otherfield12 text,
  otherfield13 int,
  UNIQUE(mainfield11)
);

CREATE TABLE sometable2 (
  id serial NOT NULL PRIMARY KEY,
  fk bigint REFERENCES sometable1(id),
  mainfield21 int,
  mainfield22 text,
  otherfield21 int,
  otherfield22 text,
  otherfield23 int,
  UNIQUE(mainfield21,otherfield21)
);
```
**WITH the JSONb option**

More compact and stable  structure (not changes basic structure with future field changes),
 
```sql
CREATE TABLE sometable1 (
  id serial NOT NULL PRIMARY KEY,
  mainfield11 int,
  mainfield12 geometry(LINESTRING,4326),
  info JSONb
  UNIQUE(mainfield1)
);

CREATE TABLE sometable2 (
  id serial NOT NULL PRIMARY KEY,
  fk bigint REFERENCES sometable1(id),
  mainfield21 int,
  otherfield21 int,
  info JSONb,
  UNIQUE(mainfield21,otherfield21)
);
```

The only rule, to not move a field to JSONb, is that is "the field is in structural use": non-trivial datatypes (as *geometry* and *geography*), PRIMARY KEY, REFERENCES (FOREIGN KEY), UNIQUE, CHECK, etc. Some (subjective election) fields are "main" so we can preserve as SQL datatype. 

We can also offer SQL VIEWs to obtain the old tables again,

```sql
CREATE VIEW old_sometable1 AS
   SELECT *, 
     info->>'otherfield11'::int as otherfield11, info->>'otherfield12' as otherfield12, info->>'otherfield13'::int as otherfield13 
  FROM sometable1;

CREATE VIEW old_sometable2 AS
   SELECT *,   info->>'mainfield22' as mainfield22,
     info->>'otherfield22'::int as otherfield22, info->>'otherfield23' as otherfield23 
  FROM sometable2;
``` 
The internal representation of `otherfield11`, `otherfield22`, etc.   is in fact *integer*, but is "JSONb number", so it need a CAST to "SQL integer" in PostgreSQL 9.6 to express non-*text* fields.
 

----

> JSONB is actually possible right now, declare a column as it, and use a lua transform which produces a string which casts cleanly to jsonb.

Perfect!  Can you show an little draft with this lua script? In principle the transform can be also after usual tables build, a `psql` script... But a previous transform save some memory and CPU time.

**Comment by pnorman** [comment]
> Do you have a UML class diagram of tables generated by osm2pgsql?

No, and the tables generated depend on the style file. If you *really* want a diagram, run it and put the schema through a tool. 

> Perfect! Can you show an little draft with this lua script? In principle the transform can be also after usual tables build, a psql script... But a previous transform save some memory and CPU time.

https://github.com/ClearTables/ClearTables/blob/v0.0.4/util.lua#L48-L59 is what I do with hstore, and then it gets cast with the COPY command. The same can be done with json or jsonb.

-----

After talking to others, I'm closing this.

The slim table schema is an internal implementation detail of osm2pgsql, so outside use is not a concern.

For the rendering tables, it is already possible to have a jsonb column. The submitter is using examples unrelated to the osm2pgsql. Our rendering tables don't have foreign keys, serials, unique constraints, or links between them. An example showing current tables and proposed changes would have been more convincing as it would have been relevant to osm2pgsql.

**Comment by ppKrauss** [comment]
Hi @pnorman , sorry about my non-contextual copy/pasted examples  (I am in holidays and not at my work computer), but the generic example was didactic... To contextualize with real tables  ideal is a consensual *big picture* of the "default" and "most used" output structures, that I suggesting in #671

-----

> is what I do with hstore, and then it gets cast with the COPY command. ...

We all can do *cast* with `hstore_to_jsonb_loose()` and work with PL/pgSQL functions, shell scripts, etc. But this proposal is to simplify this task and standardise for all *osm2pgsql* users a reliable JSONb adaptation. 

**... Let's split and simplify  _this issue_**,

* suggestion 1: simplify consumption of OSM data ...  ClearTables  is great! migrating this part of the issue to [ClearTables/issues/98](https://github.com/ClearTables/ClearTables/issues/98)

* suggestion 2: a new option to use JSONb instead hstore... See  #672.
