### ISSUE TITLE
Extreme slowdown while importing ways

### ISSUE THREAD

**Issue by ekr3peeK** [openstreetmap/osm2pgsql#534]
While trying to import a planet PBF file, on a 16 GB ram, 8 core system, with non-SSD hard drives, when I reach to the part of importing ways, I run into an extreme slowdown. While the nodes are importing with a ~1500k/s speed, the ways are only importing with 0.05k/s-0.12k/s (ocassionaly rising up to 0.44k/s, but then dropping down immediatly).

I am using the following parameters to run the script: -lsc -O gazetteer --hstore --number-processes 6 --slim -s -C 12000 --flat-nodes \<filename\> (I am running osm2pgsql through the Nominatim setup.php file, and modified some data in it, for experimenting, but nothing seems to help to speed up the import of ways)

Browsing through the internet, other people experienced this same problem, but I couldn't find any solution to it. What could cause this error? What other options could I try?

(For a detailed description to my problem, I've also posted to StackOverflow, and OSM Help, but no answer arrived there, here's a link: http://stackoverflow.com/questions/35632180/osm2pgsql-importing-of-an-openstreetmaps-planet-file-takes-very-long )

**Comment by pnorman** [comment]
Ways per second and nodes per second are not comparable - they're measuring different things and in different units.

What speed hard drive are you using?

Although it doesn't impact performance, I'd suggest cleaning up your command line, you're specifying slim mode three times.

**Comment by ekr3peeK** [comment]
I know that importing of ways supposed to be slower then that of nodes, but this slowdown seems a bit extreme to me. Analyzing some of the benchmarks (which indeed were made with better machines then the one I am using), they doesn't encounter such a signficant speed loss when importing the ways. With these speeds, and based on OSM data, to import the whole planet file, it would take about 2-3 months (considerng that relations would be even slower then ways, and we have yet to index the data).

Don't get me wrong, I am not expecting miracles here, I know that the import would take a long time, but 2-3 months is just a bit too long for me. I was expecting a 15-18 days data import, and I would be okay with that.

I don't know how to check correctly the speed of the hard drive, cause I am rather new to Linux, but I've used this command I've found on the net with the following results:

hdparm -tT /dev/sda

/dev/sda:
 Timing cached reads:   11444 MB in  2.00 seconds = 5729.45 MB/sec
 Timing buffered disk reads: 264 MB in  3.01 seconds =  87.79 MB/sec

(Note, that the import process was still running while I've used the command, I don't know if that affects the performance of hdparm or not)

**Comment by pnorman** [comment]
> I know that importing of ways supposed to be slower then that of nodes, but this slowdown seems a bit extreme to me.

The problem isn't that ways are going slower than nodes, it's that ways are slower than you're expecting.

> Analyzing some of the benchmarks

Past benchmarks are often unapplicable, since they were done when OSM was smaller.

> I don't know how to check correctly the speed of the hard drive

The rotational speed of the drive is the main parameter that matters. bonnie++ can give you iops.

**Comment by ekr3peeK** [comment]
This is the result bonnie++ gives with the following parameters:
bonnie++ -d /root/test -r 15886 -u root

Version  1.96       ------Sequential Output------ --Sequential Input- --Random-
Concurrency   1     -Per Chr- --Block-- -Rewrite- -Per Chr- --Block-- --Seeks--
Machine        Size K/sec %CP K/sec %CP K/sec %CP K/sec %CP K/sec %CP  /sec %CP
myserver.server 31772M   536  98 129442  20 58196   9  2712  98 165346  11 403.6   4
Latency             17336us     238ms    1111ms   16821us     126ms     985ms
Version  1.96       ------Sequential Create------ --------Random Create--------
myserver.server -Create-- --Read--- -Delete-- -Create-- --Read--- -Delete--
              files  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP  /sec %CP
                 16 +++++ +++ +++++ +++ +++++ +++ +++++ +++ +++++ +++ +++++ +++
Latency                97us     543us     457us      90us      15us      67us
1.96,1.96,myserver.server.server,1,1456477892,31772M,,536,98,129442,20,58196,9,2712,98,165346,11,403.6,4,16,,,,,+++++,+++,+++++,+++,+++++,+++,++
+++,+++,+++++,+++,+++++,+++,17336us,238ms,1111ms,16821us,126ms,985ms,97us,543us,457us,90us,15us,67us

**Comment by ekr3peeK** [comment]
Some additional data from a program called perpeton:

Basic
		CPU Usage	
34.41 %
		IOWait	
2.72 %
		Load	
2.37
		Memory Usage	
76.62 %
	Apache
		CPU Usage	
0 %
		Memory Usage	
0.01 %
		Disk Read	
4 KBytes
		Disk Write	
8 KBytes
		Web Requests	
0
		Outgoing Traffic	
0 Bytes
	Disk I/O - sda
		Read	
885.56 MBytes
		Write	
1.52 GBytes
		Activity	
36.15 %
	Disk I/O - sda1
		Activity	
0 %
	Disk I/O - sda2
		Activity	
35.83 %
	Disk I/O - sdb
		Read	
0 Bytes
		Write	
0 Bytes
		Activity	
0 %
	Disk Usage - /
		Usage	
7.95 %
	MySQL
		CPU Usage	
0.01 %
		Memory Usage	
0.07 %
	PostgreSQL
		CPU Usage	
4.88 %
		Memory Usage	
5.53 %
		Active Connections	
5
		Disk Read	
13.27 MBytes
		Disk Write	
404.45 MBytes
		Autovacuum Disk Read	
0 Bytes
		Autovacuum Disk Write	
0 Bytes
		Autovacuum Processes	
0
		Pagefault Ratio	
5.52 %
	Swap
		Usage	
2.69 %
		Used Space	
217.32 MBytes

**Comment by ekr3peeK** [comment]
Ok, while processing the ways, the disk which contains the flatnode file, es being used at 100%, and while processing the node, it was able to read/write to the disk with ~1GB/s and a usage of 20%, now it reads and writes with less then 1Gb/s and at a load of 100%. Any idea why is this happening?

**Comment by mboeringa** [comment]
See this:
https://github.com/openstreetmap/osm2pgsql/issues/517#issuecomment-164551795

**Comment by pnorman** [comment]
After talking to others, the speed experienced here is about what would be expected for a machine with 16GB of RAM and a 7200 RPM drive. To get better speed, use SSDs and more RAM.
