### ISSUE TITLE
Update documentation, is from 2011 and is outdated

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/osm2pgsql#535]
The basic documentation about data structure is at http://wiki.openstreetmap.org/wiki/Osm2pgsql/schema
and is outdated.

**Comment by pnorman** [comment]
The osm2pgsql documentation is stored in this repository. Wiki pages are independent of osm2pgsql, and frequently wrong.

**Comment by ppKrauss** [comment]
Hum... https://github.com/openstreetmap/osm2pgsql/tree/master/docs have no equivalent documentation: **about data structure**.
