### ISSUE TITLE
Introductory README for docs 

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/osm2pgsql#538]
An introductory `README.md` for topics presentation at [docs](https://github.com/openstreetmap/osm2pgsql/tree/master/docs) folder will be fine;   is important for enhance collaboration, and for user-friendly analisys of documents (linking all in the introduction as a "content hub").

**Comment by lonvia** [comment]
README.md in the main directory already does this. It could be a bit better organised but that is a different issue.
