### ISSUE TITLE
Store slim coordinates in unprojected units

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#542]
Storing coordinates as scaled projected units means that it is necessary to scale differently for different projection, leading to bugs like #121 and untested code in #357

Instead, we should store unprojected WGS84 units as they are in the OSM file.

**Comment by Komzpa** [comment]
Please also don't limit them to fixed point, as most reprojections will require floating point math.

**Comment by pnorman** [comment]
The plan is to use libosmium. iirc, this is fixed precision and internally uses 64 bits to store the location. This says nothing about if it can do floating point math, which shouldn't be a problem.
