### ISSUE TITLE
multipolygon ended up in _lines table?

### ISSUE THREAD

**Issue by grinapo** [openstreetmap/osm2pgsql#554]
This is 0.88.1 in Debian. 

The relation 6026949 was created and it was processed in from the minute diffs, and it ended up in the planet_osm_line as a linestring from the "two top nodes" of the poly. I don't see why these two and I don't see why in _line. 

I expected it to be in _polygon and with full geometry.

**Comment by TobWen** [comment]
It doesn't solve your problem directly, but most of the OpenStreetMap users don't like using multipolygons for normal buildings. Of course, it's correct from the topological way, but two simple polygons will have the same result and won't make problems with osm2pgsql :)

**Comment by pnorman** [comment]
Does this happen when importing as opposed to diffs?

**Comment by grinapo** [comment]
@TobWen you are right: absolutely not solving it. :-) One question is that why topo errors are generated from a topolologically correct object; other question is that why people _generally_ don't like multypoligons, regardless of whether it's a building, a forest, a park or anything else. And these people are opposed by the people who similarly dislike heaps of overlapping edges, overlapping (often duplicated) nodes and alike. :-) 
And to be honest: I could have been went on and mapped it correctly, with perimeter wall, stories, roof and wall color, which would have involved multipolygon _relationships_, but I practiced mercy on others. :-) 
See: http://wiki.openstreetmap.org/wiki/Relations/Proposed/Buildings
http://wiki.openstreetmap.org/wiki/Simple_3D_buildings

**Comment by grinapo** [comment]
@pnorman I cannot tell you unless I start with a clean import. (That's why I have given the exact object id for all of you to be able to check your possible local copies.) 
However if I do I cannot reproduce it anymore. :-) What would you like me to do? I can do a clean import with no problem (I guess :-)).

**Comment by lonvia** [comment]
I can't reproduce that anymore. Please reopen if you find a reproducible case on the latest osm2pgsql.
