### ISSUE TITLE
store all relation tags to hstore

### ISSUE THREAD

**Issue by TobWen** [openstreetmap/osm2pgsql#556]
Right now, "type" of relations doesn't seem to get stored to hstore.

**Comment by TobWen** [comment]
Sorry for pushing this. Can anyone please give me a hint, where the type gets filtered out?

**Comment by pnorman** [comment]
https://github.com/openstreetmap/osm2pgsql/blob/master/tagtransform.cpp#L132-L134

```cpp
for (const auto& rel_tag: rel_tags) {
    //copy the name tag as "route_name"
    if (is_route && (rel_tag.key == "name"))
        out_tags.push_dedupe(tag_t("route_name", rel_tag.value));
    //copy all other tags except for "type"
    if (rel_tag.key != "type")
        out_tags.push_dedupe(rel_tag);
}
```

This is intentional. If you want to have this information in your database, using your own Lua tag transform is your best bet.

**Comment by TobWen** [comment]
Thanks for pointing me to the line! 

Sorry for asking, but why is it intentional? I think, it's pretty useful to figure out, if the type is road, power or whatever and "extra attributes" seems to be the right place in my eyes. I don't want to discuss about it, just want to understand the discussion you had about it :)

**Comment by pnorman** [comment]
type is always route, boundary, or multipolygon. It would be undesirable to have type=multipolygon on every MP, as that's a detail of the geometry representation, not the object being represented in OSM data.

**Comment by TobWen** [comment]
Sorry for answering again.. I'm **not** talking about _type=route_! _route=*_ is missing in hstore tags, so you can't figure out the route's subtype.
