### ISSUE TITLE
extra-attributes default.style parsing failed

### ISSUE THREAD

**Issue by F6F** [openstreetmap/osm2pgsql#558]
I started an import while having -x set and the 
extra attributes block in the default.style uncommented

like this way:
osm_user - datatype text
osm_uid - datatype integer
osm_version - datatype integer
osm_changeset - datatype integer
osm_timestamp - datatype timestamptz(0)

[default.style.txt](https://github.com/openstreetmap/osm2pgsql/files/175223/default.style.txt)

osm2pgsql version 0.91.0-dev (64 bit id space)

Unknown flag 'text' line 75, ignored
Osm2pgsql failed due to ERROR: Weird style line ../../default.style:75

**Comment by lonvia** [comment]
> like this way:
> osm_user - datatype text
> osm_uid - datatype integer
> osm_version - datatype integer
> osm_changeset - datatype integer
> osm_timestamp - datatype timestamptz(0)

This is just a list with descriptions not something to 'uncomment'. Add properly formatted rows for each attribute, e.g.

    # OsmType   Tag         DataType       Flags
    node,way    osm_user    text           polygon

Refer to the documentation in the style file for the meaning of each column.
