### ISSUE TITLE
modified relation removes existing way and adds it again

### ISSUE THREAD

**Issue by TobWen** [openstreetmap/osm2pgsql#559]
Why is this changefile (a synthethic one derived from original) removing the row with osm_id 47036578 from planet_osm_line and inserting it again without a change to tags or geometry? Where does it get this instruction from?

```
<?xml version='1.0' encoding='UTF-8'?>
<osmChange version="0.6" generator="test">
<modify>
	<relation id="1" version="9999" timestamp="2013-12-07T19:03:20Z" changeset="0" uid="0" user="tobwen">
		<member type="way" ref="47036578" role=""/>
	</relation>
</modify>
</osmChange>
```

I've detected it using a trigger:
```
CREATE or REPLACE FUNCTION before_delete() RETURNS TRIGGER AS $$
BEGIN
    RAISE NOTICE 'Removed: %',  OLD.osm_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_before_delete
BEFORE DELETE ON planet_osm_line
FOR EACH ROW
EXECUTE PROCEDURE before_delete();
```

Edit: Maybe "clustering" (ordering by GeoHash) is the problem, which makes the trigger think the row gets deleted?

**Comment by lonvia** [comment]
That's how all updates work: delete the object unconditionally and reinsert it. See for example https://github.com/openstreetmap/osm2pgsql/blob/master/output-pgsql.cpp#L565. It's a simple strategy that avoids a lot of strange edge cases and probably will never change.

**Comment by pnorman** [comment]
This seems to be expected behavior.

The change to a relation forces it to be pending, so it's either going to be deleted or updated, and updating consists of a delete and insert. The insert just happens to be the same data because the changes didn't result in any changes to the output columns.

> Edit: Maybe "clustering" (ordering by GeoHash) is the problem, which makes the trigger think the row gets deleted?

No, it's only relevant for initial table order.

**Comment by TobWen** [comment]
I'm not talking about the relation ID being deleted. I'm talking about a member.
