### ISSUE TITLE
Use PGDATABASE and don't assume default database of gis

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#561]
Best practices are when a database is not specified to rely on libpq supplying the correct one from environment variables ([`PGDATABASE`](http://www.postgresql.org/docs/current/static/libpq-envars.html) and others)

**Comment by pnorman** [comment]
@lonvia, how do you think about doing this for the next release, since we're doing other breaking changes?

**Comment by lonvia** [comment]
'if not specified' means leaving the `-d` option as is, right? Then fine with me.

**Comment by pnorman** [comment]
`-d` would be as-is, without `-d` would change. i.e. `osm2pgsql foo.osm` would go to what libpq says, normally PGDATABASE or the user's name.
