### ISSUE TITLE
Move examples to their own directory

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#566]
We have a few example files which we don't install but are intended as a working example to show how to use a feature. These should be in their own directory.

These are
- multi.lua
- multi.style.json
- sample.multi.json
- style.lua

**Comment by SomeoneElseOSM** [comment]
Er OK, but every time a file like "style.lua" moves external links to it break - e.g. from a mail archive where someone's said "and this is the standard style.lua that comes with osm2pgsql".

**Comment by lonvia** [comment]
We have gone the other way around and moved the sources into their own directory, which has cleaned up the repo significantly. I'd say that this is good enough for now. And @SomeoneElseOSM is probably right that we break scripts if we move this stuff around. @pnorman?

**Comment by pnorman** [comment]
Yep, I think the current layout is fine now.
