### ISSUE TITLE
Problem with flag -E

### ISSUE THREAD

**Issue by lucadelu** [openstreetmap/osm2pgsql#571]
Hi, 
If I try to set different projection system with flag -E I receive the following error. I'm running osm2pgsql on Debian testing OS, and I tried the package 0.90.0 and this master repo but I got the same error.
No error is reported without -E flag or us -l 

```
osm2pgsql -s -C 4000 -k -d osm nord-italy.pbf -E EPSG:32632
osm2pgsql SVN version 0.90.0 (64 bit id space)

Osm2pgsql failed due to ERROR: creation of CRS failed: no options found in 'init' file
```

**Comment by pnorman** [comment]
`-E` takes the number of the projection ("`-E|--proj num`") and uses the projection EPSG:num, so you should use `-E 32632`

**Comment by lucadelu** [comment]
I'm sorry but also -E 32632 is not working too

```
osm2pgsql -S osm/rendering_ledro/ledro.style -s -C 4000 -k -d osm -E 32632 nord-italy.pbf
osm2pgsql SVN version 0.90.0 (64 bit id space)

Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)

```
