### ISSUE TITLE
Osm2psql needs too much memory for parsing with libosmium

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/osm2pgsql#574]
See https://github.com/osmcode/libosmium/issues/150 and https://github.com/osmcode/libosmium/issues/140
Regardless of `-C` argument, osm2pgsql crashes when parsing big files on VMs with 1-2 gigabytes of memory. Is there a way to use it still on such machines? Could you please document it? Also, osm2pgsql should present more clear error message when it runs out of memory.

For now I've downgraded to 0.88.x, which does work fine.

**Comment by pnorman** [comment]
I don't have issues running with 1GB in a VM. Can you please provide your command line, PBF size, OS, and if on Linux, the results of `free -m`, `cat /proc/sys/vm/overcommit_memory` and `/proc/sys/vm/overcommit_ratio`

**Comment by Zverik** [comment]
```console
$ osm2pgsql --slim -d gis -C 800 -S veloroad.style tileosmz.osm.pbf
...
$ ls -l /var/www/html/tileosmz.osm.pbf 
-rw-r--r-- 1 zverik zverik 713997282 Apr 20 16:41 /var/www/html/tileosmz.osm.pbf
$ ls -lh /var/www/html/tileosmz.osm.pbf 
-rw-r--r-- 1 zverik zverik 681M Apr 20 16:41 /var/www/html/tileosmz.osm.pbf
$ uname -a
Linux tile 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ free -m
             total       used       free     shared    buffers     cached
Mem:           994        891        102        135         24        574
-/+ buffers/cache:        291        702
Swap:         1023        139        884
$ cat /proc/sys/vm/overcommit_memory
0
$ cat /proc/sys/vm/overcommit_ratio
50
```

**Comment by pnorman** [comment]
800 MB cache on a system with 994 MB of RAM seems like a problem. In addition to the osm2pgsql node cache there's some memory overhead, and postgresql still needs it's shared_buffers and some free memory for disk cache

**Comment by Zverik** [comment]
Should it work with `-C 600` or 500?

**Comment by pnorman** [comment]
When I last tested on a 1GB VM I used `--cache 400`

**Comment by robinwyss** [comment]
I ran into the same issue on a VM with 1GB of memory. I was able to solve it by creating 2GB swap file:
dd if=/dev/zero of=/swap bs=1024 count=1048576 
chmod 600 /swap
mkswap /swap
swapon /swap

Instructions are from: https://wiki.debian.org/Swap

**Comment by fabriciomurta** [comment]
I'm not sure this adds up to anything but trying to restore [a NA extract from geofabrik.de](https://download.geofabrik.de/north-america.html), with these flags:
`--create --username osm --database osm_na --prefix "na" --number-processes 8 --latlong --cache 16384 --hstore-all north-america-latest.osm.pbf`

And getting the process killed by using all memory. 64GB physical + 8Gb swap.

Dmesg tells me this at the point it kills it:

```
[13678037.288635] Out of memory: Kill process 5913 (osm2pgsql) score 949 or sacrifice child
[13678037.288698] Killed process 5913 (osm2pgsql) total-vm:75500368kB, anon-rss:63322932kB, file-rss:0kB, shmem-rss:0kB
```
So unmistakably it uses all RAM to process that 8GB file. I may be overusing the import flags, maybe, but no matter what, it looks to me a much higher ram usage than what it should. I'll try resorting to the flat file.

**Comment by joto** [comment]
The new libosmium version 2.15.0 I released yesterday needs considerably less memory when reading in OSM files, especially when reading PBF files.

**Comment by lonvia** [comment]
I've updated the contrib version of libosmium to 2.15.0. Closing here as there is really not much we can do about that on the osm2pgsql side.
