### ISSUE TITLE
Make processing figures instantaneous 

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#577]
After watching a few imports, particularly where I `ionice`'ed them while running, I feel instantaneous object/s counts would be more useful for monitoring what is happening than the current figures which are total objects/total time.

**Comment by joto** [comment]
This has never been discussed and we should probably decide whether we want to change something here or not. The way I see this, the counts are, for most users, just something where they can see that osm2pgsql is still working. And maybe if the numbers are really really low to immediately see that something is wrong. Only specialists will understand exactly what those numbers mean. Then the question becomes:Is there a single display that is best or do we need several statistics. But several numbers would make it even harder to understand what's going on and clutter the output. If we change just the meaning of the numbers we have we'd loose 10 years of intuition for the specialists who have a good feeling by now what the numbers signify.

@pnorman Any thoughts on this?

**Comment by ldeffenb** [comment]
I use osm2pgsql to keep my planet database up-to-date for renderd and mod_tile.  I direct the output to a log file per run which gives me the ability to tail -f and monitor the cron-based executions.  Given that my installation barely keeps up with the updates (like I'm currently 194 hours behind and trying to do 7 days per run), being able to see any numbers to let me know it is making progress is a good thing.

I actually added an ETC (Estimated Time to Complete) which is woefully inaccurate, especially on relations, given that they are not consistent in processing time.  But at least I can get an idea of what's ahead as in days vs hours vs minutes.

Going over pending ways...
        3812021 ways are pending

Using 1 helper-processes
20 13:59:10 Left to process: 1702164 (ETC 17:58:18)....

**Comment by joto** [comment]
@ldeffenb We'll definitely keep the progress display in one shape or form. The question here is about the specific numbers shown and whether we want to change them.

**Comment by ldeffenb** [comment]
@joto - Thanks!

**Comment by joto** [comment]
Closing this as outdated. Please open a new issue if you have any specific ideas on how to improve the progress display we currently have.
