### ISSUE TITLE
Full Planet over inflated db size

### ISSUE THREAD

**Issue by MyPC8MyBrain** [openstreetmap/osm2pgsql#579]
Hi everyone,
Thank you for supporting osm2pgsql, 

I’ve been trying the past few weeks to complete full planetosm import with very mixed and confusing results,
by any means i am not an expert and fairly new to working with pgsql and osm2pgsql but not to with osm data in general,
I have completed one import which wasn’t too bad after 29h, I did get allot of “Standard exception processing relation id=…: TopologyException: side location conflict at …”
The import completed, db was around 20GB (very odd size) slim was 32gb + hchange; through accessing the data didn’t work for our application need; default projection wasn’t right for us,
I dropped the db, i changed a single flag in my string from -E 4326 to -l
This is where everything went wrong,
First I wasn’t sure about the errors I got the first run; I verified md5 all was intact; I decided to grab the latest pbf,
With the latest  pbf posted I didn’t get as many errors as i got the first time; but I also changed the projection to latlong,
I did however kept getting these two repeatedly 
“Standard exception processing relation id=2563291: TopologyException: side location conflict at 18.659793799999999 44.570205299999998
and
Standard exception processing relation id=3151399: TopologyException: side location conflict at -74.521022599999995 48.374912999999999”
But that’s it, import kept going through every time; what didn’t work out is the db size!
All I changed was -E to -l and my db size went through the roof, but I mean through the roof blowing up 405GB and failing in my one before last run,

This may be important:
Initially I noticed I wasn’t getting parallel processing, I found the right build for my OS and was finally getting 8 pthread as expected,
The first run where helper processes are used seems to be going well, all 8 cores spike up for the duration of the first batch run,
The next batch though doesn’t! strangely reduces itself to use 6-1 core all the way to the end while not utilizing more than half of the memory or processors allocated,
I also get this throughout “WARNING:  there is no transaction in progress”

Any idea why I’m getting over inflated db size with -l Flag?
i run it with flat nodes, slim, drop, Using 1.0.132 build and PG 9.5

TIA
Chris

**Comment by ImreSamu** [comment]
>Any idea why I’m getting over inflated db size with -l Flag?

my guess:   the parallel indexing need more disk space... 
have you tried : `VACUUM FULL` ?? 
https://www.postgresql.org/docs/9.5/static/sql-vacuum.html
* _VACUUM reclaims storage occupied by dead tuples. In normal PostgreSQL operation, tuples that are deleted or obsoleted by an update are not physically removed from their table; they remain present until a VACUUM is done._

**Comment by MyPC8MyBrain** [comment]
from what i read i should be keeping vacuum off during large imports,
which i did; i just didn't think it takes that much space to complete today's planet import,

**Comment by ImreSamu** [comment]
>from what i read i should be keeping vacuum off during large imports,
I mean -  after the imports  -  reclaiming storage occupied by dead tuples.

> i just didn't think it takes that much space to complete today's planet import,

imho ~400 Gb is normal.
in 2015 - the db size was:  
 * http://www.grulic.org.ar/~mdione/glob/posts/osm-planet-importing-and-rendering-times/

you can: 
* filter the planet data : 
  * http://wiki.openstreetmap.org/wiki/Osmfilter
  * https://github.com/gmgeo/osm-carto-lowzoom
  * ...
* or you can use continent  or country extracts :  http://download.geofabrik.de/index.html
* or you can use  the new :  "simplified osm2pgsql database dump"
 *  https://lists.openstreetmap.org/pipermail/dev/2015-July/028625.html

**Comment by StyXman** [comment]
> http://www.grulic.org.ar/~mdione/glob/posts/osm-planet-importing-and-rendering-times/

Wait, those numbers (mine) are for the Europe extract by Geofabrik.

**Comment by pnorman** [comment]
You do not need to reclaim any space with VACUUM, the final tables are created in a way that they have no dead tuples.

It's worth double-checking the size of the tables with `pg_total_relation_size` - they should add up to the database size, if not there's orphaned postgres files.

**Comment by MyPC8MyBrain** [comment]
thank you very much guys, very helpful information!
i was able to eventually complete the import; but not before allot of issue i had to iron out,
the db import process completed in about 30h; during that time the space used grown to close to a .5tb,
at the end of the import the space usage shrunk down by 66% to its current size of 160gb 
(full planet import without special attribute table, -s -d --flat-nodes)

**Comment by lygstate** [comment]
Is this exception are normal?
```
“Standard exception processing relation id=2563291: TopologyException: side location conflict at 18.659793799999999 44.570205299999998

```

**Comment by pnorman** [comment]
> the db import process completed in about 30h; during that time the space used grown to close to a .5tb,
> at the end of the import the space usage shrunk down by 66% to its current size of 160gb

Everything there sounds normal
