### ISSUE TITLE
way makes it to planet_osm_ways but not planet_osm_polygon

### ISSUE THREAD

**Issue by eoghanmurray** [openstreetmap/osm2pgsql#584]
I noticed the following way was missing from the planet_osm_polygon table after import:
http://openstreetmap.org/way/5049301

I created a minimal xml file with the way and the relevant nodes for the way:
https://gist.github.com/eoghanmurray/3f935350e8272562f6c7c427158cd606

This imports perfectly into both planet_osm_ways and planet_osm_polygon, but when I try to import a full xml file for the country:
http://download.geofabrik.de/europe/great-britain-latest.osm.bz2
the way only makes it as far as the planet_osm_ways table.

Here is the output of the osm2pgsql run:
https://gist.github.com/eoghanmurray/cc792df8a0c2b982f45d98bddf118ed0

**Comment by ImreSamu** [comment]
> I noticed the following way was missing from the planet_osm_polygon table after import:
> http://openstreetmap.org/way/5049301

it is in the database ..   but with the parent 'relation' id 
  * http://www.openstreetmap.org/relation/239658

```sql
dev=> select name, osm_id from planet_osm_polygon   where osm_id =-239658
;
                   name                   | osm_id  
------------------------------------------+---------
 Edinburgh Napier University (Merchiston) | -239658
(1 row)

```

for compatibility - the 'old-style multipolygon rule'  is used : 
* 'If relation is not tagged, the drawing style of outer ways is used.'
  *  http://wiki.openstreetmap.org/wiki/Relation:multipolygon#Tagging

and the  relation is not tagged : 
```xml
<relation id="239658" visible="true" version="1" changeset="2446245" timestamp="2009-09-11T13:43:31Z" user="Augustus Kling" uid="48582">
   <member type="way" ref="40622382" role="inner"/>
   <member type="way" ref="5049301" role="outer"/>        
   <tag k="type" v="multipolygon"/>
</relation>
```


I have tested with the mapzen metro extract 
```
wget https://s3.amazonaws.com/metro-extracts.mapzen.com/edinburgh_scotland.osm.pbf
```

**Comment by pnorman** [comment]
Yes, as a member of a MP it will appear under it's ID.

**Comment by eoghanmurray** [comment]
Thanks, don't know how I missed that, I must have been searching strictly by id.
