### ISSUE TITLE
unclear "A --slim --drop import is generally the fastest way to import the planet"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/osm2pgsql#589]
In https://github.com/openstreetmap/osm2pgsql/blob/master/docs/usage.md there is

> --drop discards the slim tables when they are no longer needed in the import, significantly reducing disk requirements and saving the time of building slim table indexes. A --slim --drop import is generally the fastest way to import the planet if updates are not required.

It is unlear whatever it should be interpreted "there are significant performance improvements, also for giant imports" or "there are significant performance improvements but only for giant imports".

I would make PR but I am unsure which one is true.

**Comment by lonvia** [comment]
There is some time saving for all imports because some indexes don't need to be built.

**Comment by matkoniecz** [comment]
So "the planet" may be dropped, as it suggests that it is relevant only for big imports, right?

**Comment by pnorman** [comment]
The first sentence talks about the impact of ``--drop``, the second is about importing the planet. To drop "the planet" from the second sentence changes the meaning, and it would no longer be correct.

I've looked at this a few times and not come up with a better wording, nor do I find it unclear as is.
