### ISSUE TITLE
add option to suppress progress log (-q --quiet)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/osm2pgsql#591]
It would be especially useful as due to buffering issues progress log is written to stderr rather than to stdout (see https://lists.openstreetmap.org/pipermail/dev/2011-February/021869.html)

It is especially problematic for programs calling osm2pgsql as it is currently impossible to assume that stderr output indicates problems.

**Comment by nyurik** [comment]
@ionvia I think most of the osm2pgsql output is fine, except for the node/way/rel counter.  I think this issue could be fixed without requiring a full logging rewrite of everything - a simple `--noprogress` would solve 90% of this issue (huge log files) IMO.  Thanks for maintaining it!

**Comment by hholzgra** [comment]
> "It is especially problematic for programs calling osm2pgsql"

Aside from the stdout/stderr issue, wouldn't it make sense to only print progress updates if stdout/stderr is a tty?

It's easily testable via the isatty(fd) C standard library function, and a similar approach is used by basic linux tools like "ls", which only adds colors, and columnar output, if writing to a tty.

The majority of the --noprogress use cases would already be taken care of with this, but explicit --noprogress and --progress options would then still make sense to override the automatic decision and explicitly enforce desired behavior ...
