### ISSUE TITLE
How to automate osm2pgsql tasks with a PostgreSQL password

### ISSUE THREAD

**Issue by jcj7421** [openstreetmap/osm2pgsql#596]
As osm2pgsql is used in scripts to automate updating of maps, it seems to me that there are only 2 choices to give the PostgreSQL password : 
- either osm2pgsql asks it to the keyboard (it we use the '-W' option)
- or osm2pgsql doesn't send any password to PostgreSQL ; it requires that the database is configured not to ask a password (so the database security is carried over by the Linux account security).

The problem is that, when osm2pgsql asks the password, it reads it on /dev/tty instead of stdin so we cannot use it in a script. So, It means that, if we want an osm server which updates the maps automatically, we must configure the database with no password.  It seems that, previously, osm2pgsql was able to read the password in a Unix variable (something like $PGPASS or $pgpassword) but it does work anymore.

But if osm2pgsql would read the password on stdin (and ask the question on stdout), the problem would be solved : when osm2pgsql will ask the password, the script only has to redirect the standard input .

The modification to be made consists to modify sprompt.cpp : 
replacing : 
```
    termin = fopen(DEVTTY, "r");
    termout = fopen(DEVTTY, "w");
```
by : 
```
    termin = fopen("stdin", "r");
    termout = fopen("stdout", "w");
```
and removing the line : 
```
# define DEVTTY "/dev/tty"
```

That's what I am doing on my osm server, but I post it here hoping it could help other people or, may be, you could consider modify the original sources.

**Comment by pnorman** [comment]
`-W` is intended fo r interactive use, if you need to connect to a server using a password, use a `.pgpass` file or set [libpq environment variables](https://www.postgresql.org/docs/current/static/libpq-envars.html)

**Comment by pnorman** [comment]
Closing, this is not what people should be doing.

**Comment by zacharymostowsky** [comment]
Hi @pnorman , 

I am having trouble getting osm2pgsql to work with a .pgpass file as you had specified in your previous reply. I have created the .pgpass in my home directory and removed the -W option from my command. I am still getting the no password supplied failure. Is osm2pgsql designed to automatically look for the .pgpass file when attempting to make the connection? Or am I missing as step?

Thank you greatly,
Zach

**Comment by pnorman** [comment]
This is all handled with libpq, so I suggest debugging with `psql`

**Comment by zacharymostowsky** [comment]
Hi @pnorman, the problem was running the script as sudo. Thanks for your reply. I will update my answer.
