### ISSUE TITLE
Link to osm cartocss issue - ways not being rendered

### ISSUE THREAD

**Issue by aaronstar** [openstreetmap/osm2pgsql#597]
Hi as I am just a community mapper and don't really have too much idea of the technical side of things, I thought it was important to draw your attention to an issue with some ways I have recently been mapping. Please see this link for further information:

https://github.com/gravitystorm/openstreetmap-carto/issues/713

Regards,
Aaron

**Comment by pnorman** [comment]
With the C tag processing the special boundary handling is intentionally only done with `type=boundary` relations, not any ways.
