### ISSUE TITLE
osm2pgsql: bad result during COPY error

### ISSUE THREAD

**Issue by abautis** [openstreetmap/osm2pgsql#598]
Hi Everyone so I am trying to import only the roads dataset into postgres. I have taken osm data from geofabrik regions and extracted roads from them using osmfilter them then combined them using osmconvert. I keep getting this error though when using osm2pgsql. I have tried redownloading and remerging but it still keeps giving me the error.

This is the code that I ran to fix:

`F:\Downloads\OSM_WORLD>osm2pgsql --slim --flat-nodes F:\Downloads\OSM_WORLD.cache --hstore-add-index -c -m -d OSM_World -U evidenceall -H lmtmysqlrepl02.ve.selfhost.corp.microsoft.com -S C:\Users\abautis\Desktop\OSM_USA\default.style F:\Downloads\OSM_World_ALL_roads.osm`
osm2pgsql SVN version 0.85.0 (64bit id space)
This is the error:

```
Reading in file: F:\Downloads\OSM_World_ALL_roads.osm Processing: Node(910780k 80.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)planet_osm_line - bad result during COPY, data 63 \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N service \N \N \N \N \N \N \N \N \N \N \N Maney Corner \N \N yes \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N 0 \N SRID=900913;LINESTRING (-203344.6799999999930151 6901596.5499999998137355, -203329.1300000000046566 6901514.3499999996274710, -203326.4299999999930151 6901502.9800000004470348, -203316.2799999999988358 6901479.2199999997392297, -203311.2399999999906868 6901466.3300000000745058, -203306.8699999999953434 6901441.6100000003352761, -203301.0000000000000000 6901406.7300000004470348, -203295.0799999999871943 6901356.8300000000745058, -203290.2999999999883585 6901323.5599999995902181)
```

Error occurred, cleaning up

How do I fix this?

**Comment by pnorman** [comment]
Any errors in your postgresql logs? Can you reproduce with a more recent version? Does this happen all the time or just sometimes?

**Comment by abautis** [comment]
How do I get the most recent version of osm2pgsql for Windows machines? It happens when running big sets like world or continent datasets.

**Comment by abautis** [comment]
so I upated my osm2pgsql to 0.89 but I am still getting the same error. :|

C:\Users\abautis>osm2pgsql --slim --hstore --hstore-add-index --create -E 4326 --database OSM_World --username evidenceall -H lmtmysqlrepl02.ve.selfhost.corp.microsoft.com --style C:\Users\abautis\Desktop\OSM_USA\default.style F:\Downloads\OSM_World_ALL_roads.osm
osm2pgsql SVN version 0.89.0-dev (64 bit id space)

Using built-in tag processing pipeline
Using projection SRS 4326 (EPSG:4326)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for sparse node cache
Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=9
Mid: pgsql, scale=100 cache=800
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: F:\Downloads\OSM_World_ALL_roads.osm
Using XML parser.
Processing: Node(910780k 250.2k/s) Way(0k 0.00k/s) Relation(0 0.00/s)node cache: stored: 52428801(5.76%), storage efficiency: 50.00% (dense blocks: 0, sparse nodes: 52428801), hit rate: 42.08%
Osm2pgsql failed due to ERROR: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
: middle_pgsql_t::ways_set - bad result during COPY, data 572   {251882,248597,248598}  {"foot","yes","highway","footway","created_by","osmeditor2","designation","public_footpath"}

**Comment by pnorman** [comment]
> Any errors in your postgresql logs?

We really need the answer to this to proceed.

Also, does it work with a small extract like liechtenstein?

**Comment by pnorman** [comment]
Closing as abandoned.
