### ISSUE TITLE
Any good docker containers to recommend here?

### ISSUE THREAD

**Issue by d1g** [openstreetmap/osm2pgsql#599]
I think [at least one container](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=osm2pgsql&starCount=0) should be recommended for users.

Manual installation for day-to-day user(s) is trivial and shouldn't have bazillion of steps.

PS. I think question is not limited to _docker_ but to _any automated setup_ solution

**Comment by pnorman** [comment]
We've worked to get osm2pgsql packaged on most Linux distributions. It's also available on Homebrew. Given that installing osm2pgsql with an automated setup is just a matter of installing a package, I don't see the need for anything else here.

**Comment by d1g** [comment]
> We've worked to get osm2pgsql packaged on most Linux distributions.

That's why I'm asking for a list of trusted packages among tested linux distros. Do they all named "osm2pgsql"? Is it _safe_ to use "osm2pgsql" package among all distributions?

> osm2pgsql packaged on most Linux distributions. It's also available on Homebrew

I think it should be stated in README.md explicitly "search for osm2pgsql
 package in your repo", because current [openstreetmap/osm2pgsql#installing] suggests to _clone source code and compile it_. 

Not many users may know about Homebrew (for MacOS) or Chocolately (or Docker).

**Comment by SomeoneElseOSM** [comment]
I'd agree that it makes sense to say "have a look in your distributions apt repository" (or whatever), but at least the README says "here's the source code" rather than "if your on distribution X, you _need_ to build from source" (as https://github.com/mapnik/mapnik/wiki/UbuntuInstallation for Mapnik implies on Ubuntu 16.04).
