### ISSUE TITLE
Integration test SRIDs

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#60]
The integration tests fail with

```
SELECT AddGeometryColumn('planet_osm_point', 'way', 900913, 'POINT', 2 );
 failed: ERROR:  AddGeometryColumn() - invalid SRID
CONTEXT:  SQL statement "SELECT AddGeometryColumn('','',$1,$2,$3,$4,$5, $6)"
PL/pgSQL function "addgeometrycolumn" line 5 at SQL statement
```

because they do not add the 900913 SRID. Before doing an osm2pgsql import on a new database you have to set up postgis, hstore and the 900913 SRID

**Comment by goodvibesjumper** [comment]
I ran into the same problem.  To resolve 
mkdir ~/src
cd ~/src
git clone git://github.com/openstreetmap/osm2pgsql.git
cd osm2pgsql
./autogen.sh
./configure
make
sudo make install
psql -f /usr/local/share/osm2pgsql/900913.sql -d gis
