### ISSUE TITLE
Option "--prefix" ignored for gazetteer output

### ISSUE THREAD

**Issue by vramirez122000** [openstreetmap/osm2pgsql#600]
When using the gazetteer output option, the table name is hardcoded as "place". It would be useful to prepend the value of the "--prefix" option, just like the regular "pgsql" output,  for the following reasons:
- The "place" table name conflicts with a table name that is hardcoded in the postgis_tiger_geocode extension
-  With the prefix option, it would be simpler to load multiple gazetteer tables, one per country. The current functionality requires an extra step to rename the table and indices once the data has been loaded
- Not ignoring the prefix option for gazetteer output would make the interface more consistent, with less surprises for the user

**Comment by asbjornst** [comment]
Do you have a suggestion on how to introduce this in a backward compatible manner?

Afterwards see my suggestion in #619

**Comment by lonvia** [comment]
Nominatim expects the name as it is. So it has to be made configurable over there. I think I would prefer the schema option in that case.

Closing here, as this is a Nominatim issue.

**Comment by pnorman** [comment]
We should document that this option is for the pgsql backend only, since it also doesn't change the multi-backend
