### ISSUE TITLE
osm2pgsql-0.90.0/taginfo.cpp:199]: (error) Resource leak: in

### ISSUE THREAD

**Issue by dcb314** [openstreetmap/osm2pgsql#601]
Source code is

```
    throw std::runtime_error((boost::format("Weird style line %1%:%2%")
                              % filename % lineno).str());
```

Suggest add missing call to fclose.

**Comment by pnorman** [comment]
Not a huge issue since osm2pgsql exits with the error, but proper RAII would automatically clean up the resources used when exiting.
