### ISSUE TITLE
filtering?

### ISSUE THREAD

**Issue by awdogsgo2heaven** [openstreetmap/osm2pgsql#603]
Is there anyway during import that I can filter out any rows where the column 'name' is blank? And is there any way I could not import anything from the 'roads' table?

**Comment by pnorman** [comment]
If you want custom logic you can use [lua transforms](https://github.com/openstreetmap/osm2pgsql/blob/master/docs/lua.md) which let you control what gets filtered and what is in the roads table.

**Comment by awdogsgo2heaven** [comment]
@pnorman Thank you for the reference, I guess if I understand the transformation document correctly, on that second document if I replace the roads with just returning 0, nothing will go into the road table correct?

**Comment by SomeoneElseOSM** [comment]
It's actually easier than that - just remove the tags you're not interested in.  Here, for example, is part of a lua script that removes all administrative boundaries:

https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/master/style.lua#L359

You'll want to take the example lua script that comes with osm2pgsql, add in new code to remove what you don't want and use that script when loading the rendering database.

An example of using that script is here:

http://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1404_tileserver_load#Reload_the_data_and_clear_previously_cached_tiles

but of course you'll want to use your own values for most of the parameters.
