### ISSUE TITLE
Zlib compression failed (code -3, too many length or distance symbols)

### ISSUE THREAD

**Issue by samehraban** [openstreetmap/osm2pgsql#604]
I try to import latest planet file with this command:
`osm2pgsql --slim -d gis -C 39000 --number-processes 8 /usr/local/share/maps/planet/planet-latest.osm.pbf`
and I'm constantly get error below:

> Processing: Node(3427133k 236.6k/s) Way(96936k 22.86k/s) Relation(0 0.00/s)Zlib compression failed (code -3, too many length or distance symbols)
> Error occurred, cleaning up

I have ubuntu 16.04 with 40G ram and 8 cpu cores.
any clue what might be the problem?

**Comment by pnorman** [comment]
Have you checked the md5sum of the planet you downloaded?

**Comment by samehraban** [comment]
As you guessed, downloaded file was corrupted.
