### ISSUE TITLE
Use NuGet for windows builds

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#606]
It looks like this can supply some Windows dependencies which are currently binary blobs.
- [ ] How is NuGet used from AppVeyor?
- [ ] What packages can come from it, and what still need to come as a binary blob?
- [ ] Is NuGet suitable for users wanting to get osm2pgsql? It seems to be mainly libraries.
- - AppVeyor has a project/org NuGet feed. Can we upload tagged releases to nuget.org?
- [ ] Chocolaty uses NuGet behind the scenes. Can we get the NuGet packages pushed there?

cc @alex85k

**Comment by lonvia** [comment]
We are using miniconda now which has more up-to-date packages.
