### ISSUE TITLE
Does the -G option support MultiPoint and MultiLineString geometries?

### ISSUE THREAD

**Issue by WillieMaddox** [openstreetmap/osm2pgsql#609]
I loaded the planet file into my PostGIS database using the -G option, but I only have groupings of MultiPolygons

``` sql
SELECT ST_GeometryType(way) AS geom, count(*) AS ct FROM planet_osm_polygon
GROUP BY geom ORDER BY ct DESC;

       geom      |    ct    
-----------------+----------
 ST_Polygon      | 229522629
 ST_MultiPolygon | 104743
(2 rows)
```

``` sql
SELECT ST_GeometryType(way) AS geom, count(*) AS ct FROM planet_osm_line
GROUP BY geom ORDER BY ct DESC;

     geom      |    ct     
---------------+-----------
 ST_LineString | 123433770
(1 row)
```

``` sql
SELECT ST_GeometryType(way) AS geom, count(*) AS ct FROM planet_osm_point
GROUP BY geom ORDER BY ct DESC;

   geom   |    ct    
----------+----------
 ST_Point | 84121378
(1 row)
```

Is this the intended behavior or is osm2pgsql capable of grouping MultiPoint and MultiLineString geometries?

Thanks,

-Will

**Comment by pnorman** [comment]
There are not MultiPoint or MultiLineString geometries in osm2pgsql's modeling of the OSM data model.

**Comment by WillieMaddox** [comment]
Are there any plans to do so in the future?

**Comment by yvecai** [comment]
@pnorman what about routes relation?

**Comment by WillieMaddox** [comment]
I don't know about that.  I am trying to load some of the highways into a separate postGIS table, serve them up via geoserver/WFS, and do some neat route planning studies.  I can't create primary keys on the highways due to osm_id duplicates.  I just wanted to check with you guys and see if the -G option was supposed to include multilinestrings (and somehow I was just missing them) before I attempted to write a custom SQL script to do it for me.

**Comment by pnorman** [comment]
> I can't create primary keys on the highways due to osm_id duplicates.

The rendering tables do not have a unique or primary key by design. -G will not change that, nor is it supposed to.

-----

> Are there any plans to do so in the future?

They couldn't be in the C transforms. It would mean extending the Lua interface to have another return for if an object is supposed to be transformed into a Multi geometry type or not, as well as probably another return for what distance to split linestrings on.

**Comment by WillieMaddox** [comment]
Ok, then something must be wonky with the way I am creating my tables.  Running osm2pgsql without the -G option I wasn't able to create a separate table from planet_osm_polygon for just the buildings with the osm_id as the primary key because of all the duplicate osm_ids.  Adding the -G option fixed that.  I was hoping the same would be true for the planet_osm_line.  Here is my SQL for the buildings:

```sql
DROP TABLE IF EXISTS buildings;
CREATE TABLE buildings AS SELECT
	osm_id,
	name,
	way,
	building,
	--Record the height iff the height is already in numeric form.
	CASE
	WHEN tags->'height' = '.' THEN
	    NULL
	WHEN tags->'height' ~ E'^([0-9.]+)$' THEN
	    CAST (tags->'height' AS NUMERIC)
	ELSE
	    NULL
	END AS height
	FROM planet_osm_polygon WHERE building IS NOT NULL;

--Feature id (gml:id) is based on primary key column
--http://download.deegree.org/documentation/3.3.16/html/featurestores.html
ALTER TABLE buildings ADD PRIMARY KEY (osm_id);
CREATE INDEX ON buildings USING GIST (way);
```

Should I be doing this a different way?

**Comment by pnorman** [comment]
> ALTER TABLE buildings ADD PRIMARY KEY (osm_id);

Don't do this. `osm_id` is not designed to be a primary key. You can use it like a primary key in many cases - any rows with the same osm_id will have the same tag columns, but it is not guaranteed to be unique. You can create a btree index on osm_id, just not unique.

If you require a primary key, add a serial column with postgres to make your own.

If you're designing something new, creating tables for specific features is what the [multi backend](https://github.com/openstreetmap/osm2pgsql/blob/master/docs/multi.md) is designed for, and this is a better approach than a` CREATE TABLE ... AS ... approach`

**Comment by WillieMaddox** [comment]
The multi backend approach looks promising.  Will osmosis be able to keep these tables up to date?

**Comment by pnorman** [comment]
> The multi backend approach looks promising. Will osmosis be able to keep these tables up to date?

Osmosis doesn't keep tables up to default, but osm2pgsql can append changes to them, just like with the pgsql backend

**Comment by joto** [comment]
The flex backend should be able to solve the issues mentioned here. You can create different types of geometries from relations including multi- or non-multi-linestrings and -polygons. Please give it a try.
