### ISSUE TITLE
planet_osm_roads

### ISSUE THREAD

**Issue by WillieMaddox** [openstreetmap/osm2pgsql#610]
If all the highways are kept in the planet_osm_line table, then what is the purpose of the planet_osm_roads table?

thanks,

**Comment by woodpeck** [comment]
Please don't use github issues as a Q+A forum. This is for reporting problems with the software, not for asking questions. (Use help.openstreetmap.org or the dev list at lists.openstreetmap.org/listinfo/dev for that.) 

To answer your question, planet_osm_roads contains geometries rendered on lower zoom levels and therefore relieves the rendering engine of having to trawl through lots of unneeded planet_osm_line objects.
