### ISSUE TITLE
Crash when integer contains non-integer value

### ISSUE THREAD

**Issue by PetrDlouhy** [openstreetmap/osm2pgsql#621]
If there is non-integer value in OSM data in tag, that is supposed to be integer in the style file, Osm2pgsql throws error similar to following:

```
Osm2pgsql failed due to ERROR: result COPY_END for planet_osm_point failed: ERROR:  invalid input syntax for integer: "bis 1946"
```

The error could be printed as warning, but Osm2pgsql should deal with cases of misedited OSM key/value and finish processing of the OSM file.

I tested it with on current main branch (and also with version 0.88.1) with following command:

```
./osm2pgsql test.osm -U mtbmap -d gisczech -s -S mtbmap.style
```

[test.osm.txt](https://github.com/openstreetmap/osm2pgsql/files/450965/test.osm.txt)
[mtbmap.style.txt](https://github.com/openstreetmap/osm2pgsql/files/450966/mtbmap.style.txt)

**Comment by pnorman** [comment]
If you are using types other than text for non-generated columns you need to make sure that your transform produces an output that PostgreSQL can handle. This means not using the C transforms.

**Comment by lonvia** [comment]
The import code can only handle 'int4' and 'real' as special numeric types in the C transform, see https://github.com/openstreetmap/osm2pgsql/blob/master/table.cpp#L465. If you change the type from `integer` to `int4` in your style, it will work as expected.

That said, I don't see why we shouldn't support all current integer and real types that postgres offers. It would also be a good idea to get rid of the string compare in that function.
