### ISSUE TITLE
Set up of a local server with detailed Gis Map Data of a particular area

### ISSUE THREAD

**Issue by Shree1100** [openstreetmap/osm2pgsql#623]
I want to setup a local server(no internet connectivity) with the complete Gis Data of a particular region stored in its local database.

I tried using Qgis to import data but it only returns points,polygon and line of that particular area.

Example-I went through Qgis to import london.osm.pbf and connected it with the database and using Qgis software came up with the conclusion that it only returns points,polygons and lines of the london map but not the complete detailed information of the map.
Complete information of the map meaning it should look just like the normal Google Map or OpenstreetMap with detailed information about that particular region like name of city,name of road,name of restaurants,co-ordinates,etc as it will be beneficial for further development.

I am a beginner in this field so can someone please guide me through the entire procedure of how to setup local server with local database.

Can someone please guide whether my approach of using Qgis,Osm data,osm2pgsql and pgAdmin4 is correct?
Is there any other approach for my query?I have heard about Geoserver,Mapserver but in a confusion of how to use them and what purpose do they serve?
Please guide me through the entire procedure.
Thanks.

**Comment by openstreetmap-tiles** [comment]
On Mon, Sep 26, 2016 at 05:17:46AM -0700, Shree1100 wrote:
> Example-I went through Qgis to import london.osm.pbf and connected it
> with the database and using Qgis software came up with the conclusion
> that it only returns points,polygons and lines of the london map but not
> the complete detailed information of the map.
> 
> Complete information of the map meaning it should look just like the
> normal Google Map or OpenstreetMap with detailed information about that
> particular region like name of city,name of road,name of
> restaurants,co-ordinates,etc as it will be beneficial for further
> development.

    I think you're mainly confusing a GIS server with something else,
most probably a map. A GIS server is what you setup, which in its core is
not much more than a database with points, lines, polygons and relations
with attributes. What you seem to want is a final rendring of that data,
and something that includes some interactivity with the user.

    The rendering part can be implemented with things like Mapnik (server
side) or Tangram (client side). You can read more about it here:

https://wiki.openstreetmap.org/wiki/Rendering

    As for the interactivity, that's more in the realm of Web
Applications, which use javascript to do some requests to a database,
possibly the same used for rendering, about more data than the rendered
one and displaying the results in the client. I don't know much about
these, maybe someone else can chip in.

    Cheers,

	-- Marcos.

-- 
(Not so) Random fortune:
Terrorism isn't a crime against people or property. It's a crime against
our minds, using the death of innocents and destruction of property to
make us fearful.
	    -- Bruce Schneier

**Comment by Shree1100** [comment]
Hello @Marcos,
I want to achieve the following goals:
1)I want to create a local server which would store all the detailed information of the particular area of the map.
2)I want to use this data or the map for further development with the SharpMap
3)I tried all the procedure of Postgis,Mapnik,Tilemill,osm2pgsql and came to the conclusion that Mapnik and Tilemill export map data in the form of png or xml format which i dont want as i need to achieve various zoom levels and need to perform some operations on various layers on the map with all the information displayed as it is in normal Google Map.
4)I will be provided with the map data which i want to store in the local database in case of no internet connectivity and then want to use the same data with the help of SharpMap for further development.

Please can anyone guide me if I am going in the right path and please guide through the entire procedure if you can.

Thanks.

**Comment by lonvia** [comment]
Sorry but this is an issue tracker for bugs with osm2pgsql, not a general GIS help list. There are a lot of tutorials out there that explain the basics of web rendering. I believe they are the best place for you to start.

Closing for being off topic.

**Comment by openstreetmap-tiles** [comment]
On Thu, Sep 29, 2016 at 02:23:26AM -0700, Shree1100 wrote:
> 1)I want to create a local server which would store all the detailed information of the particular area of the map.

    That can be achieved with osm2pgsql --hstore and many other tools.
The fact is, osm2pgsql is tightly related to the rendering stack, so the
databases it generates are mostly aimed at that task.

> 2)I want to use this data or the map for further development with the SharpMap

    What do you mean, 'further development'?

> 3)I tried all the procedure of Postgis,Mapnik,Tilemill,osm2pgsql and
> came to the conclusion that Mapnik and Tilemill export map data in the
> form of png or xml format which i dont want as i need to achieve various
> zoom levels and need to perform some operations on various layers on the
> map with all the information displayed as it is in normal Google Map.

    Yes, one possibility is to render the png raster tiles usually used
by online maps. Another option is to export vector tiles, which means
that the vector information is delivered to the (web) client and it uses
a rendering stack, like tangram, to draw a map. This is what most modern
maps are doing, including gmaps.

    A third option is to have a basic raster style, with not much info,
and then serve the particular data as geojson or any other format and
render that on top. This can be achieved with leaflet on the client (the
same you would be using for the raster map anyways) and some other thing
in the server. For instance, upoi.org uses OSM's tileset and
overpass-turbo.eu for the poi data.


> 4)I will be provided with the map data which i want to store in the
> local database in case of no internet connectivity and then want to use
> the same data with the help of SharpMap for further development.

    That depends a lot on the client application. If it is you who's
developing it, then it's up to you to cache locally data and use that in
offline mode. You could also take a look at the different comercial
offers on top of OSM data, which have SDKs for developing such apps and
data already prepared for you.

-- 
(Not so) Random fortune:
Terrorism isn't a crime against people or property. It's a crime against
our minds, using the death of innocents and destruction of property to
make us fearful.
	    -- Bruce Schneier

**Comment by openstreetmap-tiles** [comment]
On Thu, Sep 29, 2016 at 03:00:12AM -0700, Sarah Hoffmann wrote:
> Sorry but this is an issue tracker for bugs with osm2pgsql, not a general GIS help list. There are a lot of tutorials out there that explain the basics of web rendering. I believe they are the best place for you to start.

    Ah, I didn't notice this came through the issue tracker. I'm
receiving this through the tile-serving ML. Sorry for the noise.

-- 
(Not so) Random fortune:
Terrorism isn't a crime against people or property. It's a crime against
our minds, using the death of innocents and destruction of property to
make us fearful.
	    -- Bruce Schneier
