### ISSUE TITLE
boost::too_many_args: format-string referred to less arguments than were passed

### ISSUE THREAD

**Issue by amsoftgroup** [openstreetmap/osm2pgsql#624]
I get the above boost error in the title on running:

osm2pgsql --verbose -s -c -k -C 4000 --flat-nodes ./nodes ./myfile.osm.pbf

It occurs with osm2pgsql versions 0.90.0 and 0.90.1 with boost 1.62.0, PostgreSQL 9.5 PostGIS 2.2 on RHEL6. Is there a specific boost version I should be running? I've removed and adjusted parameters to no avail.

the last lines of output spits out, "Going over pending ways...\n100000 ways are pending" which makes me think it's occurring in osmdata.cpp between lines 232-272. I'll continue to investigate but if anyone has any insight, I'd be grateful. thanks!

**Comment by lonvia** [comment]
I'm not able to reproduce the error. Do you see the error with a specific file or with any input file?

**Comment by amsoftgroup** [comment]
It is happening with every file I have encountered, a smaller input file in particular would be Canberra.osm.pbf from http://download.bbbike.org/osm/bbbike/Canberra/

However, as I look more in to the situation it does appear the entire datasets are correctly imported, despite the error occurring. If you are unable to reproduce (and as no one else has chimed in with similar issue) I'll chalk it up to environment issues on my side and "Close with comment". I'll follow up if I isolate the cause and/or find a solution. Thanks very much for your efforts!
