### ISSUE TITLE
smart use of "unlogged tables" with postgres 9.5+

### ISSUE THREAD

**Issue by cquest** [openstreetmap/osm2pgsql#626]
Given that:
1. using unlogged tables during import is much faster
2. unlogged tables are not crash-safe
3. Postgres 9.5 and above allows to switch tables from unlogged to logged tables (and reverse).

When osm2pgsql imports on PG 9.5+, it could be interesting to use unlogged table by default during import, then switch them back to logged tables at the end of import.

**Comment by pnorman** [comment]
This would only impact slim tables AFAIK. Do you have any numbers on the impact of --unlogged? These would provide an upper bound on performance gain.

**Comment by pnorman** [comment]
ping @cquest

**Comment by cquest** [comment]
Well... it looks like the time saved is lost when switching back to "logged".

**Comment by pnorman** [comment]
Closing since it doesn't look like we'd get a performance gain in most situations, and we already use unlogged tables for the rendering tables while importing. If there is some unusual situation where someone wants to do this they can use the ``--unlogged`` option and switch the tables post-import.
