### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by yadujain** [openstreetmap/osm2pgsql#627]
While installing nominatim I am unable to build using make command. I am in ubuntu 16.04 and followed step by step instruction in https://github.com/twain47/Nominatim/blob/master/docs/install-on-ubuntu-16.md  and i am using fresh droplet of digital ocean. Below is error I am getting..

```
Scanning dependencies of target osm2pgsql_lib
[ 1%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/expire-tiles.cpp.o
[ 2%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/geometry-builder.cpp.o
[ 3%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/geometry-processor.cpp.o
[ 4%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/id-tracker.cpp.o
[ 5%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/middle-pgsql.cpp.o
[ 6%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/middle-ram.cpp.o
[ 7%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/middle.cpp.o
[ 8%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/node-persistent-cache.cpp.o
[ 9%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/node-ram-cache.cpp.o
[ 10%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/options.cpp.o
[ 11%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/osmdata.cpp.o
[ 12%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-gazetteer.cpp.o
[ 13%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-multi.cpp.o
[ 14%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-null.cpp.o
[ 15%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-pgsql.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-5/README.Bugs for instructions.
osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/build.make:398: recipe for target 'osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-pgsql.cpp.o' failed
make[2]: *** [osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-pgsql.cpp.o] Error 4
CMakeFiles/Makefile2:437: recipe for target 'osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/all' failed
make[1]: *** [osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jburgess777** [comment]
> c++: internal compiler error: Killed (program cc1plus)

Errors like these can occur if the machine runs out of RAM. How much does the droplet have?

**Comment by yadujain** [comment]
I am just using 512 for testing purpose. How much i need minimum.

**Comment by jburgess777** [comment]
At a guess I would say you probably want 4GB+. If you have ambitions for running a Nominatim install of a large area then you will need even more. One option is to do all the setup and data import with an image which has lots of RAM and then scale back the resources once the import is complete. You probably want to investigate the hourly pricing options from DO.

**Comment by jburgess777** [comment]
The numbers quoted on http://wiki.openstreetmap.org/wiki/Nominatim/Installation are:
> A minimum of 2GB of RAM is required or installation will fail. For a full planet import 32GB or more are recommended.

**Comment by jburgess777** [comment]
Not heard anything back so I guess more RAM fixed it.

**Comment by LeZhengThu** [comment]
@swarthi  I got the same error when installing osm2pgsql. How do you solve this? When I run free -g in my terminal, it seems that the RAM size is much larger than 4GB.

**Comment by rolonja** [comment]
i have the same error and i have 8GB RAM

~/src/osm2pgsql/build $ free -h
              total        used        free      shared  buff/cache   available
Memoria:        7,6G        2,1G        1,4G        315M        4,1G        4,6G
Swap:          7,8G        1,3M        7,8G

collect2: error: ld returned 1 exit status
CMakeFiles/osm2pgsql.dir/build.make:104: fallo en las instrucciones para el objetivo 'osm2pgsql'
make[2]: *** [osm2pgsql] Error 1
CMakeFiles/Makefile2:552: fallo en las instrucciones para el objetivo 'CMakeFiles/osm2pgsql.dir/all'
make[1]: *** [CMakeFiles/osm2pgsql.dir/all] Error 2
Makefile:138: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

**Comment by AmilaLiyanage** [comment]
Stop the PostgreSQL server and then build it again.
