### ISSUE TITLE
Possible to import from STDIN?

### ISSUE THREAD

**Issue by bradisbell** [openstreetmap/osm2pgsql#629]
For the purpose of installing OSM tile servers with a minimal amount of hard drive space, is it possible to import from STDIN?  That way, I could `curl "http://download.geofabrik.de/europe/great-britain-latest.osm.pbf" | osm2pgsql...` and not have to have the intermediate 36GB file on disk.

**Comment by pnorman** [comment]
For XML, yes, it is. For PBF, afaik, no.

**Comment by lonvia** [comment]
If you have curl installed, you can directly import from a URL, e.g.

    osm2pgsql -s -d gb-extract http://download.geofabrik.de/europe/great-britain-latest.osm.pbf
