### ISSUE TITLE
how can update part of gis data into sql

### ISSUE THREAD

**Issue by imhere615** [openstreetmap/osm2pgsql#657]
I use command `osm2pgsql -c -k -d osm2  -U postgres -P 5432 -S default.style belize-latest.osm.pbf` to insert the pbf to sql;
use `select count(*) from planet_osm_line` query count is 9878;
then I use command `osm2pgsql -a -k -d osm2  -U postgres -P 5432 -S default.style belize-latest.osm.pbf` to update the pbf;
now use `select count(*) from planet_osm_line` query count is 19756;
I want to ask if there is any question about the parameters?

**Comment by pnorman** [comment]
I'm not clear on what your question is, but don't use `-a`/`--append` with PBF file of OSM data, only use `-c`/`--create`.

`-a`/`--append` is for .osc update files.

**Comment by imhere615** [comment]
@ pnorman 

Thanks!My question is
How to update the data in a certain part of the world after the introduction of the global map data ?Can I update the database with the PBF file  of OSM data?
Another question,Have you ever tried to import the planet data?
"osm2pgsql -c -s -d osm2 -C 190000 -U postgres -P 5432 -S default.style planet.osm.pbf"
Is the command above correct ?

**Comment by imhere615** [comment]
@pnorman
Thanks!My question is
How to update the data in a certain part of the world after the introduction of the global map data ?Can I update the database with the PBF file  of OSM data?
Another question,Have you ever tried to import the planet data?
"osm2pgsql -c -s -d osm2 -C 190000 -U postgres -P 5432 -S default.style planet.osm.pbf"
Is the command above correct ?

**Comment by lonvia** [comment]
I suppose you used the extracts from geofabrik? In that case, you should use the daily diffs from the same server to update your data (http://download.geofabrik.de/central-america/belize-updates/). Also, if you want to update you must use slim mode (-s) for the initial import and updates.

The -C option in your planet command line looks wrong. That would be 190GB of RAM.
