### ISSUE TITLE
Make -G / --multi-geometry option default

### ISSUE THREAD

**Issue by Komzpa** [openstreetmap/osm2pgsql#660]
Option `--multi-geometry` allows for more flexibility in processing and in general produces better rendering results. This option is subtle and is often lost, giving some unexpected results.

Related:
https://github.com/gravitystorm/openstreetmap-carto/issues/59 
#609

**Comment by Zverik** [comment]
A possible reason is a significant speed decrease of tile rendering: http://www.paulnorman.ca/blog/2014/03/osm2pgsql-multipolygons/ (see the chart at the end).

**Comment by Komzpa** [comment]
For linear features there is an automated split-up based on feature length. This split is enabled unconditionally.

https://github.com/openstreetmap/osm2pgsql/blob/95a3a2036aa6c45698378e5b7b6643d9a7a276b1/geometry-builder.cpp#L293

Polygon split could be implemented in a similar way: if bounding box is wide (probably wider than 180 degrees), split up the rightmost part into a second part, until it grows up to being 180 degrees wide. This way Russia/Alaska will be split into two parts not affecting performance in Europe, but labeling for then would become much better.

**Comment by pnorman** [comment]
Let's decide on this for the next release.

**Comment by Komzpa** [comment]
@pnorman what are the things I can do to help with decision?

**Comment by pnorman** [comment]
> @pnorman what are the things I can do to help with decision?

I don't think there's anything. We don't need more information, the various factors need to be weighed and a decision made on if we're going to do this or not.

**Comment by lonvia** [comment]
I really have no opinion on that. I don't think it seriously hurts to have a less used defaults for historical reasons (there are others like --slim) but it neither hurts much to change the default in this case. Just make sure that changing the default doesn't break existing scripts, i.e. -G/--multi-geometry should continue to work as expected and we'd need a new --no-multi-geometry option.

**Comment by lonvia** [comment]
If somebody would like to make a PR implementing this along the lines I've outlined in the previous comment (please make sure the tests still pass), then we can merge this. Otherwise the option will stay as is.

**Comment by pnorman** [comment]
No PR was forthcoming, so we're going to keep the current defaults.
