### ISSUE TITLE
Schema and/or UML illustrations

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/osm2pgsql#671]
The [Osm2pgsql/schema](https://wiki.openstreetmap.org/wiki/Osm2pgsql/schema) page is outdated (from 2011), but was  important information for users... And, here, for discussions (for non-team and non-hard-user people particpate). Of course, not need all possible structure-outputs (depend on the style file), **only the *default* and/or most used**... Or a simplifyed UML diagram generated by [yUML](https://yuml.me/) or similar fast ones.

If there are a consensual "default" or "most used" schema, please post here and I generate a yUML, etc. to help projects documentation or [Wiki](https://github.com/openstreetmap/osm2pgsql/wiki).

**Comment by pnorman** [comment]
The schema of the pgsql backend is defined as in [docs/pgsql.md](https://github.com/openstreetmap/osm2pgsql/blob/master/docs/pgsql.md#database-layout), with the columns defined in https://github.com/openstreetmap/osm2pgsql/blob/master/default.style. Given that there are **no** foreign keys, primary keys on rendering tables, unique or check constraints, or other relationships you typically use UML diagrams to visualize, I don't see why one would add any value.

**Comment by ppKrauss** [comment]
Yes, the basic UML is it, very clean: 

[![](https://wiki.openstreetmap.org/w/images/b/bf/UMLclassOf-osm2pgsql-schema.png)](https://wiki.openstreetmap.org/wiki/File:UMLclassOf-osm2pgsql-schema.png)

As all illustrations, have its power of summarize and consolidate information... In this case, using UML, it is also a **standard summarization**, for any one that never see OSM maps or osm2pgsql.

... I will review (the complex) Wiki documentation and community's [Osm2pgsql/schema](https://wiki.openstreetmap.org/wiki/Osm2pgsql/schema) perspective... them back here with a good and final suggestion. Perhaps proposing something to "syncronize documentations".

-----

PS: there are a project  that exports (or check or report) the [spatial relations](https://en.wikipedia.org/wiki/DE-9IM) and "consistence constraints"? Example: all 5570 [municipalities of Brazil](https://en.wikipedia.org/wiki/Municipalities_of_Brazil) in  *osm_polygon*  must be into (by [ST_Contains](http://www.postgis.org/docs/ST_Contains.html))  a [states of Brazil](https://en.wikipedia.org/wiki/States_of_Brazil)  of *osm_polygon*.

**Comment by lonvia** [comment]
The wiki page has been updated in the meantime.
