### ISSUE TITLE
A new option to use JSONb instead hstore

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/osm2pgsql#672]
Let's simplify the suggestion of #533 , now it is only to "use JSONb instead hstore", where hstore  has been used. 
Imagine  at [`options.cpp`](https://github.com/openstreetmap/osm2pgsql/blob/master/options.cpp) 

```
JSONb options:\n\
   -g|--jsonb      Add tags without column to an additional JSONb\n\
                    (key/value) column\n\
      --jsonb-match-only   Only keep objects that have a value in one of\n\
                    the columns (default with --jsonb is to keep all objects)\n\
   -y|--jsonb-all  Add all tags to an additional JSONb (key/value) column\n\
   -n|--jsonb-column   Add an additional JSONb (key/value) column containing\n\
                    all tags that start with the specified string, eg\n\
                    --jsonb-column \"name:\" will produce an extra JSONb\n\
                    column that contains all name:xx tags\n\
      --jsonb-add-index    Add index to JSONb column.\n\
 ```

**Comment by pnorman** [comment]
``--hstore`` and related options are widely used so they need to be kept, and I'd rather not use any of our few spare one-letter options for jsonb.

I don't see an advantage to JSONb over hstore for simple text key-value.

**Comment by ppKrauss** [comment]
It is not a replacement for HStore in osm2psql tradition, it is only to be friendly with JSON users, an option... It is about "user community", JSON community is bigger tham HStore. 

It is a matter of welcoming and being nice with these users.

**JSON is a universal standard** and HStore is not... The aim, in a first moment, for a first step, is not technological advantage...   Humanity need standards to sum efforts and to simplify life, this is the advantage.

As any other formats and casts, there are many ways to convert, so, even when is simple to cast, each one by your self can produce different castings. The "do by your self" convertion is not uniform. The "JSON-lovers community" need **a help of  `osm2psql` to obtain   "the JSON  standard cast for OSM"**.

-----

For a distant future... Imagine.  All "OSM standards" are in XML. XML elements can be isolated, but some remains encoding element's informatin in a tree. JSON is also a tree:  is the "natural way" to translate OSM into SQL.

**Comment by lonvia** [comment]
"it's an universal standard" is not a good enough reason to include a new feature in a software. Here are some factors that weigh in when considering new features:

 * number of users actually using the new feature
 * grade of improvement over existing features (adding missing functionality, improving usability, etc.)
 * development effort
 * source code maintainability

Adding native JSON support doesn't get a very high rating on any of these factors, I'm afraid. There are already possibilities to use JSON, either through the lua transforms or by querying the hstore columns with hstore_to_json. hstore is reasonably well supported by postgres libraries. So far you haven't shown any examples where your life will be made easier in practise by having JSON support. The implementation of this feature is not trivial, in particular wrt performance. Finally, there is no way we add another 5 command line options. So an implementation needs to leverage the existing hstore switches.

All that said, you are still welcome to submit a PR which adds JSON. It will be much easier to discuss the advantages and disadvantages on a concrete piece of code. But please don't expect the osm2pgsql maintainers to implement it, there are simply too many issues open which are a lot more pressing.

**Comment by ImreSamu** [comment]
@ppKrauss 
> It is about "user community", JSON community is bigger tham HStore.

I think the similar issue will be in the future with:  [WKB](https://en.wikipedia.org/wiki/Well-known_text)  vs  [GeoJSON](https://en.wikipedia.org/wiki/GeoJSON)    

imho:      my quick & dirty solution  -  is  just creating  a  simple `view` :  
```sql
CREATE VIEW planet_osm_point_json   AS SELECT hstore_to_json(tags) as json_tags , ST_AsGeoJSON(way) as osm_geojson,*  FROM planet_osm_point ;
CREATE VIEW planet_osm_line_json    AS SELECT hstore_to_json(tags) as json_tags , ST_AsGeoJSON(way) as osm_geojson,*  FROM planet_osm_line ;
CREATE VIEW planet_osm_polygon_json AS SELECT hstore_to_json(tags) as json_tags , ST_AsGeoJSON(way) as osm_geojson,*  FROM planet_osm_polygon ;
CREATE VIEW planet_osm_roads_json   AS SELECT hstore_to_json(tags) as json_tags , ST_AsGeoJSON(way) as osm_geojson,*  FROM planet_osm_roads ;
```

And probably we can create a document about the best practices  (  `./docs/json_processing.md`  )

**Comment by pnorman** [comment]
Closing per @lonvia's comments above, which I endorse.
