### ISSUE TITLE
don't split route lines at import

### ISSUE THREAD

**Issue by marcosfede** [openstreetmap/osm2pgsql#677]
Hello, I downloaded the osm data for my region and I want to make spatial querys (for example, does this route intersect with these two points/areas? ) for bus routes.
I can see that the bus routes are being split into several chunks, specially when the bus makes a circle (there are lots of circular parks in my area).

the way I'm importing the data is 
```
osm2pgsql -E 3857 --cache-strategy sparse --slim -d mydb -H localhost -U myuser -P 5432 --hstore --hstore-add-index file.osm
```
I have also tried using the `-G` parameter, but the routes keeps splitting up into chunks.

How would I import the data without splitting the bus routes? 
Thanks in advance

**Comment by pnorman** [comment]
`type=route` relations cannot always form a contiguous linestring, so may end up producing multiple rows. Even where they can form a single linestring, they can be split for length.

> I have also tried using the -G parameter, but the routes keeps splitting up into chunks.

Yes, `-G` is for multipolygons only.

**Comment by marcosfede** [comment]
Is there a way I can consolidate the rows to get a single linestring? 
the problems seems that when the route enters a rondabout the line splits, example:
http://www.openstreetmap.org/relation/5419031 
has  http://www.openstreetmap.org/way/23187155 in it , and the route is being split at that point.

**Comment by lonvia** [comment]
The new 'flex' output allows to customize the splitting of route relation lines (including creating one big multiline).
