### ISSUE TITLE
non-geometrical members of a boundary relation treated as boundary

### ISSUE THREAD

**Issue by polarbearing** [openstreetmap/osm2pgsql#678]
A [boundary relation](https://wiki.openstreetmap.org/wiki/Relation:boundary) can have ```way``` members that describe the geometry of the boundary, such as ```outer```, ```inner```<strike>, and the deprecated ```enclave``` and ```exclave```</strike>. Other members should not be treated as geometrical descriptions, such as ```admin_centre```, even when they are ways and not nodes. 

See gravitystorm/openstreetmap-carto#2559 for the effects of this issue, where a townhall is the admin_centre of various boundary relations, and the boundary style is rendered on the building outline.

Thanks @pnorman for pointing me here, help would be appreciated to create the test case.

**Comment by lonvia** [comment]
That's just plain wrong tagging. admin_centres should be place nodes, nothing else. Let's not add support for degenerating multipolygon/boundary/route relations into a collection of anything remotely related.

**Comment by polarbearing** [comment]
admin_centre is an inherent part of the boundary relation, not something remotely, and not anything. Restricting tagging to a node is unreasonable. 

The fundamental issue is that only roles defined for the geometry of the relation should be white-listed as such, and not any other way (i.e. catch-all).

**Comment by lonvia** [comment]
admin_centre was defined as a place node until you've changed the definition in the wiki yesterday. Do you mind linking to the discussion that prompted that change?

**Comment by polarbearing** [comment]
Discussion page on the wiki page.

**Comment by lonvia** [comment]
Sorry, but this is not enough of a discussion. This seeming little change breaks pretty much any software that processes boundaries. I've reverted the change in the wiki page. Please bring up the issue on the tagging@ mailinglist for wider discussion first.

Closing here, as this is a tagging discussion, not a software issue.

**Comment by polarbearing** [comment]
Tagging discussion opened.

> not a software issue.

Disagree here, it is a software issue (catch-all implementation) that is now triggered by a tagging choice. I propose to re-open.
