### ISSUE TITLE
cannot import one particular building, ...

### ISSUE THREAD

**Issue by thbeutin** [openstreetmap/osm2pgsql#680]
...but the building is visible on the OSM website: https://www.openstreetmap.org/way/44523065

I try to import it by using osm2pgsql version 0.93.0-dev (64 bit id space) with the following parameters:
pbzip2 -c -d -m100000 -p48 "$planetFile" | osm2pgsql --verbose --hstore-all --create --slim --cache 16384 -S "$STYLE" -d "$dataBase" \
  --multi-geometry --extra-attributes \
  --exclude-invalid-polygon \
  --number-processes 16 \
  --unlogged \
  --tablespace-main-data osm \
  --tablespace-slim-data osm \
  --tablespace-main-index pg_default \
  --tablespace-slim-index pg_default \
  --cache-strategy dense \
  -r xml \
  /dev/stdin 2>&1

btw: it doesn't matter if i skip the option "--exclude-invalid-polygon" either.

The shell values "planetFile", "STYLE", and "dataBase" are properly set, and the nodes get imported into planet_osm_nodes, but unfortunately not the building into planet_osm_polygon.

Any help appreciated!

ps: if neccessary i can provide a stripped down OSM XML file containig just this single building and the nodes referenced by this building.

**Comment by ImreSamu** [comment]
Maybe a polygon problem ?
```
layer:	self_intersection_ways
way_id:	44523065
tags:	building=yes
```
http://tools.geofabrik.de/osmi/?view=geometry&lon=-77.06223&lat=38.86142&zoom=18

**Comment by ImreSamu** [comment]
And as I see - 
this building is missing from the  new Lua transforms map also: 
https://lua.osm-carto.paulnorman.ca/#18/38.86129/-77.06275

**Comment by thbeutin** [comment]
I know the polygon is somewhat "strange" (and the first two nodes entries on the list of the way can be removed w/o loosing any information), but it's visible on OSM.

**Comment by ImreSamu** [comment]
> but it's visible on OSM.

just a guess:
You are using the latest ( 0.93.0-dev ) version, and probably the 7y old osm data ( `timestamp="2009-11-27T10:28:33Z"`)  imported with older  osm2pgsql version , with different algorithm 

There are some major changes since 0.90.0  -  related to Invalid geometries ( https://github.com/openstreetmap/osm2pgsql/releases/tag/0.92.0 )

*  Can you re-test with older osm2pgsql versions? [ < 0.90.0  ;  < 0.92.0 ]  
* AND/OR  -   with an older [GEOS (Geometry Engine )](https://trac.osgeo.org/geos)

**Comment by pnorman** [comment]
You can see the problem on 
![image](https://cloud.githubusercontent.com/assets/1190866/22409681/cfd638f6-e642-11e6-98a3-5e601d216712.png). The way goes back over itself.

I don't consider it a bug that it fails to form a polygon, even after `buffer(0)` from geos. If it were a bug, I'd classify it as wontfix given the likely effort in expanding recovery of broken polygons.

As for why the OSMF servers produce a polygon, it could be anything from a different geos version to a different osm2pgsql version.

**Comment by thbeutin** [comment]
@ImreSamu:
using osm2pgsql SVN version 0.82.0 (64bit id space) and skipping "--exclude-invalid-polygon" i end up having a NULL (i.e. empty) polygon (WKT 010300002031BF0D0000000000) in the planet_osm_polygon table. This setup uses PostgreSQL 9.3.14, POSTGIS="2.1.2 r12389" GEOS="3.4.2-CAPI-1.8.2 r3921" ...

**Comment by thbeutin** [comment]
> As I see it has been fixed ( v3 ) https://www.openstreetmap.org/way/44523065
jepp, my colleague "destroyed"  my example ;)
