### ISSUE TITLE
output-multi: unnecessary expiry for relations

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#682]
`output_multi_t::process_relation()` does its own expiry of geometries [when looping over the wkbs created from the relation](https://github.com/openstreetmap/osm2pgsql/blob/master/output-multi.cpp#L402). It then calls `copy_to_table()` which in turn calls expiry [here](https://github.com/openstreetmap/osm2pgsql/blob/master/output-multi.cpp#L446) and [here](https://github.com/openstreetmap/osm2pgsql/blob/master/output-multi.cpp#L457). Both actually work on the content of m_way_helper which actual has still the last processed way cached.

**Comment by joto** [comment]
We have decided to deprecate the multi backend so I believe we can close this here.

**Comment by lonvia** [comment]
The links are dead now and I don't quite remember what the issue was. So closing. I do suspect though that the expiry is wrong in places in the other outputs as well.
