### ISSUE TITLE
Distribution of initial database dump

### ISSUE THREAD

**Issue by andrew-aladev** [openstreetmap/osm2pgsql#686]
I've received over 9000 issues while creating initial database from planet or its extracts. I had to increase ram, tune postgresql, filesystem and borrow ssd drives. I've lost many days of my life without any reason.
I see that everyone who started using open street map received this pain. Today I have a great powerfull machine and I don't need it. My application needs 0.1% of its power.

Why @openstreetmap couldn't distribute some kind of `pg_dumpall.lzma`? This file will be about 50G. Thank you.

**Comment by andrew-aladev** [comment]
I've used amazon r2 server (Xeon E5-2670 v2, 30 ram, big ssd) to import Africa. Than I've created `pg_dumpall.lzma` and imported it into small server (intel atom 425, 1 ram, 5400 hdd) without any problems. The power of this small server is enough to run region updates every day.

You can distribute several dumps. For example `pg_dumpall.m.lzma` for mapnik and `pg_dumpall.l.lzma` for nominatim.

**Comment by lonvia** [comment]
This is outside the scope of this issue tracker (which provides the software, not the data).

That said, given that this idea has come up again and again in the last years, yet nobody has ever stepped up to provide such a dump, it is a clear sign that it is not practical to provide. But then again, we don't know for sure until somebody actually tries it.
