### ISSUE TITLE
Should we issue DROP TABLE ... CASCADE

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#687]
I have a setup where I have a view on a rendering table, and `osm2pgsql --create` fails when dropping tables with

```
Setting up table: pier_line_raw
Osm2pgsql failed due to ERROR: DROP TABLE IF EXISTS pier_line_raw failed: ERROR:  cannot drop table pier_line_raw because other objects depend on it
DETAIL:  view pier_line depends on table pier_line_raw
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

Given that `--create` is a destructive operation to previous data in the DB, I think we should `DROP TABLE ... CASCADE`

**Comment by eldang** [comment]
I would worry about this causing collateral damage, i.e. losing views that I still need in my database.  I think it's safer to let the user deal with this - that way we can individually deal with dropping and remaking the dependent views, rather than risk losing them to an automated DROP CASCADE.

**Comment by pnorman** [comment]
They're supposed to lose them when reimporting. Any post-import SQL will need to be run again after an import, but that's already true since custom indexes are dropped too.
