### ISSUE TITLE
Tweaking Postgres for faster tiles generation

### ISSUE THREAD

**Issue by Koles500** [openstreetmap/osm2pgsql#689]
Hi. I am refering to #676 
So we made it in 15 days :-)  
However... ! Now generating tiles with generate_tiles.py script (from here: http://svn.openstreetmap.org/applications/rendering/mapnik) for whole Europe is awfully slow, it generated ~ 135 tiles in ~ 10 minutes, I am running it for zoom level from 3 to 16 for whole Europe 

```
    minZoom = 3
    maxZoom = 16
    
    bbox = (-25.7251167, 34.3190864, 34.9770923, 72.4137726)
    render_tiles(bbox, mapfile, tile_dir, minZoom, maxZoom, "Europe")
```

How can we optimize Postgres and that script so it will run faster (I know SSD would help but we dont have it yet ^^) ? Thanks.

**Comment by ImreSamu** [comment]
> How can we optimize Postgres ...

see 
* http://www.paulnorman.ca/blog/2016/06/improving-speed-with-reclustering/
* http://www.paulnorman.ca/blog/2016/08/identifying-slow-rendering-queries/
* http://www.paulnorman.ca/blog/2016/08/sampling-slow-postgres-queries/
* http://www.paulnorman.ca/blog/2015/06/real-performance-numbers-for-a-style/
* http://www.paulnorman.ca/blog/archives/
* ... 

and
* "osm2pgsql:mapnik — Optimizing the Rendering Toolchain - Paul Norman"  https://www.youtube.com/watch?v=Lxloo42gl8A  ( video )
* http://www.paulnorman.ca/files/osm2pgsql-performance.pdf

and:
*  https://wiki.postgresql.org/wiki/Performance_Optimization

**Comment by lonvia** [comment]
This is the issue tracker for osm2pgsql, not a general help forum. Closing for being off-topic.
