### ISSUE TITLE
ERROR: mark_ways_by_node failed

### ISSUE THREAD

**Issue by Laudano81** [openstreetmap/osm2pgsql#690]
Hi, I'm trying to import an *.osm file in a postgres database but a mark_ways_by_node error appared:

```
osm2pgsql -c -d bogota --slim Dati/bogota_r01.osm
osm2pgsql SVN version 0.88.1 (64bit id space)

Using built-in tag processing pipeline
Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=800MB, maxblocks=102400*8192, allocation method=11
Mid: pgsql, scale=100 cache=800
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: Dati/bogota_r01.osm
node cache: stored: 1(100.00%), storage efficiency: 0.10% (dense blocks: 1, sparse nodes: 0), hit rate: -nan%
Osm2pgsql failed due to ERROR: mark_ways_by_node failed: ERROR:  prepared statement "mark_ways_by_node" does not exist
(7)
Arguments were: -30470, 
```

I can't find any solution.

**Comment by pnorman** [comment]
Does this happen with 0.92.0? How is the file sorted?

**Comment by Laudano81** [comment]
I don't know how the file is sorted, I have dowloaded the raw xml file from mapzen.com
i have osm2pgsql SVN version 0.88.1 (64bit id space)

**Comment by pnorman** [comment]
> i have osm2pgsql SVN version 0.88.1 (64bit id space)

Please try with a more recent version

**Comment by Laudano81** [comment]
I have found this zip file
https://launchpad.net/ubuntu/+source/osm2pgsql/0.92.0+ds-1
but every time I try to install it, this error occours.

[  3%] Building CXX object CMakeFiles/osm2pgsql_lib.dir/expire-tiles.cpp.o
In file included from /home/laudano/Scaricati/osm2pgsql-0.90.1/options.hpp:5:0,
                 from /home/laudano/Scaricati/osm2pgsql-0.90.1/expire-tiles.cpp:18:
/home/laudano/Scaricati/osm2pgsql-0.90.1/reprojection.hpp:13:38: **fatal error:** osmium/geom/projection.hpp: File o directory non esistente
compilation terminated.

I'm not good enough yet to resolve this kind of error.

**Comment by pnorman** [comment]
Information on how to install and build is [in the readme](https://github.com/openstreetmap/osm2pgsql#installing)

**Comment by Laudano81** [comment]
I know. The error occours with a command of the readme.

**Comment by pnorman** [comment]
> I know. The error occours with a command of the readme.

There seems to be some confusion - you said you were getting 0.92.0 from launchpad.

**Comment by Laudano81** [comment]
I'm so sorry, probably I can't explain myself. I start again from the beginning.
Using 'apt install osm2pgsql' I get the 0.88.1 64bit version. No problem installing the packet but I have an error when I try to import OSM file in postgres database (with postgis extension).
You said me to install a more recent version.
So I find file 'osm2pgsql_0.92.0+ds.orig.tar.gz' in this url 'https://launchpad.net/ubuntu/+source/osm2pgsql/0.92.0+ds-1' and i read all the readme file. When i Try to do the step 'sudo make install' from the terminal, I get the second type of error. 
There is some step that I miss o something that I need to know?
Thanks in advance for your kindness.

**Comment by pnorman** [comment]
https://github.com/openstreetmap/osm2pgsql is the source for osm2pgsql, not launchpad.

**Comment by Laudano81** [comment]
Ok... so
1 - I un-installed the previous version;
2 - I installed the new version downloaded from github
3 - Everything works fine!!!

My mistakes were:
1 - Using an old version 0.88.1
2 - I had compiled the new version 0.93 but I haven't installed it (like a noob)
3 - Searching for a different source from github

Thank you for your time. I'll try harder to not be a noob.

**Comment by pnorman** [comment]
Whatever it is, it's fixed with recent versions, probably with the switch to libosmium for parsing.

One guess is somehow a negative ID is in the file and that's causing the problem.
