### ISSUE TITLE
Store slim table tags in hstore

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#692]
I did some testing, and the representation of tags in a hstore is more efficient than our current `text[]` array of alternating keys and values. For testing latter can be turned into the former with `hstore(tags)`.

Doing this on the slim table of a planet and summing the `pg_column_size` gives a size of 38GB for `text[]` representation and 30GB for `hstore`. The overall size of the current slim table is 94GB for the table and 190GB for the indexes so this is about a 5% space savings.

I considered jsonb, but it is the same size as hstore.

This change would require the hstore extension for osm2pgsql databases. I do not consider this an issue because hstore is a standard part of contrib, and many databases require it already.

In addition to being more efficient, if someone did want to use our internal slim tables to query by tag, it is much easier to do so with hstore.

**Comment by Komzpa** [comment]
Internally `jsonb` and `hstore` are similar, except that `jsonb` is supported in core Postgres. Reasons to use `hstore` nowadays are about it being a legacy. If you're writing new code please use `jsonb`.

**Comment by Komzpa** [comment]
If you want to go extensions, there's between-row deduplicating `jsonb` drop-in replacement from the same people who made `jsonb` and `hstore`: https://github.com/postgrespro/zson

**Comment by pnorman** [comment]
The version requirements for jsonb would require two different implementations in osm2pgsql, one for 9.4+ and another for previous versions. This rules it out.

I do not see requiring the extension as an issue, given we require the postgis extension and many uses will require the hstore extension anyways.

This would be true regardless of if I felt if jsonb was a better option for new code. Absent good evidence on performance, I don't.

**Comment by pnorman** [comment]
As for zson, requiring an extension that's not in contrib and compiled by default (or part of postgis) **is** a barrier.

**Comment by ppKrauss** [comment]
Hi, I am using direct [`jsonb_object(text[])`](https://www.postgresql.org/docs/current/static/functions-json.html#FUNCTIONS-JSON-CREATION-TABLE) to convert tags of slim tables, was fine.  For geometry tables also easy, alter table `USING hstore_to_jsonb_loose(tags)`  [as commented here](https://github.com/openstreetmap/osm2pgsql/issues/533#issuecomment-271745550) (instead `::jsonb` default cast)... And it is not only "to being more efficient", is also to being more standard.

About other (above) comments, nowdays &mdash; 2018 and [pg v9.3 end of life](https://www.postgresql.org/support/versioning/), the v9.4+ is the reference version &mdash; is time to use `jsonb`  datatype...  Even when equivalent (as @Komzpa say "Internally jsonb and hstore are similar"), `jsonb`  is better. It is important an `osm2pgsql` **option to user decision**. 

The `jsonb` datatype (a JSON-standard) is a [*de facto* standard](https://en.wikipedia.org/wiki/De_facto_standard) for PostgreSQL developer community: 

> *if you're choosing a dynamic structure you should choose jsonb over hstore*, <br/>[dba.stackexchange](https://dba.stackexchange.com/questions/115825/jsonb-with-indexing-vs-hstore) C. Ringer (2015)

> [jsonb-vs-hstore **performance**](http://mateuszmarchel.com/blog/2016/06/29/jsonb-vs-hstore-performance-battle/): `hstore` have equal performance only *"especially if it's indexed with GIN"*, M. Marchel (2016)... But default  `osm2pgsql` is without indexation, so `hstore` have low performance.

> *In most cases JSONB is likely what you want when looking for a NoSQL, schema-less, datatype* (...) <br/>(...) *JSONB - In most cases*; <br/> *hstore - Can work fine for text based key-value looks, but in general JSONB can still work great here*, [citusdata.com](https://www.citusdata.com/blog/2016/07/14/choosing-nosql-hstore-json-jsonb/) C. Kerstiens (2016).
