### ISSUE TITLE
Disk space not freed with --slim --drop

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#696]
![drop-load-disk](https://cloud.githubusercontent.com/assets/1190866/23535949/9bbe9e76-ff76-11e6-8d9d-1fc363f63e7c.png)
![drop-load-size](https://cloud.githubusercontent.com/assets/1190866/23535951/9cfc3104-ff76-11e6-9d0c-101153baa0fa.png)

The timescales are approximately the same, but from about 0530 to 0700 there's a drop in database size, but not total disk usage.

I suspect something is holding open transactions

**Comment by lonvia** [comment]
@pnorman Could you check at some point if this is still an issue or if it has been fixed with #813?

**Comment by lonvia** [comment]
Assuming fixed by #813.
