### ISSUE TITLE
Add `make uninstall` rule for easier uninstallation

### ISSUE THREAD

**Issue by jnachtigall** [openstreetmap/osm2pgsql#717]
After installing I learnt about Debian package and long-term this seems better. To uninstall a `make uninstall` rule would have been handy. So maybe this might be added.

For now I just did `locate osm2pgsql` (or `find`) and delete what I could find by hand.

**Comment by pnorman** [comment]
notes

- https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F
- https://gist.github.com/royvandam/3033428
- https://www.linux.com/blog/cmake-recipe-5-adding-uninstall-target-your-project

**Comment by mmd-osm** [comment]
I don't know if this is worth the effort, current 1.2.0 version installs just 4 files, which are listed in the `make install` log files towards the end. It should be fairly straight forward to remove those files by hand.

```
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/bin/osm2pgsql
-- Installing: /usr/local/share/man/man1/osm2pgsql.1
-- Installing: /usr/local/share/osm2pgsql/default.style
-- Installing: /usr/local/share/osm2pgsql/empty.style
```

As a side note, current Debian packages for osm2pgsql seem a bit dated (e.g. https://packages.debian.org/source/stable/osm2pgsql).

**Comment by lonvia** [comment]
I lean towards closing this issue. It's just too complicated to do in CMake and hard to test. If you needed something uninstallable, use distribution packages. They do it right.

@pnorman any opinion?
