### ISSUE TITLE
Updates with diffs saved as .osm.gz cause dropped objects

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#722]
From https://github.com/openstreetmap/chef/pull/118

If replication diffs are saved with a .osm name, then osm2pgsql drops items in modify blocks.

See https://phabricator.wikimedia.org/T160781 for more investigation.

**Comment by lonvia** [comment]
I did a quick test, libosmium processes diffs saved as .osm.gz just fine. All changes are propagated back to the handler. And osm2pgsql's handler in parse.osmium.cpp also contains no code that makes a difference between diffs and full files. Do you have an example where the different prefix makes a difference and not #735?

**Comment by pnorman** [comment]
> Do you have an example where the different prefix makes a difference and not #735?

It could have been that. That one depended on the order of the ways so I could have misdiagnosed this.
