### ISSUE TITLE
Multilinestrings built for relations with multi backend

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#726]
I had to apply #725, but with a much simplified cleartables I get

```
pnorman@pippin:~/osm/ClearTables/ClearTables$ ~/osm/osm2pgsql/build/osm2pgsql -d osm2pgsql_test --number-processes 1 --output multi --style cleartables.json --flat-nodes nodes.bin ~/osm/osm2pgsql/tests/liechtenstein-2013-08-03.osm.pbf
osm2pgsql version 0.93.0-dev (64 bit id space)

Using lua based tag processing pipeline with script admin.lua
Using lua based tag processing pipeline with script admin.lua
Using lua based tag processing pipeline with script place.lua
Using projection SRS 3857 (Spherical Mercator)
Setting up table: admin_area
Setting up table: admin_line
Setting up table: place_point
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=3

Reading in file: /home/pnorman/osm/osm2pgsql/tests/liechtenstein-2013-08-03.osm.pbf
Using PBF parser.
  parse time: 0s
Node stats: total(65733), max(65733) in 0s
Way stats: total(7121), max(7121) in 0s
Relation stats: total(113), max(113) in 0s
Committing transaction for admin_area
node cache: stored: 65733(100.00%), storage efficiency: 89.16% (dense blocks: 9, sparse nodes: 0), hit rate: 100.00%
Osm2pgsql failed due to ERROR: result COPY_END for admin_line failed: ERROR:  Geometry type (MultiLineString) does not match column type (LineString)
CONTEXT:  COPY admin_line, line 1, column way: "0105000020110F0000010000000102000020110F000045020000AD5AF7DB5E5E3041601BDF590DB35641F5C905C4385E3041..."
```

Looking at it with gdb, I *think* it's entering `get_wkb_multiline` from https://github.com/openstreetmap/osm2pgsql/commit/e1b75a5775d410b4e66cdef76d20c335b43706b3?diff=unified#diff-84169822394671b5c318a60145ba54dfR22, while before it used to call build_both

**Comment by lonvia** [comment]
There is no build_both anymore. The caller must now decide in advance if they want a polygon or line. the problem is that currently the `do_split` parameter decides if a multiline is returned or multiple linestrings. To get the old behavior back, make `split_at` a parameter to the function and then call `get_wkb_multiline` with `do_split=true` and `split_at=100000000` (i.e. a very large value).

We should make split_at configurable, see also #677.

**Comment by pnorman** [comment]
I'm wondering why the pgsql backend doesn't hit this too. Doesn't it call the code too?

**Comment by lonvia** [comment]
The split parameter for get_wkb_multiline() does the magic here. You ask for a split=true and the function returns an array of lines. With split=false a single multiline is returned. The pgsql backend has split=true.

**Comment by pnorman** [comment]
Ah, it's calling get_wkb_multiline() directly?

The diff I'm currently testing with is
```diff
diff --git a/processor-line.cpp b/processor-line.cpp
index 3c97103..4906124 100644
--- a/processor-line.cpp
+++ b/processor-line.cpp
@@ -19,5 +19,5 @@ processor_line::process_relation(osmium::Relation const &,
                                  osmium::memory::Buffer const &ways)
 {
     // XXX are multilines really acceptable?
-    return m_builder.get_wkb_multiline(ways, false);
+    return m_builder.get_wkb_multiline(ways, true);
 }
```

**Comment by lonvia** [comment]
This still doesn't get you the same behaviour as before because before the multi backend would never split ways just because they are too long. That's why I was saying that you need to make `split_at` a parameter of the `get_wkb_multiline` function.
