### ISSUE TITLE
Road labels issue

### ISSUE THREAD

**Issue by Koles500** [openstreetmap/osm2pgsql#733]
Hi. We rendered tiles with osm2pgsql #675 and road labels look quite strange as per attached screenshot. Why do these labels look so strange ?

![tile-rendering-road-labels-issue-2](https://cloud.githubusercontent.com/assets/25249143/24613815/b8379374-1889-11e7-9fb9-edb44d154768.png)

**Comment by lonvia** [comment]
You are reporting this in the wrong issue tracker. osm2pgsql has nothing to do with rendering.

**Comment by Koles500** [comment]
Of course it does! Isn't this related with default.style file ?
You are irritating me again closing my topic immidiately. Please re-open this.

**Comment by hholzgra** [comment]
default.style isn't a renderer style file, it defines the mapping from OSM tags to database tables and columns.

**Comment by Koles500** [comment]
Thank you ^^
