### ISSUE TITLE
unused column "way_area" in the _line and _roads tables

### ISSUE THREAD

**Issue by thbeutin** [openstreetmap/osm2pgsql#734]
When i import an OSM extract using the [empty.style](https://raw.githubusercontent.com/openstreetmap/osm2pgsql/master/empty.style) i got the column "way_area" in the tables for lines and roads containing NULLs only. The values in the polygon table are fine.

Is this intentionally or a mistake?

**Comment by pnorman** [comment]
I thought we didn't have a way_area column for lines, but checking shows the column is there too.

It's normal to not have an area for those, since they're not polygons.

**Comment by thbeutin** [comment]
> It's normal to not have an area for those, since they're not polygons.

Yes, that's obvious, and this is the main reason for opening this issue ;)
But wouldn't [ST_Length](http://postgis.net/docs/ST_Length.html) fit here perfectly?

**Comment by joto** [comment]
I expect we don't want to change this for backwards compatibility. The new "flex" backend allows you to set exactly the columns you need, so when people switch to it, this issue becomes moot.
