### ISSUE TITLE
Updating from unordered change file triggers assertion in persistent data storage

### ISSUE THREAD

**Issue by ge-fa** [openstreetmap/osm2pgsql#743]
Updating a planet database via:

`osm2pgsql --append --hstore --slim --flat-nodes /var/cache/osm/nodes.cache -H xxx -d xxx -U xxx --number-processes 4 -C 800 --expire-tiles 15-18 -o expired_tiles.list changes.osc.gz`

leads to

``Processing: Node(1649k 2.7k/s) Way(429k 2.44k/s) Relation(10857 26.10/s)osm2pgsql: /build/osm2pgsql-0.92.0+ds/node-persistent-cache.cpp:369: void node_persistent_cache::set_append(osmid_t, double, double): Assertion `!read_mode' failed.``

This is a Debian system, using `osm2pgsql` out of j-bp currently, which is:
`osm2pgsql version 0.92.0 (64 bit id space)`.

Anything I could do to debug this further? Any more information needed?

**Comment by pnorman** [comment]
Nothing obvious is jumping out at me from the command line. How was changes.osc.gz generated? Can you paste `zcat changes.osc.gz | head -n 30`

I'd start by trying with --number-processes 1 and without --expire tiles. Neither of these is likely to be a cause, but `--expire-tiles` isn't **required** to do the update and single process is easier to debug. 

-----

https://github.com/openstreetmap/osm2pgsql/blob/0.92.0/node-persistent-cache.cpp#L369 is the assertion, being called from https://github.com/openstreetmap/osm2pgsql/blob/0.92.0/node-persistent-cache.cpp#L390. That is either called from https://github.com/openstreetmap/osm2pgsql/blob/0.92.0/middle-pgsql.cpp#L387 or https://github.com/openstreetmap/osm2pgsql/blob/0.92.0/middle-pgsql.cpp#L415 depending on if it's a node create/modify or a delete.

**Comment by ge-fa** [comment]
Thanks for your fast reply!

I'm generating the changes file via:

`osmosis --read-replication-interval workingDirectory=. --sort-change seekable --write-xml-change changes.osc.gz`

Here is the HEAD of said file:

```
<?xml version='1.0' encoding='UTF-8'?>
<osmChange version="0.6" generator="Osmosis 0.45">
  <create>
    <node id="4775885259" version="1" timestamp="2017-04-05T00:01:59Z" uid="5616295" user="Claudio Lion" changeset="47459642" lat="-40.6612774" lon="-73.4676762">
      <tag k="name" v="Sergio baez"/>
      <tag k="name:es" v="Sergio baez"/>
      <tag k="tourism" v="alpine_hut"/>
    </node>
    <node id="4775885260" version="1" timestamp="2017-04-05T00:02:00Z" uid="5616295" user="Claudio Lion" changeset="47459642" lat="-40.6617902" lon="-73.4691038">
      <tag k="name" v="Ramona loncochino"/>
      <tag k="name:es" v="Ramona loncochino"/>
      <tag k="tourism" v="alpine_hut"/>
    </node>
    <node id="4775885261" version="1" timestamp="2017-04-05T00:02:07Z" uid="5616295" user="Claudio Lion" changeset="47459642" lat="-40.6820263" lon="-73.4706394">
      <tag k="name" v="Monuca trinpai"/>
      <tag k="name:es" v="Monuca trinpai"/>
      <tag k="tourism" v="alpine_hut"/>
    </node>
    <node id="4775885262" version="1" timestamp="2017-04-05T00:02:09Z" uid="5616295" user="Claudio Lion" changeset="47459642" lat="-40.6849612" lon="-73.4412449">
      <tag k="name" v="Maria quisiyao"/>
      <tag k="name:es" v="Maria quisiyao"/>
      <tag k="tourism" v="alpine_hut"/>
    </node>
    <node id="4775885263" version="1" timestamp="2017-04-05T00:02:14Z" uid="5616295" user="Claudio Lion" changeset="47459642" lat="-40.725325" lon="-73.5250549">
      <tag k="name" v="Ricardo coliguachun fallecido"/>
      <tag k="name:es" v="Ricardo coliguachun fallecido"/>
      <tag k="tourism" v="alpine_hut"/>
    </node>
    <node id="4775885264" version="1" timestamp="2017-04-05T00:02:17Z" uid="5616295" user="Claudio Lion" changeset="47459642" lat="-40.9456997" lon="-73.4056826">
      <tag k="name" v="Hernan acun"/>
```

I've imported [this](http://planet.openstreetmap.org/pbf/planet-170403.osm.pbf) planet file created on 2017/04/05. 

Regarding `--expire-tiles`: I'm aware of the fact that this isn't needed, but I'm operating a tile server and using this to remove expired tiles, afterwards.

I've tried without `--expire-tiles` and using only one process, without success.

**Comment by lonvia** [comment]
Try with `--sort-file streamable`. The osmosis documentation is a bit misleading there. osm2pgsql requires the more strict ordering, at least in the current version. To be real on the safe side, use `--simplify-change`. This also eliminates duplicates which occasionally might cause problems.

**Comment by lonvia** [comment]
That said, osm2pgsql really should be throwing an error when there is data it cannot handle, not an assertion. The new libosmium flatnode storage in master can handle simultaneous read and write, so is okay in that regard but I'm not sure about the other parts of the code. We should check that.

**Comment by ge-fa** [comment]
Using `--simplify-change`, works, thanks. Should I keep this issue open?

**Comment by lonvia** [comment]
Yes, please, leave it open as a reminder. I've shortend the title a bit.

**Comment by lonvia** [comment]
The old node cache with the assertion is gone. The ram cache might still complain but there is an appropriate warning there.
