### ISSUE TITLE
Option to skip clustering/sorting on ST_GeoHash

### ISSUE THREAD

**Issue by Komzpa** [openstreetmap/osm2pgsql#757]
I'm using osm2pgsql tables not for rendering but for producing different tables, filtering mostly by tags, not spatial location.

I'd like to have an option to skip clustering on ST_GeoHash (situation with native GiST tree shape should improve when https://github.com/postgis/postgis/pull/129 works/merged) to shave off import time, since I'm doing Sec Scans mostly anyway.

**Comment by pnorman** [comment]
Your use is covered by #27
