### ISSUE TITLE
need error message when --exclude-invalid-polygon is enabled

### ISSUE THREAD

**Issue by wambacher** [openstreetmap/osm2pgsql#765]
Lost about 6 hours today to find out, why a specific multipolygon (forest with one outer and many inners) was missing in planet_osm_polygon.
planet_osm_rels was ok.

reason: there were 2 touching inners, which made this polygon  "invalid" causing osm2pgsql to ignore it without any information. :(

request: please add an error message informing about that situation.

why do i use --exclude-invalid-polygon? i don't want osm2pgsql to hide that problem, i want to fix that.

regards
walter

**Comment by pnorman** [comment]
``--exclude-invalid-polygon`` has been removed with the geometry building changes so this is no longer relevant.
