### ISSUE TITLE
Creating new Schema for OSM data

### ISSUE THREAD

**Issue by JakobMiksch** [openstreetmap/osm2pgsql#768]
**Feature Request:**
I would be nice to choose the target schema in the database with the command line. So far I only know this way to load the OSM data in an own schema: https://gis.stackexchange.com/a/242814
An option like `--schema` would be great.

**Comment by lonvia** [comment]
There is #619 but that has gone stale again.

**Comment by Stalfur** [comment]
Agree - ability to choose schema would be most useful.

**Comment by mmd-osm** [comment]
I have a question about the search_path based approach used in #279: this seems to assume that we need to set the search_path to `SET search_path TO %1%,public;` everywhere, even though we need the public schema only in case of CREATE TABLE (e.g.due to the depency of hstore which presumably lives in the public schema).

I tried the patch below with a hardcoded schema name demo3. It seems to work here, even if there are no planet* tables in the public schema. 

<details>

```c++
diff --git a/db-copy.cpp b/db-copy.cpp
index a4f156e..47e27ab 100644
--- a/db-copy.cpp
+++ b/db-copy.cpp
@@ -104,6 +104,7 @@ void db_copy_thread_t::connect()
     // Let commits happen faster by delaying when they actually occur.
     pgsql_exec_simple(m_conn, PGRES_COMMAND_OK,
                       "SET synchronous_commit TO off;");
+    pgsql_exec_simple(m_conn, PGRES_COMMAND_OK, "SET search_path TO demo3;");
 }
 
 void db_copy_thread_t::disconnect()
diff --git a/middle-pgsql.cpp b/middle-pgsql.cpp
index b0f5ba1..0c76838 100644
--- a/middle-pgsql.cpp
+++ b/middle-pgsql.cpp
@@ -736,6 +736,8 @@ void middle_pgsql_t::start()
         util::exit_nicely();
     }
 
+    pgsql_exec_simple(m_query_conn, PGRES_COMMAND_OK, "SET search_path TO demo3,public;");
+
     if (append) {
         // Prepare queries for updating dependent objects
         for (auto &table : tables) {
@@ -861,6 +863,8 @@ middle_pgsql_t::get_query_instance(std::shared_ptr<middle_t> const &from) const
         src->out_options->database_options.conninfo().c_str(), src->cache,
         src->persistent_cache));
 
+    mid->exec_sql("SET search_path TO demo3;");
+
     // We use a connection per table to enable the use of COPY
     for (int i = 0; i < NUM_TABLES; i++) {
         mid->exec_sql(src->tables[i].m_prepare_query);
diff --git a/output-gazetteer.cpp b/output-gazetteer.cpp
index fcc7b6f..16807b5 100644
--- a/output-gazetteer.cpp
+++ b/output-gazetteer.cpp
@@ -69,6 +69,8 @@ void output_gazetteer_t::connect()
                 PQerrorMessage(m_conn));
         throw std::runtime_error("Connecting to database");
     }
+
+    pgsql_exec_simple(m_conn, PGRES_COMMAND_OK, "SET search_path TO demo3;");
 }
 
 int output_gazetteer_t::start()
diff --git a/table.cpp b/table.cpp
index d077367..afeb3fe 100644
--- a/table.cpp
+++ b/table.cpp
@@ -78,6 +78,8 @@ void table_t::connect()
     sql_conn = _conn;
     //let commits happen faster by delaying when they actually occur
     pgsql_exec_simple(sql_conn, PGRES_COMMAND_OK, "SET synchronous_commit TO off;");
+
+    pgsql_exec_simple(sql_conn, PGRES_COMMAND_OK, "SET search_path TO demo3;");
 }
 
 void table_t::start(std::string const &conninfo,
@@ -108,6 +110,9 @@ void table_t::start(std::string const &conninfo,
 
     pgsql_exec_simple(sql_conn, PGRES_COMMAND_OK, "RESET client_min_messages");
 
+
+    pgsql_exec_simple(sql_conn, PGRES_COMMAND_OK, "SET search_path TO demo3,public;");
+
     //making a new table
     if (!append)
     {

```
</details>

**Comment by lonvia** [comment]
Messing with the search path might look like a useful quick but I'm not convinced it is sustainable in the long term. We should reference schemas explicitly.

If you want to help out with this issue, pick up #619, update and clean it up, address the issues raised and make a new PR.

**Comment by mmd-osm** [comment]
This is interesting. I had exactly the opposite argument in mind: by setting the search_path centrally when connecting to the database, any subsequent statement would automatically take this into account, be it when creating indices, or adding/deleting tables entries. Having to take care of an explicit schema name everywhere adds more mental load, and there's some chance someone might simply forget about it in the future. So I'd be interested to find out where you see long term issues. Maybe I'm missing something here.

The one thing I find a bit unfortunate is that we need to add the hstore extension schema name during table creation. This might be different from "public" after all, and we might have to provide some parameter to specify the hstore schema name (which is _public_ by default).

**Comment by joto** [comment]
The new flex backend allows you to set the schema in the table definitions, but it doesn't yet work correctly. It needs some changes to other places in osm2pgsql to make this work. Basically we have to add the schema as an extra parameter in all places where table names are handed around inside the osm2pgsql code.

**Comment by joto** [comment]
This is now fully supported in the flex backend. See the docs for details.

**Comment by lonvia** [comment]
Flex supports a schema for the output tables but we'd still need support for the middle tables.

**Comment by joto** [comment]
With 2a339a7980bbd15e52cc92cb448a35c2123b3a0d there is now support for setting a schema for the pgsql output (`--output-pgsql-schema`) as well as for the middle (`--middle-schema`).
