### ISSUE TITLE
Dead Lock in Europe data file import

### ISSUE THREAD

**Issue by creatorness** [openstreetmap/osm2pgsql#779]
Hello,

The import of Europe took now 30 days and I think it is in the deadlock to create the index.
The server has 15 GB RAM 8 G B Swapp. Database is Postgres 9.2 with default setting in the psotgres.conf

I started the whole thing with `osm2pgsql -k -c -s -G -C 14000 -S openstreetmap-carto.style --tag-transform-script openstreetmap-carto.lua -d osm --number-processes 4 europe-latest. osm.pbf`

After about 16 days, he started with the index on the table planet_osm_ways and has not been finished for 14 days
I had thought ok after 2-4 days he would have to be finished, since the table is not bigger than the others.
Should i stop the Import and restart with other settings ?

Excerpt from log:

```
Node stats: total (1922813695), max (4962679860) in 7669s
Way stats: total (235055329), max (506558057) in 578569s
Relation stats: total (3533465), max (7387143) in 391987s
Committing transaction for planet_osm_point
Using lua-based tag processing pipeline with script openstreetmap-carto.lua
Going over pending ways ...
        170405835 ways are pending
Using 4 helper-processes
Finished processing 170405835 ways in 240092 s
170405835 Pending ways took 240092s at a rate of 709.75 / s
Sorting data and creating indexes for planet_osm_line
Sorting data and creating indexes for planet_osm_point
Sorting data and creating indexes for planet_osm_roads
Sorting data and creating indexes for planet_osm_polygon
Copying planet_osm_roads to cluster by geometry finished
Creating geometry index on planet_osm_roads
Creating osm_id index on planet_osm_roads
Creating indexes on planet_osm_roads finished
All indexes on planet_osm_roads created in 29415s
Completed planet_osm_roads
Copying planet_osm_point to cluster by geometry finished
Creating geometry index on planet_osm_point
Creating osm_id index on planet_osm_point
Creating indexes on planet_osm_point finished
All indexes on planet_osm_point created in 59439s
Completed planet_osm_point
Copying planet_osm_line to cluster by geometry finished
Creating geometry index on planet_osm_line
Creating osm_id index on planet_osm_line
Creating indexes on planet_osm_line finished
All indexes on planet_osm_line created in 125491s
Completed planet_osm_line
Copying planet_osm_polygon to cluster by geometry finished
Creating geometry index on planet_osm_polygon
Creating osm_id index on planet_osm_polygon
Creating indexes on planet_osm_polygon finished
All indexes on planet_osm_polygon created in 171986s
Completed planet_osm_polygon
Stopping table: planet_osm_nodes
Stopped table: planet_osm_nodes in 0s
Stopping table: planet_osm_ways
Building index on table: planet_osm_ways
```

**Comment by pnorman** [comment]
It's extremely unlikely to be a deadlock, but you can check that with the `pg_stat_activity` table.

The `planet_osm_ways` nodes index is the biggest and tags the longest, but it shouldn't take that long. It sounds like it's gone into swap and you have slow disks.

You need to look at what is using RAM, what is using swap, and what is being swapped in and out. 14000 MB is too high for the node cache on a machine with only 15GB of RAM.0

Other recommendations would be
- Use at least PostgreSQL 9.3, since it's faster at this work
- Tune your postgres appropriately for dealing with large amounts of data

If possible, get more RAM and faster drives.
