### ISSUE TITLE
too many clients alredy

### ISSUE THREAD

**Issue by matejko94** [openstreetmap/osm2pgsql#782]
I run this command:
osm2pgsql --create --database osm --cache 20000 --number-processes 16 --prefix europe --slim --port 5432 --host localhost --username postgres --password --keep-coastlines --extra-attributes --hstore-all europe-latest.osm.pbf 

and I get FATAL error: Connection to database failed: sorry, too many clients allredy. I use postgres 9.6 default settings. 
I want to export Europe fast, how do you propose to do:
- import separate countries in database and use append function in osm2pgsql.
- export whole Europe.
For daily updates is the easiest way to use --append function in your tool ?

**Comment by lonvia** [comment]
Your original question was answered: decrease --number-processes or increase the max_connection setting in postgresql. I don't know where this answer went.
