### ISSUE TITLE
PostGIS 2.4.0 z-curve implementation in clustering

### ISSUE THREAD

**Issue by Komzpa** [openstreetmap/osm2pgsql#788]
Starting from PostGIS 2.4.0rc1 `order by geom` implements sorting by z-curve.

http://postgis.net/2017/09/13/postgis-2.4.0rc1/

This is supposed to be faster than `order by ST_GeoHash(geom)`.

**Comment by pnorman** [comment]
> This is supposed to be faster than order by ST_GeoHash(geom).

How much faster than our ordering statement?

**Comment by pnorman** [comment]
ping @Komzpa

**Comment by Komzpa** [comment]
Hello!

I've benchmarked it and found out it's not faster. Sorry for not cross-posting.
https://trac.osgeo.org/postgis/ticket/3864

**Comment by pnorman** [comment]
Closing then
