### ISSUE TITLE
Relation member tag transform only called for member ways

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/osm2pgsql#791]
(not member nodes or member relations)

I noticed this when trying to write a lua transform to do something to a node based on its relation membership, but found that everything from "pgsql_out_relation" downwards, whether in lua or C, only processes member ways.

Obviously this would be an enhancement and perhaps (to avoid breaking existing code) a new tag transform call altogether?

**Comment by SomeoneElseOSM** [comment]
If I read https://github.com/openstreetmap/osm2pgsql/issues/230 correctly it only addresses ways that are members of relations, not nodes that are members of relations?  

The ability to change way tags based on relation membership would certainly be useful (for example it'd be great for a style to be able to render land boundaries but not maritime ones if it so wished), but what I was trying to address here was that `tagtransform::filter_rel_member_tag` was only called for ways, not nodes.

**Comment by lonvia** [comment]
Just to be clear, so you are trying to change tags of a relation based on the tags of its node members?

**Comment by SomeoneElseOSM** [comment]
I'm ultimately trying to change tags on node members based on relation membership.  I presume that that would need another tag transform altogether to avoid making `filter_rel_member_tags` incompatible with previous versions.

**Comment by lonvia** [comment]
That's what I understood. The mechanism for implementing that for nodes would be essentially the same as for ways in #230. I've added a comment that it might be useful for nodes too and prefer to close this ticket as a duplicate. (To be realistic though: it is unlikely that #230 will ever happen unless somebody else takes it on.)

**Comment by SomeoneElseOSM** [comment]
@lonvia Yes, that makes sense (it'll need to be a separate transform for compatibility I guess).  It is something that I'm planning to look at (though with no particular urgency - I'd need to get my head around the lua-calling code first).
