### ISSUE TITLE
Form polygons from relations which aren't closed

### ISSUE THREAD

**Issue by eoghanmurray** [openstreetmap/osm2pgsql#792]
I've encountered a situation where both a doubled border, and a gap in a linestring have caused relations tagged with type=boundary to end up in planet_osm_line instead of planet_osm_polygon.  Is there (or should there be) a way of specifying that certain tags should be forced to polygons no matter what? I don't know how the existing conversion works, but I'm thinking of some sort of 'best case' conversion using http://postgis.net/docs/ST_ConcaveHull.html
To me this would seem like sensible default behaviour given the maxim 'be liberal in what you accept'.
Thanks for a great tool!

**Comment by pnorman** [comment]
I've edited the title to be about forming polygons from unclosed relations.

I don't think the concave hull algorithm would work. For example, look at the following unclosed linestring and a possible concave hull

![image](https://user-images.githubusercontent.com/1190866/31407930-9456a13a-adbb-11e7-9176-db5cc9688109.png)

There are probably better algorithms, but I don't think we want to do this. We've moved away from attempting to repair invalid geometries.

**Comment by mboeringa** [comment]
> There are probably better algorithms, but I don't think we want to do this. We've moved away from attempting to repair invalid geometries.

+1, 
I think this is going backwards. Jochen Topf actually had this great idea of involving the community to fix a load of multipolygons last year, which has ameliorated the situation quite a bit. Still, admittedly, there are many broken multipolygons to be found and new ones being added, but I do think supporting them is no longer really the way to go, rather go fix them!

**Comment by pnorman** [comment]
Closing. We don't want to try to deal with invalid input. Geofabrik extracts now include some type of MPs to help avoid this.
