### ISSUE TITLE
Missing ways and polygons after importing filtered sorted data in slim mode

### ISSUE THREAD

**Issue by endro** [openstreetmap/osm2pgsql#797]
Hi guys, few days ago I have downloaded Europe extract from Geofabrik. Now I am trying to import complete filtered data to database.

Filtered using:
`osmosis --rbf /osm/europe/europe-latest.osm.pbf --log-progress --buffer bufferCapacity=1000 --tf accept-ways power=* --tf accept-nodes power=* --tf accept-relations power=* --sort --write-xml output.xml`

Imported using:
`osm2pgsql --create --database osm --prefix power --merc --cache 3000 --slim -S /osm/import.style /osm/europe/output.xml`

import.style:
```
OsmType  Tag          DataType     Flags
node,way   z_order      int4         linear # This is calculated during import
way        way_area     real         linear # This is calculated during import
node,way   power      text        polygon #,nocolumn
```

After importing, in power_line table I have found 330k ways and in power_polygon only 180 polygons. In temporary (slim?) table power_ways is 620k ways and polygons (with above 300k missing). Why they are not imported? Thanks for help.

Example of missing line: https://www.openstreetmap.org/way/340444076

osm2pgsql version 0.95.0-dev (64 bit id space)
INFO: Osmosis Version 0.46
PostgreSQL 9.5.9

**Comment by pnorman** [comment]
You're filtering through osmosis. Because this adds complications, can you give some example XML of a way that doesn't result in a polygon, but should?

**Comment by endro** [comment]
I have forgotten to tell that missing are not only polygons but also some ways.

Example of missing data (7 polygons and 3 ways):
`SELECT id, power_line.osm_id, power_ways.* FROM power_ways FULL OUTER JOIN power_line ON id=osm_id WHERE osm_id IS NULL ORDER BY random() LIMIT 10;`

> id | osm_id | id | nodes | tags
> 198823622 |        | 198823622 | {2089057342,2089057358,2089057344,2089057328,2089057335,2089057319,2089057315,2089057348,2089057337,2089057347,2089057345,2089057334,2089057343,2089057324}                                                                                                                                                                                                                                                                                                                                                                                                             | {fixme,continue,power,line,source,Landsat}
>
> 403969231 |        | 403969231 | {4062588409,4062588402,4062588394}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | {line,bay,power,line,cables,3,voltage,110000,circuits,1,frequency,50}
>
> 374617269 |        | 374617269 | {3780119079,3780119075,3780119082,3780119087,3780119060,3780119086,3780119058,3780119079}                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | {name,"Marino Point 110kV Substation",fixme,"Substation name",power,substation,barrier,fence,voltage,110000,operator,EirGrid,addr:city,"Great Island",substation,industrial,addr:street,"Marino Point",voltage-high,110000}
>
> 134427086 |        | 134427086 | {1478085131,1478085134,1478085138,1478085132,1478085131}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | {power,substation,building,yes}
>
> 217880457 |        | 217880457 | {2271890366,2271890367,2271890365,2271890364,2271890366}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | {power,sub_station,building,yes}
>
> 287754153 |        | 287754153 | {2913211515,2913211519,2913211513,2913211512,2913211515}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | {power,substation,building,service,building:levels,2,building:cladding,brick}
>
> 505087700 |        | 505087700 | {4951192224,4951192223,4951192222,4951192221,4951192220,4951192219,4951192218,4951192217,4951192216,4951192215,4951192214,4951192213,4951192212,4951192211,4951192210,4951192209,4951192208,4951192207,4951192206,4951192205,4951192204,4951192203,4951192202,4951192201,4951192200,4951192199,4951192198,4951192197,4951192196,4951192195,4951192194,4951192193,4951192192,4951192191,4951192190,4951192189,4951192188,4951192187,4951192186,4951192185,4951192184,4951192183,4951192182,4951192181,4951192180,4951192179,4951192178,4951192177,4951192176,4951192224} | {barrier,fence,fence_type,metal,landuse,industrial,name,"Central Solar de Estói",plant:output:electricity,yes,power,plant}
>
> 162794477 |        | 162794477 | {1746122392,1746122408,1746122410} 
| {line,bay,power,line,cables,3,voltage,150000,frequency,50}
>
> 280023300 |        | 280023300 | {2841997535,2841997536,2841997525,2841997524,2841997527,2841997528,2841997535}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | {name,"GPZ. Stacja 110kV Pępowo",power,substation,ref,"GPZ \"Pępowo\"",substation,distribution,voltage,110000;15000}
>
> 36444104 |        |  36444104 | {424970102,424970103,424970104,424970105,424970102}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | {power,substation,height,"8 m",building,yes,substation,minor_distribution,it:fvg:ctrn:code,4AEL,it:fvg:ctrn:revision,1A0}
>(10 rows)

`SELECT * FROM power_polygon WHERE osm_id IN (198823622, 403969231, 374617269, 134427086, 217880457, 287754153, 505087700, 162794477, 280023300, 36444104);`
>osm_id | z_order | way_area | power | way 
>--------+---------+----------+-------+-----
>(0 rows)

As you wanted I have exported these 10 records from output.xml using grep:
[data.txt](https://github.com/openstreetmap/osm2pgsql/files/1435836/data.txt)

**Comment by pnorman** [comment]
> As you wanted I have exported these 10 records from output.xml using grep:

There are no nodes in that XML.

**Comment by endro** [comment]
You are a genius. There was a problem, Osmosis tag-filtering option providing ways without nodes. Thanks bro for help.
