### ISSUE TITLE
Bad multipolygon tags

### ISSUE THREAD

**Issue by xificurk** [openstreetmap/osm2pgsql#80]
The parsing of tags for multipolygons seems broken - I'm getting man_made=pier on polygon created from relation 936128 (admin boundary for Poland). This is a very large multipolygon - out of several hundreds of way members only two (way 227911442 and 227911443) have this tag.

I'm using osm2pgsql build from git on 2013-09-16.

**Comment by lonvia** [comment]
Should be fixed by no longer handling old-style multipolygons.
