### ISSUE TITLE
Using LuaJIT to speed up lua code

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osm2pgsql#801]
LuaJIT is a powerful drop in replacement to run Lua code in native mode with JIT optimizations: see http://luajit.org/luajit.html for details. To evaluate the potential impact on osm2pgsql runtimes, I did some very quick & dirty prototyping. Primary goal was to have a working osm2pgsql , and being able to do some initial run time comparison between the current and a LuaJIT enabled version.

Test was using the latest openstreetmap-carto style on a very small country extract (30MB PBF). Platform: Core i7 and Ubuntu 16.04, 64bit.

`osm2pgsql -G --hstore --style openstreetmap-carto.style --tag-transform-script openstreetmap-carto.lua -d gis  extract.osm.pbf`

Before (Lua)
`Processing: Node(3045k 1015.2k/s) Way(556k 46.37k/s) Relation(1790 1790.00/s)  parse time: 16s`

After (LuaJIT)
`Processing: Node(3045k 3045.5k/s) Way(556k 139.12k/s) Relation(3410 3410.00/s)  parse time: 6s`

First conclusion: LuaJIT allows for some significant savings in the osm2pgsql parsing phase. I'd recommend to further evaluate this option and see how it might be integrated into osm2pgsql.

## Code

see pull request

NB: I do realize that OSRM removed LuaJIT support last year (see: Rip out LuaJIT for good #2955), due to lack of usage in their (Mapbox) own  setup, unclear impact wrt speed improvement and users reporting crashes. At least to some extent this seems to be related to the their build system, and automatic fallback to LuaJIT. That's why I'd propose `WITH_LUAJIT` should be disabled by default.

**Comment by lonvia** [comment]
This is definitely worth exploring further. Do you mind making a proper PR? Then I would do some performance tests. We do have the advantage over OSRM that we don't use Luabind which brings a whole lot of additional pain. So I suspect that having LuaJIT as a drop-in replacement is less complicated for us.

**Comment by mmd-osm** [comment]
The quality of this patch is still not good enough for a PR, but since you asked for one for testing purposes... :smile: 

Disabling WITH_LUAJIT settings via ccmake doesn't really work once it has been enabled once. I'm pretty sure there's some way to fix these caching issues, but I didn't investigate this any further yet. So for the time being, you would have to use a new build directory for testing:

1. Start with new clean `build` directory
2. Run `cmake -D WITH_LUAJIT=ON ..`
    Libraries used to build should include libluajit-5.1.so towards the end of the list. 
3. Build via `make` as usual.

**Comment by mmd-osm** [comment]
Was this somehow useful for testing, did it work as described? How should we proceed with this patch?

**Comment by sav123** [comment]
It works while I don't see a difference. Perhaps the last Lua version is faster or my lua file is not very impacted by the compiler change.
It is true that the lua filtering takes too much time in this long process.
If you filter the tags before osm2pgsql and you remove the same filters from the lua file, you may gain a lot of speed, ie parsing is twice faster for africa-latest.

**Comment by mmd-osm** [comment]
@sav123 : unfortunately your report is a bit light on details. I tested with openstreetmap-carto and ClearTables on a Germany extract, and parsing with luajit 5.1 vs. lua 5.2 showed 2.7x throughput. This includes https://github.com/openstreetmap/osm2pgsql/pull/815 (which had a very small impact only).

**Comment by sav123** [comment]
@mmd-osm : I updated the version and reinstalled your patchs. ldd reports links to Luajit and not lua. It was the same before the update ...

still running :
Node(105645k 84.3k/s) Way(468155k 53.35k/s) Relation(2091470 55.53/s)

 I got the same rate for the planet, about 55 kways/s with the same server. Nodes ratio is meaningless because it uses only dense nodes, other nodes being pre-processed ( to produce the flat nodes file which is not initialized by my patched version ). The result is a prog running with less than 400 Mb of ram in slim mode. When not running in slim mode, it hangs with a bad alloc error while the server has 100 gb ready for osm2pgsql.

If you are the developper of luajit ( or not ), I can open to you a ssh account to try it yourself with big files.

You must admit than an enhancement may impact differently different data. The planet is not so homogeneous. Parts are dense of ways with a few nodes and tags, other are dense of ways nodes and tags. It's worst for relations. If luajit earns speed with tags, I don't filter them at all. My lua bad tags lists are empty. I filter also relations on the tri-criteria but the other lua jobs are still too opaque for me to be pre computed.

**Comment by StyXman** [comment]
I have to say, I had the same thing. I imported twice the whole Europe using this lua style: https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/master/style.lua . I also used the null output driver, as I don't have mush free space to do it for real. 

As @sav123 , I didn't notice any improvements, so probably @mmd-osm can tell us where or what to look? I definitely like the idea of the PR, speeding up imports, but if it actually has no (noticeable?) impact, I'm not sure it's worth it.

@mmd-osm just a question: did you try first without luajit and the with it? maybe the speed difference has more to do with your source file being already cached or something?

**Comment by mmd-osm** [comment]
Right, the null output driver will not work... I had the same effect here.

**Comment by sav123** [comment]
In fact, lua is a versatile solution to handle tag modifications and other things but there is also a hard cpp file tagtransform-C that does almost the same thing.  osm2psgql is a very nice tool.

**Comment by lonvia** [comment]
@mmd-osm Sorry for the delay, it took a while for this issue to get to the top of my todo list.

I've tried now with the world and the openstreetmap-carto style and that worked out fine. I have about 2h processing time saved and pretty much all of it during the initial import stage. That is no surprise as that stage runs single-threaded, so faster Lua processing has a direct impact.

Given the low impact on code, I'd say we go ahead with it the way you have implemented it now: add it as an optional feature that is off per default. Code needs polishing, though, I'll add a couple of comments to the PR.

**Comment by mmd-osm** [comment]
As #810 is merged, I'm closing this one as well.

**Comment by mmd-osm** [comment]
As I mentioned in another pull request, we should probably add some instructions in the README file on how to enable LuaJIT, and what packages would be needed.

A rough indicator on possible speed ups for a full planet import would also be useful, in case someone can provide some figures.

**Comment by pnorman** [comment]
> A rough indicator on possible speed ups for a full planet import would also be useful, in case someone can provide some figures.

I can do that if someone tells me have. I haven't been following the luajit stuff since my process is bottlenecked on table optimization and rendering, not the lua transforms.

**Comment by mmd-osm** [comment]
> I can do that if someone tells me how.

Thanks a lot, that would be really helpful! On Ubuntu 18.04, it's only a matter of installing LuaJIT libraries and adding another parameter to `cmake` to turn on LuaJIT. Everything else should work out of the box as is.

### Install luajit5.1 dev library

```
sudo apt install libluajit-5.1-dev
```

### cmake with LUAJIT enabled

(from within osm2pgsql/build directory)

```
cmake -D WITH_LUAJIT=ON ..
```

### make

```
make -j7
```

### Verify build

Reported version number should include LuaJIT in there

```
~/osm2pgsql/build$ ./osm2pgsql --version
osm2pgsql version 0.96.0 (64 bit id space)

Compiled using the following library versions:
Libosmium 2.15.0
Lua 5.1.4 (LuaJIT 2.1.0-beta3)
```

**Comment by pnorman** [comment]
With a standard OpenStreetMap Carto import

```
Libosmium 2.15.0
Lua 5.2.4
Processing: Node(5006981k 1866.2k/s) Way(559475k 38.71k/s) Relation(6549380 1141.60/s)  parse time: 22872s
Node stats: total(5006981640), max(6240800798) in 2683s
Way stats: total(559475293), max(666563604) in 14452s
Relation stats: total(6549807), max(9266826) in 5737s
```

```
Libosmium 2.15.0
Lua 5.1.4 (LuaJIT 2.0.4)
Processing: Node(5006981k 5401.3k/s) Way(559475k 77.52k/s) Relation(6548690 1182.29/s)  parse time: 13683s
Node stats: total(5006981640), max(6240800798) in 927s
Way stats: total(559475293), max(666563604) in 7217s
Relation stats: total(6549807), max(9266826) in 5539s
```

The other parts of osm2pgsql take approximately 22000 seconds, meaning luajit shaves about a quarter of the import time.

**Comment by lonvia** [comment]
Closing again. This feature is implemented. If you want to document it, just open a PR.
