### ISSUE TITLE
Table relation miss out

### ISSUE THREAD

**Issue by MinChanSike** [openstreetmap/osm2pgsql#802]
I got error `relation osm_new_landusages_gen00  does not exist` with PostgreSQL 10.1

**Comment by SomeoneElseOSM** [comment]
Can you explain in a bit more detail what you were doing when the error occurred?  I can't help with PostgreSQL 10.1, but someone else might be able to.

**Comment by pnorman** [comment]
This table is not coming from osm2pgsql. I don't know where it's from, it could be scripts that you're running on top of osm2pgsql, or a different loading tool like imposm, but it's not something we can help you with in this repository.
