### ISSUE TITLE
osmpgsql for windows 32 bit

### ISSUE THREAD

**Issue by souradh** [openstreetmap/osm2pgsql#803]
Hi,

I downloaded osm2pgsql using this link :
 "https://ci.appveyor.com/api/buildjobs/iisabxffssilv7gl/artifacts/osm2pgsql_Release.zip"

After that I unzipped and tried to execute osm2pgsql.exe.
Then i got a message  :
"This version of C:\osm2pgsql\osm2pgsql-bin\osm2pgsql.exe is not compatible with
the version of Windows you're running. Check your computer's system information
to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, a
nd then contact the software publisher."

Mine is windows 7 32 bit.

Where can I download Osm2pgsql for windows 32 bit??

**Comment by pnorman** [comment]
> Where can I download Osm2pgsql for windows 32 bit??

Appveyor just builds one version. You'll have to compile it yourself and you might need to build your own dependencies.

**Comment by lonvia** [comment]
Appveyor could build a 32 bit version but we don't have the libraries for it and it was quite a bit of work to create them. Before doing that I'd like to make sure that the 32bit on Linux is still running. We don't test that at all at the moment.

**Comment by lonvia** [comment]
With thanks to @alirdn, we now have a 32bit pre-built binary as well. You can download the latest build for the master branch at https://ci.appveyor.com/api/projects/openstreetmap/osm2pgsql/artifacts/osm2pgsql_Release_x86.zip?job=Environment%3A%20arch%3Dx86&branch=master (release builds will only appear starting from the next release).

I do have to add a word of warning though. 32bit versions are not really actively maintained anymore. They still build but beyond that, they are not particularly well tested.
