### ISSUE TITLE
--flat-nodes on 64-bit windows fails at the parse Way step

### ISSUE THREAD

**Issue by jkeane** [openstreetmap/osm2pgsql#807]
Related Link: [https://github.com/openstreetmap/osm2pgsql/issues/119](url)

This issue is still happening with v0.92.0. There is a correlation between the cache size setting and this failure. 4 core,16GB, Windows 2012 R2 box.
 If I try to import north-america w/
 -C 6000 --slim --flat-nodes T:\OSM\north-america-flat-nodes.bin, it fails when trying to parse ways

If I try to import texas w/
 -C 6000 --slim --flat-nodes T:\OSM\texas-flat-nodes.bin, it succeeds.

In both cases, the flat nodes file is created (and quite large) after the Node parse step.

**Comment by mmd-osm** [comment]
0.92.0 is nearly a year old and probably doesn’t include the changes mentioned in #119. Can you retry using the most recent version?

**Comment by jkeane** [comment]
I just pulled 0.95.0-dev from the CI drop.  Running now.  It takes about an hour to get through the node parse and to the failure point, so I'll post shortly.

**Comment by jkeane** [comment]
So far so good, Ways started parsing.  I'll update at next stage.

**Comment by jkeane** [comment]
That build seems to have fixed any reliability issues.  Thanks for the help.
