### ISSUE TITLE
 ERROR:  relation "planet_osm_point_tmp does not exist

### ISSUE THREAD

**Issue by 08-15at** [openstreetmap/osm2pgsql#822]
Everything seemed to run smoothly but thats what I got now.
To me it seems as if this error happened quite at the end of the import.
Is there any chance just rebuilding some missing indices, instead of doing the whole import again ?
Copying planet_osm_polygon to cluster by geometry finished
Creating geometry index on planet_osm_polygon
Copying planet_osm_line to cluster by geometry finished
Creating geometry index on planet_osm_line
Creating osm_id index on planet_osm_line
Creating osm_id index on planet_osm_polygon
Creating indexes on planet_osm_line finished
Creating indexes on planet_osm_polygon finished
All indexes on planet_osm_line created in 377244s
Completed planet_osm_line
All indexes on planet_osm_polygon created in 377308s
Completed planet_osm_polygon
Maximum node in persistent node cache: 5354029055
Maximum node in persistent node cache: 5354029055
Maximum node in persistent node cache: 5354029055
Maximum node in persistent node cache: 5354029055
node cache: stored: 1047394074(51.84%), storage efficiency: 66.59% (dense blocks: 114336, sparse nodes: 318115084), hit rate: 53.42%
Osm2pgsql failed due to ERROR: ALTER TABLE planet_osm_point_tmp RENAME TO planet_osm_point failed: ERROR:  relation "planet_osm_point_tmp" does not exist

thank you

**Comment by sav123** [comment]
at this stage, not all the data has been copied in the tables which are about to be created. It seems that it is not only a problem of index unless the data to upload in postgress unlikely exist in some tmp files. Are you on linux or windows ? what postgres version are you using ? what is the file to import ?

**Comment by 08-15at** [comment]
thx for your comment. Actually I see, there was no osm_point table created. So import definitely went wrong somewhere. Did it on debian 9 and postgres 9.6 with europe import. Didn't notice any fatal errors ..
Seems as I need to reimport....

**Comment by sav123** [comment]
I spent too much time with the setting of the planet import. So I took two 256 Gb+ssd servers and all went fine  :)

**Comment by lonvia** [comment]
There likely was an earlier error that got ignored (the postgres logs might have an error message). We'd need a reproducible case here to get to the bottom of the ALTER TABLE error. That means a description of the hardware, OS, postgres config, osm2pgsql command line used and the full log of osm2pgsql and postgres. I guess it is a bit late to ask for that now. So closing here. If you run into that problem again, open a new issue and attach the appropriate logs.
