### ISSUE TITLE
tuning the postgres part

### ISSUE THREAD

**Issue by sav123** [openstreetmap/osm2pgsql#823]
Hi all !
Does the last part of osm2pgsql depend from the ram setting ( -C and -slim ) ? Its timing is very stable ( +/- 20% without identified reasons ). At the same time, the memory is not released and if postgres is on the same server, it becomes very hard to use a high -C or to avoid slim. The question takes sense when one sees that the slim tables may be dropped before the final stage.

******* from here
All indexes on planet_osm_roads created in 36s
All indexes on planet_osm_point created in 170s
All indexes on planet_osm_line created in 675s
All indexes on planet_osm_polygon created in 3814s

**Comment by lonvia** [comment]
The last stage only reorders table in postges and create indexes. It is independent of the cache from -C.

What version of osm2pgsql are you using? The releasing of memory should have been fixed very recently in #813. You should now be able to have a high -C for the import stage and  configure also a very high `maintenance_work_mem` in postgres to speed up the indexing stage a bit.

**Comment by sav123** [comment]
I use the version 0.95.0-dev . Your answer is very much appreciated! I'll update my copy and focuse on this maintenance_work_mem. Until now, I was raising shared_buffers and max_wal_size without a great result.
