### ISSUE TITLE
objections to renumber the ids in the process osm2pgsql / mapnik / renderd

### ISSUE THREAD

**Issue by sav123** [openstreetmap/osm2pgsql#824]
Hello All,

what are the objections to renumber the nodes/ways/relations if the database is used only for renderd/mapnik and if it handles well the updates ? Does this forbid the usage of other utilities ?

**Comment by woodpeck** [comment]
If you only use the data for rendering, then nothing speaks against renumbering. I don't see anything that speaks *for* it either, though, and I would guess that the extra effort required to enable updates in this scenario (with tables matching old to new IDs) would vastly complicate things. Why would you want to renumber?

**Comment by sav123** [comment]
For performances and memory saving, say 10 to 15% after 8 whole-load checks. My 1st stage is dedicated to data filtering. Renumbering doesn't take a lot of time and contributes to reduce the final memory and disk data sizes.

**Comment by pnorman** [comment]
You can't reasonably update with renumbered files because you have to keep track of all your past renumbers to renumber the incoming diffs.

I have doubts that renumbering **in osm2pgsql** is a performance gain in most situations because you spend additional time renumbering the input. As part of an external process it might make sense, but that's outside osm2pgsql's scope.

**Comment by lonvia** [comment]
I agree with @pnorman. While renumbering might be useful, it should be done outside osm2pgsql as a preprocessing step.

**Comment by sav123** [comment]
The pre process builds the flat nodes files and a small patch tells to osm2pgsql to not delete the file and to not set the data but to use it as usual. After that the main process doesn't need more the not-dense nodes and this saves a lot of time. Renumbering makes the o5m and flat input files a little smaller and there are no holes in memory when tracking. The external flat nodes saves 10%, the renumbering 5 to 10%, it depends of the final strategy of aggregation. This covers the time of the prebuild. Take in account that the 1st stage allows to discard tags and relations with the rules of the main process and you grab another percents. As today, after other savings, on a 64 Gb old server ( 2 gHz x2, 16 threads, DDR3, Sata allmost full ) the pre-build and the patched mid process take 15300 s on average of 4 tries and they never consume more than 32 Gb. Another thousand seconds is possible to save. The bottleneck is postgress with 53000 s for xxxx_polygon. Recent documentation on optimization is missing for big tables while tries in real conditions take a lot of time.

**Comment by pnorman** [comment]
@sav123 I'm not sure what you're trying to say there, and what you want osm2pgsql to do. You mentioned a small patch, can you submit it as a pull request?

**Comment by sav123** [comment]
I'm just asking for the rules and pratics. I read in some page that renumbering wasn't a good idea but I didn't find it re read the post.
A possible answer was that similar solutions already exist.

**Comment by lonvia** [comment]
You can use [osmium-tool](http://osmcode.org/osmium-tool/) for renumbering OSM files before import. It can even track the renumbering for you, so that you can apply it to subsequent diffs and do updates.

**Comment by sav123** [comment]
@pnorman OK , I understand
@lonvia  : the perfect page, thank you
thank you both :)

**Comment by lonvia** [comment]
You're welcome. Closing here for being out of scope for osm2pgsql.
