### ISSUE TITLE
1 deg/100 km line limit - can this be done a switchable parameter?

### ISSUE THREAD

**Issue by DeyanVasilev** [openstreetmap/osm2pgsql#828]
Hello,

I am trying to introduce mountain-labeling in my map using very long lines with suitable attributes.
Unfortunately osm2pgsql appears to split those lines in segments of 100 km each.
As far as I noticed this behavior is hardcoded due to some (probably old) Mapnik issues.

My question is - can this behavior be made switchable in osm2pgsql (e.g. --do_not_split)?

**Comment by lonvia** [comment]
Already discussed in #277. There is no such switch yet but pull requests are welcome for an option that makes the amount of splitting configurable.

Duplicate of #277.
