### ISSUE TITLE
Fedora/Redhat rpm updates

### ISSUE THREAD

**Issue by paazmaya** [openstreetmap/osm2pgsql#833]
Hi, would you happen to be in contact with @fabaff about possibly updating the rpm packages made for redhat based linux distros, as seen here https://src.fedoraproject.org/rpms/osm2pgsql ?

Would there be an area where I could be of help?

**Comment by pnorman** [comment]
The packages are maintained by distros, not the osm2pgsql maintainers. You'll have to contact someone at Fedora with your questions.

**Comment by paazmaya** [comment]
Thank you

**Comment by paazmaya** [comment]
I see that the message was delivered, thanks @fabaff, https://src.fedoraproject.org/cgit/rpms/osm2pgsql.git/commit/?id=aabe90402c809b860b40c33b3f93ea11072e4f83
