### ISSUE TITLE
Define output type: line, point, polygon

### ISSUE THREAD

**Issue by mnameghi** [openstreetmap/osm2pgsql#840]
Hi
I just need to have line table from osm file. but osm2pgsql brings together all tables.
What can I do?

**Comment by pnorman** [comment]
If you want just one table, you can either use the multi backend with lua transforms, or the lua transforms with the pgsql backend, and write a transform that drops everything except non-polygon ways.

[openstreetmap-carto.lua](https://github.com/gravitystorm/openstreetmap-carto/blob/master/openstreetmap-carto.lua) and [openstreetmap-carto.style](https://github.com/gravitystorm/openstreetmap-carto/blob/master/openstreetmap-carto.style) would be a good place to start with the latter.
