### ISSUE TITLE
message not clear when the lua file is missing

### ISSUE THREAD

**Issue by ghost** [openstreetmap/osm2pgsql#841]
the message is 
Tag transform style does not contain a function filter_tags_node
instead of "missing lua %file"

**Comment by mmd-osm** [comment]
Looks like https://github.com/openstreetmap/osm2pgsql/blob/master/tagtransform-lua.cpp#L22 could be enhanced by something like: http://lua-users.org/lists/lua-l/2007-01/msg00566.html
