### ISSUE TITLE
-x option stopped importing all objects

### ISSUE THREAD

**Issue by tomass** [openstreetmap/osm2pgsql#849]
Previously _-x_ option (extra attributes) meant that all objects (nodes, polygons, lines), even the ones without any tag, are imported into the database. 0.94 version (?) changed this to only import objects witch do have tags.
**Expected:** number of rows in _planet_osm_nodes_ is more or less equal to _planet_osm_point_
**Actual:** import of Lithuanian pbf with 12M nodes produces ~100000 objects in point table.

Is this expected? I was using this to count number of objects last touched by specific users.
P.S. User data **is** in the pbf.

**Comment by lonvia** [comment]
That's a direct results of #815. I'm not quite sure if I should call it a bug or a feature.

**Comment by tomass** [comment]
@lonvia user count is just one of many things being counted/done (others being qa, rendering etc.).

**Comment by Komzpa** [comment]
We've updated to Ubuntu Bionic and this thing bit us too.

We need node id <> geometry mapping to support constructing custom speed profile for OSRM, https://github.com/Project-OSRM/osrm-backend/wiki/Traffic

```
osm2pgsql -h
osm2pgsql version 0.94.0 (64 bit id space)
```

**Comment by pnorman** [comment]
#815 was merged for 0.96.0, not 0.94.0, so this is unrelated to that change.

What tag transform are you using?

osm2pgsql has gone back and forth on filter for untagged objects. If we decide to not short-circuit the logic for untagged items with -x, we should still have the C transforms filter out untagged objects.

**Comment by lonvia** [comment]
The transforms still need to support filtering of untagged objects anyway because the short-circuit logic only works for imports, not for updates. I'll modify the code for the -x case.

**Comment by tomass** [comment]
Compiled osm2pgsql from source.
Executed with:
`./osm2pgsql -d gis -C 2048 -E 3857 --multi-geometry -x --slim -S ./osm2pgsql.style -x ../lithuania-latest.osm.pbf`
And pbf file with 13M nodes loaded 200K nodes into points table.

**Comment by tomass** [comment]
Sorry, looked in wrong table. Commenting out „with_extra“ does not help.
_planet_osm_points_ (and other tables) are still missing objects.

**Comment by lonvia** [comment]
That's a much older issue then.

**Comment by tomass** [comment]
Any suggestions where I can look at and try? I've kind of cornered myself by upgrading OS and now version 0.92 does not compile anymore.
BTW: by the errors of our local data QA I'm getting with this load (for example errors about missing street object for existing address) I suspect that not only objects with no tags are skipped.

**Comment by lonvia** [comment]
The behaviour got introduced with the libosmium rewrite. On some further consideration, I don't want to bring back the old one. It is not a good idea to force such an increase in database size on anybody who wants to add extra attributes to the database. If you want the old behaviour you can use the lua tagtransform to implement it.
