### ISSUE TITLE
trying to update database with --append fails when piping osmosis and osm2pgsql

### ISSUE THREAD

**Issue by bambam1** [openstreetmap/osm2pgsql#861]
Hi,
When I run 
```
osmosis --read-replication-interval workingDirectory=/home/renderuser/osmosis --simplify-change --write-xml-change changes.osc.gz
``` 
and than
```
osm2pgsql --append -d gis –-slim changes.osc.gz
```
everything works fine, but when I pipe 
```
osmosis --read-replication-interval workingDirectory=/home/renderuser/osmosis --simplify-change --write-xml-change - | osm2pgsql --append -d gis –-slim -
```
I got "Osm2pgsql failed due to ERROR: --append can only be used with slim mode!" same when I try `osmosis --read-replication-interval workingDirectory=/home/renderuser/osmosis --simplify-change --write-xml-change /home/renderuser/osmosis/changes.osc.gz && osm2pgsql --append -d gis –-slim /home/renderuser/osmosis/changes.osc.gz`

any ideas why it fails ? I did import with `osm2pgsql -d gis --create --slim  -G --hstore --tag-transform-script ~/src/openstreetmap-carto/openstreetmap-carto.lua -C 7000 --number-processes 6 -S ~/src/openstreetmap-carto/openstreetmap-carto.style ~/data/europe-latest.osm.pbf`
I am using Ubuntu server 18.04 and osm2pgsql 0.94.0

**Comment by pnorman** [comment]
While editing to have more useful linebreaks I noticed the character `–` in the third command you gave, which is different from `-`. The first is an em or en dash, the second is a hyphen. If you copied and pasted these commands, you've got the wrong character from somewhere.

**Comment by lonvia** [comment]
Piping data via stdin works fine for me. As there was no further comment from the original poster, I assume that the hyphen was indeed the problem. Please be aware that you must explicitly state the file format via the `-r` when reading data from stdin.
