### ISSUE TITLE
New dependency on osmium

### ISSUE THREAD

**Issue by FlorianMickler** [openstreetmap/osm2pgsql#864]
When trying to build the current git master according to the instructions in the readme.md it fails:

>  CMake
> 
>  Error at CMakeLists.txt:94 (find_package):
>  By not providing "FindOsmium.cmake" in CMAKE_MODULE_PATH this project has
>  asked CMake to find a package configuration file provided by "Osmium", but
>  CMake did not find one.
>
>  Could not find a package configuration file provided by "Osmium" (requested
>  version 2.14) with any of the following names:
>
>    OsmiumConfig.cmake
>    osmium-config.cmake
>
> Add the installation prefix of "Osmium" to CMAKE_PREFIX_PATH or set
> "Osmium_DIR" to a directory containing one of the above files.  If "Osmium"
>  provides a separate development package or SDK, be sure it has been
>  installed.
>
>
>-- Configuring incomplete, errors occurred!

Probably the instructions need to be updated or the dependency made optional?

Tag 0.96 works though.

**Comment by lonvia** [comment]
Works fine here. libosmium comes packaged with the osm2pgsql in `contrib/libosmium`, so should just be there. Two guesses why you see this error:
* You have updated from a very old version of osm2pgsql and not cleared out the build directory, thus using an outdated cmake cache.
* You have set EXTERNAL_LIBOSMIUM from previous trials with an external libosmium.

In both cases, remove the build directory and start the build from scratch (`mkdir build && cd build && cmake .. && make`).

**Comment by FlorianMickler** [comment]
I will try to reproduce the error on fresh clone. I am not shure, but maybe I had at first tried to build the cmake project inside the source tree (not in a separate build folder) and cleaned that only half...

**Comment by lonvia** [comment]
That's possible. Building inside the source tree is not really supported. Maybe we should entirely forbid it or at least warn.

**Comment by bjacog** [comment]
I got the same thing on an AWS EC2 Instance:

```
[ec2-user@ip-xxx-xxx-xxx-xxx osm2pgsql]$ mkdir build && cd build
[ec2-user@ip-xxx-xxx-xxx-xxx build]$ cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Building osm2pgsql 0.96.0
-- Looking for include file termios.h
-- Looking for include file termios.h - found
-- Looking for include file libgen.h
-- Looking for include file libgen.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protozero: /osm2postgis_cache/osm2pgsql/contrib/protozero/include (found suitable version "1.6.3", minimum required is "1.5.1") 
-- Found EXPAT: /usr/lib64/libexpat.so (found version "2.1.0") 
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib64/libbz2.so - found
CMake Warning at cmake/FindOsmium.cmake:209 (message):
  Osmium: PROJ.4 library is required but not found, please install it or
  configure the paths.
Call Stack (most recent call first):
  CMakeLists.txt:94 (find_package)


CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Osmium (missing: PROJ_INCLUDE_DIR PROJ_LIBRARY) (found
  suitable version "2.14.2", minimum required is "2.14")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOsmium.cmake:278 (find_package_handle_standard_args)
  CMakeLists.txt:94 (find_package)


-- Configuring incomplete, errors occurred!
See also "/osm2postgis_cache/osm2pgsql/build/CMakeFiles/CMakeOutput.log".
See also "/osm2postgis_cache/osm2pgsql/build/CMakeFiles/CMakeError.log".
```

**Comment by lonvia** [comment]
Note this line in the output:
```
  Osmium: PROJ.4 library is required but not found, please install it or
  configure the paths.
```

**Comment by eyal-gonen** [comment]
I am getting the same error as bjacog: 

CMake Warning at cmake/FindOsmium.cmake:209 (message):
  Osmium: PROJ.4 library is required but not found, please install it or
  configure the paths.
Call Stack (most recent call first):
  CMakeLists.txt:94 (find_package)

How can I fix it? I am not sure what it is searching for nor where it is searching for it.
Please help.

**Comment by lonvia** [comment]
I've played a bit with disabling in-source builds in cmake and all the ways I found are either undocumented or are bound to cause more confusion due to misleading error messages. So I think it's better to leave it as is.

Closing as configuration error (while ignoring the completely unrelated PROJ.4 comments).

**Comment by jav974** [comment]
You can install libproj-dev as dependency and it will get rid of this error.
