### ISSUE TITLE
Missing MultiPolygons

### ISSUE THREAD

**Issue by jocasta** [openstreetmap/osm2pgsql#866]
Hi All

I have posted this question on the OSM forum but the responses were "well it works for me" - so I was wondering if anyone here could shed some light.....

https://forum.openstreetmap.org/viewtopic.php?id=63521

I have loaded a full planet import into Postgres and I am coming across occurrences where some multipolygons are not getting imported into the **planet_osm_polygons** table. They do however exist in the **planet_osm_rels** table. I have loaded both with and without the multipolygon switch but still these features do not get imported

This is my import command: (version 0.96 - style sheet is default):

`osm2pgsql -v -l --unlogged --create --slim -C 50000 --number-processes 6 --multi-geometry --flat-nodes planet.nodes --extra-attributes -S /usr/local/share/osm2pgsql/default_timestamp_version.style --hstore -d osm_planet -U osm planet-latest.osm.pbf`

Below are a few examples of Mutipolygons that don't get added to the planet_osm_polygon table:

https://www.openstreetmap.org/relation/3923874
https://www.openstreetmap.org/relation/5325528
https://www.openstreetmap.org/relation/5325529

Am I missing something?

Thanks,

Mike

**Comment by woodpeck** [comment]
Is there *any* polygon with highway=pedestrian in your polygon table? If not then maybe your `/usr/local/share/osm2pgsql/default_timestamp_version.style` instructs osm2pgsql to omit them?

**Comment by lonvia** [comment]
The c-transform [drops relations](https://github.com/openstreetmap/osm2pgsql/blob/master/tagtransform-c.cpp#L378) when they don't have a polygon-like tag (which highway isn't) and don't have an area tag. I think that is wrong. `type=multipolygon` should have the same effect as adding an `area=yes` tag. @pnorman?

**Comment by pnorman** [comment]
👍

**Comment by ihor-nahuliak** [comment]
I think the issue happens because some boundary linestrings can not be merged as rings.
```sql
select string_agg(distinct name, ', ') as name, ST_IsClosed(ST_LineMerge(ST_Union(way))), ST_IsSimple(ST_LineMerge(ST_Union(way))) from planet_osm_line where admin_level='2' and boundary='administrative' and tags->'name:en' = 'Spain' group by osm_id;

  name  | st_isclosed | st_issimple 
--------+-------------+-------------
 España | f           | t
(1 row)
```
```sql
select ST_AsGeoJSON(ST_MakePolygon(ST_LineMerge(ST_Union(way)))) from planet_osm_line where admin_level='2' and boundary='administrative' and tags->'name:en' = 'Spain' group by osm_id;

ERROR:  Shell is not a line
```
Does anybody know how to close unclosed linestrings automatically?

**Comment by lonvia** [comment]
Turns out that this is not trivial to fix with old-style MPs as we run into odd corner cases. I'll fix that as part of #862 instead.

**Comment by ppKrauss** [comment]
Hi, it is the same bug?

https://help.openstreetmap.org/questions/66116/how-to-configure-osm2pgsql-get-all-relations

**Comment by lonvia** [comment]
No. The relation mentioned import without issues using latest osm2pgsql and the default style when downloading them directly from the OSM API.

**Comment by ppKrauss** [comment]
> No. The relation mentioned import without issues using latest osm2pgsql and the default style when downloading them directly from the OSM API.

Thanks. I fixed upgranding osm2pgsql (`apt install` on UBUNTU 16 is old) [from source](https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/)  and adding more ~50Gb at server.
