### ISSUE TITLE
'libpq-fe.h' file not found

### ISSUE THREAD

**Issue by Malauch** [openstreetmap/osm2pgsql#868]
I use PostgresApp to run PostgreSQL server on MacOS and recently I tried to install osm2pqsql tool. However when compiling using `make` I get an error:

```
'libpq-fe.h' file not found
```

Before that `cmake ...` didn't show any errors. When I check result of `pg_config` command it shows all paths correctly.

**Comment by lonvia** [comment]
This likely means that you have an incomplete installation of the postgres libraries on your system. Sometimes for there is an extra dev package for the headers which needs to be installed. What does `pg_config` report as `INCLUDEDIR` and does it make sense on your system?

**Comment by lonvia** [comment]
No further information provided. Closing.
