### ISSUE TITLE
 ERROR: Geometry SRID (3857) does not match column SRID (900913)

### ISSUE THREAD

**Issue by u02249** [openstreetmap/osm2pgsql#869]
Hello. I am trying update my database:

 osmosis --read-replication-interval workingDirectory="${WORKOSM_DIR}" --simplify-change --write-xml-change - \
 20     |osm2pgsql --number-processes 1 -m -r xml --append --slim --hstore --database gisdb_debug --host $PGHOST --user $PGUSER --port $PGPORT -v -

when I start update, I get this error:
Osm2pgsql failed due to ERROR: result COPY_END for planet_osm_point failed: ERROR:  Geometry SRID (3857) does not match column SRID (900913)
CONTEXT:  COPY planet_osm_point, line 1, column way: "0101000020110F0000356EFC48B8615841DC109F60C73C5841"

Please tell me the solution to the problem

**Comment by woodpeck** [comment]
Are you using a different version of `osm2pgsl` now than you used when you created the database?

**Comment by u02249** [comment]
How do I upgrade to the new version of osm2pgsql. Do I need to re-create the database for this?

**Comment by woodpeck** [comment]
Not necessarily, but osm2pgsql does *sometimes* change in ways that are incompatible with old setups. Hence why I was asking whether you had updated (and ideally, from what version to what version). 

It is likely cleanest to do a full reload. (If your data is older than a month or so, you won't be able to efficiently update it anyway.) However, you can change the projection of your existing database by executing these steps:

     ALTER TABLE planet_osm_polygon ALTER COLUMN way TYPE geometry(Geometry);
     ALTER TABLE planet_osm_roads ALTER COLUMN way TYPE geometry(LineString);
     ALTER TABLE planet_osm_line ALTER COLUMN way TYPE geometry(LineString);
     ALTER TABLE planet_osm_roads ALTER COLUMN way TYPE geometry(Point);

     UPDATE planet_osm_polygon SET way = ST_SETSRID(way, 3857);
     UPDATE planet_osm_roads SET way = ST_SETSRID(way, 3857);
     UPDATE planet_osm_line SET way = ST_SETSRID(way, 3857);
     UPDATE planet_osm_point SET way = ST_SETSRID(way, 3857);

     ALTER TABLE planet_osm_polygon ALTER COLUMN way TYPE geometry(Geometry, 3857);
     ALTER TABLE planet_osm_roads ALTER COLUMN way TYPE geometry(LineString, 3857);
     ALTER TABLE planet_osm_line ALTER COLUMN way TYPE geometry(LineString, 3857);
     ALTER TABLE planet_osm_roads ALTER COLUMN way TYPE geometry(Point, 3857);

The first block removes the 900913 type specification from the column, the second updates the geometries, the third adds a specification for 3857. Projections 900913 and 3857 are identical, they just have different names.

**Comment by u02249** [comment]
Thank you so much!
