### ISSUE TITLE
osm2pgsql failed due to error: open failed for .bz2.

### ISSUE THREAD

**Issue by F-Chaudhry** [openstreetmap/osm2pgsql#870]
Hi OSM Community,

It's my first experience with osm and postgresql. After solving a few errors now i am stuck again at the error during the .osm.bz2 file parsing. I have placed the .bz2 file in osm2pgsql folder but it is still giving error due to "No such file or directory". 
Although it shows "Reading in file: pakistan-latest.osm.bz2".
Please  see the image attached.

Where should I place the file so that it can be read successfully?

![capture](https://user-images.githubusercontent.com/43579735/46058237-84e80c80-c173-11e8-99c3-9c27fd532e59.PNG)

Regards,
Chaudhry

**Comment by StyXman** [comment]
I run `osm2pgsql` under `strace` and I noticed that it says it's reading the file before even opening it:

```
$ strace -ff osm2pgsql -v --number-processes 4 -c -O null --bbox 0,43,1,44 europe-latest.osm.pbf
[...]
write(2, "\nReading in file: europe-latest."..., 40) = 40
write(2, "Applying Bounding box: 0.000000,"..., 64) = 64
write(2, "Using PBF parser.\n", 18)     = 18
openat(AT_FDCWD, "europe-latest.osm.pbf", O_RDONLY) = 3
```

What this means is that the message is misleading. Even the parser seems to be selected based on the extension of the filename passed, not checking the contents of the file.

Now, the reason the command is failing for you I don't know. You should make sure the file is there. Could you pass the list of commands you executed just before `osm2pgsql`? I have the suspicion that you executed `su - postgres`, which could have changed the directory where you're at. You could try running `ls pakistan-latest.osm.bz2` before running `osm2pgsql` to make sure the file is there. You can also use `pwd` to see that the directory where you downloaded the file is the same as the directory you're running `osm2pgsql`.

**Comment by F-Chaudhry** [comment]
Thank you so much for the reply.

yes i did run the command `su - postgres`, as the tutorial i am following ran the commands:
`su - postgres` before 
`time osm2pgsql -v --number-processes=16 -d gis -s --bbox -97.5, 43.0, -89.0, 49.5 planet.osm.bz2`

i copied the `pakistan-latest.osm.bz2` from where it was downloaded `cd /home/map/` to the directory `cd /osm/osm2pgsql/`.
running `ls pakistan-latest.osm.bz2` gave 
`ls pakistan-latest.osm.bz2`

what am i doing wrong?

**Comment by F-Chaudhry** [comment]
it was the path issue.
`pakistan-latest.osm.bz2` was not where i was running it from. i copied the file and pasted in the `postgres` home. and executed the `time ....osm.bz2` command after `su - postgres`. it worked fine, started processing Now, Relation, way.

But only till it gave a new error:
`Connection to database failed:  FATAL: sorry, too many clients already`.

what went wrong now?

**Comment by SomeoneElseOSM** [comment]
I'd suggest adding a question at https://help.openstreetmap.org/questions/ , with the full details of the tutorial that you are following, what you typed, and what happened when you did.
