### ISSUE TITLE
Add unique constraint for geometry tables

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/osm2pgsql#873]
`osm_id` is not unique in the `planet_osm_polygon` table. If there are [no particular option](https://help.openstreetmap.org/questions/66170/how-to-identify-parts-of-the-same-osm_id-in-planet_osm_polygon/66171), that would do something as a `gid`... This issue is a suggestion to add a column `osm_id2` to be used as  `UNIQUE(osm_id,osm_id2)`.  

## Example
    
```sql
ALTER TABLE planet_osm_polygon ADD COLUMN osm_id2 int;
UPDATE planet_osm_polygon
SET  osm_id2 = sub_id
FROM (
  SELECT osm_id, way, row_number() OVER (PARTITION BY osm_id) as sub_id 
  FROM planet_osm_polygon
) t WHERE t.osm_id=planet_osm_polygon.osm_id AND t.way=planet_osm_polygon.way
; -- need time ...  
ALTER TABLE planet_osm_polygon ALTER COLUMN osm_id2 SET NOT NULL;
ALTER TABLE planet_osm_polygon ADD CONSTRAINT osm_uniqids UNIQUE(osm_id,osm_id2);
```

**Comment by Nakaner** [comment]
Many users don't need a unique ID column and would be bothered by it because it wastes a lot of space for a useless number.

`osm_id` is not unique if you import without `--multi-geometry` because osm2pgsql then splits up multipolygon (OGC term here) geometries into simple polygon geometries.

**Comment by ppKrauss** [comment]
Hi @Nakaner , thanks, make sense... I am studing in application context the use or not of `--multi-geometry`, no conclusion at this moment, so no really good reason for osm2pgsql  invest time here, perhaps we can close this issue.

My suggestion is perhaps about *documentation* and  a *library of SQL snippets* to help users (mainlly in [spatial analysis](https://github.com/openstreetmap/osm2pgsql/blob/master/docs/analysis.md)) to not reinvent the wheel in this kind of special conditions (without multi-geometry).  

* Some documentation for database schemas, where is better to work with it? [at wiki.openstreetmap.org](https://wiki.openstreetmap.org/wiki/Osm2pgsql/schema) or here?

* "[SQL snippets](https://wiki.postgresql.org/wiki/Category:Snippets)" for  osm2pgsql, where we can add it as complementar tools?

**Comment by lonvia** [comment]
I honestly don't see the point of such a unique id, it has no meaning at all and wouldn't even be preserved across updates. It certainly is out of scope for this repository.
