### ISSUE TITLE
From the docs:  Array elements can be a sign of database misdesign

### ISSUE THREAD

**Issue by FranklinClinton** [openstreetmap/osm2pgsql#879]
I have importet OSM data with the following command:
`osm2pgsql --create --slim -C 2000 --hstore --latlong germany-filtered.osm`
Imprt was successfull, however I noticed a strange database scheme:
`SELECT * FROM planet_osm_ways LIMIT 2;` 
`id | nodes | text` 
`92 | {442734,442735,308149691,442736,4665821726,442737,4665821727,442738,442739,2429178447,442740} | {name,Eigenheimstraße,highway,residential,maxspeed,30}` 

In the docs of postgresql it says the following:
> Tip: Arrays are not sets; searching for specific array elements can be a sign of database misdesign. Consider using a separate table with a row for each item that would be an array element. This will be easier to search, and is likely to scale better for a large number of elements.

So I was wondering if I did something wrong.

**Comment by woodpeck** [comment]
Whether you did something wrong depends on what you wanted to achieve. There are other tools, like osmosis, which will create a PostgreSQL representation of OSM data without resorting to arrays. That representation is then "well designed" according to PostgreSQL documentation, and well suited for certain kinds of relational queries, but unsuitable for rendering.

**Comment by FranklinClinton** [comment]
I don't want to render. I'd like to run reverse geocoding queries to convert cordinates into human readable address. Should I use Osmosis or Osm2pgsql for that purpose? Also, what table should I for ways(roads), when `planet_osm_ways` is just for internal implemantation? maybe planet_osm_roads?
