### ISSUE TITLE
planet_osm_line missing some ways

### ISSUE THREAD

**Issue by BlakeWills** [openstreetmap/osm2pgsql#880]
I've just imported the latest great-britain/england/derbyshire OSM file, there are ~60 more rows in the planet_osm_ways table than planet_osm_line. 

How can I track down why these ways are not being imported into the line table? Two examples ways are 614252777 and 493653220.

I'm using the following query to identify these rows:
`SELECT * FROM PLANET_OSM_WAYS WHERE ID NOT IN (SELECT OSM_ID FROM PLANET_OSM_LINE) `

I was under the impression that all ways should end up within planet_osm_line, is this not correct?

Thank You

**Comment by jburgess777** [comment]
Those two examples both have `area=yes` so probably ended up in the polygon table instead.
https://www.openstreetmap.org/way/493653220
https://www.openstreetmap.org/way/614252777

**Comment by BlakeWills** [comment]
I didn't realise that's what happens. 

I've re-visited the docs and can confirm what I'm seeing is expected behaviour. All the rows that I thought were missing are in fact closed ways, so are in the polygon table.
