### ISSUE TITLE
Why so slow, even after upgrading to full SSD system and doubling RAM to 32Gb?

### ISSUE THREAD

**Issue by mdadduzio** [openstreetmap/osm2pgsql#883]
Hi,
don't know if it's an issue but didn't know where to ask so please bear with me.
While attempting to import the full and latest planet OSM in PBF format, I have 

PostgreSQL 10.6 (Ubuntu 10.6-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0, 64-bit
osm2pgsql version 0.96.0 (64 bit id space)

initially installed on 

ASUS ROG Strix GL553VE: 8 Intel Core i7-7700HQ - 16Gb DDR4 - 128Gb SSD - 1Tb 7200 rpm HDD.

- 1st attempt (16Gb swap partition on HDD, not SSD, default postgres.conf, flat nodes file on its own 50Gb SSD partition via mount point named ~/flat-nodes/):  

```
osm2pgsql -d gis --create --slim  -G --hstore --tag-transform-script ~/src/openstreetmap-carto/openstreetmap-carto.lua -C 12000 --number-processes 8 --password --flat-nodes ~/flat-nodes/planet-flat-node.bin -S ~/src/openstreetmap-carto/openstreetmap-carto.style ~/Downloads/planet-latest.osm.pbf

Processing: Node(4791937k 1777.4k/s) Way(531767k 9.12k/s) Relation(6188690 14.05/s)  parse time: 501542s
Node stats: total(4791937347), max(5984342717) in 2696s
Way stats: total(531767289), max(634039446) in 58316s
Relation stats: total(6188697), max(8814497) in 440530s
```

Around 18 days later chrashed for HDD space exhaustion (used all 640Gb HDD partition) with:

```
All indexes on planet_osm_point created in 125685s
Completed planet_osm_point
Creating indexes on planet_osm_roads finished
All indexes on planet_osm_roads created in 126630s
Completed planet_osm_roads
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory. 
```

Furthermore DB was corrupted and I couldn't backup it (pg_dump failed) nor I could create indexes manually.

- 2nd attempt:

Same system but updated RAM to 32Gb, replaced 1Tb HDD with Samsumg 860 Evo 1Tb SSD so now everything is on SSD: Ubuntu has it's own partition, 32Gb swap partition enabled, 50Gb dedicated partition for flat-nodes, 916Gb partition where I moved the postgres data directory and latest-planet-osm.pbf (around 43Gb) leaving around 870Gb free space for the postgres DB.

Latest planet file downloaded again for the occasion :-)

Please notice again: whole system is SSD only this time and doubled RAM memory.
Furthermore tweaked postgres.conf as below (and restarted service):

```
shared_buffers = 16GB			
work_mem = 1GB				
maintenance_work_mem = 4GB		
dynamic_shared_memory_type = posix	
effective_io_concurrency = 500		
max_worker_processes = 8		
max_parallel_workers_per_gather = 2	
max_parallel_workers = 8		
checkpoint_timeout = 1h		
max_wal_size = 64GB
min_wal_size = 1GB
checkpoint_completion_target = 0.9	
random_page_cost = 1.1			
min_parallel_table_scan_size = 8MB
min_parallel_index_scan_size = 512kB
effective_cache_size = 22GB
```

Run:
	osm2pgsql -d gis --create --slim  -G --hstore --tag-transform-script ~/src/openstreetmap-carto/openstreetmap-carto.lua -C 24000 --number-processes 8 --password --flat-nodes ~/flat-nodes/planet-flat-node.bin -S ~/src/openstreetmap-carto/openstreetmap-carto.style ~/PDB/planet-latest.osm.pbf

and... I didn't even bother to wait another 5 to 6 days for getting to relations because I already can see:

Processing: Node(4882482k 1883.7k/s) Way(23795k 4.76k/s) Relation(0 0.0/s)

Upgrading the HW nothing relevant has changed...(please,see above).

Swap partition hasn't been used and it looks like only 1 core is working.

Compared to the benchmarks found online and that I could read, I wasn't expecting such a slow import (parsing stage) even with the first HW configuration, but after having upgraded it I think there should have been an improvement (and I hoped a big one too), so something should be wrong.

Are more than 3 weeks (and no improvement due to HW upgrade) a feasible import time for such an HW/SW configuration?

Please help me and/or advise me about it,

I attach a screenshot below,
thanks very much 

![screenshot_2018-12-01](https://user-images.githubusercontent.com/36211554/49323579-d028ed80-f51d-11e8-8f46-f1b64dbb2367.png)

**Comment by pnorman** [comment]
> Processing: Node(4882482k 1883.7k/s) Way(23795k 4.76k/s) Relation(0 0.0/s)
> 
> Upgrading the HW nothing relevant has changed...(please,see above).
> 
> Swap partition hasn't been used and it looks like only 1 core is working.

You terminated it during the processing step, which is all single threaded. This is expected. You don't want swap to be used, and it shouldn't be with your settings.

**Comment by mdadduzio** [comment]
Hi pnorman,

thanks for replying.

I was expecting an improvement at the parse step after the HW upgrade, considering that now everything is using only RAM and SSD.
Why the ways (and relations later I'd expect) are being processed at the same speed as when RAM was just the half and HDD 7200rpm was used instead of the new SSD?

It looks upgrading the HW made no difference.

I restarted it later adding --unlogged and --drop but no difference again (perhaps they'll make it in a later stage).
As of now it's still running and processing ways at 9.45k/s, as I remember it was around the middle of the ways processing in the previous attempt when RAM was the half (16Gb) and disk was not an SSD...
That makes me expect another 6 days for relations and then? At least another 12 or more days for indexes as it was before?

I've read benchmarks with HW comparable to mine, or even less powerful, processing ways in the order of tens or hundreds k/s and same for relations  (not K of course for the latter).
They complete the parse stage in less the 12 hours and the full import in less than 2 days.

That's why I was expecting an improvement, at least 5 or 6 times if not an order of magnitude or more, after the HW upgrade, but having nothing, literally nothing at all, looks wrong to me.

What can I do to detect the bottle neck (which is obviously not the RAM or the SDD)?

Thanks for help

P.S.: the fact that it's not using the swap partition is good, I know, but anyway, in case needed, being it on the SSD too, should be quite fast, even if not as fast as if osm2pgsql didn't require swapping.

**Comment by lonvia** [comment]
I can't believe your system doesn't use swap. Let's have a look at your RAM use in the second case. You have 32GB RAM total. 16GB are allocated to postgresql shared buffers. This memory is blocked by postgresql and cannot be used for anything else. That leaves 16GB for the OS and osm2pgsql. However, you have asked osm2pgsql to use 24GB for the node cache. So at least 8GB of this have to come out of swap memory. In addition to that the flat node file has to be loaded into memory for lookups. Given that we have already established that all memory is used, you likely end up with a disk access on almost every lookup.

For a system with 32GB RAM and SSDs, I generally recommend a postgres configuration as follows:
```
shared_buffers = 2GB
maintenance_work_mem = 10GB
```
and during the initial import:
```
fsync = off
synchronous_commit = off
full_page_writes = off
```
(reenable these immediately after the import has finished or you might find yourself importing again because of a database corruption)

With only 32GB RAM, the node cache won't fit into RAM anyway, so you might as well disable it almost completely and leave the space for buffering the flatnode file. Use a `-C 10` or similar.

Numbers from a run I did at the beginning of the year on a 32GB RAM machine with slow SSD:

```
Processing: Node(4245103k 1453.8k/s) Way(459833k 9.29k/s) Relation(5455360 253.74/s)  parse time: 73927s
Node stats: total(4245103652), max(5302726531) in 2920s
Way stats: total(459833994), max(548925998) in 49507s
Relation stats: total(5455389), max(7838217) in 21500s

Pending ways took 21422s at a rate of 14482.89/s

Osm2pgsql took 118211s overall
```

**Comment by mdadduzio** [comment]
Hi lonvia,

thanks for your reply.

We are both right :-)
I mean, at the time of writing no swap memory was used (yet).
When ways parsing has finished and relation parsing commenced swap has been used heavily, as much as 28.5 - 29 Gb.
As I thought, being the swap memory on the SSD too, swapping didn't slow the process down as much as if it was on a HDD.
In fact this time parsing hasn't lasted around 6 days but only around 12 hours (I'll write down the right numbers when I have them).
Overall I'm experiencing numbers a bit better than the ones you wrote down.

It looks the HW upgrade has paid in the end, but not in the first two stages of parsing which have rates almost equal to the not upgraded HW.

Relation parsing was greatly sped up and, till what I can see now also the parallel processing of the pending ways (not their initial parse step).

When I have the import completed I'll write here the final results.
Unfortunately I'm experiencing another problem as of now: Ubuntu 18.04 rebooted just after ending the pending ways.
I could not determine the cause of the reboot: it may be because of an unattended update or more probably because of overheating.
I disabled all kinds of updates I could, switched the network interface off and put a big big fan cooler on the side of the notebook :-)
I'm just crossing my fingers hoping this time it can make it.
I don't think it ran out of memory, disk wasn't full, swap was 32Gb + a 16Gb swapfile I added on the fly (but swap memory peaked at 28.7Gb, so it wasn't ever used).
Later, after the reboot, I deleted the swapfile and grew the swap partition to 48Gb, just to play on the safe side. 

Let's see how it goes.

I'll test the SSD speed when I finish, I thought Samsung 860 Evo was a good one.

I only have one question: why ways parsing (from PBF) hasn't been affected by the HW upgrade? 
About nodes it was obvious because the flat nodes file was already on SSD, but ways should already be using postgres, so why that step didn't get a speed up as it was for relations and pending ways too (tables and indexes I don't know yet)?

**Comment by mboeringa** [comment]
> I could not determine the cause of the reboot: it may be because of an unattended update **or more probably because of overheating.**
> I disabled all kinds of updates I could, switched the network interface off and put a big big fan cooler on the side of the notebook :-)

Clean your laptop's fans out. 

I recently experienced similar overheating issues with my 7700HQ laptop after about a years intense usage and dust build-up inside the fans. These HQ laptops, due to their higher TDP inside a still very much confined space, seem to operate at the limits of cooling capacity and thus very prone to overheating if the airflow is even mildly blocked.

Opening the case and cleaning the fans, and putting a vacuum cleaner at the fans outlets to remove the build-up dust there, made all the difference in my case.

If you do not trust yourself opening up a laptop's case (there are usually good videos on YouTube that can help you), then at the very least use your vacuum cleaner to dust out those outlets from the outside of the case. That likely already makes a big difference.

**Comment by mdadduzio** [comment]
Hi everybody and thanks for your time, help and hints.

@mboeringa: I did it, there wasn't much to clean though. I then tested the notebook for overheating with a package called 'stress' driving all 4 cores (2 threads each ->8 threads) to a steady 100% for 1 hour and monitoring the cores temperature with another package named 'sensors'. System was stable, temperature never exceeded 85 degrees for any core and without extra fan external fan cooling. I then ran memtest86+ for all night long and no errors.
Ruled out any hardware failure, I could just examine just a single syslog (other times it rebooted writing down nothing) where there was a clue: around at the time of pending ways stage finalization (after relations) in the last 3 seconds the log reported several services failing repeatedly and being rescheduled for restart, each of them failing hopelessly again, repeating all that around a dozen of times until a shutdown sequence was finally triggered reaching the shutdown target at the end and restarting the OS.
I thus hypothesized that to be caused by too heavy load and swapping and, probably, some watchdogs triggering to assume those services as dead and rescheduling a few times their restart and then finally giving up and rebooting.
I reduced memory demand both with postgres and  osm2pgsl and left a thread free (using only 7 again both with postgres and osm2pgsql) and it worked like charm.

@lonvia, pnorman: I succeded with the following being reported:

osm2pgsql -d gis --create --unlogged --slim -G --hstore --tag-transform-script ~/src/openstreetmap-carto/openstreetmap-carto.lua -C 14000 --number-processes 7 --password --flat-nodes ~/flat-nodes/planet-flat-node.bin -S ~/src/openstreetmap-carto/openstreetmap-carto.style ~/PDB/planet-latest.osm.pbf

Processing: Node(4882482k 1865.0k/s) Way(544614k 15.40k/s) Relation(6388510 312.12/s)  parse time: 58451s
Node stats: total(4882482555), max(6091279337) in 2618s
Way stats: total(544614313), max(648920626) in 35365s
Relation stats: total(6388866), max(9047961) in 20468s

Using 7 helper-processes
Finished processing 374602255 ways in 13960 s
374602255 Pending ways took 13960s at a rate of 26833.97/s

going over pending relations...
	0 relations are pending

Using 7 helper-processes
Finished processing 0 relations in 1 s

node cache: stored: 1688291378(34.58%), storage efficiency: 92.00% (dense blocks: 203166, sparse nodes: 85339902), hit rate: 33.89%

Osm2pgsql took 109344s overall

Not bad in my eye, but I'm just beginner.
So in the end upgrading HW paid back a lot.

@Ionvia: in your experience is that time to be considered as for a slow import? What a good performing import should be expected to last?

Before closing the issue (which is not an issue anymore) I'd like to ask everybody some advice, hint or help with the tile rendering:

I attempted to tile 0 to 5 world levels with mapnik (via the generate_tiles.py and generate_tiles_multiprocess.py pyton scripts).
I waited more than 5 minutes for just starting with the first tile, and after more than 15 minutes it didn't even complete level 2... 

Is such a slow performance related to an unfit hw (like mine could be:  4 cores (8 threads) RAM 32Gb, 1Tb SSD), or maybe it is misconfiguration related, i.e. postgres' one (which looked like to be the choking part: 8Gb shared mem, 10 Gb work mem)?
I thought that, once imported, tiling should be (blazingly) fast, so where do you think the problem might lie and what should a normal tiling performance be?

Thanks again to all of you.

**Comment by mboeringa** [comment]
> I thought that, once imported, tiling should be (blazingly) fast, so where do you think the problem might lie and what should a normal tiling performance be?

The first couple of zoom levels cover vast parts of the earth in a single tile, _and thus potentially vast amounts of data_, depending on your style. They are expected to generate tiles slowly, but also to have few tiles in total, so it doesn't matter it takes relatively long to render a single tile, as they are usually not updated as frequent as higher zoom levels.

**Comment by mboeringa** [comment]
> @mboeringa: I did it, there wasn't much to clean though.

In my case, dust at first also appeared mildly. However, when I looked at the actual metal grating / fins at the outlets using a torch, maybe 1/4 was clogged. Even that may not sound much, but since these thin metal fins at the outlets do the actual job of the cooling, as being attached to the copper heatpipes transporting the heat from the processor to the cooling fans, even such a relatively mild clogging was enough to cause overheating in my laptop (which has dual fan setup due to the graphics processor). As I already wrote, this is a clear sign these HQ laptops are operating at the very limits of cooling capacity when fully throttled.

**Comment by mdadduzio** [comment]
@mboeringa : About lowest tiling levels: I see, and what you say makes senses.
I'll experiment with higher levels and see. Thanks for the insight.

About cleaning: I'll follow your advice and re-do it more carefully paying attention to smaller and thinner dust sediments which, I admit, I didn't care much when I cleaned it last time since I was used to more noticeable amounts of dirt and dust you usually find inside notebooks.
I agree with you: my impression is that, although well cooled, those gaming notebooks are at their very limits when full throttling (especially about heating) and that a tiny glitch may be well enough to make them fail.
Thanks again for help.

@anybody: What are usually good times/performance for planet-size osm2pgsql imports, but even more importantly for renderd/mapnik real time on demand tiling?
Any advices/hints about HW/SW configurations?

Would my notebook (with its HW configuration detailed in my first thread message) be enough for one or maximum two local LAN OSM tiles consumer clients at high level tiles ***acceptable real-time*** requests (having previously tiles & cached the first 11 (0-10) level tiles for example)?
For acceptable real-time I mean less than a second per tile o even better.

**Comment by lonvia** [comment]
The numbers I gave above are fairly typical for an import on a system with 32GB RAM. More RAM will make it faster.

Closing the discussion here as tile rendering is off-topic for this repo. I would suggest to move the discussion to the [OSM dev mailing list](https://lists.openstreetmap.org/listinfo/dev).

**Comment by mdadduzio** [comment]
Thanks for help, bye!
