### ISSUE TITLE
Cannot allocate memory for helper processes

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#90]
On a stock EC2 m2.2xlarge instance running ubuntu 12.04 LTS with the command

``` sh
~/osm2pgsql/osm2pgsql --create --slim --drop 
-C 20000 --number-processes 4 \
--flat-nodes ~/osm/flat.nodes \
-S ~/osm2pgsql/default.style --hstore --multi-geometry \
~/osm/planet-latest.osm.pbf
```

I get the following error:

```
Going over pending ways...
Maximum node in persistent node cache: 2297430015
        110203098 ways are pending

Using 4 helper-processes
WARNING: Failed to fork helper process 1: Cannot allocate memory. Trying to recover.
WARNING: Failed to fork helper process 2: Cannot allocate memory. Trying to recover.
WARNING: Failed to fork helper process 3: Cannot allocate memory. Trying to recover.
Mid: loading persistent node cache from /mnt/flat/flat.nodes
Maximum node in persistent node cache: 2297430015
Helper process 0 out of 1 initialised
```

m2.2xlarge has 34.20GB of memory

**Comment by roboguy** [comment]
Even I'm facing the same issue with large planet imports. I've set vm.overcommit_memory=1 and re-run the import process. Will report back with further information.

The command I used: 
```
nohup osm2pgsql -v -s -C 35000 --number-processes=8 -S -d gis -U osmrdsUser  -W planet-latest.osm.pbf
```
Running on an i2.2xlarge (Ubuntu 12.04) with 60GB of RAM.

**Comment by pnorman** [comment]
@roboguy Why 35000 MB cache? I'm trying to see what advise is leading people to use such a large value. You don't need that much.

**Comment by StyXman** [comment]
@pnorman: maybe this page: http://www.volkerschatz.com/net/osm/osm2pgsql-usage.html , in the help about the --cache option it says:

> If you don't have enough RAM, it is likely beneficial to give osm2pgsql close to the full available amount of RAM.

This could be misinterpreted as:

> give osm2pgsql close to the full available amount of RAM.

**Comment by lonvia** [comment]
I don't think this is valid anymore. If you encounter the issue with the latest version, please open a new bug.
