### ISSUE TITLE
Re-do Lua API

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#901]
Now that we have experience with the Lua API, the multi-backend, and have new feature requests which require API changes, we should redo the API.

To allow a transform to be compatible with current API we can use different function names, and then a transform can implement both entry points reasonably easily.

The current API is

```lua
function filter_tags_node(tags, num_tags)
return filter, tags

function filter_tags_way(tags, num_tags)
return filter, tags, polygon, roads

function filter_basic_tags_rel(tags, num_tags)
return filter, tags

function filter_tags_relation_member(tags, member_tags,
    roles, num_members)
return filter, tags, member_superseded, boundary,
    polygon, roads
```

Experience has shown num_tags is not needed because we're not in C. `next(tags) == nil` does the same check, is more idiomatic Lua, and is faster.

With old-style MP support gone, we don't need the superseded tests.

New features desired are
- Knowing if a way is closed or not to determine area formation (blocks recreation of C transform in multi backend)
- Allowing columns on objects from ways to be set based on relations they are a member of #230 

What other changes do we want to make?

cc @kevinkreiser @systemed

**Comment by kevinkreiser** [comment]
Propogating tags to relations (the second bullet point) was the main feature I was hoping for! If anything else springs to mind I'll post back.

**Comment by pnorman** [comment]
We should let the lua transforms set the distance for line splitting on a per-object area, as well as set if MULTIPOLYGONs are broken up

**Comment by systemed** [comment]
In an ideal world I'd like filter_tags_way to have some very limited access to the way geometry (even if just the first node), for national rendering variations. Currently I cope with this by pre-/post-processing. This may or not be at all possible!

**Comment by pnorman** [comment]
If it is possible - and I'm not sure on that - bounding box is probably the sensible arg to pass

**Comment by lonvia** [comment]
It's possible, we have the information but it would make the processing more expensive. Currently we only retrieve geometries for ways that have not been filtered. If filtering needs the geometries then we need to retrieve it for all ways. So my favourite solution would be a callback function for Lua that can retrieve the geometry when needed. (e.g. in the particular case only for ways that are rendered in a country-specific style.).

**Comment by systemed** [comment]
+1 - that's something I do in both tilemaker and my OSRM fork and it works very effectively.

**Comment by mmd-osm** [comment]
This might be a new use case for the Lua API: https://twitter.com/realgiggls/status/1138066068117884929

**Comment by lonvia** [comment]
Implemented in new 'flex' output.
