### ISSUE TITLE
Drop support for postgresql < 9.4?

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#908]
Travis finally has a xenial image to offer and given that trusty is EOL soon, we should move our CI setup. The xenial images only have postgres >= 9.4. This opens the question about what happens to support of older postgresql versions. If they are not tested on travis, they won't get tested anywhere. So should we

* drop support for Postgresql < 9.4 (as always: CentOS is the main issue here)
* official keep supporting Postgesql 9.2 and 9.3 but simply don't test it anymore
* try to get a Postgresql 9.2 setup working with Travis' xenial

I'm not really eager to try the latter, so keeping the tests is only an option if somebody else looks after moving to xenial.

Any opinions?

**Comment by pnorman** [comment]
I'd drop 9.2 and 9.3 because they are EOL.

**Comment by lonvia** [comment]
Move to xenial was done in #1047. It turns out that Postgresql 9.3 is still available, so I've kept that for now. Considering this ticket closed.
