### ISSUE TITLE
z_order values differing between default lua file and C code?

### ISSUE THREAD

**Issue by Phyks** [openstreetmap/osm2pgsql#913]
Hi,

When looking on the web at details on the way `z_order` values are computed in osm2pgsql, one often find references to the [default lua script](https://github.com/openstreetmap/osm2pgsql/blob/master/style.lua#L106-L118) (see for instance [this StackExchange answer](https://gis.stackexchange.com/a/296785)).

However, out of the box, osm2pgsql is doing tag transform with [this C code](https://github.com/openstreetmap/osm2pgsql/blob/ed0bf5b515936ec09c7b39d01223db319239aadb/tagtransform-c.cpp#L17-L32), and not this lua file.

I would have expected the LUA code to have the same results as the C code. Is there any reason for these to be out of sync?

Thanks!
Best,

**Comment by lonvia** [comment]
The Lua style, serves just as an example. It is currently written in a way that it provides output that is very similar to the C transform but we don't give guarantees that it is exactly the same outcome. 

I'm not sure why the  `z_order` differs, maybe @pnorman remembers but I'm not sure it is a good idea to adapt either of them now as likely a lot of installations depend on the default styles, both for C and Lua transforms.
