### ISSUE TITLE
Shouldn't be an empty style file allowed when using the parameter --hstore-all?

### ISSUE THREAD

**Issue by thbeutin** [openstreetmap/osm2pgsql#915]
I tried to import some OSM data into my database, because i want to do some analysis of keys used in OSM for a region.

To keep the task simple i want to have all keys (and values) at one single place, so there's no need to create any key column at all. But osm2pgsql (version 0.96.0 (64 bit id space)) refuses to accept an empty style file:
Osm2pgsql failed due to ERROR: Unable to parse any valid columns from the style file. Aborting.

Am i thinking wrong here?

**Comment by pnorman** [comment]
> Am i thinking wrong here?

Yes.

With no style file, osm2pgsql will have no idea of what is a polygon or not. For space reasons, you will also want to have some tags deleted. That's why there's [empty.style](https://github.com/openstreetmap/osm2pgsql/blob/master/empty.style) which is a starting point for a style where hstore is the primary storage of tags.

**Comment by thbeutin** [comment]
> > Am i thinking wrong here?
> 
> Yes.
> 
> With no style file, osm2pgsql will have no idea of what is a polygon or not. For space reasons, you will also want to have some tags deleted. That's why there's [empty.style](https://github.com/openstreetmap/osm2pgsql/blob/master/empty.style) which is a starting point for a style where hstore is the primary storage of tags.

Hm, what about: a way is either closed (so it is a polygon), or not (so it is a line)?
And space is not an issue - otherwise the analysis would be wrong right from start ;)

Thanks for pointing me to the style file, i'm playing with it now (it seems to have an inconsistency with the special "osm_" tags, but this will go into another issue if it "stays alive" until tomorrow).

**Comment by Redoute** [comment]
If I remember correct, I got the same error when I tried empty.style, but to set z_order and way_area as "delete". Because for me these columns are superfluous.
