### ISSUE TITLE
Error on applying OSM minutely diff in changeset sequence 3371578

### ISSUE THREAD

**Issue by thbeutin** [openstreetmap/osm2pgsql#921]
osm2pgsql version 0.96.0 (64 bit id space)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Node-cache: cache=163840MB, maxblocks=2621440*65536, allocation method=10
Mid: loading persistent node cache from ./flat_nodes
Mid: pgsql, cache=163840
Using built-in tag processing pipeline
Using projection SRS 4326 (Latlong)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads

Reading in file: /mnt/osm_data/changesets/003/371/578.osc.gz
Using XML parser.
DB writer thread failed due to ERROR: result COPY_END for planet_osm_ways failed: ERROR:  duplicate key value violates unique constraint "planet_osm_ways_pkey"
DETAIL:  Key (id)=(326726632) already exists.
CONTEXT:  COPY planet_osm_ways, line 18

The changeset file[1] contains version 4 and 5 of the way (id)=(326726632), so i wonder if this is a changeset or an osm2pgsql issue.

[1]: https://planet.openstreetmap.org/replication/minute/003/371/578.osc.gz

**Comment by thbeutin** [comment]
btw: i can provide a small file set (about 12Mb) to reproduce the issue on request

**Comment by mmd-osm** [comment]
> The changeset file1 contains version 4 and 5 of the way (id)=(326726632)

This is perfectly valid for both changeset and .osc file.

**Comment by pnorman** [comment]
Are you using a development version of osm2pgsql? What is your command line?

**Comment by thbeutin** [comment]
> Are you using a development version of osm2pgsql? What is your command line?

osm2pgsql is a gentoo live ebuild, i.e. the source comes from github when it's installed. I did this some days ago.

The command line is (in a shell script):


osm2pgsql --verbose --append --slim \
  --cache 163840 \
  --style minimal.style \
  --database highway \
  --hstore \
  --multi-geometry \
  --latlong \
  --extra-attributes \
  --number-processes 32 \
  --cache-strategy dense \
  "$changeSetFile"

**Comment by pnorman** [comment]
Do you still get the error with `--number-processes 1`?

**Comment by lonvia** [comment]
osm2pgsql cannot handle diffs with multiple versions. You need to sort and simplify your diff before feeding it to osm2pgsql. Use `osmosis --simplify-change` or more modern `osmium merge -s`.

**Comment by thbeutin** [comment]
> Do you still get the error with `--number-processes 1`?

yes.


> > osm2pgsql is a gentoo live ebuild, i.e. the source comes from github when it's installed. I did this some days ago.
> 
> Does it come from the master branch?

I think so, it says:

 * Fetching https://github.com/openstreetmap/osm2pgsql.git ...
git fetch https://github.com/openstreetmap/osm2pgsql.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/sci-geosciences/osm2pgsql/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/openstreetmap/osm2pgsql.git to /var/tmp/portage/sci-geosciences/osm2pgsql-99999999/work/osm2pgsql-99999999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/openstreetmap/osm2pgsql.git
   at the commit:            00d8220c4bed1d28ca4a80ec6e7a851f5062f929

[...]

**Comment by thbeutin** [comment]
> osm2pgsql cannot handle diffs with multiple versions. You need to sort and simplify your diff before feeding it to osm2pgsql. Use `osmosis --simplify-change` or more modern `osmium merge -s`.

Well, i guessed something like this - and i was afraid of it ;)

Is there any lightweight tool to handle this? I.e. osmconvert or another tool installable in the way of:
`wget -O - https://example.com/my_source.c | cc -x c - -lz -O3 -o small_tool`

Both osmosis and osmium have a huge dependency list i want to avoid - if possible.

**Comment by lonvia** [comment]
If you have osm2pgsql installed, then you should have most dependencies of osmium-tool installed already (they are both libosmium-based). In any case, you want to use the appropriate tools that manage the change download for you instead of a raw wget to `.osc.gz` files. pyosmium has `pyosmium-get-changes` or you can use osmosis. Both will ensure that updates are continued properly and produce diffs suitable for osm2pgsql.

**Comment by mmd-osm** [comment]
> osm2pgsql cannot handle diffs with multiple versions.

This may be a bit unexpected. Could this be included in the documentation? https://github.com/openstreetmap/chef/blob/master/cookbooks/tile/templates/default/replicate.erb might a good starting point to give people some idea how a working set up could look like.

**Comment by thbeutin** [comment]
> If you have osm2pgsql installed, then you should have most dependencies of osmium-tool installed already (they are both libosmium-based). In any case, you want to use the appropriate tools that manage the change download for you instead of a raw wget to `.osc.gz` files. pyosmium has `pyosmium-get-changes` or you can use osmosis. Both will ensure that updates are continued properly and produce diffs suitable for osm2pgsql.

well, for now i'm successfully using `osmconvert --out-osc --merge-versions  <XYZ.osc.gz>` (and (lib)osmium and it's dependencies is set on my personal ToDo list). All the other suggestions doesn't suit my needs i.e. for stopping at some desired point in time before "now".
Thanks a lot!
