### ISSUE TITLE
Support PROJ >= 6.0.0

### ISSUE THREAD

**Issue by tburschka** [openstreetmap/osm2pgsql#922]
Currently the build failed if proj >= 6.0.0 is used. The Flag ACCEPT_USE_OF_DEPRECATED_PROJ_API_H has to be defined. 

see: https://github.com/postgis/postgis/pull/354/files#r242068366

**Comment by jmckenna** [comment]
I agree that this flag is required now (as PROJ 6 was released on 2019-03-01).

Note that PROJ 7 release next year will drop proj_api.h completely.

**Comment by pnorman** [comment]
Do we use proj directly or only via libosmium?

**Comment by jmckenna** [comment]
Ah, it seems through libosmium only.

**Comment by jmckenna** [comment]
libosmium's associated ticket: https://github.com/osmcode/libosmium/issues/277

**Comment by jmckenna** [comment]
You can close this ticket, but I bet this will be an FAQ.

**Comment by jmckenna** [comment]
related PROG 7.0 discussion happening at osmcode/libosmium#295

**Comment by lonvia** [comment]
Reopening this. We are going to need osmium-independent proj >= 6 support.

**Comment by kennykb** [comment]
Thanks for reopening. I was going to grumble that I produce some paper maps projected to UTM zone 18 and therefore maintain a small subset of OSM in PostGIS in that projection, so losing support for everything but plate carree and spherical Mercator would be a problem.

**Comment by lonvia** [comment]
#1066 reorders the code so that it becomes fairly easy to implement a generic projection using the proj6 variant and then have cmake detect which one to use. Just add a `reprojection-generic-proj6.cpp` similar to the existing `reprojection-generic-proj4.cpp` implementation.

PRs would be most welcome.

**Comment by jmckenna** [comment]
support for PROJ >6.1 added by @joto in https://github.com/openstreetmap/osm2pgsql/pull/1331   

I think this ticket can be closed.
