### ISSUE TITLE
Timestamp of last change of object in database

### ISSUE THREAD

**Issue by tomass** [openstreetmap/osm2pgsql#923]
It would be useful to have a possibility to have a database column with the timestamp of last update (database update, not OSM update) of the row (change of attributes and/or geometry).

Something similar to what we would get with PostgreSQL trigger on insert/update of points/lines/polygons tables setting the value of such new column to current timestamp.

**Reasons:**
- In case where additional pre-processing of data is required before rendering maps, this would allow reducing the number of objects to be pre-processed.
- Extra attributes like _osm_timestamp_ had something similar but after GDPR public extracts of OSM data no longer have _timestamp_ data.

**Comment by mmd-osm** [comment]
> after GDPR public extracts of OSM data no longer have timestamp data.

LWG position doesn’t impose restrictions on timestamps afaik -> this assumption seems to be incorrect.

**Comment by tomass** [comment]
@mmd-osm you're right, timestamp is indeed provided in extracts.
This should cover 99% of use cases.

**Comment by mmd-osm** [comment]
Relevant LWG decision is documented here: https://wiki.osmfoundation.org/wiki/Licensing_Working_Group/Minutes/2018-10-11

> Decision: The LWG resolves to recommend to the board to retain timestamps as is in the OSM data and not to remove them from public access for data privacy reasons.
