### ISSUE TITLE
osm2pgsql hungs forever while applying version-merged minutely changeset 003/425/025

### ISSUE THREAD

**Issue by thbeutin** [openstreetmap/osm2pgsql#925]
I downloaded the minutely changeset 003/425/025.osc.gz and merged eventually existing multiple versions (see [issue #921](https://github.com/openstreetmap/osm2pgsql/issues/921)) by using `osmconvert`:
`osmconvert --out-o5c --merge-versions /mnt/scratch/obm/changesets/003/409/417.osc.gz` into an `o5c` file.
When i try to apply this to my database, the `osm2pgsql (version 0.96.0 (64 bit id space))` command hangs forever by fully using one core:
```
osm2pgsql --verbose --append --slim --cache 16384 \
--style ../import/osm2pgsql/minimal.style --database gis \
--hstore --multi-geometry --latlong --extra-attributes \
--flat-nodes /mnt/osm_data/flat_nodes/flat_nodes \
--number-processes 4 --cache-strategy dense \
/mnt/scratch/obm/changesets/003/425/025.clean.o5c
```
The last output line is:
`Processing: Node(1k 1.8k/s) Way(0k 0.94k/s) Relation(10 10.00/s)`

This happens on two different machines.

I neither tried another format of the merged changeset nor another tool for creating the merged changeset yet.
I'm happy to provide more info if you let me know what you need and how can i do this ;)

**Comment by lonvia** [comment]
See https://lists.openstreetmap.org/pipermail/dev/2019-March/030545.html

**Comment by lonvia** [comment]
Reported to libosmium in https://github.com/osmcode/libosmium/issues/278. Please follow there for updates on the issue.

The offending relation was deleted in a bit less than three hours after creation. Therefore the recommended workaround is to consume a combined diff of at least 3 hours to circumvent importing the relation. For most setups that simply means killing the stalled osm2pgsql process and restarting with a larger diff. When using osmosis for downloading diffs, make sure maxInterval is 10800 or larger. When using pyosmium-get-changes use `-s` with at least 200.

**Comment by thbeutin** [comment]
Thanks for all the help, but in general i need to deal with minutely diffs for statistics and time series.For now i'll probably combine some (i.e. >=3) hours of changesets and replay the gap after the bug is fixed on a spare system.

**Comment by lonvia** [comment]
You can also edit the diff and remove the type=boundary tag from the relation in the changefile. Then everything will pass, you just don't have the relation in the DB polygon table.

**Comment by thbeutin** [comment]
> You can also edit the diff and remove the type=boundary tag from the relation in the changefile. Then everything will pass, you just don't have the relation in the DB polygon table.

That really helped me - thanks a lot! :)
