### ISSUE TITLE
Broken Sudan relation causes missing Egypt and Eritrea boundary relations

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#926]
Hi,

I am not sure if I need to report this here, or if this is a an issue with the used Geofabrik extract, but I noticed in a recently (7th April) downloaded Geofabrik Africa extract, that after import with osm2pgsql Egypt, Sudan and Eritrea were missing as multipolygons for the boundary relations. All other African countries were there.

Now, after checking the relations in JOSM with the validator, I discovered the Sudan relation was broken and missing two "outer" roles. I have now fixed that and uploaded the new relation to OSM.

However, while I can thus understand the Sudan multipolygon was not properly imported and missing, both the Egypt and Eritrea boundary relations were fine according to JOSM validator. So why were those missing as well? Is this a potential issue in osm2pgsql, or an issue with the Africa extract?

My setup:
osm2pgsql: 0.96
PostgreSQL 11.2/PostGIS 2.5.2
Ubuntu 18.04.2 LTS

![afbeelding](https://user-images.githubusercontent.com/7635726/55863383-b27a2d80-5b7a-11e9-901e-dcef63997a36.png)

**Comment by pnorman** [comment]
If there is an osm2pgsql we need a test case that reproduces it in order to identity any problems.

**Comment by ImreSamu** [comment]
> both the Egypt and Eritrea boundary relations were fine according to JOSM validator. 
>So why were those missing as well? Is this a potential issue in osm2pgsql, or an issue with the Africa extract?

my suggestion:   check the "Africa extract" first,

For example Eritrea  - Geofabrik extract Poly - smaller than the   admin_level=2   border
![image](https://user-images.githubusercontent.com/2217320/55902217-5390d480-5bcb-11e9-93ea-aeb03a272f44.png)

And the same - in the Africa Geofabrik extract Poly.
![image](https://user-images.githubusercontent.com/2217320/55902556-137e2180-5bcc-11e9-8e3c-35e6b9f265f7.png)

imho:  for the borders ( admin_level=2 )  - the planet file is the best.

**Comment by mboeringa** [comment]
@ImreSamu 

Thanks, that likely answers it.

I had been thinking of such a problem, but at first dismissed it as, knowing Geofabrik extracts are so widely used, someone else was likely to have spotted it. But maybe, or more likely probably, this is some relatively recent change of the admin_level 2 border now incorporating these island, although I would have to check that to be sure.

In addition, noticing the Sudan relation missing those outer roles in the JOSM validator, a country that just by accident happened to border the other two countries missing, made me think there might be a relation to the problem (falsely).

I guess it is time to ask Geofabrik to update the extraction polygon for Africa to include the full admin_level=2 border lines of Africa as they are now. I will probably drop them an e-mail soon.

I agree using planet is safest for extracting (all) admin_level=2 borders.
