### ISSUE TITLE
Saving Disk Space

### ISSUE THREAD

**Issue by laptopdude90** [openstreetmap/osm2pgsql#928]
I am importing the planet on a server with 440GB of SSD space. I have found this to be a little tight, and have moved or deleted everything I can from the SSD. (The swap file is running on a 128GB USB stick). I am importing with --slim, --flat, and --drop.

At what point can I delete the original .pbf file? Right now I am at "Sorting data and creating indexes for planet_osm_roads"

**Comment by lonvia** [comment]
You can delete the pbf file safely when it is indexing. However, I suspect we don't close the file until osm2pgsql finishes. So deleting it would actually be pointless. Something to look into.

**Comment by lonvia** [comment]
We actually do close the file after the first parsing phase.
