### ISSUE TITLE
How to load OSM file from local machine to the server using osm2pgsql?

### ISSUE THREAD

**Issue by Gautamshahi** [openstreetmap/osm2pgsql#929]
I wanted to upload the OSM file from my local machine to server using osm2pgsql, but the data is not imported.

I have just created the database s1(no table), do I need to create the table also, if yes how?

My osm2pgsql query

    osm2pgsql -c -d osm -U s1 --password xx -k -H yy  /home/g/Downloads/niedersachsen-latest.osm.pbf pbf -r -S /home/g/default.style -s

I am getting an error 

    Osm2pgsql failed due to ERROR: Unknown file format '-S'.

**Comment by woodpeck** [comment]
This issue tracker is not a support forum. Please go to help.openstreetmap.org or an appropriate mailing list (e.g. lists.openstreetmap.org/listinfo/tile-serving). You have your parameters in the wrong order. Drop "pbf -r" from your command line and it should work.
