### ISSUE TITLE
Appveyor windows binary link not valid?

### ISSUE THREAD

**Issue by apiszcz** [openstreetmap/osm2pgsql#937]
I am receiving this message from the appveyor windows link in the GITHUB readme.

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:12539d2b-f01e-0117-02e5-323cd2000000 Time:2019-07-05T03:53:25.0334356Z
</Message>
</Error>
```

**Comment by apiszcz** [comment]
Latest 0.96 at
https://ci.appveyor.com/api/buildjobs/tpph6jyr00ewkyjo/artifacts/osm2pgsql_Release_x64.zip

A better link for the documentation might be
https://ci.appveyor.com/project/openstreetmap/osm2pgsql

Select environment, then select artificats

**Comment by lonvia** [comment]
Appveyor's new retention policy made the links invalid. Release builds live now at https://lonvia.dev.openstreetmap.org/osm2pgsql-winbuild/releases/ Documentation has been amended.
