### ISSUE TITLE
Remove '--unlogged' option

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#940]
The `--unlogged` option currently only has an effect on middle tables. Data tables are always unlogged first and full tables after copying. That's likely not what people expect when they use it. We could change the behaviour to also make the final data tables unlogged. However, given that the option is pretty dangerous (and we have too many command line options anyway), I'd rather see it removed completely. Instead we should just set middle tables automatically to unlogged when `--drop` is enabled.

**Comment by pnorman** [comment]
> That's likely not what people expect when they use it. We could change the behaviour to also make the final data tables unlogged. However, given that the option is pretty dangerous (and we have too many command line options anyway), I'd rather see it removed completely.

👍
