### ISSUE TITLE
Some towns from Belgium are not imported

### ISSUE THREAD

**Issue by LEDfan** [openstreetmap/osm2pgsql#941]
Hi

First of all, thanks for maintaining this library. It's very useful for my project.
I mostly use it to get the geometry in postgis format for importing in my own postgis database.

However, when importing Belgium (http://download.geofabrik.de/europe/belgium.html) two towns are not imported into the polygon table, these are:

  - `Eupen` (2400207) https://www.openstreetmap.org/relation/2400181
  - `Raeren` (2400181)  https://www.openstreetmap.org/relation/2400207
 
As you can see on the osm.org links, these have a complex border with Germany.
I'm running osm2pgsql with: `-S /workdir/empty.style -lc --hstore --keep-coastlines --slim` arguments, but with the Nominatim settings: `-S /workdir/import-full.style -lsc -O gazetteer --hstore --slim` it also does not seem to work correctly.

Both relations end up in the `rels` table.
~~Is there anyway to debug why these are not imported? I don't seem to find any specific logging. 
My guess is that the geometry of these two relations are invalid. Is there anyway I can report these? Is there maybe a way to let osm2pgsql handle the invalid geometries?~~ See below.

I exported the 2400207 town to a pbf file using `./osmium getid -r belgium-190801.osm.pbf  r2400207 -o output.osm.pbf`. I attached this file here, it may be useful for debugging.

[eupen.osm.zip](https://github.com/openstreetmap/osm2pgsql/files/3475889/eupen.osm.zip)

Let me know if you need more information and thanks in advance!

EDIT: I just found out that, the way with id `181966881` is missing from the Geofabrik Belgium export. I contacted them for this issue.
However, I'm still interested in whether osm2pgsql can either report these invalid geometries or somehow handles these.

**Comment by lonvia** [comment]
That's a know issue with Geofabrik extracts. osm2pgsql cannot help you with detecting these.

You can use the check-refs function of osmium-tool to list relations with missing members but I suspect it won't help much in the end because an extract is expected to have lots of incomplete relations along the boundaries. So there will be a lot of false positives.
