### ISSUE TITLE
Antimeridian and Far Eastern Federal District

### ISSUE THREAD

**Issue by lanmaster** [openstreetmap/osm2pgsql#945]
Hello. I was import Russia PBF to database and cannot find "Far Eastern Federal District" relation.
[https://www.openstreetmap.org/relation/1221185](https://www.openstreetmap.org/relation/1221185)
Maybe an error occured when osm2pgsql trying to construct relation splitted on antimeridian?
Antimeridian is there:
[https://www.openstreetmap.org/#map=16/68.9593/179.9990](https://www.openstreetmap.org/#map=16/68.9593/179.9990)

**Comment by lanmaster** [comment]
PBF was downloaded from there:
[https://download.geofabrik.de/russia-latest.osm.pbf](https://download.geofabrik.de/russia-latest.osm.pbf)

**Comment by lanmaster** [comment]
Windows build used from there:
[https://ci.appveyor.com/api/buildjobs/dap98adflddy0w85/artifacts/osm2pgsql_Release_x64.zip](https://ci.appveyor.com/api/buildjobs/dap98adflddy0w85/artifacts/osm2pgsql_Release_x64.zip)

**Comment by joto** [comment]
That relation contains "subarea" members which are not supported by libosmium and, therefore, osm2pgsql. Also there are 36 ways missing in the input file that would be needed to completely build the relation.

**Comment by lonvia** [comment]
That's a known issue with Geofabrik extracts. Nothing osm2pgsql can do about it.
