### ISSUE TITLE
Progress info

### ISSUE THREAD

**Issue by pedjas** [openstreetmap/osm2pgsql#947]
If would be good to add any kind of progress info while processing data. 

As it is now osm2pgsql shows number of nodes, ways and relations processed but not a clue how much is left to process.

**Comment by woodpeck** [comment]
What you are really interested in is how much time is still needed, and the n/w/r count is only small part of that - with index creating and table sorting being long-running bulk items at the end and their duration notoriously difficult to predict. -- "imposm", a competing database importer, has a progress indicator like you suggest, and AFAIK uses heuristics a.k.a. raw guessing to determine the expected number of n/w/r from the file size.

**Comment by hholzgra** [comment]
To know how many nodes/ways/relations are in the import file in total, it would have to read it in completely just to count these, and then a 2nd time to actually process it. There is no header in OSM XML or .pbf files that would tell up front "This file contains x nodes, y ways, z relations"

@woodpeck would it be possible to have these numbers shown along with the extract .pbf files on the GeoFabrik download side? When doing the actual extract, that number should be known at the end of each extract procedure?  If that info was visible along with the download links, one would at least have a rough idea of progress while watching the raw osm2pgsql numbers ...

**Comment by lonvia** [comment]
Libosmium has some support to show a progress bar, although I think we'd have to completely replace the current progress to use it. I do agree with @woodpeck though that it might do more harm than good because once you reach 100% you still have to wait twice the time spent so far until the indexes are done.

**Comment by pedjas** [comment]
I am aware it is hard to get exact progress, but it would help to get any proximate estimation than just waiting it to finish with no clue when it will end.

**Comment by lonvia** [comment]
That's not possible, I'm afraid. There is no way to predict how long indexing will take. It depends on too many external factors that are impossible to determine from within osm2pgsql (disk speed and RAM size, postgresql settings, ...). I wouldn't even dare extrapolating from work already done.

**Comment by mmd-osm** [comment]
> To know how many nodes/ways/relations are in the import file in total, it would have to read it in completely just to count these, and then a 2nd time to actually process it. There is no header in OSM XML or .pbf files that would tell up front "This file contains x nodes, y ways, z relations"

`osmium fileinfo -e planet-latest.osm.pbf` can provide you with this kind of information, though it takes a few minutes to run on a recent planet pbf.

```
osmium fileinfo -e planet-latest.osm.pbf 
File:
  Name: planet-latest.osm.pbf
  Format: PBF
  Compression: none
  Size: 49682450814
Header:
  Bounding boxes:
    (-180,-90,180,90)
  With history: no
  Options:
    generator=planet-dump-ng 1.1.6
    osmosis_replication_timestamp=2019-08-05T02:00:01Z
    pbf_dense_nodes=true
    pbf_optional_feature_0=Has_Metadata
    pbf_optional_feature_1=Sort.Type_then_ID
    timestamp=2019-08-05T02:00:01Z
[======================================================================] 100% 
Data:
  Bounding box: (-180,-90,180,90)
  Timestamps:
    First: 2005-05-01T14:56:35Z
    Last: 2019-08-05T02:00:00Z
  Objects ordered (by type and id): yes
  Multiple versions of same object: no
  CRC32: e8fd7469
  Number of changesets: 0
  Number of nodes: 5369694269
  Number of ways: 595461781
  Number of relations: 6965603
  Largest changeset ID: 0
  Largest node ID: 6682397058
  Largest way ID: 710772838
  Largest relation ID: 9884757
```

**Comment by lonvia** [comment]
@mmd-osm, as per my comments, the import part is not the issue.

Closing as won't fix.
