### ISSUE TITLE
Osm2pgsql failed Cannot detect file format. Try using -r

### ISSUE THREAD

**Issue by tyomik-mnemonic** [openstreetmap/osm2pgsql#953]
Hi, devs! I have used Osm2pgsql 1.0 for simple action with next parametres: `sudo osm2pgsql --slim -c --cache 29000 --proj 3857 russia-latest.osm.pbf  -H  xxxx.local -d osm -U osm_user -W -P 5432 
`
This was thrown by terminal in th end: `Osm2pgsql failed due to ERROR: Cannot detect file format. Try using -r.
`
Log in console betwen starting osm2pgsql and error displaing:

`Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=29000MB, maxblocks=464000*65536, allocation method=11
Mid: pgsql, cache=29000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using built-in tag processing pipeline
Using projection SRS 3857 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads

Reading in file: russia-latest.osm.pbf
Using PBF parser.
Processing: Node(347886k 399.9k/s) Way(31888k 51.02k/s) Relation(871680 759.97/s)  parse time: 2643s

Reading in file: password=xxxxxxxx
node cache: stored: 347886451(100.00%), storage efficiency: 51.32% (dense blocks: 7163, sparse nodes: 309598190), hit rate: 100.00%`

I was confused, cause there are  node(22Gi),ways and polygon (both 7+Gi) have been created in postgres database...

**Comment by mmd-osm** [comment]
Your command line has a syntax error, you need to place the name of your pbf file ` russia-latest.osm.pbf` at the end, not somewhere in the middle.

Please refer to the documentation for details:  https://github.com/openstreetmap/osm2pgsql#usage

**Comment by lonvia** [comment]
I'm not sure there is anything we can do to improve the error output, except maybe rejecting files that start with a dash.
