### ISSUE TITLE
Large values cause import failure when using int4 columns

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/osm2pgsql#955]
With the following style file:

```
# OsmType  Tag          DataType     Flags
node,way   population      int4      linear
```
and the following osm file:

```
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6">
 <node id="1" visible="true" version="1" changeset="1" timestamp="2018-10-31T10:20:19Z" user="a" uid="1" lat="51.4779481" lon="-0.0014863">
   <tag k="population" v="4000000000" />
 </node>
</osm>
```
and the following command line
```
osm2pgsql -d osm2pgsql-test --style int4.style int4.xml
```
I get a failure of:
```
...snip...
Relation stats: total(0), max(0) in 0s
DB writer thread failed due to ERROR: result COPY_END for planet_osm_point failed: 
ERROR:  value "4000000000" is out of range for type integer
CONTEXT:  COPY planet_osm_point, line 1, column population: "4000000000"
```

I think it would be reasonable for osm2pgsql to just drop numbers that are outside of the valid int4 range, since it already drops anything that it can't interpret as a number from these columns.

**Comment by gravitystorm** [comment]
I thought I'd give this a go, "how hard can it be", and so on. Turns out, not so easy, at least not easy for me.

My first attempt was to change the parsing pattern (and variables) to be `int32_t`, to match the size of integers that postgresql expects. In table.cpp:

```diff
     case COLUMN_TYPE_INT: {
         // For integers we take the first number, or the average if it's a-b
-        long from, to;
-        int items = sscanf(value.c_str(), "%ld-%ld", &from, &to);
+        int32_t from, to;
+        int items = sscanf(value.c_str(), "%d-%d", &from, &to);
         if (items == 1) {
             m_copy.add_column(from);
```
Unfortunately this shows a big problem, which is the behaviour of `sscanf` when parsing out-of-range numbers. In this case, a tag value of `"10000000000"` (ten billion) gets outputted into the database as `1410065408`! The c++ standard says, of sscanf,

> If this object does not have an appropriate type, _or if the result of the conversion cannot be represented in the object_, the behavior is undefined.

This is totally unhelpful! My compiler (g++) appears to output the value modulo UINT32_MAX. Which is totally useless, since we can't detect whether the output is valid or has been wrapped (in this case, wrapped around multiple times).

My second approach is to keep the parsing into long, and just restrict the output range:

```diff
         // For integers we take the first number, or the average if it's a-b
         long from, to;
         int items = sscanf(value.c_str(), "%ld-%ld", &from, &to);
-        if (items == 1) {
+        if (items == 1 && from <= std::numeric_limits<int32_t>::max() && from >= std::numeric_limits<int32_t>::min()) {
             m_copy.add_column(from);
```

This works surprisingly well. The out-of-range behaviour for `"%ld"` patterns is completely different from `"%d"` patterns! For a tag value like `"10000000000000000000"`, it outputs `9223372036854775807` i.e. it clamps to INT64_MAX, rather than doing any kind of modulo. That's much more useful.

However, it's still relying on undefined behaviour of sscanf, which makes me uncomfortable. A bit of reading around the internet suggests that there's no practical way of using sscanf without exposure to undefined behaviour while reading larger-than-expected numbers. 

https://stackoverflow.com/questions/28007600/detecting-integral-overflow-with-scanf

One suggestion is to limit the number of digits read, so for our example, we could limit the parsing to 18 digits. That's not a problem, since we're dropping anything larger than int32 anyway.

```diff
         // For integers we take the first number, or the average if it's a-b
-        long from, to;
-        int items = sscanf(value.c_str(), "%ld-%ld", &from, &to);
-        if (items == 1) {
+        int64_t from, to;
+        int items = sscanf(value.c_str(), "%18ld-%18ld", &from, &to);
+        if (items == 1 && from <= std::numeric_limits<int32_t>::max() && from >= std::numeric_limits<int32_t>::min()) {
             m_copy.add_column(from);
```
This has the same output as to my second option, but I think by limiting the pattern to `%18ld` we are avoiding the undefined behaviour. I also think we should change from `long` to `int64_t` to ensure this works and doesn't break somewhere where long is only 32 bits.

But maybe this is all barking up the wrong tree, and we should move to some kind of `strtol` based approach as mentioned in the above stackoverflow post. That would be beyond my capabilities!

If the `long` -> `int64_t` and `%ld` -> `%18ld` stuff is OK, then I can work up a pull request.

**Comment by lonvia** [comment]
I would indeed prefer a solution based on `strtol` in the long rung but we should then have a discussion about that odd mean computation first. Your sscanf version looks okay to me and fixes the issue at hand. So I'm happy to go with your PR. Further technical comments are over there.
