### ISSUE TITLE
Settings for importing the whole planet in 2019

### ISSUE THREAD

**Issue by georgbachmann** [openstreetmap/osm2pgsql#962]
I am currently having huge problems importing the whole planet. We are currently already waiting more than 1.5 days and it's still not done.
 And our machine is quite fast. We have 250GB RAM and 32 Cores. And all is running on SSDs...

I've read that the `--slim` should be used for the whole planet. Without this param we went out of memory quite fast.

So this is how our import statement looks currently:
```
osm2pgsql -S my.style -c -H xxx-d x -U xxx --slim --drop --cache 100000 --number-processes 8 planet.osm.pbf
```

The problem is that currently there seems to be a lot of postgres threads going on. `CREATE TABLE`, `COMMIT`, `PREPARE insert_node/way/rel`... those kind of queries.

But those are stuck waiting for IO.
We did define that osm2psql can use about 100GB of ram, but it's currently "only" using about 50GB?!?

Here's an extract of our postgres-config:
```
shared_buffers = 4GB
work_mem = 2MB 
maintenance_work_mem = 2GB
dynamic_shared_memory_type = posix
effective_io_concurrency = 200
max_worker_processes = 30
max_parallel_workers_per_gather = 15
wal_buffers = 16MB
min_wal_size = 4GB
max_wal_size = 8GB
checkpoint_completion_target = 0.9
effective_cache_size = 12GB
default_statistics_target = 500
```

Is there an obvious mistake we are making? We are happy about every hint.

**Comment by rustprooflabs** [comment]
Try using `--flat-nodes`, preferably on an SSD.  The nodes file will take up around 52 GB on disk but avoids the thrashing in postgres.

**Comment by georgbachmann** [comment]
Thank you @rustprooflabs for your fast help! Really appreciated!
Would you still keep the `--slim` as well? Are there any other params/options you would you tweak? And does the postgres-config looks ok to you? Or is there anything super-strange there?

**Comment by rustprooflabs** [comment]
--slim is required for flat-nodes per [the Wiki](https://wiki.openstreetmap.org/wiki/Osm2pgsql).

I see you've changed `checkpoint_completion_target` up (good), I would also increase `checkpoint_timeout` from default of 5min to a much higher value.  For long running loads I set to `1d`, the max it will allow.

Are you using osm2pgsql v1.0 or an older version?  If it's an older version I'd throw in `--unlogged` too, but that parameter is gone in 1.0.  If you're using 1.0 `--drop` alone enables the same behavior.

**Comment by lonvia** [comment]
Careful with drop and unlogged options. `--drop` means that your database cannot be updated afterwards (which may or may not be what you want). `--unlogged` makes the tables needed for updates unlogged and should practically only ever be used together with `--drop`.

**Comment by georgbachmann** [comment]
As we do quite a bit of post-processing the update is not that important to us. We'd like to get the import speed down do something useful and then we'd rebuild it if we need to. But thank you for this hint!

**Comment by rustprooflabs** [comment]
On the Postgres side I also change these to reduce wal activity, saving I/O.

```
wal_level=minimal
max_wal_senders=0
```

Thanks for the reminder the a caveat for drop/unlogged!

**Comment by mmd-osm** [comment]
Your report doesn’t mention which Osm2pgsql version you’re using, including which settings you used to compile it.
