### ISSUE TITLE
Cleanup Operation

### ISSUE THREAD

**Issue by joto** [openstreetmap/osm2pgsql#986]
osm2pgsql could do with a cleanup:

* Move source code into `src` subdirectory
* Format everything with `clang-format`

Doing this in one go would minimize impact for later `git blame` etc. but give us a source code that is much easier to handle. With the source code bundled in `src` scripts for clang-tidy, coverage, etc. become simpler, or just a manual `grep` over the source code.

I'd be willing to do these steps and fix CMake config etc. to work with the new directory.

@lonvia @pnorman What do you think?

**Comment by lonvia** [comment]
Fine with me as long as we keep the flat structure for source files within `src`. The number of source files is small enough that a simple `ls` is still easy enough to read.

Additional suggestion: get rid of the only underscore in `taginfo_impl.hpp`.

**Comment by joto** [comment]
There is also `tests/test-output-pgsql-z_order.cpp`.

**Comment by lonvia** [comment]
Let's keep this confined to the source code.

**Comment by pnorman** [comment]
👍 to clang-formatting everything. I'm not concerned either way with the file moves

**Comment by lonvia** [comment]
Fixed in #997.
