### ISSUE TITLE
'-' potentially parsed wrongly as an int type

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#988]
This was reported via the dev mailinglist:

> I've found out my OSM Tile Server has stopped updating and osm2pgsql (v1.2)                       
> gives off the following error:                                                                    
>                                                                                                   
> DB writer thread failed due to ERROR: result COPY_END for planet_osm_line                         
> failed: ERROR:  invalid input syntax for integer: "-"                                             
> CONTEXT:  COPY planet_osm_line, line 1437, column layer: "-"                                      
>                                                                                                   
> Looking through its changefile, the following entry can be found:                                 
> 
> ```                                                                                               
>     <way id="742619958" version="1" timestamp="2019-11-06T15:32:03Z"                              
> uid="978786" user="padvinder" changeset="76711047">                                               
>       <nd ref="6952022619"/>                                                                      
>       <nd ref="6952022612"/>                                                                      
>       <tag k="layer" v="-"/>                                                                      
>       <tag k="tunnel" v="culvert"/>                                                               
>       <tag k="waterway" v="drain"/>                                                               
>     </way>
> ```                                                                                     
>                                                                                                   
> This seems to be malformed, as the layer should've never been "-", as this is                     
> not a valid integer.                                                                              
> You can see this for yourself at:                                                                 
> https://planet.openstreetmap.org/replication/minute/003/747/729.osc.gz                            
> Also more information on the layer key is over here:                                              
> https://wiki.openstreetmap.org/wiki/Key:layer

Needs confirmation via an additional test in `tests/test-output-pgsql-int4.cpp` and potential fixing.

**Comment by Nakaner** [comment]
I tried to reproduce the error with Osm2pgsql 1.2 and found no combination of an integer column defined in the style file and the usage of either C or Lua tag transforms. Note that I did not try the gazetteer output. See also my [posting](https://lists.openstreetmap.org/pipermail/dev/2019-November/030776.html) on the mailing list.

**Comment by lonvia** [comment]
Indeed, the chances are high that this was a problem with their customized Lua script. It's still an interesting case worth adding to our test suite.

**Comment by mmd-osm** [comment]
Shouldn't table_t::escape_type take care of this, and insert a NULL value instead when parsing for an COLUMN_TYPE_INT fails?

**Comment by lonvia** [comment]
May I add an observation that is not only true for this ticket but for issue commenting in github general: this ticket was opened as a reminder that we need a test for a given corner case to either confirm a problem or close the issue. Plain and simple.

Helpful things to contribute: a PR with the test case.

Not so helpful: comments with idle speculation, which uses up the maintainer's time as they need to read, process and answer the comment.

**Comment by mmd-osm** [comment]
It's not really idle speculation, I tried the same as @Nakaner did and also couldn't reproduce it.

**Comment by lonvia** [comment]
The C tagtransform is fine then. For the Lua tagtransform, the script writer is responsible to format the numbers correctly. Sanity checking them would be too expensive.
