### ISSUE TITLE
looong wait after "Completed planet_osm_polygon"

### ISSUE THREAD

**Issue by Redoute** [openstreetmap/osm2pgsql#993]
Hi all,

When using osm2pgsql, in my case after about 10 hours I see the message "Completed osm_polygon" and the database seems complete and usable.

But it takes another 24 hours until osm2pgsql finishes. I observed this twice now. Is this a problem with osm2pgsql or PostgreSQL or am I missing something?

I am using PostgreSQL 11.5 on Ubuntu and osm2pgsql 1.2.0 on Windows with the command line
`C:\Daten2\osm2pgsql-bin\osm2pgsql.exe --host ubuntu.forplan.local --username postgres --password --slim --cache 30000 --proj 32632 --hstore --hstore-add-index --keep-coastlines --multi-geometry --prefix osm --style C:\Daten2\osm2pgsql-bin\fds.style C:\Daten2\osm-2019-11-06.pbf`

The pbf is 6.5 GB and was merged from several files from geofabrik.de, Germany and surroundings.

In PGAdmin I see an active session executing
`CREATE INDEX osm_ways_nodes ON osm_ways USING gin (nodes) WITH (FASTUPDATE=OFF) ;`
Seems this step is no more necessary when all lines are already constructed?

Last lines of output are:
```
Completed osm_polygon
Stopped table: osm_ways in 107130s

Osm2pgsql took 129500s overall
node cache: stored: 894447560(100.00%), storage efficiency: 50.00% (dense blocks: 0, sparse nodes: 894447560), hit rate: 100.00%
```

**Comment by openstreetmap-tiles** [comment]
On Thu, Nov 21, 2019 at 3:30 AM Redoute <notifications@github.com> wrote:

> When using osm2pgsql, in my case after about 10 hours I see the message
> "Completed osm_polygon" and the database seems complete and usable.
>
> But it takes another 24 hours until osm2pgsql finishes. I observed this
> twice now. Is this a problem with osm2pgsql or PostgreSQL or am I missing
> something?
>

That's entirely normal. When osm2pgsql has read and parsed the input file
and laid the data into the tables, it's done roughly a third of the work.
Most of the rest of the work is in constructing the database indices that
enable it to do fast lookup by geographic location - essential, since a
tile server needs to extract quickly the features needed to render a tile.
Building the indices, of course, entails reading the data (this time from
the database) all over again and writing the index information. Moreover,
some of the indices use 'clustering', where the indexed objects are located
physically near the index data, so that a single disc read can scoop up
both, so some of the data have to be moved around.

When people hear this, they ask, "then why not construct the index along
with the data?" That's what osm2pgsql did originally. It was modified to
work the current way because the "construct the index first" approach is
even slower - and uses more space on the file system.

**Comment by Redoute** [comment]
Thanks, but all indexing on the four resulting tables seem to finish in the first 10 hours. Why waste 24 hours more on an index on a "slim" table, after all the real work is done? And why does this one take that long? This is the corresponding output:

```
Sorting data and creating indexes for osm_roads
Sorting data and creating indexes for osm_point
Sorting data and creating indexes for osm_line
Sorting data and creating indexes for osm_polygon
Copying osm_roads to cluster by geometry finished
Creating geometry index on osm_roads
Creating osm_id index on osm_roads
Creating hstore indexes on osm_roads
Creating indexes on osm_roads finished
All indexes on osm_roads created in 1045s
Completed osm_roads
Stopping table: osm_nodes
Stopped table: osm_nodes in 0s
Stopping table: osm_ways
Building index on table: osm_ways
Copying osm_point to cluster by geometry finished
Creating geometry index on osm_point
Creating osm_id index on osm_point
Creating hstore indexes on osm_point
Creating indexes on osm_point finished
All indexes on osm_point created in 3927s
Completed osm_point
Stopping table: osm_rels
Building index on table: osm_rels
Stopped table: osm_rels in 132s
Copying osm_line to cluster by geometry finished
Creating geometry index on osm_line
Creating osm_id index on osm_line
Creating hstore indexes on osm_line
Creating indexes on osm_line finished
All indexes on osm_line created in 8935s
Completed osm_line
Copying osm_polygon to cluster by geometry finished
Creating geometry index on osm_polygon
Creating osm_id index on osm_polygon
Creating hstore indexes on osm_polygon
Creating indexes on osm_polygon finished
All indexes on osm_polygon created in 13885s
Completed osm_polygon
```

... and 24 hours later

```
Stopped table: osm_ways in 107130s

Osm2pgsql took 129500s overall
node cache: stored: 894447560(100.00%), storage efficiency: 50.00% (dense blocks: 0, sparse nodes: 894447560), hit rate: 100.00%
```

**Comment by rustprooflabs** [comment]
My guess is your disk is the bottleneck.  Are you monitoring your CPU and disk for what's going on?  Using SSDs?  Other activity on the DB server?  Is the postgres server hitting SWAP a lot?  I can infer you have 30GB RAM to throw at it, but that's about all.  

As mentioned already, clustering of indexes shuffles data on disk around.  The use of `--hstore-add-index` might compound that effect, those indexes will need to be updated as the underlying data is reordered unless I'm misunderstanding the order of operation.  Depending on the volume of tags in the data, those hstore indexes are more expensive compared to typical index overhead.

If your postgres server is not using replication you should set `wal_level=minimal` to reduce WAL activity and free up IO.  That config value defaults to `replica` in Pg10 and newer, in 9.6 and prior it defaulted to `minimal`.

The default `checkpoint_timeout=5min` and `checkpoint_completion_target=0.5` can probably benefit from adjusting too, those defaults are pretty bad.  By using `checkpoint_completion_target=0.9` and `checkpoint_timeout=30min` you can smooth out the related IO over a longer period of time reducing spikes.
When I run osm2pgsql I set `checkpoint_timeout=1d` (the max), [read the docs and understand the risks](https://www.postgresql.org/docs/11/runtime-config-wal.html) before doing that.  I never intend to run those 

This all assumes you are stuck waiting for I/O...

**Comment by lonvia** [comment]
The indexes are required for updating the database. If you don't need updates, import with `--drop` and those indexes won't be created in the first place.

This really is a discussion for the [mailinglist](https://lists.openstreetmap.org/listinfo/dev), not so much an issue for a bug tracker.
