### ISSUE TITLE
relation type=land_area

### ISSUE THREAD

**Issue by Redoute** [openstreetmap/osm2pgsql#994]
Hi again,

for example, [relation 62781 "Federal Republic of Germany (land mass)"](https://www.openstreetmap.org/relation/62781).

As far as I see osm2pgsql has no way to get the geometry for polygon relations other than type=boundary and type=multipolygon? If so, may I ask for supporting this?

See also [my question on stackexchange](https://gis.stackexchange.com/questions/342104/how-to-get-land-area-polygons-with-osm2pgsql).

Thanks a lot!

**Comment by joto** [comment]
Areas are only built for `type=boundary` and `type=multipolygon`, those everywhere accepted in OSM as special cases. Everything else that can be considered a boundary or a polygon should be tagged as such, ie get one of those tags. `type=land_area` is simply the wrong tagging.

**Comment by Redoute** [comment]
At least this tagging is documented in [OSM wiki](https://wiki.openstreetmap.org/wiki/Relation:land_area), not disputed since five years. I agree I would have expected something like type=boundary, boundary=administrative_land_area.

**Comment by SomeoneElseOSM** [comment]
> At least this tagging is documented in OSM wiki, not disputed since five years

Just because someone created a wiki page 5 years ago doesn't mean that a concept is "not disputed".  In ths case it looks like they didn't tell anyone about it and only one other person has noticed and edited the page since then.  Perhaps you could explain in a bit more detail what it is that you actually trying to do (perhaps at help.openstreetmap.org rather than in a bug tracker) so that people can help you?  "osm2pgsql" already allows significant flexibility in other area via lua; it may be that that approach is an option for you too.

**Comment by Redoute** [comment]
I will have a look at the lua functionality. If it is possible to get the desired polygon objects this way, this issue may be closed.
Thank you!

> Perhaps you could explain in a bit more detail what it is that you actually trying to do (perhaps at help.openstreetmap.org rather than in a bug tracker) so that people can help you?

See [stackexchange](https://gis.stackexchange.com/questions/342104/how-to-get-land-area-polygons-with-osm2pgsql/342530#342530).

**Comment by pnorman** [comment]
> Everything else that can be considered a boundary or a polygon should be tagged as such, ie get one of those tags. `type=land_area` is simply the wrong tagging

I'm in agreement with this, but if you want, you can turn arbitrary relations into areas with lua transforms.

**Comment by kennykb** [comment]
I wonder whether the original requester realizes that a 'multipolygon' can be a single polygon, and is in fact a widely accepted (albeit still controversial) method for creating a mesh of polygons with shared boundaries.
